### PR TITLE
Added My PCB

### PR DESCRIPTION
**Pull request by TheHackerDude1083**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/825c14afce85d09e7376d0558087b992aa375ad8/projects/ShaheerNFCCard/Gerber_PCB_New Project_2024-01-26.zip>)!

  Happy OnBoarding!

**Comment by karmanyaahm** [comment]
Hi @TheHackerDude1083!

This trace that's going accross all the IC pins might cause unexpected issues in your circuit. 
image
Please post a link to your PR in the #onboard Slack channel, and someone will help you out.

Additionally, please make a "src" folder in projects/[name]/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

Also, you need to export your schematic tab as a PDF (in the schematic tab go to [File > Export > PDF](https://docs.easyeda.com/en/Export/Export-Schematic/index.html)), and upload that.

**Review by sarthaktexas — APPROVED** [review]
Howdy! I'm approving your student verification :) The next step will be to wait 24-48 hours for the technical review and then your PR will be merged and you'll receive your grant! [@hackclub/boarding-party](https://github.com/orgs/hackclub/teams/boarding-party)

**Comment by maxwofford** [comment]
Hey, haven't heard anything on this thread for a while so I'm going to close the PR so it's not in our actively monitored list. You can still totally reopen it by just commenting here or pushing those file changes.

**Pull request closed without merging**
