### PR TITLE
Jacob Bryant's NFC Card

### PR DESCRIPTION
**Pull request by Jbryant5213**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md`
  - [X] Uploaded Gerber.zip and Schematic.pdf
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Jake's NFC Card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi Jacob! Please put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) in the 'src' folder. They should be two .JSON files, you are missing the one from the schematic tab. You already have the PCB.json file. Other than that, LGTM!

**Comment by karmanyaahm** [comment]
Hi! IDK Why those files are showing up as empty files. Can you DM me (@ Karmanyaah) on Slack and I can help you figure this out.
image

**Review by karmanyaahm — APPROVED** [review]
BTW your student verification is approved, just waiting on those two files and I can get you your grant pretty quickly

**Comment by karmanyaahm** [comment]
LGTM! Emailing grant now!

**Comment by Jbryant5213** [comment]
I have received my NFC cards but they do not respondSent from my iPhoneOn Mar 11, 2024, at 3:00 PM, Karmanyaah Malhotra ***@***.***> wrote:﻿
Feel free to ask here or on Slack if you have any questions about the process

**Comment by BrightTheBackpack** [comment]
DM me on slack!Il I'll walk u through the setup process, and try and help with any issues. My slack is @bright li

**Pull request merged**
