### PR TITLE
My pr

### PR DESCRIPTION
**Pull request by souptik-samanta**
## Submission Checklist:

- [x ] I am a current high school, middle school, or home schooled student.
  - [x ] I am 18 or under
  - [x ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ x] I made this board from scratch, even if I followed a tutorial
- [ x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x ] Created a folder called `src` and uploaded design files
  - [x ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Cannot find a file describing your project called "README.md".
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi, you need to rename `GERBER.zip` to `gerber.zip` and have your KiCad files inside a folder called `/src`.

**Comment by MichaByte** [comment]
Hi @LimesKey, this is actually an OnBoard Live submission. I'm in touch @souptik-samanta on Slack. Sorry for the confusion!

@souptik-samanta When you have a chance, please fix the issues mentioned above!

**Comment by souptik-samanta** [comment]
Hi @MichaByte I have do that changes!
When you have time check it out 
Thank you!

**Comment by souptik-samanta** [comment]
@blazecoding2009 Could you review this the pervious one is for onboard live and this time i added for onboard grant

**Comment by blazecoding2009** [comment]
> @blazecoding2009 Could you review this the pervious one is for onboard live and this time i added for onboard grant

Sadly you will have to wait till the onboard live one is closed and open a new one later.

**Comment by souptik-samanta** [comment]
Hey @MichaByte Could you please review it 😭

**Comment by MichaByte** [comment]
Hello @souptik-samanta, apologies for the delay. I'm reviewing this now

**Comment by souptik-samanta** [comment]
Thank you

**Comment by MichaByte** [comment]
@souptik-samanta decided that he wants to keep working on this project to earn a little more money for it, and since we had a little misunderstanding about how to create this PR, I'll be closing it so he can open a new one once he's done working :)

**Pull request closed without merging**
