### PR TITLE
5Vconverter

### PR DESCRIPTION
**Pull request by Marc-Blanco**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/5Vconvertors:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi, can you rename `schematics.pdf` to `schematic.pdf`. I see that not selected assembly, I just want to confirm if that is intentional as your board won't be assembled by JLCPCB. I also see that your shipping cost is very high, is there not another shipping option you can use, maybe Standard Global Direct Line?

**Comment by Marc-Blanco** [comment]
Fixed!

**Comment by LimesKey** [comment]
You didn't respond to my other 2 questions

**Comment by Marc-Blanco** [comment]
I have the cheapest shipping cost and I can assemble it myself no worries

**Review by LimesKey — CHANGES_REQUESTED** [review]
Can you add the 3D Model (.WRL) file to your pull request?

**Comment by Marc-Blanco** [comment]
How I do it

**Comment by Marc-Blanco** [comment]
Done!

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hey on your verification form, you gotta fill out the "How did you hear about OnBoard?" and "What are we doing well" sections, can you resubmit the form?

**Comment by Marc-Blanco** [comment]
I just updated it.
Sorry for the inconviniences

**Review by LimesKey — APPROVED** [review]
Hi @Marc-Blanco!

I've just sent you your [grant for OnBoard](grant link). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by Marc-Blanco** [comment]
Hey,
When I went to pay the charges raised up

**Comment by LimesKey** [comment]
That's okay

**Pull request merged**
