### PR TITLE
Added files for "Game Scorecards"

### PR DESCRIPTION
**Pull request by NoahF15**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 7826

This is the Trail project for my group, @DedFishy, @NoahF15, and @dev-gm. We are making a device that reads and writes game scores to RFID cards. This will allow us to keep track of people's skill on the trail and give the best player bragging rights.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/game-scorecards:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/65deac2e592bf1ec5c3851ddb42460d34ea48cea/projects/game-scorecards/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/65deac2e592bf1ec5c3851ddb42460d34ea48cea/projects/game-scorecards/schematic.pdf>) |
|❌| Source files - EasyEDA | Please upload both your PCB and Schematic EasyEDA files.  |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/65deac2e592bf1ec5c3851ddb42460d34ea48cea/projects/game-scorecards/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by 24c02** [comment]
hang on - schematic.pdf should be the schematic, it looks like you uploaded a plot of the PCB layout instead. can you fix that and update your PR so i can review the electrical side of your design?

**Comment by NoahF15** [comment]
I think this should do it @24c02

**Comment by NoahF15** [comment]
We are confident for a prototype, but what I am confused about is that we
can’t organize it much better due to the specific pin outs. So how should
approach that?

Noah Blandford
Marquette ZetaBotics Co-Captain
FRC Team 7826
Marquette, MI

**Comment by 24c02** [comment]
nets! look at [this section](https://jams.hackclub.com/batch/usb-hub/part-1#Connect%20it%20together,%20for%20real%20this%20time!) of the USB hub jam for instructions

**Comment by DedFishy** [comment]
Okay @24c02 I think this should be better

**Pull request merged**
