### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by sock745**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) This project is for [Trick or Trace](https://showcase.hackclub.com/)[^3].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/AlexW65%Keeb:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @sock745! 

You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order up to 5 assembled boards.

Additionally, please make a "src" folder in projects/[name]/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

Also, if you haven't done it already, you need to export your schematic tab as a PDF (in the schematic tab go to [File > Export > PDF](https://docs.easyeda.com/en/Export/Export-Schematic/index.html)), and upload that.

**Comment by LimesKey** [comment]
Can you please fix your files and add in the `/src` folder?

**Comment by sock745** [comment]
I fixed the file names but I’m confused on how I should do the .json files
for the src folder.

**Comment by LimesKey** [comment]
image

**Comment by sock745** [comment]
Alright I just made the changes, thank you so much

**Review by LimesKey — CHANGES_REQUESTED** [review]
You're still missing your `schematic.pdf`, I think you might have added a schematic but it's not named correctly? Also, you'll need your `.WRL` 3D Model File. https://github.com/hackclub/OnBoard/blob/main/docs/kicad-submission.md

**Review by LimesKey — COMMENTED** [review]
Your schematic file is still wrong, and it should not be a drill map. Can you move the WRL file into the `/src` folder as well.

**Comment by LimesKey** [comment]
I still cannot view your schematic

**Comment by sock745** [comment]
[image: image.png]
Am I mistaken?

**Comment by LimesKey** [comment]
I can see your schematic but it's wrong, please ask in the Slack in the #electronics channel for more help!

**Pull request closed without merging**
