### PR TITLE
second attempt, triple checked everything this time

### PR DESCRIPTION
**Pull request by falsonix**
## Submission Checklist:

- [/ ] I am a current high school, middle school, or home schooled student.
  - [/ ] I am 18 or under
  - [/ ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [/ ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [/ ] I made this board from scratch, even if I followed a tutorial
- [ /] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [/ ] Created a folder under `onboard/projects`
  - [ /] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ /] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [/ ] Created a folder called `src` and uploaded design files
  - [ /] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ /] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [/ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [/ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/falsonixsnumberpad:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/14268f4786fec30ebc487e98b168f4bbe03602be/projects/falsonixsnumberpad/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/14268f4786fec30ebc487e98b168f4bbe03602be/projects/falsonixsnumberpad/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/14268f4786fec30ebc487e98b168f4bbe03602be/projects/falsonixsnumberpad/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @falsonix,

Thanks for submitting your PCB order! However, it looks like you took a picture of your cart instead of completing the checkout process. To ensure your order gets processed correctly, please follow these steps:


1. Click "Secure Checkout": After adding your PCB to the cart, make sure to click "Secure Checkout."
2. Enter your shipping information: Fill in your shipping details as prompted.
3. Take a screenshot of your unpaid order: Once you reach the final page before payment, take a screenshot of this page. It should show all the details of your order.


Please send me a screenshot of your unpaid order instead of a picture of your cart. This will help us review your order more efficiently. Congrats on making the PCB though!

**Comment by falsonix** [comment]
@LimesKey
Hello there! Sorry about the confusion, I thought I followed the template for the screenshot. Here is the screenshot of my checkout, as requested:
image
If this is still not sufficient please let me know and I will work to get it up to standard.

**Comment by LimesKey** [comment]
You have to actually click "submit order" and then go to the JLCPCB orders page and send a screenshot of that.

**Comment by falsonix** [comment]
@LimesKey I understand now, thank you!
image

**Comment by torbers** [comment]
great! could you upload this as cart.png?

**Review by LimesKey — APPROVED** [review]
Hi @falsonix!
I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/Xk5Iel). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
