### PR TITLE
CANSwitch

### PR DESCRIPTION
**Pull request by Brelee2222**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 1540

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/5d4d5c1d6ebb669712d869cfaee665f87429db55/projects/CANSwitch/gerber.zip>)!

  Happy OnBoarding!

**Comment by Brelee2222** [comment]
I probably should mention some things about the circuit for the pcb, because it does not use a Voltage supply or Ground.

I color coded the tracks in the schematic so that half of them are yellow, while the rest are green (CAN bus colors). The yellow tracks are for high signals passing through the circuit and green tracks are for low signals.

When the switch is flipped one way, the yellow tracks should connect together, and when flipped the yellow tracks should pass through a 120 ohms resistor and into a green track. 

The on the PCB design, all the yellow tracks are on one side of the board while green tracks are on the other.

If you're going to verify the footprints I use, here are the links for the parts I am using. I forgot to link them in the design.
https://www.mouser.com/ProductDetail/ROHM-Semiconductor/ESR10EZPF1200?qs=DyUWGjl%252BcVtTejlGEVMJGA%3D%3D
https://www.digikey.com/en/products/detail/nidec-components-corporation/MFS401N-2-Z/5086558

**Review by maxwofford — APPROVED** [review]
I love seeing such a simple board put together! Your student verification is approved. Good luck with your CAN debugging!

**Review by karmanyaahm — APPROVED** [review]
Love that OnBoard is being helping with your robot!

**Comment by karmanyaahm** [comment]
Your grant should be emailed to you soon!

**Comment by maxwofford** [comment]
[Sent!](https://hcb.hackclub.com/grants/wM2IdK)

**Pull request merged**
