### PR TITLE
Akshat's business card

### PR DESCRIPTION
**Pull request by Akshatbigman**
## Submission Checklist:

- [yes ] I am a current high school, middle school, or home schooled student.
  - [ yes] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [yes ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [yes ] I made this board from scratch, even if I followed a tutorial
- [yes ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ yes] Created a folder under `onboard/projects`
  - [yes ] Filled out `TEMPLATE.md` as `README.md`
  - [yes ] Uploaded Gerber.zip and Schematic.pdf
  - [ yes] Created a folder called `src` and uploaded design files
  - [ yes] Uploaded screenshot of PCB order with all costs included
  - [ yes] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ yes] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/akshat's business card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by MichaByte** [comment]
Hi @Akshatbigman! 

It looks like you have a component (the LED light) on the front of the board, with all the other components on the back. This doesn't fit into the requirements of econommic assembly, so JLCPCB made you pick standard assembly, which made the cost higher. Hacker cards are supposed to be under $50 after shipping, so could you please make sure that all the parts are on the same side of the board so you can use economic assembly? Let me know if you need any help, or join [#electronics on Slack](https://hackclub.com/slack/?event=onboard)!

**Comment by Akshatbigman** [comment]
Ok, I have done the needed changes can you please check.

**Comment by MichaByte** [comment]
Hi @Akshatbigman!
It looks like the LED in your schematic is backwards, meaning it won't light up.
image
Could you flip it so that the arrow faces in the other direction? After doing that, you'll need to update your layout and then re-upload your Gerber files to JLCPCB. Feel free to ask me or join [#electronics on Slack](https://hackclub.com/slack/?event=onboard) if you need any help!

**Comment by Akshatbigman** [comment]
Alright i have fixed the direction, can you please check it once more, Please and Thank you

**Comment by MichaByte** [comment]
Hi @Akshatbigman!

It looks like you deleted your schematic and cart screenshot. Could you please add those back in? Once you do that, I can get you your grant!

**Comment by Akshatbigman** [comment]
There was a typo in the file name, I have fixed that can you check.

**Comment by MichaByte** [comment]
Hi @Akshatbigman!
I've just sent you [your grant for OnBoard](https://hcb.hackclub.com/grants/vrnIrZ). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.**

I'm looking forward to seeing your PCB be manufactured! Send pictures in the [#electronics channel on Slack](https://hackclub.com/slack/?event=onboard) once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
