### PR TITLE
Created microDucky

### PR DESCRIPTION
**Pull request by BadPotato1007**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md`
  - [X] Uploaded Gerber, sources, and schematic
  - [X] Uploaded screenshot of PCB order with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by BadPotato1007** [comment]
please confirm fast!
its the v2.0 for my ducky!

**Review by Hugoyhu — CHANGES_REQUESTED** [review]
Could you please submit the SCH and PCB .jsons in the src folder? I only see the SCH.json in the main directory. Please put both SCH and PCB .json files in the /src file, thank you.

**Review by sarthaktexas — APPROVED** [review]
Student verification already approved!

**Comment by BadPotato1007** [comment]
hey! just made the changes that you requested! do review and help me get the grant!

**Comment by BadPotato1007** [comment]
1 more reviewer please!

**Comment by karmanyaahm** [comment]
You should get an email with your grant in 24-48 business hours!

**Comment by sarthaktexas** [comment]
sent!

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/MicroDucky:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/9b50cb8709db2a9cc24c1bf95d83676113058140/projects/MicroDucky/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/9b50cb8709db2a9cc24c1bf95d83676113058140/projects/MicroDucky/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/9b50cb8709db2a9cc24c1bf95d83676113058140/projects/MicroDucky/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Pull request merged**
