### PR TITLE
added my project 'hack-pcb'

### PR DESCRIPTION
**Pull request by uniquepersun**
## Submission Checklist:

- [x ] I am a current high school, middle school, or home schooled student.
  - [x ] I am 18 or under
  - [x ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X ] I made this board from scratch, even if I followed a tutorial
- [X ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X ] Created a folder under `onboard/projects`
  - [X ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X ] Created a folder called `src` and uploaded design files
  - [X ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/hack-pcb:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/3b4fee5ab19cd1ad13936b251a2b770cdade0aa2/projects/hack-pcb/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/3b4fee5ab19cd1ad13936b251a2b770cdade0aa2/projects/hack-pcb/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/3b4fee5ab19cd1ad13936b251a2b770cdade0aa2/projects/hack-pcb/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hey, I see you've selected Standard PCB Assembly. Standard PCB assembly can be very costly and not worth it for a project like this, are you able to get it to use Economic assembly instead? That should bring your price down substantially.

**Comment by abhaytomar05** [comment]
Do I have to chage it and again upload cart.png and again pr. Or I can just change it and order to money and don't need to upload the cart.png again.

And, one more I have to select standard instead of aerospace, right??

**Comment by uniquepersun** [comment]
Do I have to chage it and again upload cart.png and again pr. Or I can just change it and order to money and don't need to upload the cart.png again.

And, one more I have to select standard instead of aerospace, right??

**Comment by LimesKey** [comment]
Can you please upload Cart.png again? Sorry. And yes, Standard not aerospace.

**Comment by uniquepersun** [comment]
yup uploaded new cart.png and yeah that reduced the price to 40$  from 120$(excluding shipping charges) thanks ❤️

**Comment by LimesKey** [comment]
The grant only covers 50$ since your doing a tutorial PCB, I still see you've chosen Standard Assembly, are you able to redo the process and select Economic and also select a cheaper shipping method?

**Comment by uniquepersun** [comment]
What's that, standard thing ?

**Comment by LimesKey** [comment]
The assembly you chose in your `cart.png`, it's standard assembly not Economic.

**Comment by LimesKey** [comment]
Looks good but is there a cheaper shipping option? If not that's fine.

**Comment by gopaldotcom** [comment]
Yeah, so I selected that one which you're taking. But on the next page it automatically switches to that worldwide 40$delivery and only option left was only another option that same delivery partner for 35$. So, I selected the 35 one

**Comment by uniquepersun** [comment]
Yeah, so I selected that one which you're taking. But on the next page it automatically switches to that worldwide 40$delivery and only option left was only another option that same delivery partner for 35$. So, I selected the 35 one

**Comment by LimesKey** [comment]
I see that your `schematic.pdf` is just an image of your PCB and not the actual electrical schematic. Make sure you are on the schematic tab of EasyEDA when you downloaded your schematic.pdf.

**Comment by uniquepersun** [comment]
yup 👍🏻 probably all done

**Review by LimesKey — APPROVED** [review]
Hi @uniquepersun!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/vzxIWD). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by uniquepersun** [comment]
Yayyy, thank you!!

**Pull request merged**
