### PR TITLE
PatOnboardCard

### PR DESCRIPTION
**Pull request by Patcybermind**
## Submission Checklist:
i already did it i just had to redo the request
- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Pat's_Onboard_Card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|❌ | schematic.pdf | You must export your schematic file as schematic.pdf |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/fb93b70ed8cdddc498e08ff4391d9cff035b6681/projects/Pat's_Onboard_Card/src/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Hi @Patcybermind! Can you please upload your 'schematic.pdf' from EasyEDA's schematic tab? It should look something like this: https://github.com/hackclub/OnBoard/blob/main/projects/Ari's%20Card/schematic.pdf

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
see above

**Comment by karmanyaahm** [comment]
Hey @Patcybermind, were you able to figure out how to upload the schematic? Feel free to ask on Slack if you have any questions!

**Comment by Patcybermind** [comment]
Hi sorry, i didnt see your message i thiught i had notifications on and was waiting lol ah ok ill try and get the pdf i thought the schematic was the json file ill so it when im on my pc

**Pull request closed without merging**
