### PR TITLE
Digispark board

### PR DESCRIPTION
**Pull request by Samarpan1122**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by maxwofford** [comment]
Hey! I'm a bit confused by the description here, you mention NFC but the schematic doesn't include a NFC antenna or what I can tell is any chip that supports NFC.

It looks like this board is from https://www.kickstarter.com/projects/digistump/digispark-the-tiny-arduino-enabled-usb-dev-board. How did you customize it?

**Comment by Samarpan1122** [comment]
sorry i copied readme from other pr so ...

**Comment by Samarpan1122** [comment]
> Hey! I'm a bit confused by the description here, you mention NFC but the schematic doesn't include a NFC antenna or what I can tell is any chip that supports NFC.
> 
> It looks like this board is from https://www.kickstarter.com/projects/digistump/digispark-the-tiny-arduino-enabled-usb-dev-board. How did you customize it?

i made it from scratch from udemy course

**Comment by maxwofford** [comment]
Ah, gotcha! Could you please update your original post to say you used a tutorial? Go ahead and post the link to it for others

**Comment by Samarpan1122** [comment]
done

**Comment by maxwofford** [comment]
Hey @Samarpan1122! Unfortunately you've already gotten the $100 grant for [your previous PCB](https://github.com/hackclub/OnBoard/tree/fadec975a8b06be542c9f20fcd947a0642768095/projects/Samarpan's%20Card), so I can't give another grant for this project. If you want, I can still merge this in so people can see the design you worked on.

**Comment by Samarpan1122** [comment]
ok merge it

**Comment by maxwofford** [comment]
For posterity, I'm merging this without review so the designs are available and open for others to see!

**Pull request merged**
