### PR TITLE
Added ESP32 based IOT Coffee Detector (with AI) and weather station

### PR DESCRIPTION
**Pull request by yutarour**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

### CODE REVIEW

**Review by daisybanks — COMMENTED** [review]
Welcome OnBoard @yutarour! Everything looks good on Bank's side. @hackclub/boarding-party.

**Comment by karmanyaahm** [comment]
This looks very innovative! However, as mentioned in the [requirements](https://github.com/hackclub/OnBoard#requirements) for OnBoard, we only support paying for approved PCB [vendors](https://github.com/hackclub/OnBoard/blob/main/docs/VENDORS.md), not Sparkfun.

Could you get those parts assembled from JLCPCB instead of Sparkfun?

**Comment by karmanyaahm** [comment]
This looks very innovative! However, as mentioned in the [requirements](https://github.com/hackclub/OnBoard#requirements) for OnBoard, we only support paying for approved PCB [vendors](https://github.com/hackclub/OnBoard/blob/main/docs/VENDORS.md), not Sparkfun.

Could you get those parts assembled from JLCPCB instead of Sparkfun? Or, you could get the board partially assembled with JLCPCB and order Sparkfun parts outside the grant.

**Comment by yutarour** [comment]
So a PCB pick and place service is allowed?

**Comment by karmanyaahm** [comment]
Anything from one of the approved vendors is allowed, including pick and place.

**Comment by zachlatta** [comment]
@yutarour: I appreciate your suggestion around making OnBoard more like WHW, but our goal for OnBoard is to specifically support people in making PCBs and learning circuit design - not funding electronics projects broadly.

Our hope is that OnBoard will inspire people to make a PCB board where they maybe haven't before, and to make it more frictionless to incorporate custom PCBs into bigger electronics projects.

Hack Club will definitely do more initiatives like WHW in the future, but each time it will likely have some sort of different focus - and this time it's on PCB design!

**Comment by yutarour** [comment]
Modifying submission. Closing once.

**Pull request closed without merging**
