### PR TITLE
Arjun's USB Hub

### PR DESCRIPTION
**Pull request by arjundeshpande08**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Arjun's-usb-hub:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/49a310ad9063a9160f00a1c8687fffaf9b912d84/projects/Arjun's-usb-hub/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/49a310ad9063a9160f00a1c8687fffaf9b912d84/projects/Arjun's-usb-hub/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/49a310ad9063a9160f00a1c8687fffaf9b912d84/projects/Arjun's-usb-hub/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by arjundeshpande08** [comment]
Although the cart.png file shows the cost as $109.86 When I press on Pay I get a New Customer coupon that makes the real price $97.86. Therefore my cost still falls in the grant.

**Review by LimesKey — DISMISSED** [review]
I see you're using Standard Assembly, that's the reason for the high price, is there any way you can use Economic Assembly instead? Standard Assembly should only be used if absolutely required.

**Comment by blazecoding2009** [comment]
@arjundeshpande08 Please do not delete and recreate PRs when we are requesting a change even if you have fixed it. PRs auto update when you commit files even after you have created the PR. Also components come in stock again and there are ways to get it even if they're not in stock. Please be patient.

**Comment by arjundeshpande08** [comment]
@LimesKey  I did try and use economic assembly however the main usb port (the one that plugs into the computer) makes jlcpcb force me into standard, and I have tried alternative parts and jts the same for all of them

**Comment by arjundeshpande08** [comment]
Any more changes I need to make in order to get approval?

**Comment by blazecoding2009** [comment]
You're good. Please be patient. We're humans too, we have our own lives outside of OnBoard.

**Review by blazecoding2009 — APPROVED** [review]
Hey @arjundeshpande08 

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/qKbI59). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
