### PR TITLE
MICHAEL"

### PR DESCRIPTION
**Pull request by mchuang413**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/MCKEYBOARD:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|❌ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/38cd41364ea8c5a612790d26905a65d364cf9029/projects/MCKEYBOARD/schematic.pdf>) | You must export your schematic file as schematic.pdf |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/38cd41364ea8c5a612790d26905a65d364cf9029/projects/MCKEYBOARD/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by mchuang413** [comment]
fixed everything ;)

**Comment by mchuang413** [comment]
fixed again

**Comment by mchuang413** [comment]
i deleted some unnecessary files

**Comment by mchuang413** [comment]
could someone take a look at it. i did upload the sch and pcb files in the src folder...

**Comment by maxwofford** [comment]
I see these files @mchuang413, but there should be a 3rd file from KiCad! Can you upload that?
Screenshot 2024-04-29 at 09 17 57

Also, the OnBoard grant only covers $100 for your board, so at the current price you'd need to pay the extra $21.16. Are you up to do that? If so, you can [pay it here](https://hcb.hackclub.com/donations/start/onboard). If not, I recommend posting your design and specifically the parts list in the #electronics channel of Slack to get feedback on cutting costs for your design!

**Comment by mchuang413** [comment]
Yeah, I can do that. Let me upload my 3rd KiCad file. Seems[image:
image.png]
 like it got accidentally deleted. I donated the $21.16.

**Review by maxwofford — APPROVED** [review]
Great, I just [sent the grant](https://hcb.hackclub.com/grants/q57IJL) with the extra funds included.

**Comment by mchuang413** [comment]
Awesome, thanks!

**Pull request merged**
