### PR TITLE
checklist for ragav_nfc_card

### PR DESCRIPTION
**Pull request by Duppi28**
## Submission Checklist:

- [y] I am a current high school, middle school, or home-schooled student.
  - [y ] I am 18 or under
  - [y ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ y] (link says there is a glitch) I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ y] I made this board from scratch, even if I followed a tutorial
- [ y] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ y] Created a folder under `onboard/projects`
  - [ y] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ y] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ y] Created a folder called `src` and uploaded design files
  - [ y] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ y] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ y] (Optional) This project is from a tutorial[^1].
- [ n] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ y] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 503

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by torbers — CHANGES_REQUESTED** [review]
some issues here.
1. You do have to join Slack - try this link: https://hackclub.com/slack/?event=onboard
2. You have selected "Standard PCBA," which is not needed for the business card board, and costs a lot of money. Please make sure the board thickness is 1.6mm and that you are using the correct components from the tutorial.
Everything else looks fine.

**Comment by Duppi28** [comment]
> some issues here.
> 
> 1. You do have to join Slack - try this link: https://hackclub.com/slack/?event=onboard
> 2. You have selected "Standard PCBA," which is not needed for the business card board, and costs a lot of money. Please make sure the board thickness is 1.6mm and that you are using the correct components from the tutorial.
>    Everything else looks fine.

The link you gave me redirects me to "Arcade slack" which I a already in, as as for the PCB board I have switched it from pcba to pcb.

**Comment by Duppi28** [comment]
> > some issues here.
> 
> > 
> 
> > 1. You do have to join Slack - try this link: https://hackclub.com/slack/?event=onboard
> 
> > 2. You have selected "Standard PCBA," which is not needed for the business card board, and costs a lot of money. Please make sure the board thickness is 1.6mm and that you are using the correct components from the tutorial.
> 
> >    Everything else looks fine.
> 
> 
> 
> The link you gave me redirects me to "Arcade slack" which I am already in, as for the PCB board I have switched it from pcba to pcb.

I joined slack, sry

**Comment by torbers** [comment]
thanks!
Sorry, I should have been more clear about PCBA. You DO want PCBA, or else there will be no components on the board. But it should be "Economic PCBA," not "Standard PCBA." There should be a setting while uploading your board to JLC.

**Comment by Duppi28** [comment]
ok i fixed the pcb here is the updated version 
image

**Comment by torbers** [comment]
could you re-upload that image as your cart.png? sorry to make you do all this, we have to document everything.

**Review by torbers — CHANGES_REQUESTED** [review]
could you re-upload that image as your cart.png? sorry to make you do all this, we have to document everything.

**Comment by Duppi28** [comment]
Seems like my repo got deleted should I make a new pull request?

**Pull request closed without merging**
