### PR TITLE
Keyboard PCB with Assembly

### PR DESCRIPTION
**Pull request by mchuang413**
## Submission Checklist:

- [Yes] I am a current high school, middle school, or home schooled student.
  - [Yes ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [No because the link keeps telling me it is glitched ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [Yes] I made this board from scratch, even if I followed a tutorial
- [Yes] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Yes] Created a folder under `onboard/projects`
  - [Yes] Filled out `TEMPLATE.md` as `README.md`
  - [Yes] Uploaded Gerber.zip and Schematic.pdf
  - [No, accidentally uploaded everything in my project folder] Created a folder called `src` and uploaded design files
  - [Yes ] Uploaded screenshot of PCB order with all costs included
  - [Yes] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [Yes] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [] (Optional) This project is from a tutorial[^1].
- [Yes] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 9634 (FRC)(Zero Tolerance)

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Keyboard/PROJECT_NAME:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @mchuang413, looks like you typed "PROJECT_NAME" instead of replacing it with your actual project name!

Could you get your files and folders in order first?

Screenshot 2024-04-24 at 17 17 09

**Comment by mchuang413** [comment]
is it better now?

**Comment by mchuang413** [comment]
fixed everything:

Submission Checklist:
[Yes] I am a current high school, middle school, or home schooled student.

[Yes ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
[No because the link keeps telling me it is glitched ] I have joined the [#electronics](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)

[Yes] I made this board from scratch, even if I followed a tutorial

[Yes] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)

[Yes] Created a folder under onboard/projects
[Yes] Filled out TEMPLATE.md as README.md
[Yes] Uploaded Gerber.zip and Schematic.pdf
[No, accidentally uploaded everything in my project folder] Created a folder called src and uploaded design files
[Yes ] Uploaded screenshot of PCB order with all costs included
[Yes] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
[Yes] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)
[] (Optional) This project is from a tutorial[1](https://github.com/hackclub/OnBoard/pull/485#user-content-fn-1-387d293c554b4644584366ec3dba445a).

[Yes] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 9634 (FRC)(Zero Tolerance)

**Review by mchuang413 — COMMENTED** [review]
### fixed

**Pull request closed without merging**
