### PR TITLE
Add "LightUp" board

### PR DESCRIPTION
**Pull request by Dongathan-Jong**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/LightUp:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Hey @Dongathan-Jong! You can replace your WS2812's with XL-5050RGBC-WS2812B's. I've used them in several projects and they behave the same but are much cheaper and support economic assembly.
image

Another thing I would suggest is that if you break out your final DOUT pin, you could daisy chain multiple of these boards together

**Comment by karmanyaahm** [comment]
For the PCB layout, you have to make copper wires between each of the pads. The schematic connections are just theoretical, whereas your PCB layout is where the wires will actually be placed! 
image
Also the holes for your through hole pin connector are interfering with your LEDs, you might want to move it somewhere else (and on the top layer for single sided assembly) 
image

**Comment by karmanyaahm** [comment]
BTW your student verification is approved

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
above

**Comment by Dongathan-Jong** [comment]
Hey! Thank you for the feedback :) I just changed it, could you have another look? Thanks.

**Comment by karmanyaahm** [comment]
You still have to connect the positive and negative traces of every other LED to the positive and negative lines. Also, the DOUT of your first LED needs to go to the DIN of the next, and so on and so forth
image

Basically every green wire in your schematic should have a corresponding wire in the PCB
image

Also, you should probably make the power traces 3-4 times thicker, because you have so many LEDs they will draw a lot of current

**Comment by Dongathan-Jong** [comment]
Just updated it, is that trace big enough?

**Comment by karmanyaahm** [comment]
Your easyeda file looks perfect to me! But it looks like you might've uploaded the wrong gerber.zip and cart.png, as soon as you fix that I can get you your grant!

**Comment by karmanyaahm** [comment]
Hi @Dongathan-Jong!
I've just sent you [your grant](https://hcb.hackclub.com/grants/XpjI3B) for OnBoard. You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
