### PR TITLE
Update TOTKey with new revisions

### PR DESCRIPTION
**Pull request by rivques**

### CODE REVIEW

**Comment by karmanyaahm** [comment]
Just to make sure you know this, JLCPCB is the only supported vendor here. You can't use Onboard funds for Amazon, LCSC etc

**Review by karmanyaahm — APPROVED** [review]
LGTM

**Comment by rivques** [comment]
> Just to make sure you know this, JLCPCB is the only supported vendor here. You can't use Onboard funds for Amazon, LCSC etc

Yep, figured that one out eventually


Also: If I need a rev 2, is there a way I can add like $5 to the OnBoard grant so it can cover it, or do I just need to make the board cost less than my balance?

**Comment by karmanyaahm** [comment]
Yeah, you can add money to your grant.

**Comment by karamassie** [comment]
hi @rivques  ! i DM'd you in our Slack about this project and maybe getting a tutorial on it in MAKE magazine. Pinging you here too, in case you don't check Slack often. Can you get in touch? here, Slack or I'm kara@hackclub.com 
TYSM!!

**Comment by rivques** [comment]
Thanks so much for getting in touch @karamassie! I sent you an email.

**Pull request merged**
