### PR TITLE
Sabya's Controllable usb

### PR DESCRIPTION
**Pull request by Sabya19**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by kvnyng** [comment]
This is pretty neat! LGTM! 

cc @daisybanks

**Review by karmanyaahm — APPROVED** [review]
very cool project! Is this like an Arduino dev board?

**Comment by Sabya19** [comment]
like an esp32 but with usb

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Can you please upload your schematic as `schematic.pdf`? You can export it from the EasyEDA schematic - [file > export > PDF](https://docs.easyeda.com/en/Export/Export-Schematic/index.html).

Additionally, please put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) into the `src/` folder.

**Review by daisybanks — APPROVED** [review]
Welcome OnBoard @Sabya19! Everything looks good on HCBs end @hackclub/boarding-party!

**Comment by Sabya19** [comment]
what do i do now

**Pull request merged**
