### PR TITLE
Pour Cup PCB

### PR DESCRIPTION
**Pull request by BoredFishRE**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)

- [ ] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — APPROVED** [review]
Wow that's awesome! Hope your project works out as expected. Please share the finalized project on Slack.

**Comment by BoredFishRE** [comment]
I will!

**Comment by BoredFishRE** [comment]
I wasn't sure if I needed to do the verification again so I did it anyways.

**Comment by karmanyaahm** [comment]
No since this is your second PCB, you can just go ahead and order it. You don't need to wait for this PR to be merged.

**Comment by BoredFishRE** [comment]
> No since this is your second PCB, you can just go ahead and order it. You don't need to wait for this PR to be merged.

Ah ok! thanks

**Review by karmanyaahm — APPROVED** [review]
This is an update and ready to merge

**Pull request merged**
