### PR TITLE
Hack Card

### PR DESCRIPTION
**Pull request by Rafi13082007**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [] (Optional) This project is for OnBoard Live[^2].
- [X] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 1884, 1797

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/HackCard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Rafi13082007** [comment]
How long does it take

**Review by LimesKey — CHANGES_REQUESTED** [review]
Can you clean up your files, looks like you have duplicates of your gerber and JSON files.

**Comment by Rafi13082007** [comment]
I've completed the change. I wanted to also ask, do you think its still possible to get the FIRST pcb badge?

**Comment by Rafi13082007** [comment]
Hello, It's been 3 days

**Comment by LimesKey** [comment]
Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of your cart rather than the completed unpaid order.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to the [JLCPCB Order page](https://jlcpcb.com/user-center/orders/), then take a rectangular screenshot of the PCB you just submitted. It should show all the details of your order including the price and assembly.

This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congratulations on making the PCB! Please ask in [#electronics](https://slack.com/archives/C056AMWSFKJ) in the [Slack](https://hackclub.com/slack/) if you need any further help.

**Comment by Rafi13082007** [comment]
Ive uploaded the new picture as cart.png
I think everything should be fine now

**Review by LimesKey — CHANGES_REQUESTED** [review]
You've selected Standard Assembly, this is a much more costly option and is usually never needed for the Hackercard Jam, can you switch to economic assembly?

**Comment by Rafi13082007** [comment]
I chose standard assembly because my hackercard is double sided

**Comment by Rafi13082007** [comment]
Just double checked and I dont neet double sided assembly, ill be doing economic now, thanks

**Comment by Rafi13082007** [comment]
Since im going with economic assembly, can I order a different design of the same gerber, i have both vertical and horizontal designs

**Comment by LimesKey** [comment]
Can you upload your new `cart.png`?
> Since im going with economic assembly, can I order a different design of the same gerber, i have both vertical and horizontal designs

You're limited to 50$ total and a max of 5 PCBs, so I don't think you're able to do this but you can try.

**Comment by Rafi13082007** [comment]
After customs and everything it falls to 62 dollars, would that be fine?

**Comment by Rafi13082007** [comment]
I've uploaded the new cart.png . Also, it's the FIRST offer still going on?

**Comment by LimesKey** [comment]
Sorry for the late response but it looks like you're trying to buy 10 PCBs in 2 different orders, can you get rid of one of them and reupload the cart?

**Comment by Rafi13082007** [comment]
Everything should be in order now

**Comment by Rafi13082007** [comment]
How long would it take for the grant to process?

**Comment by LimesKey** [comment]
Your PCB won't work as you have a BottomLayer copper trace on a TopLayer component, they won't connect since their not on the same layer. Please ask in the #electronics channel in Slack for more help. 
image

**Comment by Rafi13082007** [comment]
I've fixed the connections but now im getting drc errors 
image

**Comment by LimesKey** [comment]
That should be okay, just confirm by posting a message in the Slack.

**Comment by Rafi13082007** [comment]
I've posted a message on slack, once I get confirmation ill upload the new gerber here and update the cart too

**Comment by Rafi13082007** [comment]
All done

**Comment by LimesKey** [comment]
You have your QR code on the same copper layer as your antenna, your PCB will not work with this.
image

**Comment by Rafi13082007** [comment]
Ive done it again

**Comment by LimesKey** [comment]
image
Anyway you can also remove some of the graphics on the copper layers near the antenna? Not all but just a few, it should help with reading the NFC tag better.

**Review by LimesKey — CHANGES_REQUESTED** [review]
Can you put in the new price of 29.99$ in your README?

**Comment by Rafi13082007** [comment]
Changes done again, all graphics are on silk layer now so it shouldnt conflict

**Comment by Rafi13082007** [comment]
Hello, I'm awaiting confirmation whether my grant was approved. I've followed the new steps and uploaded the new files.

**Review by LimesKey — APPROVED** [review]
Hi @Rafi13082007!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/3OI3br). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the [#electronics](https://slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/) once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by LimesKey** [comment]
So sorry for the delay!

**Comment by Rafi13082007** [comment]
Hello @LimesKey,

No worries, glad it worked out at the end. Thanks for everything.

Also about my previous question, is the FIRST pcb promotion still ongoing?

**Comment by LimesKey** [comment]
I believe the First PCB promotion and the OnBoard one are the same thing? I'm not quite sure, are you able to ask in #electronics in the Slack?

**Comment by Rafi13082007** [comment]
Oh I see, I'll ask on slack. Thanks for everything

**Pull request merged**
