### PR TITLE
Add VFD Tool 

### PR DESCRIPTION
**Pull request by Haxintosh**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/VFD-Tool:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ee1e5e3938e6ee10dbaed79d6cb7be78384eb3e9/projects/VFD-Tool/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ee1e5e3938e6ee10dbaed79d6cb7be78384eb3e9/projects/VFD-Tool/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/ee1e5e3938e6ee10dbaed79d6cb7be78384eb3e9/projects/VFD-Tool/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — COMMENTED** [review]
Everything in your PR looks great, I love how you've added all the special KiCad files along with your PR like the symbols and 3D models, those always get left out and it's a pain without them. Just one more thing, are you confident you're able to hand-solder all the components on your PCB with the stencil you're purchasing? 

You might be able to do both a partial assembly of a lot of the smaller cheap components (to save time and cost) then do the larger components like the USB-C and JST headers by hand with the stencil. But don't let me change your mind, you do you, the board looks fantastic!

**Comment by Haxintosh** [comment]
Yep! I got a reflow plate and most of the components already from other projects so I didn't want to waste the money on assembly.

**Comment by LimesKey** [comment]
As far as I know, you're the first person to order a stencil along with your PCB with your OnBoard grant. I talked it over a bit with my partners and we're now allowing people to order stencils starting with you.

If you're up for it, I'd love it if you could take some photos of the SMD soldering process with the stencil, and share a little about how it works. It's totally up to you, but if you can do it, I'm eager to hear about the steps you took and if you could post it in this issue, #809, that'd be helpful. 

Also quick tip, not sure about JLCPCB, but for another PCB manufacturer, they packaged the stencils in a weird way that I thought was just the packing material for the box so I accidentally threw out my stencil! Make sure you don't do that!

**Comment by Haxintosh** [comment]
Sure, I'd love to document the process and post it here! 

As for the packaging, I think JLCPCB put the stencils in a plastic bag inside the box, but I'm not entirely sure. I'll be careful not to accidentally throw anything away, thanks for the tip! 😅

**Pull request merged**
