### PR TITLE
PCB Motor

### PR DESCRIPTION
**Pull request by DominicTYLau**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/PCB Motor:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/de182ed394261d87ae741f90fb533ca3b17fa892/projects/PCB Motor/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/de182ed394261d87ae741f90fb533ca3b17fa892/projects/PCB Motor/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/de182ed394261d87ae741f90fb533ca3b17fa892/projects/PCB Motor/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by LimesKey** [comment]
Hi @DominicTYLau, your motor design looks great but I see a couple issues. I see in your cart image it's already in production, have you already paid for it? If so, would you like to be reimbursed instead? Taking a look at your schematic and Gerber files, I see you've included an Arduino Uno in your schematic but not in your Gerber files for assembly, is this a mistake or are you planning to add it in later?

**Comment by DominicTYLau** [comment]
Hi,

I have already purchased it, so would it be possible to be reimbursed? I
included the Arduino Uno in the schematic because, without it, there wasn't
anything to put in the schematic. The PCB should only include the motor
(not the Arduino and ESC, as I already have them).

Thanks,

Dominic Lau

**Comment by LimesKey** [comment]
I've sent you a reimbursement via Hack Club Bank, it should be in your email. That makes sense with the Arduino, best of luck! Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please keep this in mind before you make any purchases.** More info in the OnBoard community shipping doc.

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by LimesKey** [comment]
Hey @DominicTYLau, I see you've set up a reimbursement but it's saying you haven't added your payout details? I'm just waiting on that.

**Comment by DominicTYLau** [comment]
Sorry for the wait. I have been trying to figure out the routing number,
but I realized that it only includes US banks. Unfortunately, I live in
Canada and do not have a PayPal account. I’ll pay this out of pocket, but
hopefully, I'll be able to follow the instructions next time for another
OnBoard project :)

Thanks,

Dominic Lau

**Comment by LimesKey** [comment]
Best of luck with future designs, sorry I couldn't help more!

**Comment by DominicTYLau** [comment]
No problem, thank you!

**Pull request merged**
