### PR TITLE
DINO_BOARD

### PR DESCRIPTION
**Pull request by vale217**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by torbers — CHANGES_REQUESTED** [review]
Hi Valeria,
Please make sure your project folder `DINO_BOARD` is in `/projects/`. You can review [this section](https://github.com/hackclub/OnBoard?tab=readme-ov-file#5-add-your-design-to-your-project-repo) of readme.md if you're confused. Thank you!

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by vale217** [comment]
Hi! Thank you for considering my submission and sorry about that!! I think it should be fixed now :)

**Review by torbers — CHANGES_REQUESTED** [review]
Hi Valeria,
Your gerber.zip file should contain the PCB manufacturing files (copper layers, drills, board outline, etc.) rather than the source files (the .jsons). This should be the same file you uploaded to JLCPCB.
Also, it doesn't look like you've selected assembly, for your board, so there won't be any components soldered on, if you aren't expecting to assemble the board yourself. The PCB printing alone also looks like it will cost much more than usual - it should cost less than $20, but it seems like it's almost $75 in your cart. [Here's a reference](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) for how to make sure you use the correct printing options.
Thanks so much for participating - I can't wait to see your board!
tori

**Comment by LimesKey** [comment]
Hi @vale217!

Please feel free to ask for help if you need any here or [#electronics on Slack](https://hackclub.com/slack/?event=onboard). I'm closing this for cleanup right now, but if you get your PR fixed, please open up a new PR and link the old one!

**Pull request closed without merging**
