### PR TITLE
Pizzalover's NFC Card

### PR DESCRIPTION
**Pull request by pizzalover125**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/pizzaCard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ee78c8a92e727458b40a66f7f81f2ee395221d19/projects/pizzaCard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ee78c8a92e727458b40a66f7f81f2ee395221d19/projects/pizzaCard/schematic.pdf>) |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/ee78c8a92e727458b40a66f7f81f2ee395221d19/projects/pizzaCard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @pizzalover125,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Review by LimesKey — COMMENTED** [review]
Can you export your `PCB.json` from EasyEDA and put it in your `/src` fole as well?

**Comment by pizzalover125** [comment]
Added the PCB json file. What else do I need to do?

**Comment by LimesKey** [comment]
I see you selected `Standard Assembly`, that assembly method is very costly and not needed for this PCB. Can you chose Economic Assembly instead and go through the JLCPCB ordering process?

**Comment by pizzalover125** [comment]
With economic assembly, will I still get my text on the back?

**Comment by blazecoding2009** [comment]
> With economic assembly, will I still get my text on the back?

Yes, economic assembly is for the parts on the PCB, not the PCB itself

**Comment by pizzalover125** [comment]
Wait... am I done? It seems like @blazecoding2009 merged my request. Do I need to do anything else?

**Review by LimesKey — CHANGES_REQUESTED** [review]
It looks like you have no traces on your board, so none of your components will work. Can you fix that please?

**Comment by pizzalover125** [comment]
I just added traces! Did I do it right?

**Comment by LimesKey** [comment]
The trace for your antenna isn't connected, 
image
Make sure you run the DRC finder and it will show you all the problem with the PCB traces

**Review by LimesKey — CHANGES_REQUESTED** [review]
I can't seem to find your verification form, are you sure you submitted it with your correct GitHub username?

**Comment by pizzalover125** [comment]
Hmmm... that's odd. I did this for Sprig and got that in the mail. My Bin order was also approved. I ran /check-eligibility as well and it shows I am eligible.

**Comment by pizzalover125** [comment]
Is the technical side of my project done? Also, if I have money left over, am I able to design another PCB?

**Comment by LimesKey** [comment]
It's a different verification form, see here https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form

**Comment by LimesKey** [comment]
> Is the technical side of my project done? Also, if I have money left over, am I able to design another PCB?
yes

**Comment by pizzalover125** [comment]
Did that! Anything else?

**Comment by pizzalover125** [comment]
Any updates... ?

**Review by LimesKey — APPROVED** [review]
Hi @pizzalover125!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/v6lIpZ). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
