### PR TITLE
NFC Card

### PR DESCRIPTION
**Pull request by TheSaltTable**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi! Please put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) into the "src" folder. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

Also, your exported PDF needs to be from the schematic tab, not the PCB tab.

Your cart.png look good to me though, and I love the design!

**Comment by TheSaltTable** [comment]
Hello, thank you so much for the feedback. Although, I am having a bit of
trouble on how to get the two .JSON files

**Comment by TheSaltTable** [comment]
Actually I believe I did it. Whenever you are free, may you check it.

Best Wishes- Neel Patel

**Comment by karmanyaahm** [comment]
I think you uploaded the PCB.pdf again, the pdf file needs to be from the schematic tab, like [this one](https://github.com/hackclub/OnBoard/blob/main/projects/Alex%20P's%20NFC%20Card/schematic.pdf)

**Comment by TheSaltTable** [comment]
I am really sorry about that mistake. I have fixed it. The PDF is called
Schematic_USB project_2023=01-06.pdf. Also, I don't really know how to
delete the PCB.pdf file so is it fine if they can just stay there.

Best Wishes- Neel Patel

**Review by karmanyaahm — APPROVED** [review]
lgtm!

**Comment by karmanyaahm** [comment]
Have you filled out the verification form? If you already have, np, just waiting on that to get approved

**Comment by karmanyaahm** [comment]
cc @sarthaktexas

**Comment by TheSaltTable** [comment]
Hey I was wondering if there is anyone else I need to talk to so I can get
the second approval for the PCB card thing.

-Neel Patel

**Comment by karmanyaahm** [comment]
@TheSaltTable you've filled out [the airtable form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form) from the PR right?

**Comment by TheSaltTable** [comment]
Yes, I did.

**Review by sarthaktexas — APPROVED** [review]
approved! sent rn

**Pull request merged**
