### PR TITLE
Ali's NFCards

### PR DESCRIPTION
**Pull request by alialiwa2005**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection

### CODE REVIEW

**Comment by kvnyng** [comment]
Hey @alialiwa2005,

I see that you selected to make 25 boards. OnBoard currently asks orders to be made for 5 boards at a time, so you can make as many different boards as possible. It also lets you purchase additional boards in case your first design doesn't work. Can you resubmit a screenshot a cart with 5 boards only?

**Review by daisybanks — COMMENTED** [review]
Hey @alialiwa2005! Welcome OnBoard - so excited to have you participating!! Everything looks good on Bank's side @kvnyng!

**Comment by alialiwa2005** [comment]
> Hey @alialiwa2005,
> 
> I see that you selected to make 25 boards. OnBoard currently asks orders to be made for 5 boards at a time, so you can make as many different boards as possible. It also lets you purchase additional boards in case your first design doesn't work. Can you resubmit a screenshot a cart with 5 boards only?

Sure! Is it 5 boards per design?

**Comment by alialiwa2005** [comment]
> Hey @alialiwa2005,
> 
> I see that you selected to make 25 boards. OnBoard currently asks orders to be made for 5 boards at a time, so you can make as many different boards as possible. It also lets you purchase additional boards in case your first design doesn't work. Can you resubmit a screenshot a cart with 5 boards only?

Hi. 

Yes, I can.

I've updated the cart screenshot to have 5 PCBs for one of my NFCard designs (I have multiple different PCB designs).

I've also updated the README.md price, specifying the cost being around 25 dollars per 5 PCBs, dependent on PCB color used for each design.

image

**Comment by kvnyng** [comment]
@alialiwa2005 this looks great!

Thank you!

**Comment by kvnyng** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! In 24 hours, you should be receiving an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank ([@Daisy](https://hackclub.slack.com/team/U046V3EK56W) on Slack).
 
Now, you can finally get those PCBs ordered!:tada:

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

**Pull request merged**
