### PR TITLE
Fatuma's NFC Card

### PR DESCRIPTION
**Pull request by fatuma-tahalil**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [X] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 9575

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Fatuma_GitHub_Card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|❌ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/793f79d9c8f8f0fa2187d1ffbbfe3bbdced00015/projects/Fatuma_GitHub_Card/schematic.pdf>) | You must export your schematic file as schematic.pdf |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/793f79d9c8f8f0fa2187d1ffbbfe3bbdced00015/projects/Fatuma_GitHub_Card/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @342629342 

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by blazecoding2009** [comment]
Also PLEASE name your files correctly

**Comment by fatuma-tahalil** [comment]
Hey Blaze,

That's cool that you belong to Orbit Robotics. I visited your girl's build workshop this year.
Nice to see you're doing Arcade as well. :)

**Comment by blazecoding2009** [comment]
> Hey Blaze,
> 
> That's cool that you belong to Orbit Robotics. I visited your girl's build workshop this year.
> Nice to see you're doing Arcade as well. :)

Hey! 
Nice! Let me know on slack how we should improve and what we did well

**Comment by blazecoding2009** [comment]
Schematics.pdf should be named schematic.pdf

**Comment by fatuma-tahalil** [comment]
It is now named schematics.pdf

**Comment by fatuma-tahalil** [comment]
It is now named schematic.pdf

**Review by LimesKey — COMMENTED** [review]
Hi @fatuma-tahalil! 

You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order up to 5 assembled boards.

**Comment by fatuma-tahalil** [comment]
Hello,

I selected the parts and changed my carts.png.

**Comment by blazecoding2009** [comment]
@fatuma-tahalil Are you able to select a cheaper shipping option? We only give grants upto $50 for tutorial projects

**Comment by fatuma-tahalil** [comment]
@blazecoding2009 Yes, it is now under 50 dollars.

**Review by blazecoding2009 — APPROVED** [review]
Have fun! https://hcb.hackclub.com/grants/q3OIGB

**Pull request merged**
