### PR TITLE
Hackers buisness card

### PR DESCRIPTION
**Pull request by CodeSakshamY**
## Submission Checklist:

- [yes ] I am a current high school, middle school, or home schooled student.
  - [ yes] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ yes] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [yes ] I made this board from scratch, even if I followed a tutorial
- [ yes] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ yes] Created a folder under `onboard/projects`
  - [ yes] Filled out `TEMPLATE.md` as `README.md`
  - [yes ] Uploaded Gerber.zip and Schematic.pdf
  - [ yes] Created a folder called `src` and uploaded design files
  - [ yes] Uploaded screenshot of PCB order with all costs included
  - [ yes] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [yes ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ yes] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/hackercard_CodeSaksham:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by MichaByte** [comment]
Hi @CodeSakshamY!

It looks like the screenshot you took is of the ordering page, not your cart. That means that the price of $13.50 is lower than it will be, since that doesn't include any parts. Could you please go through the rest of the steps by clicking "Next" and take another screenshot once you get to the cart? Once you do that, I can get you your grant! Let me know or join [#electronics on Slack](https://hackclub.com/slack/?event=onboard) if you have any questions!

**Comment by CodeSakshamY** [comment]
Hi
I have added the screenshot of the final bill here.

Thanks.

**Comment by MichaByte** [comment]
Hi @CodeSakshamY!
I've just sent you [your grant for OnBoard](https://hcb.hackclub.com/grants/qlYIPP). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please keep this in mind before you make any purchases.**

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
