### PR TITLE
Add "Hack-n-roll" Board

### PR DESCRIPTION
**Pull request by 120Chicken120**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/hack-n-roll:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Hey @120Chicken120! Are you getting parts assembled onto your board or are you soldering them on yourself? If you need parts from JLC, check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to select those options.

**Comment by karmanyaahm** [comment]
Other than that your design and student verification looks good to me

**Comment by 120Chicken120** [comment]
Hi, Hackclub,

I couldn't find out how to put the template.md into the README.md. The
shipping is quite expensive from the JLCPCB. Could I change it to order
from OSH park instead?

Thanks

**Comment by karmanyaahm** [comment]
Yes, feel free to change it to oshpark, just delete the cart.png from your repo and reupload it with an oshpark cost estimate

**Comment by maxwofford** [comment]
Hey @120Chicken120, I haven't heard anything so I'm going to go ahead and remove this from our review queue for the time being. We can open it back up once you're ready!

**Pull request closed without merging**
