### PR TITLE
GatesAddition: Addition of binary digits using a 4-bit adder IC.

### PR DESCRIPTION
**Pull request by Pradevel**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — APPROVED** [review]
Wow, this is the first digital logic OnBoard project (IIRC). Really excited to see a video of it working.

**Review by daisybanks — APPROVED** [review]
Welcome OnBoard @Pradevel! Everything looks good on HCB's side @hackclub/boarding-party. :)

**Comment by karmanyaahm** [comment]
Hi @Pradevel, how did you project go? Do you have any pictures of the board? We'd love to share it with the OnBoard community because this is a really cool idea!

**Comment by Pradevel** [comment]
Actually I messed up in one part of the circuit (I missed some resistors) I need to buy some and Re add those manually... I'll probably complete it by this month. And I'll surely upload some pics after the completion.

**Comment by karmanyaahm** [comment]
Sorry for pinging again @Pradevel. Just curious have you gotten it working? If you need help fixing it, please don't hesitate to ask in #onboard on Slack!

**Comment by Pradevel** [comment]
It's no problem! I was actually busy with school these days but I'll surely debug the problem and fix it.

If I need help contact the server for sure!
Thanks, again.

**Pull request merged**
