### PR TITLE
Max's Tiny4FSK

### PR DESCRIPTION
**Pull request by maxsrobotics**
## Submission Checklist:

- [x ] I am a current high school, middle school, or home schooled student.
  - [ x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x ] I made this board from scratch, even if I followed a tutorial
- [x ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x ] Created a folder under `onboard/projects`
  - [x ] Filled out `TEMPLATE.md` as `README.md`
  - [x ] Uploaded Gerber.zip and Schematic.pdf
  - [ x] Created a folder called `src` and uploaded design files
  - [x ] Uploaded screenshot of PCB order with all costs included
  - [x ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Tiny4FSK:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|🟨 | schematic.pdf | Manually check schematic.pdf |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/709f2f3a155f0e8622ddba1c05f0b35de00cbf99/projects/Tiny4FSK/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Awesome! Looking forward to seeing how your board turns out! I want to learn to make some more Ham Radio PCBs myself.

**Comment by karmanyaahm** [comment]
Grant emailed!

**Comment by maxsrobotics** [comment]
Thanks so much! I'll post pictures in the Slack!

**Pull request merged**
