### PR TITLE
Jesse Beteas project

### PR DESCRIPTION
**Pull request by StuoodJ**
## Submission Checklist:

- [yes ] I am a current high school, middle school, or home schooled student.
  - [yes] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [yes ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ yes] I made this board from scratch, even if I followed a tutorial
- [ yes] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [yes ] Created a folder under `onboard/projects`
  - [ yes] Filled out `TEMPLATE.md` as `README.md`
  - [yes ] Uploaded Gerber, sources, and schematic
  - [ yes] Uploaded screenshot of PCB order with all costs included
  - [yes ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [yes ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [no ] (Optional) This project is from a tutorial[^1].
- [ yes] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: __6566__

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/b50a75bd3db3bacdd6c094d5ef8be27862706735/projects/jesse betea's rc motor driver/Gerber_arduinomotor_PCB.zip>)!

  Happy OnBoarding!

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi Jesse! Love the idea! I sooo want to see more robots and cars built using OnBoard. Just a couple of small issues with the submission, and once you fix them we can get you your grant:

Additionally, please make a "src" folder in projects/[name]/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab. You already have the PCB.json file.

Also, your schematic file should be a PDF from the schematic tab (in the schematic tab go to [File > Export > PDF](https://docs.easyeda.com/en/Export/Export-Schematic/index.html)), and upload that. Right now your PDF is from the PCB tab.

**Review by sarthaktexas — APPROVED** [review]
student verification approved :)

**Comment by StuoodJ** [comment]
I fixed the problems with the submission

**Review by karmanyaahm — APPROVED** [review]
LGTM! You should get an email with your grant in 24-48 business hours!

**Comment by StuoodJ** [comment]
Thank you so much!

**Comment by sarthaktexas** [comment]
sent!

**Pull request merged**
