### PR TITLE
ItzHex_NFC_Card

### PR DESCRIPTION
**Pull request by Itz-Hex**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
For your board to work with NFC, you need to assemble components on top of it. Check out this image on slack for how to do that: https://hackclub.slack.com/archives/C056AMWSFKJ/p1694630882690769?thread_ts=1694630755.537299&cid=C056AMWSFKJ

**Comment by Itz-Hex** [comment]
Right. I think I've done that and reuploaded it to here now. Thanks.

**Review by karmanyaahm — APPROVED** [review]
LGTM

**Comment by karmanyaahm** [comment]
Have you filled out the verification form? @daisybanks should contact you if so.

**Comment by Itz-Hex** [comment]
Yep. I did that when I submitted the request.

**Comment by daisybanks** [comment]
Hi @Itz-Hex, please check your email (including spam). For your student verification I need to be able to see your name, grade, and the academic year please.

**Comment by Itz-Hex** [comment]
> Hi @Itz-Hex, please check your email (including spam). For your student verification I need to be able to see your name, grade, and the academic year please.

I can't seem to find an email from you anywhere. I've check spam.

**Comment by daisybanks** [comment]
ollie@olliewells.co.uk is the email I sent it to. The email I sent asks for the same information asked for above for your student verification if you can send that over to daisy@hackclub.com.

**Comment by Itz-Hex** [comment]
I've just sent that to you now.

**Review by daisybanks — APPROVED** [review]
Approving for HCB's side @hackclub/boarding-party and @Itz-Hex. :)

**Pull request merged**
