### PR TITLE
HackerBadge with Battery

### PR DESCRIPTION
**Pull request by LimesKey**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/HackerPCBNameTag:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by maxwofford — APPROVED** [review]
Oooh, this looks awesome! I love that you're driving it from a battery– I've seen a lot of NFC tags so far, but not a powered one yet. Because this is sufficiently different from the tutorial this is eligible for the full $100 (USD) grant, not just the $50 NFC card grant

**Comment by maxwofford** [comment]
@LimesKey are you helping organize Apocalypse?

**Comment by LimesKey** [comment]
I am

**Comment by maxwofford** [comment]
I just [sent the grant](https://hcb.hackclub.com/grants/w4DI41)! I assume you're shipping to Canada based on your prices being in CAD, so you might want to double check customs fees for the different shipping methods– the grant card doesn't cover customs.

**Comment by LimesKey** [comment]
Thanks, I am shipping to Canada, and I can pay customs fees, thanks for letting me know.

**Pull request merged**
