### PR TITLE
Elias Duckworth PCBHeater

### PR DESCRIPTION
**Pull request by EliasDuck**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/PCBHeater:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|❌ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/89c2784a43dccd5c7fb85deced193c8477fd3a6e/projects/PCBHeater/schematic.pdf>) | You must export your schematic file as schematic.pdf |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/89c2784a43dccd5c7fb85deced193c8477fd3a6e/projects/PCBHeater/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by EliasDuck** [comment]
Sorry, but I'm a bit confused. I could use some guidance as to how to correctly format the PR. I think I attached all the right files and filled out all the forms, but I could just use some confirmation or aid as to the formatting. Thank you! -Elias D

**Comment by MichaByte** [comment]
Hi @EliasDuck! 

You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, buttons, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order 5 assembled boards.

Also, make sure that your `schematic.pdf` file starts with a lowercase `s` - our bot is a little picky!

Please feel free to ask for help here or on the [#electronics on Slack](https://hackclub.com/slack/?event=onboard) if you need any!

**Comment by EliasDuck** [comment]
Thank you so much for letting me know. For now please make sure my PR is
not filed/my PCB isn’t ordered because I do need the PCB with the
components. I cannot rename the files and everything because it was not
done through a personal computer. If you would like, I can email you next
week when everything is squared away, but for now please don’t order my
pcb. Let me know if there are any other problems
Thank you so much
-Elias D

**Comment by EliasDuck** [comment]
My mistake, I thought I needed assembly, but I realized I don't. The PR should be good to go.

**Comment by MichaByte** [comment]
Hi @EliasDuck!
I've just sent you [your grant for OnBoard](https://hcb.hackclub.com/grants/vbpIAp). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please keep this in mind before you make any purchases.**

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
