### PR TITLE
Spookydoro

### PR DESCRIPTION
**Pull request by Ahnaf-nub**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [X] (Optional) This project is for [Trick or Trace](https://showcase.hackclub.com/)[^3].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Spookydoro:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/55ffb89a833ec5820307ae15cfed5f868f4ea6ee/projects/Spookydoro/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/55ffb89a833ec5820307ae15cfed5f868f4ea6ee/projects/Spookydoro/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/55ffb89a833ec5820307ae15cfed5f868f4ea6ee/projects/Spookydoro/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — COMMENTED** [review]
Really cool design, at first it looked a little bit wonky in the gerber viewer but in your JLCPCB cart image, the white color makes it look really nice. I hope this wins! I just wanted to confirm that no JLCPCB assembly is intentional and that you'll be assembling it yourself?

**Comment by Ahnaf-nub** [comment]
Thanks @LimesKey !! And Yes I'm going to assemble it by myself!

**Review by LimesKey — COMMENTED** [review]
Because your order total is so little - you're free to order more than 5 if you'd like. Or not, the rest of the grant money you can spend on anything you'd like electronics-related and not just PCB manufacturing.

**Review by LimesKey — APPROVED** [review]
Hi @Ahnaf-nub!

Thanks for submitting your design to [Trick or Trace](https://trickortrace.hackclub.com/)! Project voting opens Oct 21st, check in to [#electronics](https://slack.com/archives/C056AMWSFKJ) (in the Slack) or on the [website](https://trickortrace.hackclub.com/) for the link to see your project in the gallery, and to vote on other's designs. Look forward to receiving a small package in the mail in the next few weeks, just a small gift to continue you on your journey of making.

**Comment by Ahnaf-nub** [comment]
> Because your order total is so little - you're free to order more than 5 if you'd like. Or not, the rest of the grant money you can spend on anything you'd like electronics-related and not just PCB manufacturing.

Umm, does that mean i can use the remaining 47.98$ on anything i want electronics related? and I can order this pcb through jlcpcb with that grant money?

**Comment by LimesKey** [comment]
Yes

**Comment by Ahnaf-nub** [comment]
Screenshot 2024-10-23 154458

I'm trying to order these but its saying Purchase declined at SEEEDSTUDIO.

**Comment by LimesKey** [comment]
OnBoard grants are only for JLCPCB orders, and you haven't gotten a Trick or Trace grant yet.

**Pull request merged**
