### PR TITLE
Sai_PCB

### PR DESCRIPTION
**Pull request by SaiGodavarthi**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 2079

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Sai_PCB:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|❌ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/0a1997c56c09648372dbeb7682341d56db342875/projects/Sai_PCB/schematic.pdf>) | You must export your schematic file as schematic.pdf |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/0a1997c56c09648372dbeb7682341d56db342875/projects/Sai_PCB/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @SaiGodavarthi,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by SaiGodavarthi** [comment]
Hi, I am unsure how to change my cart.png image, but I will upload the new
image here. If I need to upload it in GitHub, please guide me!

Thank you,
Sai Kushal Godavarthi

**Comment by SaiGodavarthi** [comment]
Hi,it’s linked in the email above, not on GitHub.

Thank you,
Sai Kushal godavarthi

**Comment by LimesKey** [comment]
I'm unable to see your image by email, please upload it here on GitHub.

**Comment by SaiGodavarthi** [comment]
Hi,

Could you guide me? My folder, Sai_PCB, is not showing up in the onboard
projects folder, and I don’t know how to edit edit the existing submission

Thank you

**Comment by SaiGodavarthi** [comment]
Can you let me know if you can see it?

cart

**Comment by LimesKey** [comment]
If you're looking in the official onboard repository, it won't show up as your pull request hasn't been merged yet. You need to be looking at your forked repository. Go to the pull request you have here, https://github.com/hackclub/OnBoard/pull/832, then click the "Paste, drop, or click to add files" to add a image.

**Comment by LimesKey** [comment]
I see it thanks!

**Comment by SaiGodavarthi** [comment]
Thank you so much!!!

**Pull request merged**
