### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by spencerl20**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by sarthaktexas — APPROVED** [review]
Howdy Spencer! I'm approving your student verification :) The next step will be to wait 24-48 hours for the technical review and then your PR will be merged and you'll receive your grant! [@hackclub/boarding-party](https://github.com/orgs/hackclub/teams/boarding-party)

**Review by karmanyaahm — APPROVED** [review]
Hi! Please put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) into the "src" folder. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

Also, your exported PDF needs to be from the schematic tab, not the PCB tab.

Your  cart.png look good to me though, and I love the design!

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
oops my bad, that was supposed to be a request changes

**Comment by spencerl20** [comment]
I've added the JSON files and the schematic pdf now

**Review by karmanyaahm — APPROVED** [review]
Awesome!

**Comment by karmanyaahm** [comment]
You should get an email with your grant in 24-48 business hours!

**Comment by spencerl20** [comment]
Thank you so much!

**Pull request merged**
