### PR TITLE
FPV flight controller

### PR DESCRIPTION
**Pull request by joennematti**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/DIY 30x30 FPV FC:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @joennematti Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

Also it seems that you haven't selected assembly, is this purposefully?

**Comment by blazecoding2009** [comment]
Hey @joennematti 

You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order up to 5 assembled boards.

**Comment by joennematti** [comment]
I haven't selected assembly as I plan to assemble the PCB myself. I will order the parts for assembly directly from LCSC.

**Comment by blazecoding2009** [comment]
Sounds good, just to note that as far as I understand, we do not allow you to buy the parts after ordering the PCB.

**Comment by joennematti** [comment]
Ok, I’ll go ahead and have it assembled then. Should I update the shopping cart image as well?

**Comment by joennematti** [comment]
Changed!

**Comment by blazecoding2009** [comment]
Hi @joennematti,
The most we can offer for the grant is $100. Here are some suggestions for reducing the price:


* Select PCBA for only two boards rather than all 5. You will still receive all 5, but only two will have components.
* Select green soldermask and leaded HASL finish
* Make sure as many parts as possible are "Basic" or "Preferred Extended" parts; these parts have the $3 assembly fee waived. Here is the list: https://jlcpcb.com/parts/basic_parts
* Use a coupon by JLCPCB for a minor price reduction

If the cost still ends up above $100, DM me on Slack (@your name) and I can help you pay the remainder with your own card.
Thanks!

**Review by blazecoding2009 — APPROVED** [review]
Hey @joennematti 

I've just sent your [grant](https://hcb.hackclub.com/grants/vGyIe7) :) Please keep sending me updates on this! I'm very excited to see this work! I'm going to be building one myself later too!

**Pull request merged**
