### PR TITLE
Added my PCB

### PR DESCRIPTION
**Pull request by TheHackerDude1083**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/fba3dfca87ecf7ddcaca7a40655bc4d458c97ca2/projects/ShaheerNFCCard/Gerber_PCB_New Project_2024-01-26.zip>)!

  Happy OnBoarding!

**Comment by TheHackerDude1083** [comment]
Hello, Looks good

**Comment by BrightTheBackpack** [comment]
Hi, did you mean to close this? If you want people to review it so you get your grant, you need to reopen this pull request.

**Comment by BrightTheBackpack** [comment]
nvm, i see your new one

**Comment by TheHackerDude1083** [comment]
Yes I meant to close this I forgot to add the components and this was only the PCB. I have made a proper new pull request.

**Comment by Hugoyhu** [comment]
Has been reopened as PR#330

On Jan 26, 2024, at 10:31 PM, BrightTheBackpack ***@***.***> wrote:



Hi, did you mean to close this? If you want people to review it so you get your grant, you need to reopen this pull request.

**Pull request closed without merging**
