### PR TITLE
PCB grant for Sign language gloves

### PR DESCRIPTION
**Pull request by PilliSiddharth**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by MichaByte** [comment]
Hi @PilliSiddharth!
This board looks awesome, I love seeing accessibility projects here! Do you think you could select the cheapest shipping option and re-upload `cart.png`? $40 is a lot for shipping, and we want you to have money left over for future projects!

**Comment by PilliSiddharth** [comment]
hey @MichaByte, I guess the 40$ is the cheapest option 🥶, but if your cool with it I can try using some local vendors here where I can probably get it for even cheaper instead of JLCPCB, if that works for you?

**Comment by karmanyaahm** [comment]
Hey @PilliSiddharth are you using "Air Registered Mail" for shipping?

**Comment by PilliSiddharth** [comment]
oh lol yeah air registered mail is cheaper, I didn't notice it before xd, it's costing now $17.01

**Comment by MichaByte** [comment]
Hi @PilliSiddharth!
I've just sent you [your grant for OnBoard](https://hcb.hackclub.com/grants/vm3Ied). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please keep this in mind before you make any purchases.**

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
