### PR TITLE
ESPHome HAN Reader

### PR DESCRIPTION
**Pull request by Lazylllama**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/esphome-han-reader:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/b4f4abc1f3f47d927ea4f9d8877d2fe9f8db1124/projects/esphome-han-reader/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/b4f4abc1f3f47d927ea4f9d8877d2fe9f8db1124/projects/esphome-han-reader/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/b4f4abc1f3f47d927ea4f9d8877d2fe9f8db1124/projects/esphome-han-reader/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
This is one of the most interesting projects I've seen, it's so cool you're able to do this and monitor your power usage this way. A few questions though,
* Is there a reason you chose to not use a USB-C port for flashing the microcontroller, and instead opted to have the male pin headers?
* Why are you using Tantalum Capacitors and not regular MLCC capacitors which are much smaller and used for decoupling?
* You might want to use thicker power traces, especially for 3V. Also, a GND fill wouldn't hurt.

**Comment by Lazylllama** [comment]
Heya, just woke up from my 6 hour sleep haha. Thank you! I can't take all the credit though for this. The firmware is already made and theres a whole repository about this https://github.com/psvanstrom/esphome-p1reader, It's really awesome though!

1. Putting an USB-c port for flashing would require me to put the programmer onboard and that would make insane, since I have like every single type of ESP at home, I also have programmers for them so It's much easier for me to just program it once, shove it in my electrical box and be done with it.
2. This is probably the part on my PCB that I understand the least. I had to ask ChatGPT if I needed the capacitors when I first made the schematic cause I saw it on another PCB and it told me yes and explained how and other yap, It also recommended tantalum capacitors cause of I think it was more stability and lower "ESR" no clue what that is. Couldn't really find anything about the cap thing on google. Let me know If I should switch, I have no clue what I'm doing for that part other than 5v -> 3.3v _(Just noticed I had switched the volt in and out on my schematic, fixed on my next commit.)_
3. Yeah, I used to have that. Then JLCPCB told me I could only assemble on one side so had to remake the entire layout and traces and at like 4AM I lost my will to live and used freerouting which didn't take that into account, will fix and also make them straighter. For ground fill, I simply have no idea how to do that. It looks awesome, but my skills are not awesome. Also felt like it would be a royal pain in the arse if i need to move one single trace even a mm. Gonna look at some youtube videos and try to implement it though.

**Comment by LimesKey** [comment]
Makes sense, however, if it were me I would have gone with a simple ESP32 chip you can find commonly around LCSC, then it'd be quite simple to program it with a USB-C connector. I have never seen that specific variety of microcontrollers before.

> recommended tantalum capacitors cause of I think it was more stability and lower "ESR"

This is true but you don't need it for your design, it's only for larger power supplies and sensitive components and such. Use these, they're much smaller, have a higher capacitance and will work as a replacement, https://jlcpcb.com/partdetail/4414076-GRM158R61A226ME15D/C3845593. I'd also recommend swapping out your voltage regulator for either the `Texas Instruments TLV76133DCYR` or `Texas Instruments TLV1117LV33DCYT`, both are pretty common and should be more efficient. 

> For ground fill, I simply have no idea how to do that. It looks awesome, but my skills are not awesome
It's very easy in KiCad, like it takes a minute and is really easy to re-fill when you update your traces. Look up online how to do that, it should be simple.

**Comment by Lazylllama** [comment]
I ended up adding an FTDI chip with an USB-C port as input and staying with my ESP-07. I switched my caps to 22uF caps like the ones you linked and my LDR to an Texas Instruments TLV1117LV33DCYT like you said and ALOT of component adjustments for pricing. Learnt how to do ground fill 1 minute after I sent the message :P.

Hopefully this is my last revision! Happy holidays 🎄

**Review by LimesKey — APPROVED** [review]
Hi @Lazylllama!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/DZIjkJ). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the [#electronics](https://slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/) once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
