### PR TITLE
Add PCBWay to vendors

### PR DESCRIPTION
**Pull request by aicoder2009**
This is litteraly the only place that can manufacture my order the name is "PCBWay"

### CODE REVIEW

**Comment by maxwofford** [comment]
Thanks for submitting this! I'm hopping between meetings right now, but I'll check this out once I'm out of them.

**Comment by maxwofford** [comment]
@aicoder2009 so I have more context, what features or specific parts can PCBWay only assemble?

**Comment by maxwofford** [comment]
Ok, I checked them out and it looks like they [don't follow our requirements for a vendor](https://github.com/hackclub/OnBoard/pull/77#issuecomment-1576920465).

That said, I def want to make sure your board can still get manufactured. Can you share more about what you're trying to make? I could only find your [NFC design](https://github.com/hackclub/OnBoard/pull/298/files), but it looks like that's orderable on OSHPark, which is an approved vendor.

**Review by sarthaktexas — APPROVED** [review]
Howdy Karthick! I'm approving your student verification :) The next step will be to wait 24-48 hours for the technical review and then your PR will be merged and you'll receive your grant! [@hackclub/boarding-party](https://github.com/orgs/hackclub/teams/boarding-party)

**Comment by karmanyaahm** [comment]
Closing as Max explained above

**Pull request closed without merging**
