### PR TITLE
scg-nfc-card

### PR DESCRIPTION
**Pull request by Rj2500**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/scg-nfc-card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/b1c2fdb65cd2e29c9fab1d616dae8f570b82ff55/projects/scg-nfc-card/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/b1c2fdb65cd2e29c9fab1d616dae8f570b82ff55/projects/scg-nfc-card/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/b1c2fdb65cd2e29c9fab1d616dae8f570b82ff55/projects/scg-nfc-card/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Rj2500** [comment]
I think the LED part of the schematic is backwards but on the actual PCB it isn't as far as I know

**Review by maxwofford — CHANGES_REQUESTED** [review]
You might want to flip the LED in your schematic. It won't work backwards and if JLCPCB checks it based on your schematic they might place the part backwards.

**Comment by Rj2500** [comment]
Ok, after three or four moments where I wondered if I knew how to follow a tutorial, I think I've got both the PCB file and the schematic flipped around from 2 ->7 to 7 -> 2. Sorry for all the commits I apparently can't manage GitHub correctly...

**Comment by Rj2500** [comment]
Ok, after three or four moments where I wondered if I knew how to follow a tutorial, I think I've got both the PCB file and the schematic flipped around from 2 ->7 to 7 -> 2. Sorry for all the commits I apparently can't manage GitHub correctly

**Comment by Rj2500** [comment]
Hi, it's been a few days. I think I read somewhere that May 1 was a holiday, and that's okay. But, even not counting that day it's still been about 2 or 3 days. Have I done something wrong?

**Pull request closed without merging**
