### PR TITLE
Grant Application

### PR DESCRIPTION
**Pull request by VM-fll**
## Submission Checklist:

- [ ] I am a current high school, middle school, or home schooled student.
  - [ ] I am 18 or under
  - [ ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ ] I made this board from scratch, even if I followed a tutorial
- [ ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ ] Created a folder under `onboard/projects`
  - [ ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ ] Created a folder called `src` and uploaded design files
  - [ ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Vansh-PCB:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/b262e41e6983e53e667f3a1ac89cea68e77b71a2/projects/Vansh-PCB/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/b262e41e6983e53e667f3a1ac89cea68e77b71a2/projects/Vansh-PCB/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/b262e41e6983e53e667f3a1ac89cea68e77b71a2/projects/Vansh-PCB/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @VM-fll,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by VM-fll** [comment]
Hi here is the picture
cart

**Comment by LimesKey** [comment]
Thanks for that, but i'm having trouble finding your verification form, are you sure you submitted it with your correct GitHub username?

**Comment by VM-fll** [comment]
yes, I believe I did a verification form for arcade. Do I need to fill one out again? And if so where do I fill it out?

**Comment by LimesKey** [comment]
Your proof of high school verification isn't valid, can you resubmit the verification form with a different piece of identification? Ask in #onboard-help what verification you can use for suggestions.

**Comment by VM-fll** [comment]
I got an email saying my verification was approved
IMG_1917

**Review by LimesKey — APPROVED** [review]
Hi @VM-fll!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/wPxI62). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by LimesKey** [comment]
My mistake, I mixed up your pull request and online form with somebody else.

**Comment by LimesKey** [comment]
You submitted the verification form for Aracde but not for Onboard, fill out the [Onboard Verification Form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form).

**Comment by VM-fll** [comment]
Hi I just did the form, did not realize it was different from arcade!

**Comment by LimesKey** [comment]
Apologies about that, someone else had a similar name to yours and it confused me. Your grant is [here](https://hcb.hackclub.com/grants/qnZIza).

**Comment by VM-fll** [comment]
Hi! So once I spend this $50 do I get the other $50 for other pcb builds/iterations?

**Comment by LimesKey** [comment]
Yep

**Pull request merged**
