### PR TITLE
Artsey Ergo

### PR DESCRIPTION
**Pull request by tmshader**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Artsey-Ergo:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/67cf7d8b50e202b7068b995efb98685511e900d5/projects/Artsey-Ergo/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/67cf7d8b50e202b7068b995efb98685511e900d5/projects/Artsey-Ergo/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/67cf7d8b50e202b7068b995efb98685511e900d5/projects/Artsey-Ergo/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
I see you've selected Standard PCB assembly, is there any way you can use economic instead?

**Comment by tmshader** [comment]
Thanks for the quick review! :)
I didn't notice it was on Standard PCB assembly, I looked into it and it's because black soldermask + ENIG is not available on Economic PCB assembly. :(
I removed ENIG, uploaded my updated `cart.png` and updated the price in `README.md`.

**Comment by LimesKey** [comment]
I enjoy having you submit all your files, but I worry that the increased file size from your project will make it difficult for others to clone the repo. Are you able to only have the required files in your pull request, but add a link in the README to your personal repo containing the rest of the files?

**Comment by tmshader** [comment]
I updated the pull with the requested changes.

I think it could be helpful in the future to add to the main README of this repo some instructions about projects with big and/or lot of files and how and where to upload those. Usage of `github.dev` could also be added to the README, because people won't have to clone the full repo to make slight adjustments to their submissions.

**Comment by tmshader** [comment]
Hey @LimesKey !

Any update on this?

**Comment by LimesKey** [comment]
> Usage of github.dev could also be added to the README
Are you able to create an issue for this? This would be a great addition to speed up repo clones!

I see you've moved the files to your own repo, but are you still able to add one PCB out of the many you've made to this pull request? Even though you have multiple, can you add your most worked on PCB's `.kicad_pcb`, `.kicad_pro` and `.kicad_sch`?

**Comment by tmshader** [comment]
My schematic is split into multiple files (but they are not huge in size), should I upload all of those or only just the pdf?

**Comment by LimesKey** [comment]
Can you upload the largest schematic file on which you worked the most?

**Review by LimesKey — APPROVED** [review]
Hi @tmshader!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/WPI1eK). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the [#electronics](https://slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/) once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
