### PR TITLE
Lightwand

### PR DESCRIPTION
**Pull request by themagicfrog**
I already submitted for Onboard -> https://github.com/hackclub/OnBoard/tree/main/projects/lightwand but I realized that I accidently had my address and phone number on the cart.png so I just blocked that info out for privacy. Thanks! :)

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/lightwand:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/46c8a3d441902c396771381a98e402f523b41f0b/projects/lightwand/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/46c8a3d441902c396771381a98e402f523b41f0b/projects/lightwand/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/46c8a3d441902c396771381a98e402f523b41f0b/projects/lightwand/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
I went back and rebased your repo to delete the original cart.png commit

**Comment by karmanyaahm** [comment]
So I think the git history is clean now too

**Comment by themagicfrog** [comment]
Awesome! Thank you so much

**Comment by karmanyaahm** [comment]
@themagicfrog can you go to [this link](https://github.com/hackclub/OnBoard/pull/873/files) and see if u have deletion perms 
image

**Comment by themagicfrog** [comment]
[image: Screenshot 2024-07-30 at 7.45.40 PM.png] i don't think so

**Comment by karmanyaahm** [comment]
Huh, you could email GitHub support to delete that if youd like

**Pull request merged**
