### PR TITLE
Tamzid's NFC Card PCB

### PR DESCRIPTION
**Pull request by tamzid1000**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
You need to select "Economic", not "Standard assembly" from JLCPCB. Economic saves a lot of money and is enough for the Hacker Card. Please look at the options selected here https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-assembly for how to do this.

BTW, you can keep editing your repo, and the changes will reflect in this PR. You don't have to close it and reopen it.

**Review by sarthaktexas — APPROVED** [review]
Howdy Tamzid! I'm approving your student verification :) Once @karmanyaahm approves your grant, I'll send it over.

**Review by karmanyaahm — APPROVED** [review]
LGTM. Sarthak will send your grant in 24-48 hours!

**Comment by karmanyaahm** [comment]
@sarthaktexas pinging just to put this on your TODO list whenever you're back at work.

**Comment by tamzid1000** [comment]
@sarthaktexas hi, i'm still up for the PCB. Let me know when you're available to send the grant?

**Comment by tamzid1000** [comment]
@karmanyaahm you can also take a look into this and help me out?

**Comment by sarthaktexas** [comment]
Hey! I sent it a while ago, can you check your spam?

**Comment by sarthaktexas** [comment]
We don't have an email for you, that's why you didn't get the grant, can you email me at sarthak@hackclub.com and then I'll send it!

**Comment by tamzid1000** [comment]
@sarthaktexas, my hcb email is: sj16-3ev-155@sjs.edu.bd

**Comment by sarthaktexas** [comment]
sent!

--
*Sarthak Mohanty*
*operations + engineering contributor*
cv <https://read.cv/srtk> / web <https://sarthakmohanty.me/> / github
<https://srtk.me/gh>

meet with me: https://cal.com/sarthak-mohanty/hcb
slack: @sarthak
call / text: +1 (415) 849-0024
email: ***@***.***

*Hack Club is an open source
<https://github.com/hackclub/hackclub> and financially transparent
<https://bank.hackclub.com/hq/> 501(c)(3) nonprofit. Our EIN is 81-2908499.
By the students, for the students.*

*Clubs <https://hackclub.com/> • Slack
<https://hackclub.com/slack/> • Fiscal Sponsorship
<https://hackclub.com/hcb/> • Hackathons <https://hackathons.hackclub.com/>*

**Pull request merged**
