### PR TITLE
creating new project

### PR DESCRIPTION
**Pull request by arielTROY**
## Submission Checklist:

- [ /] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [/ ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ /] I made this board from scratch, even if I followed a tutorial
- [ /] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [/ ] Created a folder under `onboard/projects`
  - [ /] Filled out `TEMPLATE.md` as `README.md`
  - [ /] Uploaded Gerber, sources, and schematic
  - [ /] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Wow this is such a cool idea! Please upload your schematic from EasyEDA as 'schematic.pdf' https://docs.easyeda.com/en/Export/Export-Schematic/index.html

And, just like your exported PCB_PCB_sfstgr...json, please export a JSON from the schematic tab and upload it here.

For the cart image, if you close the tab you put a screenshot of right now, it should save to "my orders". We need an image like this one that shows a summary of the PCB and Assembly parameters: https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#cart

Looking forward to seeing the console!

**Comment by arielTROY** [comment]
> Wow this is such a cool idea! Please upload your schematic from EasyEDA as 'schematic.pdf' https://docs.easyeda.com/en/Export/Export-Schematic/index.html
> 
> And, just like your exported PCB_PCB_sfstgr...json, please export a JSON from the schematic tab and upload it here.
> 
> For the cart image, if you close the tab you put a screenshot of right now, it should save to "my orders". We need an image like this one that shows a summary of the PCB and Assembly parameters: https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#cart
> 
> Looking forward to seeing the console!

no problem i will update the files. what about the grant?

**Comment by karmanyaahm** [comment]
You'll get the OnBoard grant in 24-48 hrs after your PR is merged.

**Comment by arielTROY** [comment]
@karmanyaahm thank you , i updated the pull request with the neccesery files

**Comment by arielTROY** [comment]
i would be happy if you can check it soon

**Review by daisybanks — APPROVED** [review]
I'm approving student verification! Once the pr is merged in 24-48 hours (after technical review after your changes) I will send the grant. :) @hackclub/boarding-party

**Comment by arielTROY** [comment]
@daisybanks thank you :) hope you liked the idea

**Review by karmanyaahm — APPROVED** [review]
lgtm

**Comment by karmanyaahm** [comment]
You should receive an email with your grant credit card soon after this! Please post in the OnBoard channel and someone will guide you through the process of adding more money to your grant.

**Comment by arielTROY** [comment]
@karmanyaahm thank you very much

**Pull request merged**
