### PR TITLE
Flipper Zero addon board

### PR DESCRIPTION
**Pull request by cryptopapi713**
## Submission Checklist:

- [✅] I am a current high school, middle school, or home schooled student.
  - [✅] I am 18 or under
  - [✅ ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ ✅] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ ✅] I made this board from scratch, even if I followed a tutorial
- [ ✅] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ ✅] Created a folder under `onboard/projects`
  - [✅ ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ ✅] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ ✅] Created a folder called `src` and uploaded design files
  - [ ✅] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ ✅] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ✅] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Business Card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/10eb1966615e2efc062ed0a09d8de4e51da81bf4/projects/Business Card/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/10eb1966615e2efc062ed0a09d8de4e51da81bf4/projects/Business Card/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/10eb1966615e2efc062ed0a09d8de4e51da81bf4/projects/Business Card/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by blazecoding2009** [comment]
@cryptopapi713 Please don't delete and recreate PRs when we are requesting a change even if you have fixed it. PRs auto update when you commit files even after you have created the PR

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
It seems that you have selected Standard PCBA. Please try selecting Economic as it is much cheaper and has almost no difference for what you're trying to make. (This should drastically drop your price from $90 to 60)

**Comment by cryptopapi713** [comment]
> It seems that you have selected Standard PCBA. Please try selecting Economic as it is much cheaper and has almost no difference for what you're trying to make. (This should drastically drop your price from $90 to 60)

I drastically changed my design and opted for a more practical PCB. This is thanks to my friend, who showed me how to use a Easy EDA. This board hooks up to my flipper and gives it tons of extra uses. It comes out to 97 dollars after a -9 dollar coupon.

**Comment by blazecoding2009** [comment]
I see, alright. I just want to remind you that you only get 1 grant so please see if you can reduce it at all. If you cannot, I'll go ahead and send you grant @cryptopapi713

**Comment by blazecoding2009** [comment]
I see, alright. I just want to remind you that you only get 1 grant so please see if you can reduce it at all. If you cannot, I'll go ahead and send you grant @cryptopapi713

**Comment by cryptopapi713** [comment]
> I see, alright. I just want to remind you that you only get 1 grant so please see if you can reduce it at all. If you cannot, I'll go ahead and send you grant @cryptopapi713

Sadly I cannot reduce the price.

**Comment by blazecoding2009** [comment]
Hey @cryptopapi713 

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/Xk5Iry). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Review by blazecoding2009 — APPROVED** [review]
Hey @cryptopapi713 

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/Xk5Iry). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
