### PR TITLE
PikachuChaserFirstProj

### PR DESCRIPTION
**Pull request by ABHCI15**
## Submission Checklist:

- [ Y] I am a current high school, middle school, or home schooled student.
  - [Y] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ Y] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [Y] I made this board from scratch, even if I followed a tutorial
- [Y] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Y] Created a folder under `onboard/projects`
  - [Y] Filled out `TEMPLATE.md` as `README.md`
  - [ Y] Uploaded Gerber.zip and Schematic.pdf
  - [Y] Created a folder called `src` and uploaded design files
  - [ Y] Uploaded screenshot of PCB order with all costs included
  - [Y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ NA] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [Y] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: __3128__

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/PikachuChaser:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/1dd8efabc136ae5e07b0e0ff782124e6b7d8687d/projects/PikachuChaser/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/1dd8efabc136ae5e07b0e0ff782124e6b7d8687d/projects/PikachuChaser/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/1dd8efabc136ae5e07b0e0ff782124e6b7d8687d/projects/PikachuChaser/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by maxwofford — APPROVED** [review]
Nice design @ABHCI15! I just [sent the full grant](https://hcb.hackclub.com/grants/X8pIZo), but you did a good job keeping your costs down. Try to save on shipping too & you'll have enough funds left for another design.

**Comment by ABHCI15** [comment]
do you see any other methods to reduce costs (its a school project)

**Comment by maxwofford** [comment]
Ask around in the #electronics channel of the Slack! Those people are super experience on designing boards

**Pull request merged**
