### PR TITLE
Olivia's_LED_Cartoon_Pins

### PR DESCRIPTION
**Pull request by olivesssoup**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md`
  - [X] Uploaded Gerber and design files
  - [X] Uploaded screen shot of PCB passing JLCPCB inspection
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

### CODE REVIEW

**Comment by olivesssoup** [comment]
These boards are being manufactured without assembling components, this is why no design files are included. The components are going to be soldered by hand from my personal stock.

**Review by Leo32345 — APPROVED** [review]
The cartoon characters look cute. Looks good to me!

**Review by daisybanks — COMMENTED** [review]
Welcome OnBoard @olivesssoup! Everything looks good on Banks side @hackclub/boarding-party. :)

**Comment by karmanyaahm** [comment]
Hi! We need the design files regardless of whether you're soldering the components yourself or not. Whatever format your designer outputs should be included (design.json, design.sch, design.brd, etc). It'll help everyone learn from your project!

**Comment by maxwofford** [comment]
These look so cool @olivesssoup! did you draw them yourself? i'd love to see your other art!

**Pull request merged**
