### PR TITLE
business card pcb!!!

### PR DESCRIPTION
**Pull request by elberto22**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/batuhan card pcb:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Hi @elberto22! 

You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order 5 assembled boards.

Additionally, please make a "src" folder in projects/[name]/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

Feel free to ask if you have any more questions!

**Comment by karmanyaahm** [comment]
Hey @elberto22 did you get that figured out? Feel free to ask if you have any questions!

**Comment by karmanyaahm** [comment]
Hi @elberto22!

Please feel free to ask for help if you need any here or [[#electronics on Slack](https://hackclub.com/slack/?event=onboard)](https://hackclub.com/slack/?event=onboard). I'm closing this for cleanup right now, but if you get your PR fixed, please let me know.

**Comment by elberto22** [comment]
Oh Shoot! i completely forgot about this, is this still on going? im really sorry

**Comment by karmanyaahm** [comment]
Yeah when you make the fixes above we can merge your PR!

**Comment by abitchinmorewaysthanone** [comment]
Please upload your SCH JSON to /src! The file name should look like `SCH_PCB_BusinessCard_2024-04-14.json` Everything else is fixed.

**Comment by elberto22** [comment]
Hey! i just added the SCH file, thanks a lot for letting me know guys!

**Review by abitchinmorewaysthanone — CHANGES_REQUESTED** [review]
Your files are all correct but it seems like you haven't done the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form) - we need this info to contact you and send your grant! Thank you!

**Comment by elberto22** [comment]
Done!

**Review by abitchinmorewaysthanone — APPROVED** [review]
Ok, I've sent [your grant](https://hcb.hackclub.com/grants/vbpIgd)! You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by elberto22** [comment]
Could i ask what the email the grant was sent to? because i might have typed in something else and i don't really see anything in my email

**Pull request merged**
