### PR TITLE
jackie's pcb

### PR DESCRIPTION
**Pull request by 28jackiiee**
[ ✅ ] I am a current high school, middle school, or home schooled student.

[ ✅] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
[ ✅] I have joined the [#electronics](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)

[✅ ] I made this board from scratch, even if I followed a tutorial

[✅ ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)

[✅ ] Created a folder under onboard/projects
[✅ ] Filled out TEMPLATE.md as README.md inside your project folder
[ ✅] Uploaded gerber.zip and schematic.pdf inside your project folder
[✅ ] Created a folder called src and uploaded design files
[✅ ] Uploaded screenshot of PCB order called cart.png with all costs included
[✅ ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
[✅ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/jackie's_pcb:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/16231a24bfa1baa122d719791516c9a75afa31f9/projects/jackie's_pcb/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/16231a24bfa1baa122d719791516c9a75afa31f9/projects/jackie's_pcb/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/16231a24bfa1baa122d719791516c9a75afa31f9/projects/jackie's_pcb/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by SerenityUX** [comment]
Hi Jackie! Just confirming, this is for The Trail, right?

**Comment by 28jackiiee** [comment]
Yes

**Comment by 24c02** [comment]
lgtm!

**Pull request merged**
