### PR TITLE
Add Nick's USB to Aux board (2nd submission because I goofed on the first)

### PR DESCRIPTION
**Pull request by 28add11**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [X] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 21832

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Nick's USB-audio board:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|❌ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/d9eb970fb99d69b3adff5ba582dceae592bcd9bc/projects/Nick's USB-audio board/schematic.pdf>) | You must export your schematic file as schematic.pdf |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/d9eb970fb99d69b3adff5ba582dceae592bcd9bc/projects/Nick's USB-audio board/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by 28add11** [comment]
Bruh I mislabeled schematic.pdf 😭
Is that still alright, or should I change it?

**Comment by blazecoding2009** [comment]
Please change it.

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by 28add11** [comment]
Ah, my apologies! I'll try to fix those right now, thanks for letting me know!

**Comment by 28add11** [comment]
All should be good now, let me know if any more changes need to be made! Thanks!

**Comment by blazecoding2009** [comment]
Hey @28add11 

I can't seem to find your ID, would you mind resubmitting the form?

**Comment by 28add11** [comment]
Hello,

I've resubmitted the form now using my most recent school ID, I hope that works!
Just for future reference as well, I applied to arcade using my drivers license, but I noticed OnBoard specifically says school ID. Is that why it couldn't be used? 
Thanks!

**Review by blazecoding2009 — APPROVED** [review]
Looks good! I've sent your [grant](https://hcb.hackclub.com/grants/XRGI1o)

**Comment by 28add11** [comment]
Many thanks! I can't wait to see them arrive, I'll post in the slack!

**Pull request merged**
