### PR TITLE
card

### PR DESCRIPTION
**Pull request by cott3**
## Submission Checklist:

- [ x] I am a current high school, middle school, or home schooled student.
  - [x ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ x] I made this board from scratch, even if I followed a tutorial
- [ x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ x] Created a folder under `onboard/projects`
  - [ x] Filled out `TEMPLATE.md` as `README.md`
  - [ x] Uploaded Gerber.zip and Schematic.pdf
  - [ x] Created a folder called `src` and uploaded design files
  - [ x] Uploaded screenshot of PCB order with all costs included
  - [ x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/be5e14d097622273898af5d04485e74519a7fe5e/projects/cott's card/Gerber_New-Project_PCB_New-Project_2024-02-21.zip>)!

  Happy OnBoarding!

**Comment by maxwofford** [comment]
I haven't seen your student verification form filled out yet. If you still need to fill it out, here's the link: https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form

**Review by maxwofford — CHANGES_REQUESTED** [review]
I haven't seen your student verification form filled out yet. If you still need to fill it out, here's the link: https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form

**Comment by cott3** [comment]
ye srry forgot abt that

**Comment by cott3** [comment]
> I haven't seen your student verification form filled out yet. If you still need to fill it out, here's the link: https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form

filled it!

**Review by maxwofford — APPROVED** [review]
Your student verification is approved!

Heads up though, your card just includes the PCB. You probably want PCB assembly (PCBA) when you actually go to order. Can you update that screenshot with the full order?

**Comment by maxwofford** [comment]
Screenshot 2024-03-05 at 09 43 28

excited to see what you end up building!

**Pull request closed without merging**
