### PR TITLE
Usb Converter

### PR DESCRIPTION
**Pull request by Alecsis**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X]  Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [X] (Optional) This project is for [Trick or Trace](https://showcase.hackclub.com/)[^3].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Alecsis** [comment]
The latest commit is my USB converter PCB for the trick or treat event

**Comment by Alecsis** [comment]
trace mb!

**Review by LimesKey — CHANGES_REQUESTED** [review]
Looks like you're trying to commit two projects, are you able to create a separate pull request for each project?

**Comment by Alecsis** [comment]
No, the other project should be merged

**Comment by Alecsis** [comment]
Like the other one was my other 50$ for a non tutorial

**Comment by LimesKey** [comment]
They're both for Trick or Trace? We have automation that doesn't work when you try to submit two projects in one pull request.

**Comment by Alecsis** [comment]
wait there should be only one project that is being submitted, I can't see the other one. Can you tell me what's the other project?

**Comment by LimesKey** [comment]
image

**Comment by Alecsis** [comment]
Type a to c should be merged but can you delete it?

**Comment by Alecsis** [comment]
okay should be good, i deleted the directory

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @Alecsis,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by Alecsis** [comment]
Should be updated

**Review by LimesKey — CHANGES_REQUESTED** [review]
Thanks for your Trick or Trace submission but do you think you can re-complete the verification form so that we can send you some stickers in the mail?

**Comment by Alecsis** [comment]
Yea, all good! I filled it out

**Review by LimesKey — COMMENTED** [review]
Great submissions, going to approve it, but I'm a little confused on how your board looks in the gerber viewer? It seems very different compared to the `schematic.pdf` you submitted.

**Comment by Alecsis** [comment]
K should be good

**Review by LimesKey — APPROVED** [review]
Hi @Alecsis!

Thanks for submitting your design to Trick or Trace! Project voting open Oct 21st, check in to [#electronics](https://slack.com/archives/C056AMWSFKJ) (in the Slack) or on the [website](https://trickortrace.hackclub.com/) for the link to see your project in the gallery, and to vote on other's designs. Look forward to receiving a small package in the mail in the next few weeks, just a small gift to continue you on your journey of making.

**Comment by Alecsis** [comment]
Thanks!

**Comment by Alecsis** [comment]
Thanks!

**Pull request merged**
