### PR TITLE
EasyEDA Layers tip

### PR DESCRIPTION
**Pull request by Shrey-Mehra**
This Layers tip is wrote by Camdan Mead. I am just create a PR for Adding his Tips on GitHub

### CODE REVIEW

**Comment by Shrey-Mehra** [comment]
Hey @maxwofford I have Added EasyEDA Layers Tips By Camdan Mead can you check it once if you think it's helpful then merge it

Thanks

**Comment by bykevinyang** [comment]
OOOoo! This is nice!

Do you think you can add pictures to each section as well? It's a little hard to see what you're talking about without some visual aid.

Good work!

**Comment by Shrey-Mehra** [comment]
Sure @bykevinyang why not I'll try to add pictures till then pls don't merge this pull

**Comment by Shrey-Mehra** [comment]
BTW credit goes to camdan i just make pr

**Review by Shrey-Mehra — COMMENTED** [review]
Hey @bykevinyang , 
As I'm new to PCB Design so I don't know about the Top/bottom paste mask layer, Ratlines, BoardOutLine:,  Multi-Layer

So can't able to upload image of them can you help me in this

Thanks

**Comment by kvnyng** [comment]
> Hey @bykevinyang , As I'm new to PCB Design so I don't know about the Ratlines, Multi-Layer
> 
> So can't able to upload image of them can you help me in this
> 
> Thanks

Hey Shrey,

Do you want to ask Camdan about this?

**Pull request merged**
