### PR TITLE
Raksshana's PCB bolard

### PR DESCRIPTION
**Pull request by raksshana**
## Submission Checklist:

- [x] I am a current high school, middle school, or home-schooled student.
- [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: FTC 18715

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by sarthaktexas** [comment]
Hi Raksshana! I'm approving your student verification :) The next step will be to wait 24-48 hours for the technical review and then your PR will be merged and you'll receive your grant! @hackclub/boarding-party

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi! Sorry for the delay in reviewing, my bad, it's finals week right now.


Your design looks great! Can you please upload your schematic from EasyEDA as 'schematic.pdf' https://docs.easyeda.com/en/Export/Export-Schematic/index.html and export a source JSON from the schematic tab. The exact same process as the PCB.json and PCB.pdf you have uploaded, but in the schematic tab. Other than that this looks great to me!

**Review by sarthaktexas — APPROVED** [review]

**Comment by maxwofford** [comment]
Hey @raksshana, I just wanted to check in on this. Do you need some help getting that schematic.pdf uploaded?

**Comment by karmanyaahm** [comment]
Hi @raksshana, let me know if I can answer any questions :)

**Comment by karmanyaahm** [comment]
Closing this for cleanup, please feel free to reopen or comment on here if you get your board working.

**Pull request closed without merging**
