### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by xROBERTINOx**
## Submission Checklist:

- [yes] I am a current high school, middle school, or home schooled student.
  - [yes] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [yes] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [yes] I made this board from scratch, even if I followed a tutorial
- [yes] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [yes] Created a folder under `onboard/projects`
  - [yes] Filled out `TEMPLATE.md` as `README.md`
  - [yes] Uploaded Gerber, sources, and schematic
  - [yes] Uploaded screenshot of PCB order with all costs included
  - [yes] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [yes] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [yes] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/8c05f6e5b9570b68fe3ebc0904b90ae6dc9acbba/projects/RobertBCard/gerber.zip>)!

  Happy OnBoarding!

**Comment by BrightTheBackpack** [comment]
Hi there!
Please  upload your PCB_PCB.json file, please File > Export > EasyEDA a JSON from the Schematic tab of your project!
Also, it appears that your design is missing wires that connect the components. 
If you need help on anything feel free to reach out!

**Comment by xROBERTINOx** [comment]
I have just added hte PCB_PCB.json file, redid the wiring, and re-put all of the required resources in the folder with the updated pcb with wiring.

**Comment by BrightTheBackpack** [comment]
lgtm! just make sure you update the cart with your new design.

**Comment by xROBERTINOx** [comment]
I have, I have added it to the cart and went through the process and got it approved, 
Screen Shot 2024-01-30 at 8 34 57 PM
there are now 2 things in the cart, however I only want the blue one because it has the wiring, that is also the one that I put in the cart.png screenshot

**Comment by BrightTheBackpack** [comment]
ok! once someone from the tech review and student verification team approve this, you'll get this grant!

**Comment by xROBERTINOx** [comment]
So at this point in the process, after it gets approved, which I think it did, I did get an email from Zach Latta saying it was, will you guys be sending out the pcb or will you be sending an e debit card for me to get it?

**Comment by BrightTheBackpack** [comment]
After it gets approved, you'll receive an email from HCB with a e card so you can order it

**Review by sarthaktexas — APPROVED** [review]
Howdy Robert! I'm approving your student verification :)

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi @xROBERTINOx! You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this

Additionally, please make a "src" folder in projects/[name]/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab. Currently, you only have one from the PCB tab.

Other than that, your design looks great to me!

**Review by Hugoyhu — CHANGES_REQUESTED** [review]
Screenshot 2024-02-03 at 11 09 26 AM

This seems shorted. Once you upload your SCH .json, can you ping me so I can take a look at what's going on? Thanks.

**Comment by maxwofford** [comment]
Hey, haven't heard anything on this thread for a while so I'm going to close the PR so it's not in our actively monitored list. You can still totally reopen it by just commenting here or pushing those file changes.

**Pull request closed without merging**
