### PR TITLE
Shrey Business Card

### PR DESCRIPTION
**Pull request by ShreyShingala**
## Submission Checklist:

- [Yes ] I am a current high school, middle school, or home schooled student.
  - [Yes ] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [Yes ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ Yes] I made this board from scratch, even if I followed a tutorial
- [Yes ] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [ Yes] Created a folder under `onboard/projects`
  - [Yes ] Filled out `TEMPLATE.md`
  - [Yes ] Uploaded Gerber and design files
  - [Yes ] Uploaded screen shot of PCB passing JLCPCB inspection
  - [Yes ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [Yes ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ Yes] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by Leo32345 — APPROVED** [review]
Looks great! Congrats on designing your first PCB!

**Review by daisybanks — APPROVED** [review]
Welcome OnBoard @ShreyShingala! Everything looks good on Banks side @hackclub/boarding-party!

**Comment by Leo32345** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! In 24 hours, you should be receiving an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank ([@Daisy](https://hackclub.slack.com/team/U046V3EK56W) on Slack).

Now, you can finally get those PCBs ordered! 🎉

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

P.P.S. Remember to reach out to [@Caleb](https://hackclub.slack.com/team/U013B6CPV62) on Slack to figure out the extra cost.

**Comment by Leo32345** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! In 24 hours, you should be receiving an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank ([@Daisy](https://hackclub.slack.com/team/U046V3EK56W) on Slack).

Now, you can finally get those PCBs ordered! 🎉

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

P.P.S. Remember to reach out to [@Caleb](https://hackclub.slack.com/team/U013B6CPV62) on Slack to figure out the extra cost.

**Comment by Leo32345** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! In 24 hours, you should be receiving an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank ([@Daisy](https://hackclub.slack.com/team/U046V3EK56W) on Slack).

Now, you can finally get those PCBs ordered! 🎉

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

P.P.S. Remember to reach out to [@Caleb](https://hackclub.slack.com/team/U013B6CPV62) on Slack to figure out the extra cost.

**Comment by Leo32345** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! In 24 hours, you should be receiving an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank ([@Daisy](https://hackclub.slack.com/team/U046V3EK56W) on Slack).

Now, you can finally get those PCBs ordered! 🎉

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

P.P.S. Remember to reach out to [@Caleb](https://hackclub.slack.com/team/U013B6CPV62) on Slack to figure out the extra cost.

**Pull request merged**
