### PR TITLE
Auro Deej Mixer

### PR DESCRIPTION
**Pull request by MrAuro**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/AuroDeej5Slider:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/51b39607a1fee6fe5698b9c9fb56a431e6239746/projects/AuroDeej5Slider/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/51b39607a1fee6fe5698b9c9fb56a431e6239746/projects/AuroDeej5Slider/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/51b39607a1fee6fe5698b9c9fb56a431e6239746/projects/AuroDeej5Slider/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by torbers** [comment]
Hi Andrew,
Apologies, but you must be under the age of 18 for the grant. Thanks for your interest!
Tori

**Comment by MrAuro** [comment]
@LimesKey CC'ing you on this since you seem to be reviewing all the PRs recently.

The requirements mention being 18 or under, which applies to me.

**Comment by LimesKey** [comment]
Hi, I believe we are able to give you a grant actually after I confirmed with some other people, sorry about that. I do see though that your PCB has already been ordered from JLCPCB, are you looking for a reimbursement instead? Also, taking a look at your board preview I see that the ProMicro and the Sliders are awfully close together, are you sure there'll be enough clearance?

**Comment by MrAuro** [comment]
Thanks, no worries.

I have already built this, and submitted it that way if anyone wants to build one, they can, and can also learn from my mistakes. The ProMicro and sliders are very close together however with some electrical tape between them it works fine.

I'm not looking for reimbursement on this, but I would like the grant so I can explore another project: a nixie tube clock (or something similar). I can start working on the PCB and submit another pull request if needed.

**Review by LimesKey — APPROVED** [review]
Hi @MrAuro!
I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/vGyI5o). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by LimesKey** [comment]
Great to hear, make sure you make a new pull request for every PCB you order with the grant too!
> a nixie tube clock

*Did you just watch the new technology connections [video](https://www.youtube.com/watch?v=YGT1EvmDJh4)?*

**Comment by MrAuro** [comment]
Thanks!

> Did you just watch the new technology connections [video](https://www.youtube.com/watch?v=YGT1EvmDJh4)?

Yeah haha. I had thought about building a nixie tube clock for a while but they all seemed too expensive. After that video I did a lot of research and found if I build it all myself it would be far cheaper

**Pull request merged**
