### PR TITLE
Small weight machine pull request

### PR DESCRIPTION
**Pull request by Sh1vGupta**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Small_Weight_machine:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|❌ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ddce65d477e760ee0bf386dd1f36183fa758d2fa/projects/Small_Weight_machine/schematic.pdf>) | You must export your schematic file as schematic.pdf |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/ddce65d477e760ee0bf386dd1f36183fa758d2fa/projects/Small_Weight_machine/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by maxwofford — DISMISSED** [review]
Hey, great project! I wanted to check a couple things before sending the grant

- your JSON file's layers don't seem to render properly on gerber.zip– does the 3d view on easyEDA work for you?
- there seem to be some resistors (R4, R3) that don't lead anywhere- is this purposeful?

**Comment by Sh1vGupta** [comment]
> * your JSON file's layers don't seem to render properly on gerber.zip– does the 3d view on easyEDA work for you?

Yes the 3D view is working fine and I think I have attached the wrong JSON layers sorry I had a messy folder there and have many iterations of the same one 
> * there seem to be some resistors (R4, R3) that don't lead anywhere- is this purposeful?

Yes it is purposeful as it is for a weight machine it needs 2 load cell/Strain Guages such that they connect to the Wheatstone Bridge  R3 and R4 are part of the Wheatstone Bridge

**Comment by Sh1vGupta** [comment]
image
the 3D view

**Comment by abitchinmorewaysthanone** [comment]
Shiv, this is very nice work. I need a bit more information because your final cost is greater than $100. Could you PM me on [Slack](https://hackclub.com/slack/?event=onboard)? My tag is @tori. Thanks!

**Pull request closed without merging**
