### PR TITLE
USB Variable Power Supply

### PR DESCRIPTION
**Pull request by AbeG123**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @AbeG123, congrats on making your PCB and I hope you're able to get it soon. In your `cart.png`, I see you selected "Standard Assembly", do you absolutely need Standard Assembly for your board or could you go with Economic assembly? Standard Assembly can be very costly.

**Comment by LimesKey** [comment]
I'm having trouble finding your verification forum @AbeG123, are you sure you submitted it with your correct github username?

**Review by LimesKey — CHANGES_REQUESTED** [review]
I see you've already got a 50$ grant for your HackerCard PCB but haven't spent it yet, would you like me to cancel that grant and issue a new one for this PCB? The grant is limited to 100$ per person. Everything looks good though, very intricate design, I tried to do something similar with boost/buck converters but failed twice when I ordered my PCB, maybe you can teach me something haha?

**Comment by LimesKey** [comment]
Is there any way you can get only one side assembled with Economic Assembly and hand-solder the components on the back? I only see a few components on the backside that shouldn't be too difficult to put on yourself. This will largely decrease the price of the PCB allowing you to make revisions to it in the future or use your grant for something else down the line.

**Comment by LimesKey** [comment]
Great, you mean `Economic Assembly` and not `Standard Assembly` right? Can you please update your `cart.png` with the new total? Thanks

**Review by LimesKey — APPROVED** [review]
Hi @AbeG123!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/q16IKD). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
