### PR TITLE
Business Card

### PR DESCRIPTION
**Pull request by WizardCatz**
## Submission Checklist:

- [ yes] I am a current high school, middle school, or home schooled student.
  - [yes ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [yes  ] I have joined the [`#onboard`] #wizard catz (https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ yes] I made this board from scratch, even if I followed a tutorial
- [yes ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [yes ] Created a folder under `onboard/projects`
  - [ yes] Filled out `TEMPLATE.md` as `README.md`
  - [yes ] Uploaded Gerber.zip and Schematic.pdf
  - [ yes] Created a folder called `src` and uploaded design files
  - [ yes] Uploaded screenshot of PCB order with all costs included
  - [yes ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [I am in the US ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ i would guess so ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/business card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by MichaByte** [comment]
Hi @WizardCatz!

It looks like you have some cool snowflake graphics on the copper layer on the front of your board. Some of the snowflakes overlap with the traces (wires), which will cause a short circuit. I've circled the problematic ones in red - can you either move the snowflakes to the silkscreen layer, or remove them? Once you do that, I can get you your grant!
WizardCatz Onboard Screenshot

**Comment by MichaByte** [comment]
You might also want to remove the snowflakes inside of the antenna, as they might cause problems with reading your card wirelessly.
image

**Comment by WizardCatz** [comment]
Hi @MichaByte Hope you are doing great today.
I have fixed the problem with the snowflakes interfering with the antenna/wires. I have attached an image below since I am unsure if I can edit my GitHub project (I am kind of new to using Github). I have also provided the updated files in Case you need them.
**src file:**
[PCB_PCB_Business-card-2_2024-04-10.json](https://github.com/hackclub/OnBoard/files/14939238/PCB_PCB_Business-card-2_2024-04-10.json)
[SCH_Business-card-2_2024-04-10.json](https://github.com/hackclub/OnBoard/files/14939240/SCH_Business-card-2_2024-04-10.json) 
**schematic.pdf**
[Schematic_Business-card-2_2024-04-10.pdf](https://github.com/hackclub/OnBoard/files/14939253/Schematic_Business-card-2_2024-04-10.pdf) 
**gerber.zip**
[FIXGerber_Business-card-2_PCB_Business-card-2_2024-04-10.zip](https://github.com/hackclub/OnBoard/files/14939256/FIXGerber_Business-card-2_PCB_Business-card-2_2024-04-10.zip)
**cart.png**
Screenshot_10-4-2024_204820_jlcpcb com
Merchandise Total:$18.62
Shipping:$12.69
Payment fee:$0.50
Sales Tax:$2.32
Grand Total :$34.13
If there is anything else that you need, I will be sure to fix it :) Thanks so much.

**Comment by MichaByte** [comment]
Hi @WizardCatz!
I've just sent you [your grant for OnBoard](https://hcb.hackclub.com/grants/wNJI20). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please keep this in mind before you make any purchases.**

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
