### PR TITLE
Add my project (Darren's Keyboard)

### PR DESCRIPTION
**Pull request by mickeydarrenlau**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md`
  - [X] Uploaded Gerber, sources, and schematic
  - [X] Uploaded screenshot of PCB order with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — COMMENTED** [review]
Very cool! Are you intentionally using standard assembly? Economic assembly might be a lot cheaper if you can substitute some parts for ones that are economic supported. Just want to confirm that you are aware of that, other than that LGTM.

**Comment by mickeydarrenlau** [comment]
The parts that I needed is using an extended part so yes

**Review by karmanyaahm — APPROVED** [review]
LGTM. You can get extended parts with economic assembly. I'm assuming you're referring to the "Standard only" ESP32 S2 WROVER? You can proceed as is, but I'd suggest trying to swap that out for a module that is not "Standard only". You can save a lot of money (like $30-$40) and make more boards with that.

**Comment by mickeydarrenlau** [comment]
@karmanyaahm thanks
When will I receive my virtual hack club visa card

**Comment by karmanyaahm** [comment]
HCB team still needs to review this (and several other PRs), and they're super busy rn, but I'm sure they'll get to our fairly soon

**Review by daisybanks — APPROVED** [review]
Approving student verification merging pr, and sending grant now! Thanks so much @mickeydarrenlau for your patience! :)

**Pull request merged**
