### PR TITLE
Koeg Bord split wireless keyboard

### PR DESCRIPTION
**Pull request by KOEGlike**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [X] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Koeg-Board:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/502a36f4ab173746492231b1d3f953afcbd12195/projects/Koeg-Board/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/502a36f4ab173746492231b1d3f953afcbd12195/projects/Koeg-Board/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/502a36f4ab173746492231b1d3f953afcbd12195/projects/Koeg-Board/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by KOEGlike** [comment]
I ordered 10 PCs because it cost only 8 usd more, so it is a steal to get 10 instead of 5 for 8$

**Comment by maxwofford** [comment]
@KOEGlike this is sick, but to keep things even for everyone we can only pay for the smallest batch order. In JLC's case that's 5. Can you swap out your checkout screenshot to that quantity? If you really want to still get 10, you can pay for that extra cost out-of-pocket.

**Comment by KOEGlike** [comment]
Hello, thanks! Updated to only 5 PCBs, i don't need 10, but its a good deal, thanks for the opportunity

**Comment by maxwofford** [comment]
I see $78 in your cart screenshot, but your readme says $180

**Comment by KOEGlike** [comment]
Oh forgot to change that, that price is from when I still wanted to use  PCBA

**Comment by KOEGlike** [comment]
@LimesKey could you please review this🥺👉👈

**Comment by WolfGamer2** [comment]
Hi [KOEGlike](https://github.com/KOEGlike),

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of your cart rather than the completed unpaid order.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to the [JLCPCB Order page](https://jlcpcb.com/user-center/orders/), then take a rectangular screenshot of the PCB you just submitted. It should show all the details of your order including the price and assembly.

This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congratulations on making the PCB! Please ask in [#electronics](https://slack.com/archives/C056AMWSFKJ) in the [Slack](https://hackclub.com/slack/) if you need any further help.

**Comment by KOEGlike** [comment]
updated files here, updated cart image

**Comment by WolfGamer2** [comment]
Heya! Since you did Onboard Live I assigned @MichaByte. He will get to this ASAP.

**Comment by KOEGlike** [comment]
Thanks!

**Comment by KOEGlike** [comment]
Not to be rude, but how long does it usually take to review? Just to know an ETA, if it takes more time it's all right, I'm just interested

**Comment by MichaByte** [comment]
Will do this tomorrow!

**Comment by KOEGlike** [comment]
@MichaByte sorry for ping, just in case you forgot

**Comment by maxwofford** [comment]
argh, screw it. this board is amazing and it's been held up for 3 weeks now! @WolfGamer2 please get this hacker a grant! If it's not covered by the onboard live funds we'll pay it from the marketing budget.

**Comment by WolfGamer2** [comment]
Hi KOEGlike!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/rnIEY1). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the [#electronics](https://slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/) once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by KOEGlike** [comment]
Thank you!!!

**Comment by KOEGlike** [comment]
Thank you!!!

**Comment by KOEGlike** [comment]
And the onboard-live grant will be separate?

**Comment by WolfGamer2** [comment]
This is the grant! @MichaByte Will top it up based on his records in the youtube system!

**Comment by KOEGlike** [comment]
Thanks!

**Comment by WolfGamer2** [comment]
❤️

**Comment by MichaByte** [comment]
Hey all, so sorry for the delay on this. My life has been super stressful lately and this slipped through the cracks. I just finished reviewing this and found US$77.54 worth of valid recordings. Since @KOEGlike already got the regular OnBoard grant, what's the move here? I see that they have not spent any of the $100 OnBoard grant. Should I top it up with the new funds, or cancel it and issue a new one so that they are eligible for regular OnBoard's full $100 for a future project while still covering this one with OnBoard Live?

cc @maxwofford @WolfGamer2

**Comment by WolfGamer2** [comment]
Depending on how much the pcb costs I think you should cancel the $100 one
so they can do it again!

**Pull request merged**
