### PR TITLE
Super cool lora transmitter for rc cars!

### PR DESCRIPTION
**Pull request by fatpotato317**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [X] (Optional) This project is for [Trick or Trace](https://showcase.hackclub.com/)[^3].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Lora Transmitter for Rc cars and planes!:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/83414aa2ecd720090c3b4d9e05e0844b4a0434ab/projects/Lora Transmitter for Rc cars and planes!/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/83414aa2ecd720090c3b4d9e05e0844b4a0434ab/projects/Lora Transmitter for Rc cars and planes!/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/83414aa2ecd720090c3b4d9e05e0844b4a0434ab/projects/Lora Transmitter for Rc cars and planes!/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by fatpotato317** [comment]
Also sorry for the number of commits, GitHub is hard lol

**Review by LimesKey — CHANGES_REQUESTED** [review]
Thanks for submitting! Can you re-export your `schematic.pdf` as that's just a picture of your PCB, you need to export your `schematic.pdf` from the schematic tab of EasyEDA.

**Comment by fatpotato317** [comment]
sorry about that! just finished doing that

**Comment by fatpotato317** [comment]
Hi! Why has this now been merged yet?

**Comment by LimesKey** [comment]
Hi, sorry for the late reply, I cannot seem to find your verification form, are you sure you've submitted it with your correct GitHub username? https://verify.onboard.hackclub.com/

**Comment by fatpotato317** [comment]
I filled it tho! 😔 Didn't get the grant now... Even after spending so much effort on it 😔

**Comment by LimesKey** [comment]
We're still giving out grants,
> However, I don't want to turn a blind eye to the fact that there's a number of people who are still trying to submit and have an open pull request, or had their pull request merged very recently, it wouldn't be fair to deny of them of the grant opportunity after they worked so hard on their PCB. Which is why we're continuing to give grants to people who didn't get their pull request merged in on time,  or people who did not receive enough votes to quantify the quality of their project. I realize that there were delays and setbacks in getting the infrastructure setup for this, so I want to return the patience you've given me by doing this. Applicable projects will instead be voted on by the OnBoard Reviewer Team and grants will be given to those winners in the next few days.

**Comment by LimesKey** [comment]
Hey, I can't seem to find your eligibility form, are you sure you've submitted it? https://forms.hackclub.com/eligibility

**Pull request closed without merging**
