### PR TITLE
Flatbox

### PR DESCRIPTION
**Pull request by Marc-Blanco**
## Submission Checklist:

- [ X] I am a current high school, middle school, or home schooled student.
  - [X ] I am 18 or under
  - [X ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X ] Created a folder under `onboard/projects`
  - [X ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [ X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Fightbox:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by blazecoding2009** [comment]
Hey @Marc-Blanco please name all the files correctly.

**Comment by Marc-Blanco** [comment]
I'll fix it

**Comment by Marc-Blanco** [comment]
How do I fix it I can't enter the files

**Review by LimesKey — CHANGES_REQUESTED** [review]
Is this project really for OnBoard Live or was that a mistake?

**Comment by Marc-Blanco** [comment]
Yes, it is.
Sorry

2024年9月12日(木) 21:04 LimesKey ***@***.***>:

**Comment by Marc-Blanco** [comment]
Updated

**Comment by Marc-Blanco** [comment]
How do I do that?
I didn't use easyeda

2024年9月18日(水) 15:49 LimesKey ***@***.***>:

**Comment by LimesKey** [comment]
What did you use?

**Comment by Marc-Blanco** [comment]
I'm fixing it

**Comment by Marc-Blanco** [comment]
It should be finished

**Comment by LimesKey** [comment]
Thanks for doing that, I see your schematic is not named `schematic.pdf` and also I don't believe it was exported from the KiCad schematic page, did you get that schematic from somewhere else?

**Comment by Marc-Blanco** [comment]
Yes, I did!

**Comment by Marc-Blanco** [comment]
Ok, so I moved from pcs and I losed some material, I tried to recover as much as I could but I couldn't recover the schematic, so I was scared of it being invalid so I tried to cover it. 
I understand if you still invalidate the request and sorry for the inconviniances

**Comment by LimesKey** [comment]
I will have to close the pull request, sorry. OnBoard also does not pay for JLCPCB's 3D Printing service. Feel free to make another pull request but with a different PCB.

**Comment by Marc-Blanco** [comment]
Ok, no problem.

**Pull request closed without merging**
