### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by KanishkThamman**
## Submission Checklist:

- [Yes ] I am a current high school, middle school, or home schooled student.
  - [Yes ] I am 18 or under
  - [ Yes] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Yes ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ Yes] I made this board from scratch, even if I followed a tutorial
- [ Yes] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ Yes] Created a folder under `onboard/projects`
  - [ Yes] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ Yes] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ Yes] Created a folder called `src` and uploaded design files
  - [ Yes] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [Yes ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ Yes] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ Yes] (Optional) This project is from a tutorial[^1].
- [No ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ No] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/4 Port USB DOC (CUZ NEW COMPUTERS HATE IO):**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png | /cart.png>) |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/36ed4293716035a121cef3e659d1581e7242fbc1/projects/4 Port USB DOC (CUZ NEW COMPUTERS HATE IO)/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/36ed4293716035a121cef3e659d1581e7242fbc1/projects/4 Port USB DOC (CUZ NEW COMPUTERS HATE IO)/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/36ed4293716035a121cef3e659d1581e7242fbc1/projects/4 Port USB DOC (CUZ NEW COMPUTERS HATE IO)/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @KanishkThamman,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by KanishkThamman** [comment]
I have made the changes and added the new cart picture to the folder

**Comment by LimesKey** [comment]
I see you have chosen Standard Assembly, are you able to choose Economic Assembly instead? You might have to replace a component with another very similar component as some components are standard-only. Economic assembly is much cheaper and usually what most people use.

**Comment by KanishkThamman** [comment]
I tried but the male USB part needed the Standard assembly. I tried different parts and could not find one that would not require standard assembly. I would love to know if you happen to know of any male USB part options that don't require the use of standard assembly!

**Comment by BrightTheBackpack** [comment]
check out https://hackclub.slack.com/archives/C056AMWSFKJ/p1719136609923349 regarding the usb parts change!

**Comment by LimesKey** [comment]
See [here](https://github.com/hackclub/jams/pull/221) for some more info

**Comment by LimesKey** [comment]
This pull request has been inactive for some time and has therefore been closed. Feel free to create a new one when you're ready.

**Pull request closed without merging**
