### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Nikos1508**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Yay! Great design. However,
> I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)

Like you checked in the submission checklist, you are only supposed to order 5 boards, not 10. The rest of the grant is to allow you to play with more unique designs. If you'd like, you can make 2 unique designs and order them in the same order.

**Comment by Nikos1508** [comment]
Ok thanks I will make a order for 5 pcb's.

**Comment by Nikos1508** [comment]
I took a new screenshot but I don't know how to replace the old one, so uploading it may take some time. Or I can send it to you in another way (slack, mail, etc)

**Review by daisybanks — APPROVED** [review]
Welcome OnBoard @Nikos1508! Everything looks good on Bank's side @hackclub/boarding-party. :)

**Comment by kvnyng** [comment]
@Nikos1508 welcome to OnBoard! When you get your boards, send them in the slack!

**Pull request merged**
