### PR TITLE
iCE40 DevBoard

### PR DESCRIPTION
**Pull request by Mirrrek**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/iCE40DevBoard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/fd278ea23d1eb6ca272bbaa1c4a2a336d6db11cd/projects/iCE40DevBoard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/fd278ea23d1eb6ca272bbaa1c4a2a336d6db11cd/projects/iCE40DevBoard/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/fd278ea23d1eb6ca272bbaa1c4a2a336d6db11cd/projects/iCE40DevBoard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Lightshayan** [comment]
Hey! 
You have selected the wrong components, which is increasing the price. Please follow the [jam](https://jams.hackclub.com/jam/hacker-card) and select the right components. 

Feel free to ask any questions in the #electronics channel!

**Comment by Mirrrek** [comment]
@Lightshayan Hi, I haven't actually added PCB assembly into the order as I already have some of the ICs at home, and therefore my design is not even ready for JLCPCB's automated assembly (e.g. has no space for the "tooling holes"). I could redesign it but I also think I would enjoy soldering it myslef, if that isn't an issue. Can I only request the board itself?

PS: Quick question: Is the $100 grant only appliable to the submitted design or can it be used to order other designs in the future? I'm not sure how this whole thing works but assuming the remaining credits are not refunded to Hack Club, it would be a bit of a waste to only use like $10 from the $100 available.

Thanks a lot

**Comment by Lightshayan** [comment]
Hey! Sure, you can build it yourself. The money is available to you to use on another PCB as long as you make a PR and have it approved. I'll finish your submission and hopefully get you your grant right now!

**Comment by Lightshayan** [comment]
Hey! Yeah, thats fine. I'll review your submission soon!

**Comment by Lightshayan** [comment]
Hi @Mirrrek!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/XBYIo4). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by Lightshayan** [comment]
You can use your grant to make multiple PCB, but make a PR every time!

**Pull request merged**
