### PR TITLE
Circuit YT NFC card

### PR DESCRIPTION
**Pull request by poone123**
## Submission Checklist:

- [✓] I am a current high school, middle school, or home schooled student.
  - [✓] I am 18 or under
  - [✓] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [✓] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [✓] I made this board from scratch, even if I followed a tutorial
- [✓] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [✓] Created a folder under `onboard/projects`
  - [✓] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [✓] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [✓] Created a folder called `src` and uploaded design files
  - [✓] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [✓] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [✓] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [✓] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/CircuitYTNFCcard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/f38f1c70fa376a281be4cd34b187a70cee9953ed/projects/CircuitYTNFCcard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/f38f1c70fa376a281be4cd34b187a70cee9953ed/projects/CircuitYTNFCcard/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/f38f1c70fa376a281be4cd34b187a70cee9953ed/projects/CircuitYTNFCcard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by 46-HA** [comment]
Hello poone123,
You have selected standard assembly, can you please select economic because you don't need it for the hacker card

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!
 
If you have any questions feel free to reach out to me on slack (HenHen) or here

**Comment by BrightTheBackpack** [comment]
btw this *might* cause issues 
image

**Comment by poone123** [comment]
Hi, thanks for the feedback. Is there any way I can have a gold finish silk
or texture on my card and is there a setting for that? I also got to the
next point where it asks for materials which I am not sure what to do. Any
assistance would be greatly appreciated!
[image: image.png]

**Comment by BrightTheBackpack** [comment]
you can add a gold/copper texture by adding the copper(red) layer, and removing the silkscreen, but it can't be on a component. you can either move the image or the componenet(or make the image bigger so you can fit the led inside )

**Comment by poone123** [comment]
Hi, I am a bit confused. For my design I set a top layer and then a solder
layer as the video showed. Is that what you are referring to? Also what
should I do when I get to the materials board page?

**Comment by poone123** [comment]
Was my board successful? I just received an email that it was approved.

**Comment by poone123** [comment]
Here is my updated cart, is there any way I can modify my pull request? 
Screenshot 2024-07-31 134637

**Comment by poone123** [comment]
Would that screenshot be sufficient?

**Comment by poone123** [comment]
The cart.png file has just been updated and also has been changed from standard to economic

**Comment by 46-HA** [comment]
Hi poone123!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/woQIBQ). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
