### PR TITLE
Harshit NFC Card

### PR DESCRIPTION
**Pull request by harshit-stacked**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection

### CODE REVIEW

**Comment by harshit-stacked** [comment]
d90e1303-0a91-4c83-8381-26e7f7938ed5

**Comment by kvnyng** [comment]
Hey @harshit-stacked,

I see that you selected to make 75 boards. OnBoard currently asks orders to be made for 5 boards at a time, so you can make as many different boards as possible. It also lets you purchase additional boards in case your first design doesn't work. Can you resubmit a screenshot a cart with 5 boards only?

**Comment by harshit-stacked** [comment]
@kvnyng i thought i would order less pcb's and one zephyr hub but the budget exceeds $100 so i thought to order that many cards

**Comment by kvnyng** [comment]
> @kvnyng i thought i would order less pcb's and one zephyr hub but the budget exceeds $100 so i thought to order that many cards

Hmmmm. Are you unable to fit two boards within budget?

**Comment by harshit-stacked** [comment]
@kvnyng yess the shipping charges are way too high!

**Comment by harshit-stacked** [comment]
how can i get the pr merged?

**Comment by daisybanks** [comment]
Hi @harshit-stacked. I still need proof of current high school enrollment. I had emailed you letting you know that I've seen quite a few of the same type of student ID's as yours come through but the one you sent me has the school year date cropped out. Could you please send me a full picture of the ID so I can verify that you are a current high school student?

**Comment by harshit-stacked** [comment]
ahh! i"ll provide that but except that anything else required?

**Comment by daisybanks** [comment]
There won't be anything else required on Bank's end. @kvnyng anything on your end?

**Comment by kvnyng** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! In 24 hours, you should be receiving an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank ([@Daisy](https://hackclub.slack.com/team/U046V3EK56W) on Slack).
 
Now, you can finally get those PCBs ordered!:tada:

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

**Pull request merged**
