### PR TITLE
box985

### PR DESCRIPTION
**Pull request by kattschan**
## Submission Checklist:

- [ Y ] I am a current high school, middle school, or home schooled student.
  - [ Y ] I am 18 or under
  - [ Y ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ Y ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ Y ] I made this board from scratch, even if I followed a tutorial
- [ Y ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ Y ] Created a folder under `onboard/projects`
  - [ Y ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ Y ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ Y ] Created a folder called `src` and uploaded design files
  - [ Y ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ Y ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ Y ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/box895:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/2f534595c5868d865a8449e1066c6b40202d884b/projects/box895/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/2f534595c5868d865a8449e1066c6b40202d884b/projects/box895/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/2f534595c5868d865a8449e1066c6b40202d884b/projects/box895/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by kattschan** [comment]
image
In reading other threads I realised I may have sent the wrong view for the cart. Price appears unchanged.

**Review by LimesKey — COMMENTED** [review]
Great design, thanks for your submission. I'm having a little trouble finding your verification form, are you sure you submitted it with your correct GitHub username? Also, are you able to add your KiCad 3D model `.wrl`file? I'd love to see how your board looks as a 3d model.

**Comment by kattschan** [comment]
I just (re?)submitted the form, so it should be there now. I just added the .wrl with default export settings from Kicad.

**Comment by LimesKey** [comment]
Thanks for doing that, I see it! Also, one more thing, is there any way you can use Economic Assembly instead? Standard assembly can be very expensive and you should really only use it if you require it for your PCB.

**Comment by kattschan** [comment]
I don't think so. I initially started with economic however after selecting my parts for assembly it said they were only available with standard.

**Comment by kattschan** [comment]
image
I just confirmed that this part does require standard assembly and also that there is no variant of this part that works with economy.

**Comment by LimesKey** [comment]
That's ok then!

**Review by LimesKey — APPROVED** [review]
Hi @kattschan!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/Xk5In8). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please keep this in mind before you make any purchases.** More info in the OnBoard community shipping doc.

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
