### PR TITLE
OnBoard

### PR DESCRIPTION
**Pull request by big-man-max**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi @big-man-max! Your PR mostly looks good, you just uploaded a PDF from your PCB design tab, instead of your schematic tab. I deleted that for you, can you please upload a file called 'schematic.pdf' from the schematic tab?

**Review by karmanyaahm — APPROVED** [review]
LGTM! Your student verification should be approved soon by @sarthaktexas!

**Comment by karamassie** [comment]
@sarthaktexas can you approve this?

**Comment by maxwofford** [comment]
@big-man-max it looks like you uploaded some grades for your verification. We're looking for a student ID or something with your photo on it!

**Review by maxwofford — APPROVED** [review]
Approved the student verification via Zoom call!

**Comment by sarthaktexas** [comment]
sent!

**Pull request merged**
