### PR TITLE
Add Nick's LED board project

### PR DESCRIPTION
**Pull request by 28add11**
## Submission Checklist:

- [x ] I am a current high school, middle school, or home schooled student.
  - [x ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x ] I made this board from scratch, even if I followed a tutorial
- [404 error ] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x ] Created a folder under `onboard/projects`
  - [x ] Filled out `TEMPLATE.md` as `README.md`
  - [x ] Uploaded Gerber, sources, and schematic
  - [x ] Uploaded screenshot of PCB order with all costs included
  - [x ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [x ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 21832

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by sarthaktexas** [comment]
Hi Nick! I'm approving your student verification :) The next step will be to wait 24-48 hours for the technical review and then your PR will be merged and you'll receive your grant! @hackclub/boarding-party

**Review by sarthaktexas — APPROVED** [review]

**Review by maxwofford — APPROVED** [review]
Hi @28add11, this is awesome! Super excited to see how it goes with the order. Your grant should arrive soon!

**Comment by sarthaktexas** [comment]
Sent!

**Comment by 28add11** [comment]
Thanks everyone! I'll keep the slack channel updated 👀.
I presume I'll be good to use the card for second revisions? If not, how would I go about that? I already have a few ideas, but one step at a time. Thanks!

**Comment by karamassie** [comment]
@sarthaktexas

**Comment by sarthaktexas** [comment]
Yep, just use the same card.

**Pull request merged**
