### PR TITLE
Add LIN Bus Adapter ESP32

### PR DESCRIPTION
**Pull request by OrhanYigitDurmaz**
## Submission Checklist:

- [Y] I am a current high school, middle school, or home schooled student.
  - [Y] I am 18 or under
  - [Y] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Y] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [Y] I made this board from scratch, even if I followed a tutorial
- [Y] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Y] Created a folder under `onboard/projects`
  - [Y] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [Y] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [Y] Created a folder called `src` and uploaded design files
  - [Y] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [Y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [Y] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/LIN Bus ESP32:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/c389080e8417658db7dd8aa2d870b7393cb6cffd/projects/LIN Bus ESP32/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/c389080e8417658db7dd8aa2d870b7393cb6cffd/projects/LIN Bus ESP32/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/c389080e8417658db7dd8aa2d870b7393cb6cffd/projects/LIN Bus ESP32/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by OrhanYigitDurmaz** [comment]
Here's a little easter egg:

**Comment by Lightshayan** [comment]
Hey - your Readme.md says that it will cost $18 but the cart significantly bumped up the price to almost $100 - Why is that?

**Comment by OrhanYigitDurmaz** [comment]
> Hey - your Readme.md says that it will cost $18 but the cart significantly bumped up the price to almost $100 - Why is that?

ah, 18 bucks is for one board, 5 of them yes go up to 90 bucks

**Comment by Lightshayan** [comment]
Hi @OrhanYigitDurmaz!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/qnZIKr). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by OrhanYigitDurmaz** [comment]
> Hi @OrhanYigitDurmaz!
> 
> I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/qnZIKr). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.
> 
> **Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).
> 
> I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

Thanks!

**Pull request merged**
