### PR TITLE
USB-HUB

### PR DESCRIPTION
**Pull request by 164KiloBytes**
## Submission Checklist:

- [ Y] I am a current high school, middle school, or home schooled student.
  - [Y ] I am 18 or under
  - [ Y] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ Y] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ Y] I made this board from scratch, even if I followed a tutorial
- [Y ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Y ] Created a folder under `onboard/projects`
  - [ Y] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [Y ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ Y] Created a folder called `src` and uploaded design files
  - [ Y] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ Y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [Y ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/USB-HUB-164KiloBytes:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/19aa9fa82d426b5929ddc30ec2cc7095bd4a2634/projects/USB-HUB-164KiloBytes/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/19aa9fa82d426b5929ddc30ec2cc7095bd4a2634/projects/USB-HUB-164KiloBytes/schematic.pdf>) |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/19aa9fa82d426b5929ddc30ec2cc7095bd4a2634/projects/USB-HUB-164KiloBytes/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by torbers — CHANGES_REQUESTED** [review]
Hi Ben,
The [tutorial](https://jams.hackclub.com/batch/usb-hub) had some mistakes, and it's making your board cost more than it should by forcing you to use Standard PCBA rather than Economic PCBA. This isn't your fault - JLCPCB just switched the assembly class of the male USBA port. The tutorial is updated now. Could you review it and replace the male USBA port, then reupload all your files?
Thanks!

**Comment by 164KiloBytes** [comment]
No don't worry I will just leave it

**Comment by torbers** [comment]
We can't provide more than $50. The old part makes the board cost more than $50.

**Comment by torbers** [comment]
Designer's no longer interested. Closing PR.

**Pull request closed without merging**
