### PR TITLE
DIY DRONE

### PR DESCRIPTION
**Pull request by BadPotato1007**
## Submission Checklist:

- [ x ] I am a current high school, middle school, or home schooled student.
  - [ x ] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [ x ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ x ] I made this board from scratch, even if I followed a tutorial
- [ x ] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [ x ] Created a folder under `onboard/projects`
  - [ x ] Filled out `TEMPLATE.md`
  - [ x ] Uploaded Gerber and design files
  - [ x ] Uploaded screen shot of PCB passing JLCPCB inspection
  - [ x ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ x ] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by daisybanks — APPROVED** [review]
Welcome OnBoard @BadPotato1007!  Everything looks good on HCB's side @hackclub/boarding-party. :)

**Comment by BadPotato1007** [comment]
Just 1 more approval now! Hope to get it soon! Can't wait to order everything

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Wow, this is the coolest project OnBoard has seen so far! However, there's a couple small issues:
1. If you have a friend, you need to @mention them on GitHub, and and add their slack/github/name details to the README.md file. They will also have to fill out the verification form. (cc @daisybanks, I think this is the first group grant, how does the process work?)
2. Unfortunately, you can only order from approved [vendors](https://github.com/hackclub/OnBoard/blob/main/docs/VENDORS.md). Even though LCSC is a JLCPCB sister company, it's not allowed. You can order assembled parts from JLCPCB, however.

**Comment by daisybanks** [comment]
Each person will need to apply separately for the grant and you can both work on the project together with your grants.

**Pull request closed without merging**
