### PR TITLE
Add project

### PR DESCRIPTION
**Pull request by AsgerFD**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [~] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/bm-usbc-hub:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/2bd0396479e16a31730395c7fba13865cfe14a01/projects/bm-usbc-hub/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/2bd0396479e16a31730395c7fba13865cfe14a01/projects/bm-usbc-hub/schematic.pdf>) |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/2bd0396479e16a31730395c7fba13865cfe14a01/projects/bm-usbc-hub/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @AsgerFD,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Review by LimesKey — CHANGES_REQUESTED** [review]
I see you selected Standard Assembly by JLCPCB, are you able to use Economic instead? I believe the USB Hub Jam was recently updated and now has a new part number for the USB-A connectors. Also, are you able to convert your EasyEDA Pro project to Standard yourself? I don't think it's too difficult to do but if you have trouble let me know and you can just skip that step.

**Comment by AsgerFD** [comment]
Hi,
It seems i can't figure out how to export it into another format other than pictures or pdfs (And their own proprietary format, not even standard EasyEDA format). If you know a way to do so i would gladly oblige.

About the assembly, the USB-C connecter i use is "complicated to assemble" so i had to choose standard. If there's another USB-C connecter that doesn't require standard assembly you know of i can rework the design.

**Comment by LimesKey** [comment]
Oh, somehow I didn't realize that JLCPCB didn't offer any non-standard assembly USB-C connector, my bad. As for the .epro, that's fine if you're not able to, thanks for trying though. I can't seem to find your verification form, are you sure you filled it out with your GitHub username?

**Comment by AsgerFD** [comment]
Hm, I think I did, but I can't remember. I presume this is the same verification form as for ordering stickers (and other arcade-stuff)?

**Comment by LimesKey** [comment]
Unfortunately it's not, it is it's own seperate form.

**Comment by AsgerFD** [comment]
Sorry, I had thought that the verification form was the same as the one for Arcade, without checking, but I've filled it in now.

**Review by LimesKey — APPROVED** [review]
Hi @AsgerFD!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/qlYI6n). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
