### PR TITLE
Aditya PV- VikramSat Demonstration Board V1

### PR DESCRIPTION
**Pull request by Vipremigini**
## Submission Checklist:

- [X ] I am a current high school, middle school, or home schooled student.
  - [X ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X ] I made this board from scratch, even if I followed a tutorial
- [X ] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [X ] Created a folder under `onboard/projects`
  - [X ] Filled out `TEMPLATE.md` as `README.md`
  - [X ] Uploaded Gerber, sources, and schematic
  - [X ] Uploaded screenshot of PCB order with all costs included
  - [X ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — APPROVED** [review]
:rocket: So exciting!!! LGTM, but I'd recommend that you should look into other shipping options, $31 is a lot, there might be cheaper ones available. If it's cheaper, you could have enough money left over to make v2 or a different design. Here are some tips: https://github.com/hackclub/OnBoard/tree/main/community/shipping.md Also waiting on approval of student verificaiton.

Keep us updated in #onboard on Slack!

**Comment by Vipremigini** [comment]
yeah! its the cheapest already!!

**Review by sarthaktexas — APPROVED** [review]
Howdy Aditya! I'm approving your student verification :) @karmanyaahm Is this good to send?

**Comment by karmanyaahm** [comment]
Yes, it's good to send.

**Pull request merged**
