### PR TITLE
Ishit's PCB

### PR DESCRIPTION
**Pull request by NotIshi28**
## Submission Checklist:

- [ y] I am a current high school, middle school, or home schooled student.
  - [ y] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ it shows that there has been a glitch] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [y ] I made this board from scratch, even if I followed a tutorial
- [y ] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [ y] Created a folder under `onboard/projects`
  - [y ] Filled out `TEMPLATE.md` as `README.md`
  - [ y] Uploaded Gerber, sources, and schematic
  - [ y] Uploaded screenshot of PCB order with all costs included
  - [y ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [y ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ took help from a tutorial] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by sarthaktexas — APPROVED** [review]
Hi Ishit! I'm approving your student verification :) The next step will be to wait 24-48 hours for the technical review and then your PR will be merged and you'll receive your grant! @hackclub/boarding-party

**Review by maxwofford — APPROVED** [review]
Wahooo! Let's get this design fabricated

**Comment by karmanyaahm** [comment]
You should get your grant in the next 24 hours!

**Comment by sarthaktexas** [comment]
Sent!

**Pull request merged**
