### PR TITLE
My pcb card

### PR DESCRIPTION
**Pull request by luxkatana**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/taseenspcbhackercard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/4eba58f886b8dc1c31291474d92dbb7339468cf3/projects/taseenspcbhackercard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/4eba58f886b8dc1c31291474d92dbb7339468cf3/projects/taseenspcbhackercard/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/4eba58f886b8dc1c31291474d92dbb7339468cf3/projects/taseenspcbhackercard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hey! You haven't selected assembly which means no components will be placed onto the PCB, did you forget or are you going to assemble it yourself?

**Comment by luxkatana** [comment]
Huh? I have designed it at EasyEDA..

**Comment by LimesKey** [comment]
Follow the [JLCPCB ordering guide](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) and try again, there are steps there on selecting assembly. Ask in the Slack in the #electronics channel if you need more help.

**Comment by luxkatana** [comment]
Alright, should I make a new PR or should I keep using this one?

**Comment by LimesKey** [comment]
Keep this one, just reupload the cart.

**Comment by luxkatana** [comment]
I am so confused, JLPCB is telling me that it can't order the 25X48MM_NFC_ANTENNA but the tutorial needs it..
image

**Comment by LimesKey** [comment]
That's not a part! It does not need to be placed, ignore placing that part and continue on!

**Comment by luxkatana** [comment]
Heya is this what you need? I clicked on "do not place this part"

**Comment by LimesKey** [comment]
I need the unpaid order, see here,

> Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of your cart rather than the completed unpaid order.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:
> 
> 1. Click "Secure Checkout": After adding your PCB to the cart
> 2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
> 3. Close that tab and open a new one to the [JLCPCB Order page](https://jlcpcb.com/user-center/orders/), then take a rectangular screenshot of the PCB you just submitted. It should show all the details of your order including the price and assembly.
> 
> This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congratulations on making the PCB! Please ask in [#electronics](https://slack.com/archives/C056AMWSFKJ) in the [Slack](https://hackclub.com/slack/) if you need any further help.

**Comment by luxkatana** [comment]
Think I should be doing this on pc

**Comment by luxkatana** [comment]
And this is what I get if I close that payment tab
image

**Comment by LimesKey** [comment]
Go to https://jlcpcb.com/user-center/orders/ and take a screenshot of your order there

**Comment by luxkatana** [comment]
image

**Comment by LimesKey** [comment]
Great, can you now replace your `cart.png` with this new one?

**Comment by luxkatana** [comment]
Alrighty

**Comment by luxkatana** [comment]
By the way I heard that y'all don't pay sending fees or something?

**Comment by luxkatana** [comment]
By the way I heard that OnBoard doesn't cover some cost? What was it again?

**Comment by LimesKey** [comment]
OnBoard covers everything except customs fees for your specific country.

**Review by LimesKey — CHANGES_REQUESTED** [review]
Can you update your `README.md` with the new price total?

**Comment by luxkatana** [comment]
I'm not sure yet that I am going to order the pcb card.. I'll cancel this, should I remove then my directory?

**Comment by LimesKey** [comment]
Mark the pull request as a draft if you're still making edits to the PCB, or if you're not going to order this entirely, close the pull request.

**Comment by luxkatana** [comment]
Alright thank you for helping me!

**Pull request closed without merging**
