### PR TITLE
Create BlackCardNfcPcb

### PR DESCRIPTION
**Pull request by rouguecrow10639**
## Submission Checklist:

- [ yes] I am a current high school, middle school, or home schooled student.
  - [ yes] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [no ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [yes ] I made this board from scratch, even if I followed a tutorial
- [yes ] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [yes ] Created a folder under `onboard/projects`
  - [yes ] Filled out `TEMPLATE.md` as `README.md`
  - [yes ] Uploaded Gerber, sources, and schematic
  - [yes ] Uploaded screenshot of PCB order with all costs included
  - [yes ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ yes] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [yes ] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi! You need to select "Economic", not "Standard assembly" from JLCPCB. Economic saves a lot of money and is enough for the Hacker Card. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-assembly for how to do this.

Additionally, put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) in the "src" folder. They should be two .JSON files containing details about your project, one from the schematic tab, one from the PCB tab.

**Comment by rouguecrow10639** [comment]
When I tried to put it on economic it wouldn’t let me last time I will
check again though

**Comment by rouguecrow10639** [comment]
should be all good now

**Comment by rouguecrow10639** [comment]
Thanks I will I have certain restrictions so I might not get to do it for a
little while can I still get the grant?

**Review by karmanyaahm — APPROVED** [review]
LGTM

**Review by daisybanks — APPROVED** [review]
Everything looks good on HCB's side for student verification. I'll be checking for the technical apprval and if we have that Ill go ahead and merge the pr and send the grant. :)

**Pull request merged**
