### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by juan-gonzalez6**
## Submission Checklist:

- [✓ ] I am a current high school, middle school, or home schooled student.
  - [✓ ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [✓ ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [✓ ] I made this board from scratch, even if I followed a tutorial
- [✓ ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [✓ ] Created a folder under `onboard/projects`
  - [✓ ] Filled out `TEMPLATE.md` as `README.md`
  - [ ✓] Uploaded Gerber.zip and Schematic.pdf
  - [✓ ] Created a folder called `src` and uploaded design files
  - [ ✓] Uploaded screenshot of PCB order with all costs included
  - [✓ ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ✓] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [✓ ] (Optional) This project is from a tutorial[^1].
- [ X] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Juan G's NFC card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by MichaByte** [comment]
Hi @juan-gonzalez6!
Could you please add your source files? Here's what you need:
2024-04-18-095120_hyprshot-mh Once you do that, I can get you your grant! Let me know or join [#electronics on Slack](https://hackclub.com/slack/?event=onboard) if you need any help!

**Comment by MichaByte** [comment]
Scrap that, it looks like you've already added them! Let me fix the file naming for you!

**Comment by MichaByte** [comment]
It looks like you're missing your PCB source file @juan-gonzalez6. Also, your `schematic.pdf` is actually your layout. Could you please fix those issues? Let me know or join [#electronics on Slack](https://hackclub.com/slack/?event=onboard) if you need any help!

**Comment by juan-gonzalez6** [comment]
Hello there,
I believe that i fixed everything, please do not hesitate on contacting me if anything is missing
Thank you so much

**Comment by juan-gonzalez6** [comment]
Hello @MichaByte 
Thank you for checking again, I finally figured it out 🎉
Please do not hesitate to message me if anything is missing
Have a great week!

**Pull request merged**
