### PR TITLE
Soumay's Card

### PR DESCRIPTION
**Pull request by BLADE9078**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

### CODE REVIEW

**Comment by BLADE9078** [comment]
[gerber.zip](https://github.com/hackclub/OnBoard/files/11754773/gerber.zip)
[bom.csv](https://github.com/hackclub/OnBoard/files/11754774/bom.csv)
[picknplace.csv](https://github.com/hackclub/OnBoard/files/11754775/picknplace.csv)

**Comment by kvnyng** [comment]
Hey @BLADE9078, 

You had the right idea before with the project folder.

Since we've been at it for a week I'm going to make a submission on your behalf.

**Comment by kvnyng** [comment]
@BLADE9078 can you attach to this comment some screenshots of the design and of our JLCPCB checkout cart?

After that's done, I'll add those in and you'll be all set for the grant!

**Comment by BLADE9078** [comment]
Thanks @kvnyng ! here are the files



Screenshot (65)
image
image

**Comment by kvnyng** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! In 24 hours, you should be receiving an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank ([@Daisy](https://hackclub.slack.com/team/U046V3EK56W) on Slack).
 
Now, you can finally get those PCBs ordered!:tada:

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

**Pull request merged**
