### PR TITLE
Urgent Question.

### PR DESCRIPTION
**Pull request by mchuang413**
hello. i have a question
so i got the HCB OnBoard grant in April, but I bought the PCB with my own money because the actual price was greater than the $100 provided by the grant. I thought I could use the grant later, but turns out the grant is restricted to what purchases I can make...
However, it turns out that my grant can only be used to purchase certain things? Is there any way to transfer the money to my card?

If you need proof that I indeed purchased the PCB, I can attach an image for you to see.
image

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/MCKEYBOARD:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/c7ae5c90b7adb9de0b507e0a710392e9ca28cbad/projects/MCKEYBOARD/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/c7ae5c90b7adb9de0b507e0a710392e9ca28cbad/projects/MCKEYBOARD/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/c7ae5c90b7adb9de0b507e0a710392e9ca28cbad/projects/MCKEYBOARD/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by mchuang413** [comment]
I already asked in Slack but nobody responded.

**Comment by abitchinmorewaysthanone** [comment]
Try again in #electronics and ping @msw and @nora.

**Comment by mchuang413** [comment]
Ok. Thank you

**Pull request closed without merging**
