### PR TITLE
Create Checklist README.md

### PR DESCRIPTION
**Pull request by sahilchess**
## Submission Checklist:

- [Y ] I am a current high school, middle school, or home schooled student.
  - [Y ] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [Y ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ Y] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [Y ] Created a folder under `onboard/projects`
  - [Y ] Filled out `TEMPLATE.md`
  - [ Y] Uploaded Gerber and design files
  - [Y ] Uploaded screen shot of PCB passing JLCPCB inspection

### CODE REVIEW

**Comment by kvnyng** [comment]
Hey @sahilchess,

I see that you're using the advanced PCB setting. Is there a reason for that?

**Review by daisybanks — COMMENTED** [review]
Hi @sahilchess! I'm so excited to have you joining us for OnBoard! Everything looks good on Bank's end @kvnyng. :)

**Comment by sahilchess** [comment]
> Hey @sahilchess,
> 
> I see that you're using the advanced PCB setting. Is there a reason for that?

No, should I change it to the normal setting?

**Comment by sahilchess** [comment]
hi @kvnyng, is there anything left to change or am i good?

**Comment by kvnyng** [comment]
> > Hey @sahilchess,
> > I see that you're using the advanced PCB setting. Is there a reason for that?
> 
> No, but should I change it to the normal setting?

Yeah you should since you'll be paying for more (without any difference to your design).

**Comment by kvnyng** [comment]
Otherwise you're all set!

**Comment by kvnyng** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! In 24 hours, you should be receiving an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank ([@Daisy](https://hackclub.slack.com/team/U046V3EK56W) on Slack).
 
Now, you can finally get those PCBs ordered!:tada:

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

**Comment by daisybanks** [comment]
Yep! I'll be sure to use new email going forward! @sahilchess

**Pull request merged**
