### PR TITLE
Touch Capacitive Piano

### PR DESCRIPTION
**Pull request by sohjeet**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection

### CODE REVIEW

**Comment by sohjeet** [comment]
I did it, fill the verification form

**Comment by bykevinyang** [comment]
Hey @sohjeet!

Love the idea! I've always wanted one of these!

Quick note: The voltage booster that I think you're using (TP4056) boosts to 5V. That would mean you would need to connect to the 5V rail of the Nano rather than Vin. Is that the case?

**Comment by maxwofford** [comment]
Hey @sohjeet your project is so cool! I just reviewed your student verification and it was missing a date on it so I can't approve it. Could you fill out the form again with a dated document?

**Comment by sohjeet** [comment]
@maxwofford I fill the form again with date and teacher's signature.

**Review by daisybanks — COMMENTED** [review]
Welcome OnBoard @sohjeet! Everything looks good on Bank's end @bykevinyang. :)

**Comment by bykevinyang** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! In 24 hours, you should be receiving an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank ([@Daisy](https://hackclub.slack.com/team/U046V3EK56W) on Slack).
 
Now, you can finally get those PCBs ordered!:tada:

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

**Pull request merged**
