### PR TITLE
ledbuttonthingy

### PR DESCRIPTION
**Pull request by Elementxp**
## Submission Checklist:

- [Yes ] I am a current high school, middle school, or home schooled student.
  - [Yes ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Yes ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ Yes] I made this board from scratch, even if I followed a tutorial
- [Yes ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Yes ] Created a folder under `onboard/projects`
  - [Yes ] Filled out `TEMPLATE.md` as `README.md`
  - [ yes] Uploaded Gerber.zip and Schematic.pdf
  - [no, I did not make a design ] Created a folder called `src` and uploaded design files
  - [ yes] Uploaded screenshot of PCB order with all costs included
  - [yes ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by maxwofford** [comment]
@Elementxp hey, this board looks really cool, but it looks like you accidentally added it to your cart a couple times. There should just be a manufacturing charge and an assembly charge in your cart.png.

**Comment by 24c02** [comment]
Hey @Elementxp, do you need any help with this? Feel free to reach out to me here or in #electronics in Slack.

**Comment by karmanyaahm** [comment]
Hi @Elementxp!

Please feel free to ask for help if you need any here or [[#electronics on Slack](https://hackclub.com/slack/?event=onboard)](https://hackclub.com/slack/?event=onboard). I'm closing this for cleanup right now, but if you get your PR fixed, please let me know.

**Pull request closed without merging**
