### PR TITLE
Muhammad Shah's DIY Power Bank PCB

### PR DESCRIPTION
**Pull request by Babyyoda777**
## Submission Checklist:

- [ yes] I am a current high school, middle school, or home schooled student.
- [ yes] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ yes] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [ yes] Created a folder under `onboard/projects`
  - [ yes] Filled out `TEMPLATE.md`
  - [ yes] Uploaded Gerber and design files
  - [ yes] Uploaded screen shot of PCB passing JLCPCB inspection

### CODE REVIEW

**Comment by bykevinyang** [comment]
Hey @Babyyoda777!

So great to see you're submission! While we review your design, can you fill out this airtable [form](https://airtable.com/shrbcDANe6ug6gj0p)? This is so we can verify your student status.

See you in a bit!

**Comment by Babyyoda777** [comment]
@bykevinyang Filled in the form. Just had a question, is it okay to make small changes after PR has been made in case I find issues or areas to improve?
Thanks.

**Comment by bykevinyang** [comment]
Hey @Babyyoda777!

Yeah of course! In fact, that's encouraged!

I'll get back to you of the status of your board tomorrow (since today is a holiday for the team).

Best,
Kevin

**Comment by Babyyoda777** [comment]
Thanks! Just one more question, since I now realise what I'm trying to attempt is a lot more complicated than I initially anticipated, where is the best place to seek help? I tried multiple subreddits but most of them expect you to have significant prior knowledge which I am struggling with.

**Review by daisybanks — APPROVED** [review]
Hey @Babyyoda777! We were able to review your Airtable form info and everything looks great! Excited to get you onto HCB so you start ordering your parts! @bykevinyang. :)

**Comment by Babyyoda777** [comment]
> Hey @Babyyoda777! We were able to review your Airtable form info and everything looks great! Excited to get you onto HCB so you start ordering your parts! @bykevinyang. :)

Great! Thanks so much!

**Comment by bykevinyang** [comment]
Hey @Babyyoda777,

Great to hear!

Yeah just make another PR and I'll merge it.

**Pull request merged**
