### PR TITLE
Binary Clock

### PR DESCRIPTION
**Pull request by meee-ing**
## Submission Checklist:

- [ x] I am a current high school, middle school, or home schooled student.
  - [ x] I am 18 or under
  - [x ] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [ x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x ] I made this board from scratch, even if I followed a tutorial
- [x ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x ] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ x] Created a folder called `src` and uploaded design files
  - [ x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [x] (Optional) This project is for [Trick or Trace](https://showcase.hackclub.com/)[^3].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by meee-ing** [comment]
I want to assemble it myself

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Binary-Clock:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/5009013c568f5b88e3ea64410b439311a2abc385/projects/Binary-Clock/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/5009013c568f5b88e3ea64410b439311a2abc385/projects/Binary-Clock/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/5009013c568f5b88e3ea64410b439311a2abc385/projects/Binary-Clock/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Nice PCB! Are you able to re-upload your `cart.png` with the assembly and PCB shown so I can check that you've selected ordered correctly?

**Comment by meee-ing** [comment]
Updated

**Comment by LimesKey** [comment]
Hey good work, but are you able to add a little more to your PCB? Perhaps add some more features/electronics, or if not just decorate it a little?

**Comment by meee-ing** [comment]
Done

**Comment by LimesKey** [comment]
Did you update your PCB files, if so, can you re-upload those files?

**Comment by LimesKey** [comment]
Yeah probably add some more to the silkscreen, the name of the board and some more information on using it like the name of some of the pins.

**Pull request closed without merging**
