### PR TITLE
feat: kcoderhtml hacker card and ruler

### PR DESCRIPTION
**Pull request by kcoderhtml**
## Submission Checklist:

- [x] I am a current high school, middle school, or homeschooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by kcoderhtml** [comment]
Thank you!

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi! Your projects look very cool but two small issues:
1. Since the Ruler and NFC Card are two separate projects, can you make them two separate folders with separate READMEs? Like `projects/kcoderhtml-card` and `kcoderhtml-ruler`.
2. You need to select "Economic", not "Standard assembly" from JLCPCB. Economic saves a lot of money and is enough for the Hacker Card. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-assembly for how to do this.

**Comment by karmanyaahm** [comment]
I moved some files around to get you started, only need the updated cart.png (the same image in both folders, since you're ordering together), and a README for the ruler.

**Review by karmanyaahm — APPROVED** [review]
Awesome! Looking forward to pictures of the ruler

**Comment by karmanyaahm** [comment]
You should get an email with your grant virtual card in 24-48 hours.

**Comment by kcoderhtml** [comment]
Thank you!

**Pull request merged**
