### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by possiblyselena**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 2056

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/PianoUSBBUS:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/77650cb1f5b3c60c5bbcb293c9cb008319b93e9f/projects/PianoUSBBUS/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/77650cb1f5b3c60c5bbcb293c9cb008319b93e9f/projects/PianoUSBBUS/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/77650cb1f5b3c60c5bbcb293c9cb008319b93e9f/projects/PianoUSBBUS/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by torbers — CHANGES_REQUESTED** [review]
Hi Selena,
Could you make sure you fill out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)? Thanks!
Also, it looks like the male USB-A port might not be assembled on the board. Could you make sure this is ok and you can solder it on yourself? If not, the tutorial has been updated with a part that should work with Economic PCBA.
Another thing - any idea why the PCBs themselves are costing like $30? They should cost only about $2 to $10. The total cost of the order, including shipping, shouldn't exceed $50 for tutorial projects.
Thanks,
Tori

**Comment by possiblyselena** [comment]
Hi Tori,
I just filled out the verification form.
To choose the economic PCBA type, I can't have the male USB-A port assembled. So I'm fine soldering it myself!
I rechecked my prices and what makes it so expensive is choosing 4 layers, while only having 2 layers in use. Also, the via covering wasn't selected to tented. The board is now around 15$
Screenshot 2024-06-25 074721

Thank you!
Selena

**Comment by torbers** [comment]
Thank you, excellent!
I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/vzxIBn). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Review by torbers — APPROVED** [review]

**Comment by possiblyselena** [comment]
Hi Tori,

I received the grant and I am trying to order the PCB right now, but with
shipping, the total still came out to 52.61$ with a 10$ coupon. Is there
any way I could make the board cheaper or receive a little more of the
grant? I chose Global Standard Direct Line.
[image: image.png]
[image: image.png]

**Pull request merged**
