### PR TITLE
[Snow's] NFC Business Card

### PR DESCRIPTION
**Pull request by CoolCoderSJ**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection

### CODE REVIEW

**Comment by maxwofford** [comment]
Thanks for submitting this @CoolCoderSJ! Go ahead and ignore those breaking CI issues– that's just an automation that's supposed to post a welcome message.

This'll get reviewed soon (everyone on the team is busy with angelhacks), but in the meantime go ahead and fill [this form](https://airtable.com/shrbcDANe6ug6gj0p) out to show your enrollment status, then post here once you've submitted it!

**Comment by CoolCoderSJ** [comment]
Thank you! I've filled it out, hope everyone is having fun is Angelhacks!

**Comment by daisybanks** [comment]
Awesome idea @CoolCoderSJ - can't wait to see you build this out! @bykevinyang - everything looks good on my end! :)

**Review by daisybanks — COMMENTED** [review]
Awesome idea @CoolCoderSJ - can't wait to see you build this out! @bykevinyang - everything looks good on my end! :)

**Comment by bykevinyang** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! You should have just received an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank (
[@Daisy](https://hackclub.slack.com/team/U046V3EK56W)
 on Slack).
 
Now, you can finally get those PCBs ordered!:tada:

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

**Pull request merged**
