### PR TITLE
TinyDUCKY Badpotato1007

### PR DESCRIPTION
**Pull request by BadPotato1007**
## Submission Checklist:

- [ x ] I am a current high school, middle school, or home schooled student.
  - [ x ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ x ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ x ] I made this board from scratch, even if I followed a tutorial
- [ x ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ x ] Created a folder under `onboard/projects`
  - [ x ] Filled out `TEMPLATE.md` as `README.md`
  - [ x ] Uploaded Gerber, sources, and schematic
  - [ x ] Uploaded screenshot of PCB order with all costs included
  - [ x ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by BadPotato1007** [comment]
Hey! Sorry for this, but i forgot to add the $40 shipping that jlcpcb is taking to ship this project to India! 
I can verify in advance that I am OK to pay any import dudy on this project!

**Comment by maxwofford** [comment]
Thanks for submitting this @BadPotato1007! It looks like the project is based on the TinyDuck, but I don't see a tutorial link in your post description. Can you share more about how you designed it?

**Comment by BadPotato1007** [comment]
Huh.. i genuinely did not know a project with the same name existed! And this would probably have made my work easier, if i had seen that before... I have designed it on my own using attiny85's datasheets and a few YouTube videos related to programming this ic 😁

**Comment by BadPotato1007** [comment]
making a newer version

**Comment by karmanyaahm** [comment]
btw you can reopen the same PR, and it should reflect all the changes you made in your source repo.

**Pull request closed without merging**
