### PR TITLE
Shayan's Buisness Card

### PR DESCRIPTION
**Pull request by Lightshayan**
## Submission Checklist:

- [ x] I am a current high school, middle school, or home schooled student.
  - [ x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x ] I made this board from scratch, even if I followed a tutorial
- [ x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ x] Created a folder under `onboard/projects`
  - [ x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x ] Created a folder called `src` and uploaded design files
  - [ x] Uploaded screenshot of PCB order with all costs included
  - [ x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/5c7d9e9121be2ec0ebe3d6208dffb80000340401/projects/Buisness_card_SM/Gerber_New-Project_PCB_New-Project_3_2024-03-04.zip>)!

  Happy OnBoarding!

**Comment by Lightshayan** [comment]
The link looks right.

**Comment by Lightshayan** [comment]
I want to add that I was able to bring the cost down to $21.52 by using a coupon.
image

**Review by maxwofford — APPROVED** [review]
Hey @Lightshayan, your student verification is approved! Can you add your src folder and upload your easyeda json in there?

**Comment by Lightshayan** [comment]
@maxwofford Let me know if I need anything else!

**Comment by maxwofford** [comment]
Nice! I just [sent the grant](https://hcb.hackclub.com/grants/Xk5IZe)!

**Comment by Lightshayan** [comment]
Can I use the remainder of the grant for another PCB or a duplicate with improvements?

**Pull request merged**
