### PR TITLE
submission BEN-NFC-CARD

### PR DESCRIPTION
**Pull request by 2008wbbv**
## Submission Checklist:

- [x ] I am a current high school, middle school, or home schooled student.
  - [x ] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x ] I made this board from scratch, even if I followed a tutorial
- [x ] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [ x] Filled out `TEMPLATE.md`
  - [ x] Uploaded Gerber and design files
  - [ x] Uploaded screen shot of PCB passing JLCPCB inspection
  - [ x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x ] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by daisybanks — APPROVED** [review]
Welcome OnBoard @2008wbbv! So excited to have you joining! Everything looks good on Bank's side @hackclub/boarding-party1

**Comment by daisybanks** [comment]
@2008wbbv you need one more approval from @hackclub/boarding-party and then your pr will be merged and you'll receive your grant.

**Comment by 2008wbbv** [comment]
do people check this super often or no?

**Review by karmanyaahm — APPROVED** [review]
LGTM!

**Comment by 2008wbbv** [comment]
so now do I have to do the survey like for the sprig?

**Pull request merged**
