### PR TITLE
Project Submission: Alex P's NFC Card

### PR DESCRIPTION
**Pull request by alx-alexpark**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: FRC624

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
The design LGTM! Can you please export a .json from the schematic tab, just like you have a pcb-easyeda.json? Also, please put these two JSONs into a new folder at projects/Alex P's NFC Card/src/

**Comment by alx-alexpark** [comment]
@karmanyaahm Should be done. Sorry for the unverified commit I was lazy and spun up a codespace.

**Review by karmanyaahm — APPROVED** [review]
lgtm. Waiting on approval of student verification

**Review by sarthaktexas — APPROVED** [review]
Howdy Alex! I'm approving your student verification :) I'll send you your grant now.

**Pull request merged**
