### PR TITLE
Tofy's Keyboard

### PR DESCRIPTION
**Pull request by tofy-dev**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/tofyKeeb:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/58be480c6c71bae6e130f9e5b1c1ab7c78be554b/projects/tofyKeeb/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/58be480c6c71bae6e130f9e5b1c1ab7c78be554b/projects/tofyKeeb/schematic.pdf>) |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/58be480c6c71bae6e130f9e5b1c1ab7c78be554b/projects/tofyKeeb/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by tofy-dev** [comment]
@maxwofford i uploaded my src files, but it seems like the system didn't recognize them. Thank you.

**Comment by tofy-dev** [comment]
Hi @MichaByte Thank you so much for getting back to me. I also wanted to do the economic assembly, but due to board size or something, JLCPCB only offered Standard Assembly. I wanted to have JLCPCB assemble my components because I don't think I have the expertise and tools to solder such smaller components. I plan on soldering the hot-swap sockets on the PCB myself though (because those are much larger and easier to solder by hand). Is the grant only $100 max per person?

**Comment by MichaByte** [comment]
Hi @tofy-dev!

That reason for using standard assembly makes sense. The grant is only $100 per person, but if you want, we can split the difference, meaning that we will cover $100 and you will cover the rest. Before that, it looks like your layout source file is not properly uploaded and is an empty file. Could you try uploading it again? Once you do that, try going through the checkout process to see how much shipping and tax will be, and update the `cart.png` screenshot with the screen that says "Awaiting Payment" and the final amount. That's needed so that you can send the right amount for us to add to your grant. Just make sure to not submit payment quite yet - we'll get to that later!

**Comment by tofy-dev** [comment]
Hi @MichaByte ~

I was able to fix the issues and reduce the cost to $99!!! Thank you! I uploaded new cart image to cart.png. However, I'm not sure why my pcb file is showing up blank (you must click on the "view raw" button to see it I guess...

Thank you again!

**Review by abitchinmorewaysthanone — CHANGES_REQUESTED** [review]
Your board looks great - the PCB is showing up fine for me. Your submission still has some issues though.

1. It seems you put your last name in the "email" field on the OnBoard (verification form)[https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form]. I need your email to send you the grant! Also, your ID looks a bit out of date - if you could upload a current one that would be great. Please resubmit the form.
2. You haven't (joined Slack)[https://hackclub.com/slack/?event=onboard] - you do have to join for OnBoard.

I will merge the PR & send you your grant when you have made these changes!

**Comment by tofy-dev** [comment]
Hi @abitchinmorewaysthanone 

I have fixed your above requests and uploaded a recent transcript. I also joined the slack as Skyler Tabofunda. Thank you!

**Comment by abitchinmorewaysthanone** [comment]
Excellent! Looks awesome. I've just sent you your (grant)[https://hcb.hackclub.com/grants/w9NIZm]. You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Review by abitchinmorewaysthanone — APPROVED** [review]

**Pull request merged**
