### PR TITLE
Pi Day Pie PCB

### PR DESCRIPTION
**Pull request by revaga**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Pi Day Pie Keychain:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|🟨 | schematic.pdf | Manually check schematic.pdf |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/7a33b2113d3fa5c391a34f9e2ad6bf18c387d1ca/projects/Pi Day Pie Keychain/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Your schematic uses 1N4007W, which is a diode, not a _light emitting_ diode. A diode is simply a one way valve for current - I'm assuming you want an LED here

Here's something Max wrote about LEDs (and also has a link for shine through LEDs) https://github.com/hackclub/OnBoard/blob/main/examples/ingredients/led.md

Also, I would recommend adding resistors before the LEDs in the schematics. Which resistor you use depends on what color LED you end up picking. You could get away without resistors on here because the battery has a fairly high internal resistance, but your battery would last less than a few hours

Feel free to ask if you have any questions here or on Slack!

**Comment by karmanyaahm** [comment]
Student verification is approved

**Comment by revaga** [comment]
> Your schematic uses 1N4007W, which is a diode, not a _light emitting_ diode. A diode is simply a one way valve for current - I'm assuming you want an LED here
> 
> Here's something Max wrote about LEDs (and also has a link for shine through LEDs) https://github.com/hackclub/OnBoard/blob/main/examples/ingredients/led.md
> 
> Also, I would recommend adding resistors before the LEDs in the schematics. Which resistor you use depends on what color LED you end up picking. You could get away without resistors on here because the battery has a fairly high internal resistance, but your battery would last less than a few hours
> 
> Feel free to ask if you have any questions here or on Slack!

Thank you so much for these tips! I think I've fixed all the issues. I'm not sure if I picked the right resistor. 

I really appreciate your help, it's made me feel a lot more confident about ordering my PCB knowing that it's being reviewed!

**Comment by karmanyaahm** [comment]
Hey @revaga! The LEDs look great, but (I should've clarified this before, mb) I would recommend that each LED get it's own resistor. Because of minor differences in the manufacturing process, with one resistor, it's possible that one LED takes up all the current, and the others are starved. (simplifying, but that's a good rule of thumb to be safe). 

Also I'd recommend using like 100-something ohms on each. This is how I derived that
CR2032 batteries typically output around 2.9V
image
The LED consumes around 2.7V at 3mA (235mAh battery / 3mA / 3 leds = 26 hours, and should be somewhat bright?)
image

And (2.9V - 2.7V) / 3mA = 70 ohms

Of course there are a lot more variables with the battery's own resistance and stuff, but with a 100-200ohm resistor it should be fine overall.


Other than that, everything looks good, so I can send you your grant as soon as you upload the changed files!

**Comment by revaga** [comment]
Thank you for the detailed explanation! I understand the resistor issue, current likes to travel the path of least resistance, so one resistor for all 3 might cause issues.

**Comment by karmanyaahm** [comment]
Hi Name!
I've just sent you your grant for OnBoard. You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.**

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #onboard channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
