### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Aaditya-Aniraj**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Business_card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Aaditya-Aniraj** [comment]
> Hi, I'm Orpheus Leap! Here to help you review your PR.
> **projects/Business_card:**
> 
> Required files
> 
> ✅	README.md	A description of your project
> ❌	cart.png	You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png".
> **❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".** Happy OnBoarding! This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.

I did add a cart.png file that is called that and i did call the gerber file gerber.zip

**Comment by blazecoding2009** [comment]
Hey @Aaditya-Aniraj 

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process. For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

Click "Secure Checkout": After adding your PCB to the cart

Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options

Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

Also please name the schematic `schematic.pdf`

**Comment by blazecoding2009** [comment]
@Aaditya-Aniraj 

Once you've made the changes I requested, I can send your grant

**Comment by blazecoding2009** [comment]
Also please do your verification form

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Please refer to other PRs on what we need to see as the cart.ong

**Comment by Aaditya-Aniraj** [comment]
Do you know what I need to add to my cart.png?

**Comment by blazecoding2009** [comment]
Please open a new tab to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

**Comment by blazecoding2009** [comment]
I can't find your name in our verification form list, have you done it?

**Comment by Aaditya-Aniraj** [comment]
Apologies, I thought that when it was asking for the verification form it was asking for the inital age verification form. I have filled it in and I am waiting for it to be approved.

**Review by blazecoding2009 — APPROVED** [review]
Looks good! I've sent your [grant](https://hcb.hackclub.com/grants/q16INO)

**Pull request merged**
