### PR TITLE
Dexter_Dual_NFC

### PR DESCRIPTION
**Pull request by Speedlet1**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by Speedlet1** [comment]
Sorry didn't mean to do that 😅😅

**Review by Leo32345 — APPROVED** [review]
Looks cool!

As a side note, it looks like you have selected HASL with lead for your surface finish, it might be safer to select lead-free HASL instead :)

**Comment by Speedlet1** [comment]
Sounds great! Another side note, would I be able to apply for another grant in order to produce these? I'm not sure how this works as my other project had the costs increased as almost all of the components were extended for JLCPCB with no drop in replacements so I wouldnt have enough budget to produce these as well.
Thanks!

**Comment by daisybanks** [comment]
@Speedlet1 as of right now it's only 1 grant per person.

**Comment by karmanyaahm** [comment]
Since this cannot be granted, I'm closing this issue. Please lmk if anything changes here.

**Pull request closed without merging**
