### PR TITLE
Buck Regulator

### PR DESCRIPTION
**Pull request by Peepesucksstiks**
## Submission Checklist:

- [x ] I am a current high school, middle school, or home schooled student.
  - [ x] I am 18 or under
  - [ x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x ] I made this board from scratch, even if I followed a tutorial
- [ x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ x] Created a folder under `onboard/projects`
  - [ x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ x] Created a folder called `src` and uploaded design files
  - [ x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/buck-regulator:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/add28d4d060aa662c712a4950d8e8e6353778961/projects/buck-regulator/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/add28d4d060aa662c712a4950d8e8e6353778961/projects/buck-regulator/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/add28d4d060aa662c712a4950d8e8e6353778961/projects/buck-regulator/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by blazecoding2009** [comment]
Hey @Peepesucksstiks 

Are you able to use a slower shipping option or try and reduce the price of the overall PCB? $70 is really expensive for such as simple board!

**Comment by Peepesucksstiks** [comment]
I know it's expensive, but it's the cheapest shipping option avaliable to me.

**Comment by Peepesucksstiks** [comment]
@blazecoding2009 
The only other avaliable Shipping method is `DHL Express Worldwide` wich is more expensive than the one I've selected

**Comment by blazecoding2009** [comment]
> @blazecoding2009 The only other avaliable Shipping method is `DHL Express Worldwide` wich is more expensive than the one I've selected

Ah okay no worries. It looks like you were already given your $100 grant around a month ago, if you didn't know, that grant is only given once and cannot be regiven. If you'd like to add money to your grant, let me know and I can help you donate to the onboard HCB and then top up your grant with that amount.

**Comment by Peepesucksstiks** [comment]
Hi, This grant isn't for me, it's for a friend, and he doesn't want to create a GH account "bc he doesn't like microsoft". Is there a way to give to him the grant without needing to create a GH account? Thanks
PS: If it is necesary to create an account, will he have create a PR or will you be able to add him to this one?
Thanks

**Comment by blazecoding2009** [comment]
Sorry, we can't do that. We need your friend to create the PR.

**Comment by blazecoding2009** [comment]
And the account

**Comment by Peepesucksstiks** [comment]
Ok, so I'll close this PR

**Pull request closed without merging**
