### PR TITLE
Sang's W TOTK Key

### PR DESCRIPTION
**Pull request by SangTNguyen2**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md`
  - [X] Uploaded Gerber.zip and Schematic.pdf
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Sang's W TOTK Key:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/1a04de00bfb30ed4020366a34b1a83704868f3a3/projects/Sang's W TOTK Key/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/1a04de00bfb30ed4020366a34b1a83704868f3a3/projects/Sang's W TOTK Key/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/1a04de00bfb30ed4020366a34b1a83704868f3a3/projects/Sang's W TOTK Key/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by SangTNguyen2** [comment]
To whoever that may be reviewing my design on the Engineering Team, I greatly thank you and look forward to the feedback!

**Comment by MichaByte** [comment]
Hi @SangTNguyen2! This design looks awesome and I'm excited to get you your grant! I was looking at your student verification, and I didn't see a year on your proof of enrollment. Could you please find another screenshot that contains a year, such as a picture of a student ID card? Thank you!

**Comment by SangTNguyen2** [comment]
Hi @MichaByte Thank you for the feedback and the green light! I lost my student card LOL but I submitted using powerschool Naviance profile which includes year and my id :)

Thanks so much!

**Comment by MichaByte** [comment]
Hi @SangTNguyen2!
Would you me able to [join us on Slack](https://hackclub.com/slack/?event=onboard) and DM me (My username is `@Micha` there) so I can talk to you about this? I'm excited to get you your grant!

**Comment by SangTNguyen2** [comment]
i updated the gerber file as well as the pcb.json

**Comment by MichaByte** [comment]
Hi @SangTNguyen2!
I've just sent you [your grant for OnBoard](https://hcb.hackclub.com/grants/woQINL). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please keep this in mind before you make any purchases.**

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
