### PR TITLE
my hackercard project (first pcb) !!

### PR DESCRIPTION
**Pull request by arsoninstigator**
## Submission Checklist:

- [Y] I am a current high school, middle school, or home schooled student.
  - [Y] I am 18 or under
  - [Y] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Y] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [Y] I made this board from scratch, even if I followed a tutorial
- [ Y] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Y] Created a folder under `onboard/projects`
  - [ Y] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ Y] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ Y] Created a folder called `src` and uploaded design files
  - [ Y] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [Y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ Y] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [Y ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/ANNE_HACKERCARD:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/db21de45a76364af7226e73259bc825b7bba73a5/projects/ANNE_HACKERCARD/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/db21de45a76364af7226e73259bc825b7bba73a5/projects/ANNE_HACKERCARD/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/db21de45a76364af7226e73259bc825b7bba73a5/projects/ANNE_HACKERCARD/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by arsoninstigator** [comment]
Thank you! I'm new to PCBs so I don't know how to exactly change the setting but on JLCPCB I chose a black / blue board color instead of the green that can be seen on this rendering. Please let me know if there's any steps I need to take to ensure the board isn't green or any other color.
Regards,
Anoushka
________________________________

**Comment by LimesKey** [comment]
The PCB should be very similar to what JLCPCB's render/preview is, the preview on the Gerber view here is not accurate to the color of what you'll be getting. What do you mean by Blue, I see your solder mask is only Black?

**Comment by arsoninstigator** [comment]
> The PCB should be very similar to what JLCPCB's render/preview is, the preview on the Gerber view here is not accurate to the color of what you'll be getting. What do you mean by Blue, I see your solder mask is only Black?

I meant that I'd settle for blue in a worst case scenario but black is what I actually want. Since the JLCPCB's rendering is exactly similar to the easyeda's 3d rendering of what I want it to look like, I'm going to ignore the board color difference in the gerber view for now.

**Review by LimesKey — CHANGES_REQUESTED** [review]
It looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by arsoninstigator** [comment]
> It looks like you took a picture of the cart ordering process instead of completing the checkout process. For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:
> 
> 1. Click "Secure Checkout": After adding your PCB to the cart
> 2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
> 3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.
> 
> Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

I'm attaching the newer files below, please let me know if the update needs to be made on the actual initial repository because I don't know how to update it without making this thread disappear completely. 

cart
cart2
[gerber.zip](https://github.com/user-attachments/files/16329108/gerber.zip)
[schematic.pdf](https://github.com/user-attachments/files/16329092/schematic.pdf)
[bom.csv](https://github.com/user-attachments/files/16329099/bom.csv)
[schematic.json](https://github.com/user-attachments/files/16329093/schematic.json)
[pcb.json](https://github.com/user-attachments/files/16329094/pcb.json)

**Review by LimesKey — CHANGES_REQUESTED** [review]
It looks good, thanks, but I see the resistor you chose, U2, is very large. Did you mean to choose a resistor different from the tutorial?

**Comment by arsoninstigator** [comment]
> It looks good, thanks, but I see the resistor you chose, U2, is very large. Did you mean to choose a resistor different from the tutorial?

I meant to follow the tutorial itself. Should I go back and redo the process? Or should I change the resistor **before** the BOM is generated? Should something be changed in the schematic / pcb itself?

**Comment by LimesKey** [comment]
Delete the current resistor in the schematic and find the one specified in the jam, you will have to replace the resistors in the PCB and get a new JLCPCB order though.

**Comment by arsoninstigator** [comment]
> Delete the current resistor in the schematic and find the one specified in the jam, you will have to replace the resistors in the PCB and get a new JLCPCB order though.

Okay! So I went back, redid the process of creation and created a new order on jlcpcb.com. 
[cart](https://github.com/user-attachments/assets/e716b363-490d-40fd-a503-9e5ecfb85e78)
[gerber.zip](https://github.com/user-attachments/files/16364746/gerber.zip)
[schematic.pdf](https://github.com/user-attachments/files/16364752/schematic.pdf)
[schematic.json](https://github.com/user-attachments/files/16364753/schematic.json)
[pcb.json](https://github.com/user-attachments/files/16364754/pcb.json)

**Review by LimesKey — APPROVED** [review]
Hi @arsoninstigator!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/vA5IBm). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
