### PR TITLE
Kumaraswamy's Card

### PR DESCRIPTION
**Pull request by XomaDev**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by daisybanks — APPROVED** [review]
Welcome OnBoard @XomaDev! Happy to have you here! Everything looks good on Bank's side @hackclub/boarding-party!

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
> I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)

Like you checked in the submission checklist, you are only supposed to order 5 boards, not 15. The rest of the grant is to allow you to play with more unique designs. If you'd like, you can make 3 unique designs and order them in the same order to reduce shipping costs, or you can experiment with other boards.

**Comment by kvnyng** [comment]
@karmanyaahm what's the status on merging this PR?

**Comment by XomaDev** [comment]
Hi Karmanyaahm, I had uploaded two screenshots, in which the other one was a old one where I had selected Qty 15, please refer the "jcl-pcb-order.png" file.

Thanks!

**Comment by XomaDev** [comment]
Just to make sure, are these connections right?

image

**Review by karmanyaahm — APPROVED** [review]
👍

**Pull request merged**
