### PR TITLE
add karmanyaahs pcb motor

### PR DESCRIPTION
**Pull request by karmanyaahm**
my third board

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/karmanyaahs-pcb-motor-v0:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/8c071cf2721d567700429a8dacd2d7872329119a/projects/karmanyaahs-pcb-motor-v0/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/8c071cf2721d567700429a8dacd2d7872329119a/projects/karmanyaahs-pcb-motor-v0/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/8c071cf2721d567700429a8dacd2d7872329119a/projects/karmanyaahs-pcb-motor-v0/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/karmanyaahs-pcb-motor-v0:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/8c071cf2721d567700429a8dacd2d7872329119a/projects/karmanyaahs-pcb-motor-v0/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/8c071cf2721d567700429a8dacd2d7872329119a/projects/karmanyaahs-pcb-motor-v0/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/8c071cf2721d567700429a8dacd2d7872329119a/projects/karmanyaahs-pcb-motor-v0/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by blazecoding2009** [comment]
Hi 
your PR has been approved! I see you already have a outstanding grant so I won't be sending you another one, good luck getting your PCB!

PS I'll merge them in a few hours :)

**Review by blazecoding2009 — APPROVED** [review]
Merged, No HCB needed, already given a grant

**Pull request merged**
