### PR TITLE
MiniMorse

### PR DESCRIPTION
**Pull request by pricken45**
## Submission Checklist:

- [x ] I am a current high school, middle school, or home schooled student.
  - [ x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x ] I made this board from scratch, even if I followed a tutorial
- [x ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x ] Created a folder under `onboard/projects`
  - [x ] Filled out `TEMPLATE.md` as `README.md`
  - [x ] Uploaded Gerber.zip and Schematic.pdf
  - [x ] Created a folder called `src` and uploaded design files
  - [x ] Uploaded screenshot of PCB order with all costs included
  - [x ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/MiniMorse:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/0040763d352964ef0ef02d64fb486ce256fcbddb/projects/MiniMorse/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/0040763d352964ef0ef02d64fb486ce256fcbddb/projects/MiniMorse/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/0040763d352964ef0ef02d64fb486ce256fcbddb/projects/MiniMorse/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by maxwofford — APPROVED** [review]
This is so coool! I'd love to hear about how you're coding the morse translator– is it just timeouts, or something more advanced?

**Comment by pricken45** [comment]
Hello! The conversion is done with arduino using the code below. You basically type some text using a potentiometer and a button and then you press the other button to hear the message play out loud!

`#include "SSD1306Ascii.h"
#include "SSD1306AsciiAvrI2c.h"

#define I2C_ADDRESS 0x3C
#define RST_PIN -1

SSD1306AsciiAvrI2c oled;


#define TIMEUNIT 100
#define TONEPIN 9

int letters[26][4] = {
  { 1, 2 },
  { 2, 1, 1, 1 },
  { 2, 1, 2, 1 },
  { 2, 1, 1 },
  { 1 },
  { 1, 1, 2, 1 },
  { 2, 2, 1 },
  { 1, 1, 1, 1 },
  { 1, 1 },
  { 1, 2, 2, 2 },
  { 2, 1, 2 },
  { 1, 2, 1, 1 },
  { 2, 2 },
  { 2, 1 },
  { 2, 2, 2 },
  { 1, 2, 2, 1 },
  { 2, 2, 1, 2 },
  { 1, 2, 1 },
  { 1, 1, 1 },
  { 2 },
  { 1, 1, 2 },
  { 1, 1, 1, 2 },
  { 1, 2, 2 },
  { 2, 1, 1, 2 },
  { 2, 1, 2, 2 },
  { 2, 2, 1, 1 }
};

void shortBeep() {
  tone(TONEPIN, 900, TIMEUNIT);
  delay(TIMEUNIT);
}
void longBeep() {
  tone(TONEPIN, 900, TIMEUNIT * 3);
  delay(TIMEUNIT * 3);
}

void playIndex(int* cL) {
  int al = sizeof(cL) / sizeof(cL[0]);

  for (int i = 0; i < 4; i++) {
    int c = cL[i];
    if (c == 1) {
      shortBeep();
      delay(TIMEUNIT);
    } else if (c == 2) {
      longBeep();
      delay(TIMEUNIT);
    }
  }
}

void playString(String input) {
  input.toLowerCase();
  const char* inputC = input.c_str();

  const int len = input.length();
  for (int i = 0; i < len; i++) {
    char c = inputC[i];
    if (c == 'a') {
      playIndex(letters[0]);
    } else if (c == 'b') {
      playIndex(letters[1]);
    } else if (c == 'c') {
      playIndex(letters[2]);
    } else if (c == 'd') {
      playIndex(letters[3]);
    } else if (c == 'e') {
      playIndex(letters[4]);
    } else if (c == 'f') {
      playIndex(letters[5]);
    } else if (c == 'g') {
      playIndex(letters[6]);
    } else if (c == 'h') {
      playIndex(letters[7]);
    } else if (c == 'i') {
      playIndex(letters[8]);
    } else if (c == 'j') {
      playIndex(letters[9]);
    } else if (c == 'k') {
      playIndex(letters[10]);
    } else if (c == 'l') {
      playIndex(letters[11]);
    } else if (c == 'm') {
      playIndex(letters[12]);
    } else if (c == 'n') {
      playIndex(letters[13]);
    } else if (c == 'o') {
      playIndex(letters[14]);
    } else if (c == 'p') {
      playIndex(letters[15]);
    } else if (c == 'q') {
      playIndex(letters[16]);
    } else if (c == 'r') {
      playIndex(letters[17]);
    } else if (c == 's') {
      playIndex(letters[18]);
    } else if (c == 't') {
      playIndex(letters[19]);
    } else if (c == 'u') {
      playIndex(letters[20]);
    } else if (c == 'v') {
      playIndex(letters[21]);
    } else if (c == 'w') {
      playIndex(letters[22]);
    } else if (c == 'x') {
      playIndex(letters[23]);
    } else if (c == 'y') {
      playIndex(letters[24]);
    } else if (c == 'z') {
      playIndex(letters[25]);
    }

    noTone(TONEPIN);
    if (c == ' ') {
      delay(TIMEUNIT * 7);
    } else {
      delay(TIMEUNIT * 3);
    }
  }
}

void startSound() {
  tone(9, 800, 100);
  delay(100);
  tone(9, 1600, 100);
}

//------------------------------------------------------------------------------
void setup() {
  Serial.begin(9600);

#if RST_PIN >= 0
  oled.begin(&Adafruit128x64, I2C_ADDRESS, RST_PIN);
#else   // RST_PIN >= 0
  oled.begin(&Adafruit128x64, I2C_ADDRESS);
#endif  // RST_PIN >= 0
  // Call oled.setI2cClock(frequency) to change from the default frequency.

  oled.setFont(Adafruit5x7);
  oled.clear();
  oled.setCursor(12, 3);
  oled.set2X();
  oled.println("MorseNANO");
  pinMode(3, INPUT_PULLUP);
  pinMode(4, INPUT_PULLUP);
  startSound();
  delay(3000);
  oled.set1X();
}
int lastValue = 0;

const char* alfabet = "abcdefghijklnmopqrstuvwxyz ";
String sendString = "";
String displayString = "";

int lastAddButtonRead = 0;
int lastSendButtonRead = 0;

bool updated = false;
//------------------------------------------------------------------------------
void loop() {
  int addButtonRead = digitalRead(3);
  int sendButtonRead = digitalRead(4);
  int readVal = map(analogRead(A3), 0, 1023, 0, 27);
  if (readVal > 26) {
    readVal = 26;
  }

  if (addButtonRead == LOW && lastAddButtonRead == HIGH) {
    sendString += String(alfabet[readVal]);
    displayString += String(alfabet[readVal]);
    if (displayString.length() > 20) {
      displayString.remove(0, 1);
    }
    oled.clear();
    oled.setCursor(0, 3);
    oled.println(displayString + alfabet[readVal]);
    delay(250);
  }

  if (sendButtonRead == LOW && lastSendButtonRead == HIGH) {
    oled.clear();
    playString(sendString);
    sendString = "";
    displayString = "";
    oled.setCursor(0, 3);

    oled.println(displayString + alfabet[readVal]);
  }

  if (readVal != lastValue || updated == false) {
    oled.clear();
    oled.setCursor(0, 3);

    oled.println(displayString + alfabet[readVal]);
    updated = true;
  }

  lastValue = readVal;
  lastAddButtonRead = addButtonRead;
  lastSendButtonRead = sendButtonRead;
}
`

**Comment by maxwofford** [comment]
Lol, love that approach! I just [sent your grant](https://hcb.hackclub.com/grants/vzxIL5).

p.s. `char` is just an int under the hood, so you could do something like this...
```ino
char c = inputC[i];
playIndex(letters[c - 65]);
```

This works because letters start at 65 going up

**Comment by pricken45** [comment]
Wow that's cool, and it saves like a hundred LoC! 

Thank you so much!

**Pull request merged**
