### PR TITLE
Duck

### PR DESCRIPTION
**Pull request by Jark5455**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Duck:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/9e7b02f9e31d900fc5c7e7b74e0617a6dc767462/projects/Duck/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/9e7b02f9e31d900fc5c7e7b74e0617a6dc767462/projects/Duck/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/9e7b02f9e31d900fc5c7e7b74e0617a6dc767462/projects/Duck/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @Jark5455,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by Jark5455** [comment]
@LimesKey Here is the new screenshot

**Comment by LimesKey** [comment]
Very intricate design, I like the LORA and GPS module you are using and I hope everything turns out as you expect. Do you think you can include a WRL 3D Model of the PCB from KiCad, I'd love to see it in 3D.

**Comment by Jark5455** [comment]
Uploaded it :)

Just one quick question tho. Right now the via holes look a little bit too close together resulting in the "margin" of the vias sort of merging together. This creates some sharp angles in the copper plane which is noticeable in vias that are really close together. Is this a problem for manufacturing? I know cnc machines typically suck at really sharp angles like this,  which is why I had originally spaced the vias far enough apart that the "margin" doesn't overlap, but due to misreading jlc's manufacturing constraints, the margins do overlap.

**Comment by LimesKey** [comment]
I took a look at your board and ran these [DRC Rules](https://github.com/labtroll/KiCad-DesignRules) meant for KiCad from JLCPCB capabilities and it came back all fine. Normally I'd have you look at the [JLCPCB Capabilities](https://jlcpcb.com/capabilities/pcb-capabilities) document but you've already done that. The VIA holes don't look too bad, I've seen much worse come back fine. 

Make sure you've checked "Confirm Production file" and "Confirm Parts Placement" when ordering your PCB from JLCPCB, that'll allow the engineers to check the gerber and approve it for any design challenges that JLCPCB cannot do.

**Comment by Jark5455** [comment]
alright thanks

**Review by LimesKey — APPROVED** [review]
Hi @Jark5455!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/v6lIjW). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
