### PR TITLE
Chord Board

### PR DESCRIPTION
**Pull request by udu3324**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [X] (Optional) This project is for [Trick or Trace](http://showcase.hackclub.com/)
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/chordboard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/908776a8ffa480b09e96da88b21ef81b0bfd5aa6/projects/chordboard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/908776a8ffa480b09e96da88b21ef81b0bfd5aa6/projects/chordboard/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/908776a8ffa480b09e96da88b21ef81b0bfd5aa6/projects/chordboard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @udu3324,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by LimesKey** [comment]
Are you also able to submit your KiCad `.WRL` (VRML) 3D Model file? More info [here](https://github.com/hackclub/OnBoard/blob/main/docs/kicad-submission.md).

**Comment by udu3324** [comment]
> Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

> Are you also able to submit your KiCad `.WRL` (VRML) 3D Model file? More info [here](https://github.com/hackclub/OnBoard/blob/main/docs/kicad-submission.md).

I have added both the wrl and the new cart.png

**Comment by LimesKey** [comment]
Awesome board, I liked reading your design process and it's really cool how the board turned out in the end. Curious though why you're entering this for Trick or Trace, have you already gotten your general 100$ OnBoard grant yet?

**Comment by udu3324** [comment]
> Awesome board, I liked reading your design process and it's really cool how the board turned out in the end. Curious though why you're entering this for Trick or Trace, have you already gotten your general 100$ OnBoard grant yet?

Thanks! I entered this for Trick or Trace because of the stickers and the kit, but i also need a general grant for the board itself

**Comment by LimesKey** [comment]
Thanks for your submission to Trick or Trace!

**Pull request merged**
