### PR TITLE
cloudcake8's custom keyboard

### PR DESCRIPTION
**Pull request by CloudCake8**
## Submission Checklist:

- [✔] I am a current high school, middle school, or home schooled student.
  - [✔] I am 18 or under
  - [✔] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [✔] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [✔] I made this board from scratch, even if I followed a tutorial
- [✔] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [✔] Created a folder under `onboard/projects`
  - [✔] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [✔] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [✔] Created a folder called `src` and uploaded design files
  - [✔] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [✔] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [N/A] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [✔] (Optional) This project is from a tutorial[^1]. (ish... i used the tutorial but extrapolated from a 4 key macropad to a 71 key keyboard)
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [✔] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: FRC 3006

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

the price is over the $100, but i can cover the difference. let me know how/where to do this.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/The Ultimate™ custom keyboard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/279ee1ab26ed0b04ae9a3f0edb11ff45f8b70acb/projects/The Ultimate™ custom keyboard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/279ee1ab26ed0b04ae9a3f0edb11ff45f8b70acb/projects/The Ultimate™ custom keyboard/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/279ee1ab26ed0b04ae9a3f0edb11ff45f8b70acb/projects/The Ultimate™ custom keyboard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by torbers — CHANGES_REQUESTED** [review]
Hi Khangai,
The most we can offer for the grant is $100. Here are some suggestions for reducing the price:

- Select PCBA for only two boards rather than all 5. You will still receive all 5, but only two will have components.
- Select green soldermask and lead-free or leaded HASL finish
- Make sure as many parts as possible are "Basic" or "Preferred Extended" parts; these parts have the $3 assembly fee waived. Here is the list: https://jlcpcb.com/parts/basic_parts
- Delete the green PCB prototype that won't be assembled; it seems like it's a mistake and it's costing you $18

If the cost still ends up above $100, DM me on Slack (@tori) and I can help you pay the remainder with your own card.
Thanks!

**Comment by CloudCake8** [comment]
I've made some changes and i got the price down by $19, but it's still $31 over budget. I can pay for the difference (i've DM'd you on Slack already).

The "green PCB prototype" is actually my top plate for my keyboard - but it seems like theres some weird rendering issue with JLCPCB (im fairly certian its just a rendering issue, because when i click "view gerber" it takes me to their online viewer and the pcb is completely fine.

**Comment by torbers** [comment]
I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/Xj8IjW). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Review by torbers — APPROVED** [review]

**Pull request merged**
