### PR TITLE
Carthy - HackerCard

### PR DESCRIPTION
**Pull request by CarthyPoo**
## Submission Checklist:

- [Y] I am a current high school, middle school, or home schooled student.
  - [Y] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Y ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [Y ] I made this board from scratch, even if I followed a tutorial
- [Y] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Y] Created a folder under `onboard/projects`
  - [Y] Filled out `TEMPLATE.md` as `README.md`
  - [Y] Uploaded Gerber.zip and Schematic.pdf
  - [Y] Created a folder called `src` and uploaded design files
  - [Y] Uploaded screenshot of PCB order with all costs included
  - [Y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [Y] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Lawrence's HackerCard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/c6e8a798697176d241f4c7da7c9cbce3fc5df4a0/projects/Lawrence's HackerCard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/c6e8a798697176d241f4c7da7c9cbce3fc5df4a0/projects/Lawrence's HackerCard/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/c6e8a798697176d241f4c7da7c9cbce3fc5df4a0/projects/Lawrence's HackerCard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by 24c02** [comment]
Hi @CarthyPoo! 

You haven't selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order 5 assembled boards.

**Comment by CarthyPoo** [comment]
Apologies!!!! I believe everything should be looking okay now!

**Comment by karmanyaahm** [comment]
Hi @CarthyPoo !
I've just sent you [your grant](https://hcb.hackclub.com/grants/qlYI4z) for OnBoard. You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
