### PR TITLE
Rubifier PCB Project

### PR DESCRIPTION
**Pull request by alexfinger21**
## Submission Checklist:

- [Yes ] I am a current high school, middle school, or home schooled student.
  - [Yes ] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [Yes ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [Yes ] I made this board from scratch, even if I followed a tutorial
- [ Yes] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [ Yes] Created a folder under `onboard/projects`
  - [Yes ] Filled out `TEMPLATE.md`
  - [Yes ] Uploaded Gerber and design files
  - [ Yes] Uploaded screen shot of PCB passing JLCPCB inspection
  - [Yes ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ Not Outside US] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ No] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — APPROVED** [review]
Really cool idea!!!

**Comment by karmanyaahm** [comment]
Since you've ordered a stencil, I'm assuming you have equipment for SMD soldering and the required components. Just FYI you cannot buy those separately with the grant, you can only get components assembled from JLCPCB. 

Also, I moved you Screenshot.png, if it's not needed (looks like it's redundant), please delete it.

**Comment by alexfinger21** [comment]
Ok, thanks so much! Yes, I do have soldering tools so I should be good.

**Comment by alexfinger21** [comment]
Could you please delete the screenshot.png? It looks like I am not able to.
Thanks!

**Comment by kvnyng** [comment]
@daisybanks just bumping this PR!

**Review by daisybanks — APPROVED** [review]
Hi @alexfinger21! Welcome OnBoard! Everything looks look on Bank's side. :)

**Pull request merged**
