### PR TITLE
Taylor Jackson's PCB NFC Card 

### PR DESCRIPTION
**Pull request by Taylortot11**
## Submission Checklist:

- [yes] I am a current high school, middle school, or home schooled student.
  - [yes ] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [yes ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [yes ] I made this board from scratch, even if I followed a tutorial
- [ yes] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [yes ] Created a folder under `onboard/projects`
  - [ yes] Filled out `TEMPLATE.md` as `README.md`
  - [ yes] Uploaded Gerber, sources, and schematic
  - [yes ] Uploaded screenshot of PCB order with all costs included
  - [ yes] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [n/a ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ yes] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by daisybanks — APPROVED** [review]
Hi Taylor! I'm approving your student verification! Next step will be to wait for the technical review which will happen in the next 24-48 hours and then your pr will get merged and I'll get you your grant. :) @hackclub/boarding-party

**Comment by Taylortot11** [comment]
Hi! Thank you for approving my student verification. I'm super excited!
Sounds good and thank you for the update!

Sincerely,
Taylor Jackson
11th Grade Student
Da Vinci Science High School
Advisory - Sy
(P1- HBS) (P2-English 10) (P3- Biology ) (P4- Digital Electronics) (P5-
U.S. History) (P6- Pre-Calc)
www.davincischools.org

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Nice design, I love the holiday theme! Please upload your schematic from EasyEDA as 'schematic.pdf' https://docs.easyeda.com/en/Export/Export-Schematic/index.html

And, just like your exported PCB_PCB_Taylor...json, please export a JSON from the schematic tab and upload it here.

Your design looks great!

**Comment by Taylortot11** [comment]
[Schematic_Taylor_2023-11-27.pdf](https://github.com/hackclub/OnBoard/files/13480308/Schematic_Taylor_2023-11-27.pdf)
[SCH_Taylor_2023-11-27.json](https://github.com/hackclub/OnBoard/files/13480312/SCH_Taylor_2023-11-27.json)
Hi, here are the remaining files that were requested. Thank you!

**Review by karmanyaahm — APPROVED** [review]
LGTM!

**Comment by karmanyaahm** [comment]
You should receive an email with your grant within 24 hours!

**Comment by Taylortot11** [comment]
Yayy thank you so much! I’m looking forward to printing my card!

**Pull request merged**
