### PR TITLE
SnailHub Project Grant

### PR DESCRIPTION
**Pull request by second2falcon**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by second2falcon** [comment]
Will fix the multiple README.md error/mistake and open another PR.

**Comment by second2falcon** [comment]
I am unable to fix the error, but my project files are in the following Git commit: [f793d1b](https://github.com/hackclub/OnBoard/commit/f793d1be34973140a3a3f640ead6777c3e1d332a)

Files are located at [projects/snailhub](https://github.com/hackclub/OnBoard/tree/f793d1be34973140a3a3f640ead6777c3e1d332a/projects/snailhub)

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @second2falcon 

Please upload the proper schematic and not the PCB view, thanks!

**Comment by second2falcon** [comment]
@blazecoding2009 thanks for pointing that out.

I am unsure if it was ammended to this PR, but it should now be in my project files.

**Pull request merged**
