### PR TITLE
PILOT v2 and v3

### PR DESCRIPTION
**Pull request by Jckoneal**
## Submission Checklist:

- [ x] I am a current high school, middle school, or home schooled student.
  - [ x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ x] I made this board from scratch, even if I followed a tutorial
- [ x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ x] Created a folder under `onboard/projects`
  - [ x] Filled out `TEMPLATE.md` as `README.md`
  - [ x] Uploaded Gerber.zip and Schematic.pdf
  - [x ] Created a folder called `src` and uploaded design files
  - [x ] Uploaded screenshot of PCB order with all costs included
  - [ x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by MichaByte** [comment]
Hi @Jckoneal! It looks like you have two different projects in this pull request. We can only accept one project per pull request right now. Can you delete one of the projects from this pull request? You can submit another one later! Once you do that, I can get you your grant!

**Comment by maxwofford** [comment]
@MichaByte I just noticed that @Jckoneal already has a grant card. Want to ignore the 1 project per PR thing for these projects?

**Comment by karmanyaahm** [comment]
Merging! Thanks for submitting @Jckoneal!

**Pull request merged**
