### PR TITLE
Li-Ion Battery pcb

### PR DESCRIPTION
**Pull request by DefinetlyNotAI**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [ ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1]. (Only the schematic part)
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by DefinetlyNotAI** [comment]
Any issues please tell me

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Li-ion_Battery:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|❌ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/94e3a1fbb06a3bc4a03db26e30d2848dbc4d724d/projects/Li-ion_Battery/schematic.pdf>) | You must export your schematic file as schematic.pdf |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/94e3a1fbb06a3bc4a03db26e30d2848dbc4d724d/projects/Li-ion_Battery/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @DefinetlyNotAI 

Please put the files into the correct directories with the correct names.

**Comment by DefinetlyNotAI** [comment]
Done :) Sorry im new to this

**Comment by blazecoding2009** [comment]
Please upload a schematic, not the bom.

**Comment by DefinetlyNotAI** [comment]
where do i get the schematic? The pdf file?

**Comment by DefinetlyNotAI** [comment]
Ok, finished, it should be done, super sorry for any inconveniance

**Comment by blazecoding2009** [comment]
Hey @DefinetlyNotAI 

Are you able to use economic assembly by any chance? if not then it's fine

**Comment by DefinetlyNotAI** [comment]
Well when i said economic it gave an error, BUT if it works for you, then go ahead ;)

**Comment by blazecoding2009** [comment]
I'm asking you as we usually want you to do a few revisions of the pcb with 100 dollars.

I'm not looking to order it, I'm a part of the onboard reviewing team

**Comment by DefinetlyNotAI** [comment]
yes no problem,just tell me if any issues occur, this is my first pcb
:)

**Review by blazecoding2009 — APPROVED** [review]
I've just sent your [grant](https://hcb.hackclub.com/grants/w4DIym), have fun!

**Pull request merged**
