### PR TITLE
"PCB-Dock" request

### PR DESCRIPTION
**Pull request by JimmmithyOrSomething**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/pcb-dock:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @JimmmithyOrSomething 

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by blazecoding2009** [comment]
Additionally, please make a "src" folder in projects/[name]/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

Also, you need to export your schematic tab as a PDF (in the schematic tab go to [File > Export > PDF](https://docs.easyeda.com/en/Export/Export-Schematic/index.html)), and upload that.

**Comment by blazecoding2009** [comment]
Please delete ALL the other files outside your project folder.
image

**Comment by JimmmithyOrSomething** [comment]
Hello, thank you for your help. I am not sure about this but is there a way to move my files into the projects folder? I think that I put the ones that I need outside of the folder. I am new to GitHub and I don't really know how to move things. Thanks for all your help.

**Comment by JimmmithyOrSomething** [comment]
Ok, I deleted the files and put them under projects. Thank you so much for your help. Is there anything else that I need to do or should I just wait to hear back? Thanks again.

**Comment by blazecoding2009** [comment]
Looks like you have lots of repeating files and/or illegal names, please clean that up
image

**Review by blazecoding2009 — APPROVED** [review]
Hey!
I've just sent your [grant](https://hcb.hackclub.com/grants/XdBIB8). Have fun!

**Pull request merged**
