### PR TITLE
NFC Card-akul saju

### PR DESCRIPTION
**Pull request by akulsaju**
## Submission Checklist:

- [ ✅] I am a current high school, middle school, or home schooled student.
  - [ ✅] I am 18 or under
  - [✅ ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [✅ ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [✅ ] I made this board from scratch, even if I followed a tutorial
- [ ✅] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [✅ ] Created a folder under `onboard/projects`
  - [✅ ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ ✅] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [✅ ] Created a folder called `src` and uploaded design files
  - [ ✅] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ ✅] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [✅] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Akul-NFC Card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/1de3a1f3e278fb31baaa2dd28f54e08c3eab5472/projects/Akul-NFC Card/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/1de3a1f3e278fb31baaa2dd28f54e08c3eab5472/projects/Akul-NFC Card/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/1de3a1f3e278fb31baaa2dd28f54e08c3eab5472/projects/Akul-NFC Card/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by blazecoding2009** [comment]
Hey @akulsaju 

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process. For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide here or here:

Click "Secure Checkout": After adding your PCB to the cart
Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.
Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!


Also you are our 1000th PR!

**Comment by akulsaju** [comment]
cart
hey, i cant replace the file

**Comment by blazecoding2009** [comment]
Please delete the old cart.png and upload that

**Comment by akulsaju** [comment]
done

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Please upload the actual schematic and not the PCB view, also please delete the picture! it has your personal information on it

**Comment by blazecoding2009** [comment]
The schematic.pdf

**Comment by akulsaju** [comment]
yes, i changed the schematic.pdf

**Comment by LimesKey** [comment]
Your `cart.png` also seems incorrect, can you look at other pull requests for reference and reupload it?

**Comment by akulsaju** [comment]
What about now

**Comment by blazecoding2009** [comment]
That's good, I'm coming back to canada tomorrow, so I won't have my laptop. Please be patient. You'll get your grant on Friday

**Review by LimesKey — CHANGES_REQUESTED** [review]
Your PCB does not contain any traces, please refer back to the Jam on how to use the auto-router to add traces or add the manually. Additionally, you haven't selected assembly in JLCPCB as seen in your `cart.png`.

**Comment by akulsaju** [comment]
check now

**Comment by blazecoding2009** [comment]
I don't see your Gerber file, please upload that

**Comment by akulsaju** [comment]
image
its there

**Review by blazecoding2009 — COMMENTED** [review]
Please remove the capitals from your file names, other than that, everything looks good!

**Review by blazecoding2009 — APPROVED** [review]

**Review by LimesKey — APPROVED** [review]

**Pull request merged**
