### PR TITLE
PCB Hacker Card for Sayhan Rahman

### PR DESCRIPTION
**Pull request by sayhan1610**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/sayhan_rahman:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by jacquelinelita** [comment]
From Despair to Relief: My Incredible Recovery Journey with Hack Savvy Tech

mail: [contactus@hacksavvytechnology.com](mailto:contactus@hacksavvytechnology.com)
Website: https://hacksavvytechrecovery.com/
Whatsapp : +79998295038

Like many, I was drawn to the potential of Bitcoin as a lucrative investment. With excitement and high hopes for my financial future, I invested $52,000 in Bitcoin. The prospects seemed endless, and for a while, everything appeared to be on track. I watched as my investment grew, and I felt secure in the belief that this decision would pay off handsomely in the long run. But then, disaster struck. A security breach, a misplaced transfer, and an unexpected technical failure led to the loss of my entire Bitcoin investment. I was devastated. In an instant, the $52,000 I had worked so hard to accumulate was gone. I was paralyzed by shock and regret. What felt like a promising venture had turned into a nightmare. The weight of the loss was crushing, and I couldn’t fathom how I would recover from it. For weeks, I was in a state of disbelief. I tried contacting various recovery services, but each attempt ended in disappointment or frustration. It seemed like no one could help, and my hope for recovering my investment began to dwindle. The thought that I would never see my $52,000 again was overwhelming, and I was left wondering if my financial future was lost forever. I came onto HACK SAVVY TECH at that point. I was dubious at first. I've been disappointed previously, and scammers abound in the cryptocurrency recovery industry. But after learning about HACK SAVVY TECH track record and reading good reviews, I made the decision to give them a try. They appeared to be my final hope, and I had nothing left to lose. The road to recovery was not easy, and there were times when I felt anxious about the outcome. However, HACK SAVVY TECH team was always responsive and diligent. They applied their deep knowledge of blockchain and cryptocurrency recovery strategies, and I could see that they were determined to help me every step of the way. Then, after what seemed like an eternity of waiting, I received the news I had been praying for: my $52,000 in Bitcoin had been successfully recovered. The relief I felt was indescribable. What seemed like an impossible situation had been turned around, and thanks to HACK SAVVY TECH, I had my investment back. This was a truly transforming event. I moved from a state of hopelessness and financial ruin to one of recuperation. In addition to returning my $52,000, HACK SAVVY TECH helped me regain faith in the cryptocurrency industry. Their passion, professionalism, and knowledge were genuinely transformative. They turned my disaster into a success story, and I am forever grateful for their role in restoring my investment. Thanks to them, I now feel empowered to continue my journey in the world of cryptocurrency without the constant fear of loss."My sincere gratitude.

**Comment by WolfGamer2** [comment]
I love this! Looks so cool!

**Comment by WolfGamer2** [comment]
Hi [sayhan1610](https://github.com/sayhan1610)!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/bpIp43). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the [#electronics](https://slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/) once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
