### PR TITLE
add "nfc business tag" board

### PR DESCRIPTION
**Pull request by Shreyanshdiwakar**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by karmanyaahm** [comment]
Hey @Shreyanshdiwakar sorry your PR got lost in the queue for so long, can you please share what cart settings you used? 

Your PCB should be around $2, not $33
image
Your PCBA at $16 is correct.

**Comment by Shreyanshdiwakar** [comment]
> Hey @Shreyanshdiwakar sorry your PR got lost in the queue for so long, can you please share what cart settings you used?
> 
> Your PCB should be around $2, not $33 image Your PCBA at $16 is correct.

I think I chose this option that might have increased the price, let me know if I need to make any changes. 
image

**Comment by karmanyaahm** [comment]
@Shreyanshdiwakar can you send me screenshots of the full page please? I need the PCB section before the PCB Assembly section.

Also, your PCBA type should be economic not standard.

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/nfc business tag:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/cdc9f8f54d23d02a307f6a5b65c78c3129d8c102/projects/nfc business tag/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/cdc9f8f54d23d02a307f6a5b65c78c3129d8c102/projects/nfc business tag/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/cdc9f8f54d23d02a307f6a5b65c78c3129d8c102/projects/nfc business tag/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Other than that your circuit design looks perfect!

**Comment by karmanyaahm** [comment]
Hey @Shreyanshdiwakar once you make the fixes above, feel free to let me know. For now, I'm closing this for cleanup

**Pull request closed without merging**
