### PR TITLE
My Hacker Card

### PR DESCRIPTION
**Pull request by AverseABFun**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 21606(FTC)
For FIRST, this isn't for my team, but I am in a team.

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by sarthaktexas** [comment]
Hi @AverseABFun! So excited to have you participating in OnBoard! The next step will be to get an engineers approval and then we'll merge your pr and get you your grant. :) Everything looks good for student verification @hackclub/boarding-party!

**Comment by AverseABFun** [comment]
So I filled out the HCB form thing, do I just wait now?

**Comment by sarthaktexas** [comment]
yup! they'll get to your PR when they have time later today and once they approve it, I'll get notified and I'll send your grant to your email :)

**Comment by AverseABFun** [comment]
Sounds good!

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi @AverseABFun! Hi! You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this.

Additionally, please make a "src" folder in projects/saranPCBBoard/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

**Comment by AverseABFun** [comment]
Sorry, can't do that right now as I'm going to my Grandma's for
Thanksgiving. When I get home tomorrow I will. Thanks for giving this info!

**Comment by AverseABFun** [comment]
> Hi @AverseABFun! Hi! You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this.
> 
> Additionally, please make a "src" folder in projects/Arthur's Hacker Card/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

I would fix it, but my computer is acting up AND WITH ANY BROWSER THE BROWSER CRASHES AFTER I PRESS "ADD TO CART" and thus I CAN NOT MAKE THE FIRST PART OF CHANGES. I did add the jsons though.

**Comment by karmanyaahm** [comment]
@AverseABFun Can you send me a screenshot/video in Slack of what happens, I'd love to help you solve it? I'm @Karmanyaah there. Without doing the first part, your board won't work at all, so there would be no point in ordering it.

**Comment by AverseABFun** [comment]
> @AverseABFun Can you send me a screenshot/video in Slack of what happens, I'd love to help you solve it? I'm @Karmanyaah there. Without doing the first part, your board won't work at all, so there would be no point in ordering it.

Yeah I know, and I will once I get home from school and finish homework at ~4:00. Sorry for the wait.

**Comment by AverseABFun** [comment]
> Hi @AverseABFun! Hi! You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this.
> 
> Additionally, please make a "src" folder in projects/Arthur's Hacker Card/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

Alright, I used a different computer and it worked. But for some reason now it will cost $46.32? At any rate I changed the screenshot and I made all the changes you wanted.

**Comment by karmanyaahm** [comment]
Sorry @AverseABFun, you need to select "Economic", not "Standard assembly" from JLCPCB. Economic saves a lot of money and is enough for the Hacker Card. Please click the same buttons specified in https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-assembly .

If you need help setting this up, please message me on Slack and send screenshots or hop in a call - your board is good, it's just the ordering settings - I really want you to be able to make this PCB!

**Comment by AverseABFun** [comment]
Alright. I think it is finally good and the final total is $20.31. Thank you @karmanyaahm .

**Comment by AverseABFun** [comment]
Ok dang it hold on

**Review by karmanyaahm — APPROVED** [review]
lgtm!

**Comment by karmanyaahm** [comment]
Just realizing @sarthaktexas you didn't mark the PR as approved on GitHub, so cannot merge. cc @daisybanks, not sure if you're back yet?

Regardless, @AverseABFun you should get an email with your HCB card in ~24 hours when they approve and merge it. Then you can order your board from JLCPCB!

**Comment by karmanyaahm** [comment]
You can click on the various shipping options and see which one's the cheapest. Get the cheapest one so you have more money saved for future PCBs.

**Comment by AverseABFun** [comment]
> You can click on the various shipping options and see which one's the cheapest. Get the cheapest one so you have more money saved for future PCBs.

Alright

**Comment by AverseABFun** [comment]
Looks like GSDL

**Comment by AverseABFun** [comment]
Also while working on getting this one printed ive been working on designing my own custom arduino uno-compatible board and im around half done(just need to layout the PCB, i already did the schematic) although its prob gonna be a while until i have it done enough to print

**Comment by AverseABFun** [comment]
also with a discount and other stuff it will actually cost $29.32

**Comment by AverseABFun** [comment]
Oh, and I'm looking on the HCB page, and should I change the billing address to my address?

**Comment by AverseABFun** [comment]
> > looking on the HCB page
> > Which HCB page were you looking at when trying to change the address?

like the settings page with the address thing
i don't need help, im just waiting to be able to order it

**Comment by karmanyaahm** [comment]
Sorry for the delay, I've pinged them on slack

**Comment by maxwofford** [comment]
@AverseABFun sorry for the delays here! It's 24 hours once the student ID is reviewed. I know you submitted yours so this isn't on you, but it'll be just a little bit longer.

@sarthaktexas what's the situation here on the ID review?

**Comment by maxwofford** [comment]
Merging now– you should get an email about your card arriving shortly. Hope ordering goes well. Oh, and I'd love to see the uno board you end up making once it's done!

**Comment by maxwofford** [comment]
Grant sent! https://hcb.hackclub.com/hcb/MNHJdLV

**Comment by AverseABFun** [comment]
Thanks!

**Pull request merged**
