### PR TITLE
Ari's Gadget Geocache PCB

### PR DESCRIPTION
**Pull request by AriM224**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Love the idea!! Two small things, just like you uploaded a PCB_PCB....json file, can you File > Export > EasyEDA a file from the schematic tab as well and put it in src?

Also, you schematic.pdf needs to be exported from the schematic tab (the one with the circuit symbols, not PCB).

Really looking forward to your board. Also DMing you on Slack about some other details.

**Comment by AriM224** [comment]
I deleted the PCB json and PCB schematic. I added the actual schematic pdf and json like you requested.

**Comment by Hugoyhu** [comment]
Hi @AriM224 could you please actually re-attach the PCB json? I think there was a bit of miscommunication- needed the PDF + json schematics in addition to everything you had. 

This is so that I can quickly take a look over both schematic and your pcb routing to try and catch any mistakes. Thank you!

**Comment by AriM224** [comment]
Oh sorry, I didn't understand that both are needed.

**Comment by AriM224** [comment]
Ok, everything should be there now. As you might notice, the schematic is different than the PCB because I designed most of it in the PCB editor. karmanyaahm said it was fine as long as I had the schematic uploaded.

**Comment by Hugoyhu** [comment]
Hi! Thanks for the prompt reply. I don't see any problems with the PCB, so as long as your "in-pcb editor design" was correct, it should be OK. In the future I'd definitely recommend going through schematic just for ease of checking/routing. 

Want to note one thing that might be an issue: 
Screen Shot 2024-01-20 at 9 03 26 PM
On C1/2, R1-3 you have a via on one of the pads. I'd recommend rerouting it so that the vias are not on the SMD pad. You can route the via out until it clears the pad and then you can add the via. 

https://electronics.stackexchange.com/questions/39287/vias-directly-on-smd-pads

**Comment by AriM224** [comment]
I was wondering if it was ok to put vias on a pad. I guess I should have looked it up. I just fixed that, should I replace the files in this project with the updated board? thanks for the help

**Comment by Hugoyhu** [comment]
Yes please. Just update the new PCB file and that should be great: ping me over slack ***@***.*** Hu) or reply to the thread when that’s done and I’ll take a quick look to make sure everything is OK!

On Jan 20, 2024, at 9:24 PM, Ari Mastor ***@***.******@***.***>> wrote:



I was wondering if it was ok to put vias on a pad. I guess I should have looked it up. I just fixed that, should I replace the files in this project with the updated board? thanks for the help

**Comment by AriM224** [comment]
I updated all PCB-related files just to make sure.

**Review by Hugoyhu — APPROVED** [review]
This looks OK to me. I'd be wary about the placement of R11 in case it's too close to the holes on the sides. If you're getting something assembled by the fab then I'd consider moving it just to add some clearance. 

I might just suggest moving it either way just so you don't need to worry about it being too close and accidentally causing a short but this depends on your application. 

If you do want to move it + want a re-check, feel free to update your files again and re-request review from me so I know.

**Comment by AriM224** [comment]
I moved R11 to a better place, definitely wouldn't want a short circuit there.

**Review by Hugoyhu — APPROVED** [review]
Looks OK to me and ready to approve when everything else is good.

**Review by sarthaktexas — APPROVED** [review]
Howdy Ari! I'm approving your student verification :) Just waiting on @karmanyaahm's review and I'll send your grant.

**Comment by AriM224** [comment]
sounds good, thanks!

**Comment by Hugoyhu** [comment]
@karmanyaahm everything looks good and files have been fixed. OK to approve? Thank you and good night!

**Review by karmanyaahm — APPROVED** [review]
lgtm

**Comment by sarthaktexas** [comment]
sent!

**Pull request merged**
