### PR TITLE
USB C Power Distribution Board

### PR DESCRIPTION
**Pull request by Babyyoda777**
## Submission Checklist:

- [ yes] I am a current high school, middle school, or home schooled student.
  - [ yes] I am 18 or under
  - [ yes] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ yes] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ yes] I made this board from scratch, even if I followed a tutorial
- [ yes] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [yes ] Created a folder under `onboard/projects`
  - [ yes] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ yes] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ yes] Created a folder called `src` and uploaded design files
  - [ yes] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ yes] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ yes] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/EPQ-Power-Distribution-Board:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by LimesKey** [comment]
Hey @Babyyoda777, I see you've already got your 100$ grant, so what's this pull request for?

**Comment by Babyyoda777** [comment]
Hi,this is another board I was working on for a school project, I was wondering if (as a group project) whether OnBoard would cover it as a separate grant (although I understand that's unlikely)? Unfortunately my previous grant was basically unused because the courier lost my order and I didn't have enough left to reorder.

**Comment by LimesKey** [comment]
Unfortunately, it's a hard limit of 100$ per person, but perhaps if you could get a friend to further design this board with you, and then have the friend submit it, that could be a way to get the board ordered. I'd look more into talking with the courier and seeing if the courier could offer a reimbursement or has shipping insurance, but that's just me.

**Comment by second2falcon** [comment]
> Unfortunately, it's a hard limit of 100$ per person, but perhaps if you could get a friend to further design this board with you, and then have the friend submit it, that could be a way to get the board ordered. I'd look more into talking with the courier and seeing if the courier could offer a reimbursement or has shipping insurance, but that's just me.

@LimesKey but you are completely right. Oftentimes couriers have shipping insurance (I know a standard DHL Parcel in Europe is insured for up to 500€). 

Otherwise @Babyyoda777 could try contacting JLCPCB (if I saw it right, otherwise the PCB manufacturer where you ordered) and try with them as they effectively have a contract with the courier where the courier didn't fulfill their part of the contract (delivering the package).

**Pull request closed without merging**
