### PR TITLE
JPL.mp3v2

### PR DESCRIPTION
**Pull request by JPLabsystems**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [X] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 5804

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/JPL.mp3v2:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/1897aee3b03c19c72cd2b426828c85a5dfdaf790/projects/JPL.mp3v2/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/1897aee3b03c19c72cd2b426828c85a5dfdaf790/projects/JPL.mp3v2/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/1897aee3b03c19c72cd2b426828c85a5dfdaf790/projects/JPL.mp3v2/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @JPLabsystems,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of your cart rather than the completed unpaid order.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to the [JLCPCB Order page](https://jlcpcb.com/user-center/orders/), then take a rectangular screenshot of the PCB you just submitted. It should show all the details of your order including the price and assembly.

This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congratulations on making the PCB! Please ask in [#electronics](https://slack.com/archives/C056AMWSFKJ) in the [Slack](https://hackclub.com/slack/) if you need any further help.

**Comment by JPLabsystems** [comment]
Gotcha! Thanks!

**Comment by LimesKey** [comment]
Looks good, just confirming you'll be assembling this PCB yourself?

**Comment by JPLabsystems** [comment]
I will indeed be assembling the board myself!

**Review by LimesKey — CHANGES_REQUESTED** [review]
Can you add your `.WRL` VRML file and not a .STEP?

**Comment by JPLabsystems** [comment]
Gotcha!

**Comment by LimesKey** [comment]
I see you've submitted the older verification form and not the new one, did you have trouble with the new one? Are you able to fill out the new one [here](https://verify.onboard.hackclub.com/)?

**Comment by JPLabsystems** [comment]
@LimesKey 
image
I had an issue verifying with the new way, so I used the older way instead. As far as I am aware, it said that that is OK?
Justinas

**Comment by JPLabsystems** [comment]
Hi, given that I needed to order this PCB by a deadline, and the cost outlay isn't too large, I'll be closing this PR and paying for it myself. 
Thanks, Justinas.

**Comment by LimesKey** [comment]
Best of luck! We might be able to reimburse you for the cost later on if you open up a new pull request. Also, it's saying that because you need to go through the Slack workflow in order to gain access to the full slack, through High Seas, https://highseas.hackclub.com/.

**Pull request closed without merging**
