### PR TITLE
Re-order :(

### PR DESCRIPTION
**Pull request by therealfiish**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 226

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/8a71247c7fdd4112036eda68af4122c07ff9e82a/projects/Krrish's Simple Card/Gerbers.zip>)!

  Happy OnBoarding!

**Comment by maxwofford** [comment]
Hey @therealfiish, I remember you also submitted https://github.com/hackclub/OnBoard/pull/315. Did it not work?

**Comment by maxwofford** [comment]
It looks like your routing is a little funny still. Not sure if intentional, but you can really reduce your traces by bringing your NFC IC up closer to your other components.
Screenshot 2024-03-04 at 11 02 55

**Comment by therealfiish** [comment]
I wanted to keep my NFC + LED on the right, like how a credit card has a chip on the right.

**Comment by maxwofford** [comment]
You're free to try it, let's see if it works!

**Pull request merged**
