### PR TITLE
Alexander's PCB NFC Business Card

### PR DESCRIPTION
**Pull request by Suave101**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [ ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 23765 & 9787

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/0451967df9b536601f16f5a1beb3744082579f38/projects/AlexandersBuisinessCard/Gerber_PCB_Business Card_2024-01-24.zip>)!

  Happy OnBoarding!

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi @Suave101! Your design looks mostly good to me, except can you export your schematic tab as a PDF (in the schematic tab go to [File > Export > PDF](https://docs.easyeda.com/en/Export/Export-Schematic/index.html)), and upload that.

**Review by Hugoyhu — CHANGES_REQUESTED** [review]
Hey! Routing looks good but have some problems here: 

Screenshot 2024-02-03 at 11 01 57 AM

Not 100% sure if this is meant to look the way you want it to? You have your bullet points for your contacts on the bottom silk layer, and have some only on the solder mask layer. 

Screenshot 2024-02-03 at 11 03 17 AM
Screenshot 2024-02-03 at 11 03 13 AM

As another note, those yellow parts you see won't actually turn out and look nice in person. It will look like a plain substrate layer and may look a bit ugly. 

I'd suggest turning these to silkscreen and making sure they're on the correct layer.

**Comment by maxwofford** [comment]
Hey, haven't heard anything on this thread for a while so I'm going to close the PR so it's not in our actively monitored list. You can still totally reopen it by just commenting here or pushing those file changes.

**Pull request closed without merging**
