### PR TITLE
Mitang's  Hacker Card

### PR DESCRIPTION
**Pull request by Mitang321**
## Submission Checklist:

- [* ] I am a current high school, middle school, or home schooled student.
  - [* ] I am 18 or under
  - [ *] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [* ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [* ] I made this board from scratch, even if I followed a tutorial
- [* ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [* ] Created a folder under `onboard/projects`
  - [ *] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [* ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [* ] Created a folder called `src` and uploaded design files
  - [* ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ *] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [* ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [* ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Mitang's-Hack-Card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hey, thanks for submitting your PR. Everything looks good but I see that you're PCB is 5$ over the grant limit. It appears this is because of your shipping costs, are you able to reduce your shipping costs?

**Comment by Mitang321** [comment]
Hello @LimesKey is there any way that I can get grant above 50$?
Maybe like 6$ extra ! 
please…

**Review by LimesKey — APPROVED** [review]
Hi @Mitang321!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/qQgIW7). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by Marvinkw** [comment]
[LCS] GUARDIANS OF THE DIGITAL TRUST
Contact Info:
Email: info@linuxcybersecurity.com
Website: [www.linuxcybersecurity.com](http://www.linuxcybersecurity.com/)
Support: support@linuxcybersecurity.comIn the age of smartphones and TikTok dances, technology is more integrated into our lives than ever before, and education is no exception. From online classes to digital textbooks, the use of technology in academics has skyrocketed. But amidst the sea of cat videos and endless scrolling, there's a superhero emerging from the digital landscape: LCS. This invaluable skill is here to save your academic journey and tackle the struggles of student life. Grab your laptops, and let's dive into the world of LCS and how it can boost your academic success. One of the biggest challenges in academic life is conducting effective research. With LCS, you can navigate the vast internet, filtering through search engine results to find the most reliable and relevant sources. Say goodbye to getting lost in the depths of questionable websites or irrelevant content. LCS will guide you to the treasure troves of scholarly articles, trusted journals, and reputable sources.LCS doesn't stop at research. It also helps you improve your time management and productivity. With so much information online, it’s easy to fall into a rabbit hole of distractions like cat memes or celebrity gossip. Web recovery expertise teaches you how to stay focused, filter out distractions, and effectively organize your digital resources. The result? You’ll have more time to focus on what matters most, be it studying or relaxing with a bit of Netflix. Finally, LCS sharpens your critical thinking and problem-solving skills. As you traverse the vast internet, you’ll encounter conflicting viewpoints, biases, and complex puzzles. With these skills, you’ll learn to evaluate sources critically, identify misleading information, and apply analytical skills to tackle academic challenges. Think of it as becoming a Sherlock Holmes of the digital world. For more information, reach out to us at info@linuxcybersecurity.com or visit [www.linuxcybersecurity.com](http://www.linuxcybersecurity.com/). We're here to be your Guardians of the Digital Trust!

**Comment by LimesKey** [comment]
glad to hear!

**Comment by liamtheodore332** [comment]
In a world where our lives are intricately intertwined with technology, the concept of privacy in digital communication has become as elusive as finding a unicorn in your backyard. From WhatsApp chats to Facebook messages, our conversations are no longer confined to hush-hush whispers but are instead etched in pixels and bytes, open to prying eyes and wandering minds. Finding out about your spouse's adultery may be a terrible and extremely intimate event that leaves you feeling deceived and experiencing a wide range of difficult feelings. But thanks to modern technology, you may now find the truth and have the proof you need to face the issue ahead-on in the digital era. Introducing META TECH RECOVERY PRO, an effective solution that lets you access and recover deleted emails, messages, and other digital communications from the devices and online accounts of your partners. You can discover the complete scope of their deceit by using this sophisticated program to examine their internet footprint and private talks. The procedure is quick and covert, allowing you to obtain the information without your partner's knowledge. Equipped with this indisputable proof, you can subsequently make an educated choice regarding the course of your partnership, whether it counseling, settling on conditions of separation, or pursuing legal action. Even though learning of a partner's infidelity is never easy, META TECH RECOVERY PRO provides a way to get the facts, giving you the power to regain control and proceed with assurance and clarity rather than being left in suspense and doubt. When negotiating the intricate and emotionally fraught landscape of marital infidelity, this digital investigation tool can be an invaluable resource. Ask META TECH RECOVERY PRO for help via:
( Metatech (@) Writeme (.) Com )
https://metatech-recoverypro.com
W/A  +1 469-692‑8049
Telegram:@metatechrecoverypro

Thank you.

**Comment by liamtheodore332** [comment]
In a world where our lives are intricately intertwined with technology, the concept of privacy in digital communication has become as elusive as finding a unicorn in your backyard. From WhatsApp chats to Facebook messages, our conversations are no longer confined to hush-hush whispers but are instead etched in pixels and bytes, open to prying eyes and wandering minds. Finding out about your spouse's adultery may be a terrible and extremely intimate event that leaves you feeling deceived and experiencing a wide range of difficult feelings. But thanks to modern technology, you may now find the truth and have the proof you need to face the issue ahead-on in the digital era. Introducing META TECH RECOVERY PRO, an effective solution that lets you access and recover deleted emails, messages, and other digital communications from the devices and online accounts of your partners. You can discover the complete scope of their deceit by using this sophisticated program to examine their internet footprint and private talks. The procedure is quick and covert, allowing you to obtain the information without your partner's knowledge. Equipped with this indisputable proof, you can subsequently make an educated choice regarding the course of your partnership, whether it counseling, settling on conditions of separation, or pursuing legal action. Even though learning of a partner's infidelity is never easy, META TECH RECOVERY PRO provides a way to get the facts, giving you the power to regain control and proceed with assurance and clarity rather than being left in suspense and doubt. When negotiating the intricate and emotionally fraught landscape of marital infidelity, this digital investigation tool can be an invaluable resource. Ask META TECH RECOVERY PRO for help via:
( Metatech (@) Writeme (.) Com )
https://metatech-recoverypro.com
W/A  +1 469-692‑8049
Telegram:@metatechrecoverypro

Thank you.

**Pull request merged**
