### PR TITLE
RP2040-Zero Macropad

### PR DESCRIPTION
**Pull request by KoKoOogit**
## Submission Checklist:

- [ x] I am a current high school, middle school, or home schooled student.
  - [ x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ x] I made this board from scratch, even if I followed a tutorial
- [ x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x ] Created a folder under `onboard/projects`
  - [x ] Filled out `TEMPLATE.md` as `README.md`
  - [ x] Uploaded Gerber.zip and Schematic.pdf
  - [ x] Created a folder called `src` and uploaded design files
  - [ x] Uploaded screenshot of PCB order with all costs included
  - [ x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by KoKoOogit** [comment]
This is a new pull request but it looks like it combine from my previous pull request ATMega32u4-Macropad.

**Comment by karmanyaahm** [comment]
Hey! I'm deleting the second gerber.zip as it looks like the bot can't handle two gerbers yet. I need to handle that case better.

**Comment by karmanyaahm** [comment]
Can you please post a better picture of your cart? Not just the price. Thanks

**Comment by KoKoOogit** [comment]
Sure! I just make a new commit and updated the cart with more details.

**Comment by karmanyaahm** [comment]
Emailing grant now. Please send pictures in #onboard on slack when you get your PCBs! Very excited to see how they turn out!

**Comment by KoKoOogit** [comment]
Sure! I just received the grants.

**Pull request merged**
