### PR TITLE
Thunder_Ceiling

### PR DESCRIPTION
**Pull request by Shortcircuit-163**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/36dee02acf05d473b73d6a29211d3e23ba6ae7ef/projects/Thunder_Ceiling/Gerber_leds_PCB_leds_2024-02-19.zip>)!

  Happy OnBoarding!

**Review by maxwofford — CHANGES_REQUESTED** [review]
Wow! I didn't think you could get so many LED boards for so cheap! I can't wait to see what this looks like fabricated. I don't see a year on your student verification so I don't know if that is up-to-date. Could you DM me in slack (my username is `msw`) and we can figure out something else for verification?

**Review by maxwofford — APPROVED** [review]
Great, thanks for messaging me! Excited to see this thing light up when you get it

**Comment by maxwofford** [comment]
Your grant was [just sent](https://hcb.hackclub.com/grants/v6lIk3)

**Comment by Shortcircuit-163** [comment]
> Your grant was [just sent](https://hcb.hackclub.com/grants/v6lIk3)

Thank you!!!

**Pull request merged**
