### PR TITLE
Add Sahiti's Hacker Card

### PR DESCRIPTION
**Pull request by sahitid**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/sahitid-hacker-card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by abitchinmorewaysthanone — CHANGES_REQUESTED** [review]
Hi Sahiti,

Please fill out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form) so we know how to contact you.

Also, it's very important that your files are all named correctly (including file types - for example, cart.png HAS to be a .png) and in the correct place. Please review [this section of the tutorial](https://github.com/hackclub/OnBoard?tab=readme-ov-file#5-add-your-design-to-your-project-repo) or look at some of the [merged projects](https://github.com/hackclub/OnBoard/tree/main/projects) to learn how to structure your pull request.

I will send your grant after these steps are complete!

**Comment by abitchinmorewaysthanone** [comment]
Thanks! I recieved your form but your PR still has some issues. I've PMed you on Slack about it. thanks!

**Comment by sahitid** [comment]
I don't think I received the DM on slack! My username is @sahiti :)

Best,
Sahiti
________________________________

**Comment by abitchinmorewaysthanone** [comment]
That's weird, that handle looks correct. Perhaps we should keep the conversation here then.

**Comment by sahitid** [comment]
I can send you a DM to your handle if you would like!Best,SahitiOn Jun 9, 2024, at 10:02 PM, tori ***@***.***> wrote:﻿
That's weird, that handle looks correct. Perhaps we should keep the conversation here then.

**Comment by abitchinmorewaysthanone** [comment]
ok cool! probably just search “tori” in #electronics my tag is different

Le lun. 10 juin 2024 à 10:09 AM, Sahiti Dasari ***@***.***> a
écrit :

**Review by abitchinmorewaysthanone — APPROVED** [review]

**Pull request merged**
