### PR TITLE
USB hub

### PR DESCRIPTION
**Pull request by olivermets**
## Submission Checklist:

- [+] I am a current high school, middle school, or home schooled student.
  - [ +] I am 18 or under
  - [ +] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [+ ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [+ ] I made this board from scratch, even if I followed a tutorial
- [ +] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [+ ] Created a folder under `onboard/projects`
  - [+ ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [+ ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [+ ] Created a folder called `src` and uploaded design files
  - [+ ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [+ ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [+ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/USB hub:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ba14b9c20d782000962aabc923d56e2993a06318/projects/USB hub/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ba14b9c20d782000962aabc923d56e2993a06318/projects/USB hub/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/ba14b9c20d782000962aabc923d56e2993a06318/projects/USB hub/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by olivermets** [comment]
I can get it under 50 dollars using a coupon.

**Comment by blazecoding2009** [comment]
Hey @olivermets 

You might want to add a resistor in there so that the LED doesn't blow up
image

**Comment by blazecoding2009** [comment]
Also please do your verification form

**Comment by olivermets** [comment]
> Hey @olivermets
> 
> You might want to add a resistor in there so that the LED doesn't blow up image

It is a DIODE

**Comment by olivermets** [comment]
> Also please do your verification form

@blazecoding2009 I just did it.

**Comment by blazecoding2009** [comment]
Just sent your [grant](https://hcb.hackclub.com/grants/qlYImV)!

**Review by blazecoding2009 — APPROVED** [review]

**Pull request merged**
