### PR TITLE
SidakHackerCard

### PR DESCRIPTION
**Pull request by Sidak08**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/SidakHackerCard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/cc9b3fd03fc48a458bab0a883c6f085b5311b7a8/projects/SidakHackerCard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/cc9b3fd03fc48a458bab0a883c6f085b5311b7a8/projects/SidakHackerCard/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/cc9b3fd03fc48a458bab0a883c6f085b5311b7a8/projects/SidakHackerCard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by torbers — CHANGES_REQUESTED** [review]
Hi Sidak,
It looks like you haven't filled out the checklist (the first comment in this PR) or the verification form. We need this information to send you the grant!
Everything else looks good.
Thanks,
tori

**Comment by Sidak08** [comment]
Hi @torbers,

Sorry for any inconvenience I have read the checklist and followed the instruction. I filled it out again just in case. Not sure if I have to make another pr. If so please tell me. Secondly I am verified on hack club. I have the confirmation email on my email address (SidakSingh318@gmail.com). 
Screen Shot 2024-06-25 at 1 11 33 PM
Screen Shot 2024-06-25 at 1 13 59 PM

**Review by torbers — CHANGES_REQUESTED** [review]
Sidak,
You still need to fill out the verification form at this link: https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form
We need to know your address and some other data before we can send the grant.
Thanks!
Tori

**Comment by Sidak08** [comment]
Hi I just filled out the form :) 
Screen Shot 2024-06-26 at 1 15 33 PM

**Review by torbers — APPROVED** [review]

**Comment by torbers** [comment]
I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/qKbI3R). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
