### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by AnthonyTran061004**
## Submission Checklist:

- [YES] I am a current high school, middle school, or home schooled student.
  - [ YES] I am 18 or under
  - [ YES] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [YES ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [YES] I made this board from scratch, even if I followed a tutorial
- [YES ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ YES] Created a folder under `onboard/projects`
  - [YES ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [YES ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ YES] Created a folder called `src` and uploaded design files
  - [YES ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [YES ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ YES] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [YES ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by abitchinmorewaysthanone — CHANGES_REQUESTED** [review]
Hi Anthony!
Your files are organized incorrectly. Please delete the folder /projects/Business_Card/, it seems like it's redundant. Also, rename schematic.pdf.pdf to just schematic.pdf. Thanks!

**Comment by AnthonyTran061004** [comment]
Thank you for your email, I will do that right now!

**Comment by abitchinmorewaysthanone** [comment]
Ok, looks alright, but `Gerber_Business-Card_PCB_Business-Card_2024-06-13.zip` Should be renamed to just gerber.zip, and your schematic and cart files should be named all lowercase. I can’t see your board until you make these changes!

**Comment by AnthonyTran061004** [comment]
Sorry about that, I’m a bit new to GitHub and I’m not at home right now but
I will fix those mistakes when I get home.

**Comment by abitchinmorewaysthanone** [comment]
Ok, if you're still interested, can you rename "Cart.png" to "cart.png" (all lowercase) and rename your gerber file to simply "gerber.zip"? Github is really confusing, I know. And our bot isn't very smart lol. If you need any more help please ask in [Slack](https://hackclub.com/slack/?event=onboard).

**Comment by AnthonyTran061004** [comment]
Sorry about that, I completely forgot to make the changes but I just did.
Thank you for your patience and understanding.

**Comment by torbers** [comment]
Looks great. 
I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/q57INN). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Review by torbers — APPROVED** [review]

**Comment by AnthonyTran061004** [comment]
Question, where do I upload the receipts?

**Pull request merged**
