### PR TITLE
Charlie's Projects

### PR DESCRIPTION
**Pull request by crnicholson**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/2ff56174f7dc7b23eaefa447a0fe17dde5ff0f84/projects/Charlie's Projects/GERBERS_DRAFT1.zip>)!

  Happy OnBoarding!

**Review by sarthaktexas — APPROVED** [review]
student verification approved!

**Review by maxwofford — APPROVED** [review]
This is approved from an engineering side! @crnicholson I might move some files around so we can store all this in a folder similar to the other projects, but I know this has 8 different projects so it's a little harder to format here.

**Comment by maxwofford** [comment]
@sarthaktexas go ahead and give the grant!

**Pull request merged**
