### PR TITLE
I got the grant - Files still unmerged

### PR DESCRIPTION
**Pull request by DefinetlyNotAI**
I already got the grant, but i dont know why the pr didnt get accepted?

Can you just merge this - No grant needed

### CODE REVIEW

**Comment by LimesKey** [comment]
Do you mean this PR https://github.com/hackclub/OnBoard/pull/993 ? It was merged

**Comment by DefinetlyNotAI** [comment]
Hmm, this is 19 commits vs the 17 commits...

Not sure tho

**Comment by DefinetlyNotAI** [comment]
GitGuardian says the npmrc file has a vuln, this was given to me when i updated this branch

image

**Comment by blazecoding2009** [comment]
I can see commits were made but these were already merged. No files were changed afterwards. I'll be closing this now.

**Comment by DefinetlyNotAI** [comment]
Thx

**Pull request closed without merging**
