### PR TITLE
Briyan's Project - DIY NFC card

### PR DESCRIPTION
**Pull request by briyandyju09**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
- [X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md`
  - [X] Uploaded Gerber and design files
  - [X] Uploaded screen shot of PCB passing JLCPCB inspection

### CODE REVIEW

**Comment by bykevinyang** [comment]
Hey @briyandyju09!

So great to see you're submission! While we review your design, can you fill out this airtable [form](https://airtable.com/shrbcDANe6ug6gj0p)? This is so we can verify your student status.

See you in a bit!

**Review by daisybanks — COMMENTED** [review]
Hi @briyandyju09! Welcome to OnBoard - we're so excited to have you! Everything looks good on Bank's end @bykevinyang. :)

**Comment by briyandyju09** [comment]
Nice!

**Comment by bykevinyang** [comment]
Congrats! You're project has just been merged!

Your next step is to claim your grant! In 24 hours, you should be receiving an email from Hack Club Bank on joining the OnBoard bank platform. Make sure to check spam!

If you have any questions, feel free to reach out in [#onboard-help](https://hackclub.slack.com/archives/C0593MG26TT) or to contact [@daisybanks](https://github.com/daisybanks) from bank ([@Daisy](https://hackclub.slack.com/team/U046V3EK56W) on Slack).
 
Now, you can finally get those PCBs ordered!:tada:

P.S. If you haven't already, join the [#onboard](https://hackclub.slack.com/archives/C056AMWSFKJ) channel. There's a party brewing!

**Pull request merged**
