### PR TITLE
Add "businesscardformom" board

### PR DESCRIPTION
**Pull request by michellemeng06**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/businesscardformom:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/976643f7cbceb14c5cd86a231bca5b7e44bae003/projects/businesscardformom/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/976643f7cbceb14c5cd86a231bca5b7e44bae003/projects/businesscardformom/schematic.pdf>) |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/976643f7cbceb14c5cd86a231bca5b7e44bae003/projects/businesscardformom/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by michellemeng06** [comment]
Hi, I fixed it!
cart

**Comment by michellemeng06** [comment]
Hi, not sure what you mean by "No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB." I thought i uploaded those two already?? Please let me know. Thank you so much!
--


</markdown-accessiblity-table><br class="Apple-interchange-newline">
[pcb.json](https://github.com/user-attachments/files/16860302/pcb.json)
[schematic.json](https://github.com/user-attachments/files/16860303/schematic.json)

**Comment by michellemeng06** [comment]
How do you edit files?

**Comment by blazecoding2009** [comment]
> Hi, I fixed it! cart

Please put this as your cart.png

**Comment by blazecoding2009** [comment]
> How do you edit files?

If you need to change an image or schematic, delete the file then reuplaod

**Comment by michellemeng06** [comment]
Hi, do you see the new files added?

**Comment by blazecoding2009** [comment]
Please put your schematic.json and pcb.json into the src folder

**Comment by michellemeng06** [comment]
IMG_5331

I have done it already, did I do it wrong? I’m confused.

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
your SRC folder is not inside your project folder. please move it into your project folder. same wtih your new cart.png

**Comment by michellemeng06** [comment]
It seems I am unable to created a folder called src and upload my design files. I tried to do it multiple times and nothing shows up. I hope this can still work though!

**Comment by michellemeng06** [comment]
Screenshot 2024-09-09 at 9 23 19 PM
What do you want me to delete? All of these look right

**Comment by michellemeng06** [comment]
I think someone might have deleted the old cart image already

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
You deleted the wrong schematic.json and pcb.json. please put those in src  by putting `/src` before the name when renaming

**Comment by michellemeng06** [comment]
I can't change any files. Can someone help me?

**Comment by michellemeng06** [comment]
Screenshot 2024-09-09 at 10 18 33 PM

**Comment by blazecoding2009** [comment]
Hey @michellemeng06 
Are you able to provide another form of ID? This can be anything from a driver's license to a passport and anything inbetween.

**Review by blazecoding2009 — APPROVED** [review]
Looks good! Have fun with your [grant](https://hcb.hackclub.com/grants/wM2Ign)!

**Pull request merged**
