### PR TITLE
Aiden'sCompSwitchControllerPCB

### PR DESCRIPTION
**Pull request by PilotOfGolf**
## Submission Checklist:

- [ ] I am a current high school, middle school, or home schooled student.
  - [ ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ ] I made this board from scratch, even if I followed a tutorial
- [ ] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [ ] Created a folder under `onboard/projects`
  - [ ] Filled out `TEMPLATE.md` as `README.md`
  - [ ] Uploaded Gerber, sources, and schematic
  - [ ] Uploaded screenshot of PCB order with all costs included
  - [ ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by PilotOfGolf** [comment]
I was unable to figure out how to join the slack, therefore I was not able to meet that requirement bubble.

**Comment by PilotOfGolf** [comment]
Oh wait - I think I got in. I got an email saying to join. I think this is my handle or whatever it is called. U06CHEJ7P6U

**Comment by PilotOfGolf** [comment]
OH I SEE AN ERROR IN THIS. Sorry for any inconvenience.

**Comment by karmanyaahm** [comment]
Oh wow this is very cool! I did VRC too for the past two years. Feel free to DM me on Slack @Karmanyaah or post in #onboard if you need help with the designs. Also if you're getting stuck in the Slack welcome flow lmk here.

Also I'll reopen this (if you don't mind) because you can just delete old files and add new files to your repo, that will automatically update your pull request once you fix your board.

**Comment by PilotOfGolf** [comment]
Ok, so I tested this on a breadboard and there is not an issue. I just wanted to make sure. I did not change any files, since there are no issues, and this will work as intended. I am so sorry for any inconvenience I may have caused. Thanks!

**Review by sarthaktexas — APPROVED** [review]
Howdy Aiden! I'm approving your student verification :) Once your PR is merged, you'll receive your grant!

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
1. Not entirely sure if it's possible with your parts but please check if you can use "Economic" assembly instead of standard. It's usually like $20 cheaper. See the options select here: https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-assembly
2. Just like you uploaded your src/PCB_PCB.json, we need a Schematic JSON in the src folder which you can get by going to the schematic tab, and then File > Export > EasyEDA. (This is in addition to the schematic PDF you have already uploaded)
3. If you can edit the README with your Slack name, like "@ Aiden" or what it is, that'd be great.

Looking forward to getting you your grant!

**Comment by PilotOfGolf** [comment]
1. Yes, it is, however I needed to change PCB color to green, which is fine, I couldn't care less about the color. 
2. I think I uploaded the right file here. 
3. Done!

**Review by karmanyaahm — APPROVED** [review]
LGTM! Please send a video of your board working when you get it to #onboard on Slack, I'd love to see it working!

**Comment by karmanyaahm** [comment]
You should receive an email with your grant card within 24-48 hours!

**Comment by karmanyaahm** [comment]
ping @sarthaktexas

**Comment by sarthaktexas** [comment]
sent!

**Pull request merged**
