### PR TITLE
USB A/C input to 3 USB-A + 1 USB-C Output

### PR DESCRIPTION
**Pull request by LandonBayer**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [X] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 1757

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/usbactoachub:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/d91fad6a09ac56cf0bfd0b8f0c611edb71232ad3/projects/usbactoachub/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/d91fad6a09ac56cf0bfd0b8f0c611edb71232ad3/projects/usbactoachub/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/d91fad6a09ac56cf0bfd0b8f0c611edb71232ad3/projects/usbactoachub/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @LandonBayer,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by LandonBayer** [comment]
@LimesKey Thanks for letting me know! That should be the accurate picture

**Comment by LimesKey** [comment]
Thanks for doing that, everything looks good but I see your order total is $55.05 but you only have $46.15 left on your grant, are you able to pay for the rest?

**Comment by LandonBayer** [comment]
Yes, I also plan to use a coupon and a promo code so hopefully that brings it down. You can't enter them until checkout with payment info, so I can't show it in the picture unfortunately @LimesKey

**Comment by LimesKey** [comment]
Great, good luck with the coupon code. Here are some instructions on reducing the cost that I found,
> The most we can offer for the grant is $100. Here are some suggestions for reducing the price:

> 
> 
> * Select PCBA for only two boards rather than all 5. You will still receive all 5, but only two will have components.
> * Select green soldermask and lead-free or leaded HASL finish
> * Make sure as many parts as possible are "Basic" or "Preferred Extended" parts; these parts have the $3 assembly fee waived. Here is the list: https://jlcpcb.com/parts/basic_parts
> 
> If the cost still ends up above $100, DM me on Slack (@your name) and I can help you pay the remainder with your own card.
>

**Review by LimesKey — APPROVED** [review]

**Comment by LandonBayer** [comment]
@LimesKey By instead only ordering 2 boards with parts, combining the shipping, and using leaded solder instead of lead free, I got it just below the price on my card by about $1.50. Thanks for your help!!!

**Pull request merged**
