### PR TITLE
tally-lights PR

### PR DESCRIPTION
**Pull request by techyporcupine**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/TALLY_LIGHTS:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/11cdecf0772572526f9089f80e84ae72538851d3/projects/TALLY_LIGHTS/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/11cdecf0772572526f9089f80e84ae72538851d3/projects/TALLY_LIGHTS/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/11cdecf0772572526f9089f80e84ae72538851d3/projects/TALLY_LIGHTS/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
I'm having trouble finding your verification form, are you sure you've submitted it with your correct GitHub username?

**Comment by techyporcupine** [comment]
Is the verification form for Arcade and the one for OnBoard different??

**Comment by LimesKey** [comment]
It is unfortunately, we're working to make it into one form but for now, you'll just have to do both.

**Comment by techyporcupine** [comment]
Alrighty then. I'll let you know when I finish it

**Comment by techyporcupine** [comment]
Submitted it.

**Review by LimesKey — APPROVED** [review]
Hi @techyporcupine!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/vGyIxQ). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by techyporcupine** [comment]
Awesome thank you! I'm a little worried about whether it'll work or not but I had a couple people look it over so here's to hoping that it'll work!

**Comment by LimesKey** [comment]
I was going to comment on that, you're using a lot of components that I used in my PCB and I thought that was interesting. In my experience, be careful of the component placement on the PCB, capacitors used for components need to be a specific distance away from what they're connected to. Also, you should pay attention to DRC errors and input the correct parameters for DRC from JLCPCB's capability details, I feel some of the traces and components are too close together. If you're interested, take a look at my schematic design as I used some similar parts to you, https://github.com/LimesKey/NameTagPCB/blob/main/HackerBadgePCBV3.pdf.

**Comment by techyporcupine** [comment]
Ah okay. First of all, if I do any changes that are just rerouting do I need to make a new PR? 

About the capacitors, I tried my best on this but I could redo the routing and really make sure I got it right. You said that there is a specific distance, does that mean they have to be a certain distance from the component, as I was just trying to get them as close as I could. 

About JLC's capabilities, I had previously just used the defaults in EasyEDA, are those not reflective of JLC's capabilities?

**Comment by LimesKey** [comment]
> Ah okay. First of all, if I do any changes that are just rerouting do I need to make a new PR?

Nope! Not unless it's a major change

> About the capacitors, I tried my best on this but I could redo the routing and really make sure I got it right. You said that there is a specific distance, does that mean they have to be a certain distance from the component, as I was just trying to get them as close as I could.

In the datasheet of some components like U9 or U3 on your schematic, they can be particular on the accompanying crystals/capacitors/resistors for reasons I barely know myself. On the datasheet of say the ESP8266, there's a [design guide](https://www.espressif.com/sites/default/files/documentation/esp8266_hardware_design_guidelines_en.pdf) on where to place what 
image 
image
Might not be required for it to work but it's best practice.

> About JLC's capabilities, I had previously just used the defaults in EasyEDA, are those not reflective of JLC's capabilities?

I'm not sure but I would just double-check to be safe, maybe the default values are out of date or something? I use KiCad myself and the values in KiCad are not reflective of JLCPCB's capabilities.

**Comment by techyporcupine** [comment]
Awesome, thanks for the help. I just re-did some routing and spread things out a bit more, and I think it's better now!

**Comment by techyporcupine** [comment]
Is it okay that after making the changes, the shipping cost went up a couple cents?

**Comment by LimesKey** [comment]
That's fine

**Pull request merged**
