### PR TITLE
Macropad

### PR DESCRIPTION
**Pull request by lxsquid**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/AAAAMACRO:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/0737129b47128f291c84c35be10a4d5a18e1cd6a/projects/AAAAMACRO/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/0737129b47128f291c84c35be10a4d5a18e1cd6a/projects/AAAAMACRO/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/0737129b47128f291c84c35be10a4d5a18e1cd6a/projects/AAAAMACRO/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by lxsquid** [comment]
@maxwofford, is everything fixed?

**Comment by lxsquid** [comment]
How do I receive the grant?

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @lxsquid! Seems like you just selected pcb fabrication and not assembly in the shopping cart. I'm also surprised the order amount comes out to that high– is that all from shipping costs?

**Comment by lxsquid** [comment]
Hi @maxwofford ! Thanks for getting back to me. I don't plan on doing PCBA because I have the Arduino and the necessary switches to solder on to the PCB. I was also surprised that the macropad PCB costed that much (some of it mainly does come from shipping: around $30). I did request for ENIG on the PCB though...

**Review by maxwofford — APPROVED** [review]
Great! there should be a cheaper shipping option if you talk to JLC support, but I won't block merging on that!

**Comment by lxsquid** [comment]
I checked the cheapest shipping option though.

**Comment by lxsquid** [comment]
Hi, could you please let me know how or when I will recieve the grant? My email for my github is lxsquidttv@gmail.com. Do I recieve the grant there?

**Comment by lxsquid** [comment]
@maxwofford

**Comment by maxwofford** [comment]
@lxsquid You submitted a different email address in your verification so the grant was sent there! Switching to Slack DMs

**Comment by maxwofford** [comment]
It looks like your slack username has changed since then. Your grant is at https://hcb.hackclub.com/grants/q57IJL & is tied to your gmail account starting with "m"

**Comment by lxsquid** [comment]
Hi. @maxwofford I found the link to accept the grant! Tt seems like the system cancelled the grant for some reason. Is there an issue with the link? Did it expire?

image

**Comment by maxwofford** [comment]
You're being linked to the expired grant– I had to cancel that one to reissue your grant with the increased spending limit. Sign in with your mchuangyc@gmail.com account & then go to https://hcb.hackclub.com/grants/q57IJL.

**Pull request merged**
