### PR TITLE
Add "Hack-n-roll board"

### PR DESCRIPTION
**Pull request by RohitPandey1729**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by RohitPandey1729** [comment]
Link to the old PR: [gh pr checkout 792](https://github.com/hackclub/OnBoard/pull/792)
#792

**Comment by 46-HA** [comment]
Hello! Can you fix these errors?
1. Resubmit the verification form. We need a document with your name and a date.
2.  The card seems to be a lot of money compared to others, do you have any expensive add-ons or fast shipping?
3. Can you add a project name? It can be anything you want it to be (i.e "Rohit Hacker card"), be as creative as you want to be!

**Comment by RohitPandey1729** [comment]
Hello, thank you for your reply. I will fix those mistakes immediately. But
I have a question. After I fix that do I have to make a new PR? Or can I
keep the same one

Thank you,
Rohit Pandey

**Comment by RohitPandey1729** [comment]
I have fixed all that you have said

**Comment by 46-HA** [comment]
Awesome! I've went ahead and issued you [your grant here](https://hcb.hackclub.com/grants/w0EIyz)! If you have any questions feel free to contact me on Slack (HenHen) or ask here. Keep on hacking :)

**Pull request merged**
