### PR TITLE
!!!USB HUB with USB-C!!!

### PR DESCRIPTION
**Pull request by MrKillerShaunBa**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [NA] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [NA] (Optional) This project is from a tutorial[^1].
- [NA] (Optional) This project is for OnBoard Live[^2].
- [X] (Optional) This project is for [Trick or Trace](https://showcase.hackclub.com/)[^3].
- [NA] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/!!!Shaunak's-Usb-c-hub!!!:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/223a90ff210398e71d03abba64b30c8a8aa52fe1/projects/!!!Shaunak's-Usb-c-hub!!!/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/223a90ff210398e71d03abba64b30c8a8aa52fe1/projects/!!!Shaunak's-Usb-c-hub!!!/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/223a90ff210398e71d03abba64b30c8a8aa52fe1/projects/!!!Shaunak's-Usb-c-hub!!!/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by MrKillerShaunBa** [comment]
@Pegoku

**Comment by Pegoku** [comment]
did you "@" me? I can't do Trick or Trace.

**Comment by MrKillerShaunBa** [comment]
no i didnt

**Comment by MrKillerShaunBa** [comment]
can someone see my project?

**Comment by MrKillerShaunBa** [comment]
@LimesKey can you get someone to review this?

**Comment by Pegoku** [comment]
It's not a regular OnBoard PCB, idk if it gets reviewed. I think it just gets voted by people. (not sure)

**Review by LimesKey — CHANGES_REQUESTED** [review]
Looks good, are you able to add to your README a little bit more? Can you also fill out the [verification form](https://verify.onboard.hackclub.com/) once again so we can send you a little gift in the mail?

**Comment by MrKillerShaunBa** [comment]
Yeah, I can do that.

**Comment by MrKillerShaunBa** [comment]
can you check if this works
?

**Comment by MrKillerShaunBa** [comment]
verification complete.

**Review by LimesKey — APPROVED** [review]
Hi @MrKillerShaunBa!

Thanks for submitting your design to Trick or Trace! Project voting open Oct 21st, check in to [#electronics](https://slack.com/archives/C056AMWSFKJ) (in the Slack) or on the [website](https://trickortrace.hackclub.com/) for the link to see your project in the gallery, and to vote on other's designs. Look forward to receiving a small package in the mail in the next few weeks, just a small gift to continue you on your journey of making.

**Comment by MrKillerShaunBa** [comment]
Hey @LimesKey , do i still get a normal OnBoard grant?

**Pull request merged**
