### PR TITLE
LCard - Lucas Business Card

### PR DESCRIPTION
**Pull request by LucasHT22**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection

### CODE REVIEW

**Review by daisybanks — COMMENTED** [review]
Hey @LucasHT22! So glad to have you here for OnBoard! Everything looks good on Bank's end @bykevinyang. :)

**Comment by LucasHT22** [comment]
Thanks Daisy!

**Review by bykevinyang — APPROVED** [review]
Congrats @LucasHT22! Welcome to OnBoard. You'll be receiving an email from bank shortly!

**Comment by LucasHT22** [comment]
Thanks @bykevinyang !

**Pull request merged**
