### PR TITLE
Change part specifics

### PR DESCRIPTION
**Pull request by BoredFishRE**
Changed parts requirements due to availability of the 1984617

### CODE REVIEW

**Review by karmanyaahm — APPROVED** [review]
Approving this one, but in general you don't need to make minor part changes to the OnBoard repo. If you're trying to make a tutorial, it might be better to link to an external blog post or GitHub repo.

**Comment by karmanyaahm** [comment]
cc @kvnyng second approval needed

**Comment by BoredFishRE** [comment]
> Approving this one, but in general you don't need to make minor part changes to the OnBoard repo. If you're trying to make a tutorial, it might be better to link to an external blog post or GitHub repo.

Good to know, thanks!

**Comment by BoredFishRE** [comment]
I'll go ahead and add a link to the main repo

**Comment by maxwofford** [comment]
I don't think we need a double approve for this– it's just a project update. Thanks for keeping your project updated @BoredFishRE!

**Pull request merged**
