### PR TITLE
Upload saumilthecode namecard

### PR DESCRIPTION
**Pull request by saumilthecode**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
(I used the namcard tutorial :D)

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/saumilthecode:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by saumilthecode** [comment]
sorry boss ill change it rn

**Comment by saumilthecode** [comment]
heyo @Lightshayan any updated on if im approved yet?
thanks for your time :D

**Comment by Lightshayan** [comment]
Hey! You didn't wire your board properly - ideally your board has a wire that connects the copper in the front in the back. Check the jam and make sure your board is wired properly to ensure your card is functional. 

Feel free to ask any questions in the #electronics channel!

**Comment by saumilthecode** [comment]
Hello! If I recall correctly that trace is for the NFC chip which from what I learned is actually just a copper coil which JLPCB doesn't carry.So that trace is effectively not doing anything.
Lmk if I really need to remove it completely

**Comment by Lightshayan** [comment]
image
This should be connected and ideally, the bottom design should not be made out of copper.

**Comment by saumilthecode** [comment]
Hello! @Lightshayan i belive i fixed it accordingly now :D

**Comment by Lightshayan** [comment]
Hey! Your antenna does not look correct - try using the tutorial antenna so the NFC can work!

**Comment by saumilthecode** [comment]
Heyo! @Lightshayan i belive this should be up to standard now :DD (please help the git is killing me)

**Comment by LimesKey** [comment]
Hi, sorry LightShayan had to leave, your PR looks good but I did notice another issue in your schematic file. I think your LED is rotated the wrong way, it should be to the left pointing to VSS. Double check you did that right in the jam and please create a new JLCPCB order, then I should be able to approve your pull request.

**Comment by LimesKey** [comment]
This pull request has been inactive for some time and has therefore been closed. Feel free to create a new one when you're ready.

**Pull request closed without merging**
