### PR TITLE
HirokiNariyoshiHackerCard

### PR DESCRIPTION
**Pull request by HirokiNariyoshi**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by HirokiNariyoshi** [comment]
Please refer to the latest commit for the files and ignore the previous commits (I don't know how to delete them). Thank you!

**Comment by MichaByte** [comment]
Hi @HirokiNariyoshi!

Could you please fill out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)? We need that info to make sure you're eligible for the grant. Don't worry about deleting the files - I can take care of that. Once you submit the form, I can get you your grant!

**Comment by HirokiNariyoshi** [comment]
> Hi @HirokiNariyoshi!
> 
> Could you please fill out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)? We need that info to make sure you're eligible for the grant. Don't worry about deleting the files - I can take care of that. Once you submit the form, I can get you your grant!

Hi! I just completed the verification form. Thank you!!

**Comment by MichaByte** [comment]
@HirokiNariyoshi Could you check your Slack DMs? I want to confirm something

**Comment by MichaByte** [comment]
Hi @HirokiNariyoshi! I've just sent you [your grant](https://hcb.hackclub.com/grants/qZEI2L). Make sure to share your PCBs in #electronics when they arrive, and enjoy your hacker cards!

**Pull request merged**
