### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by devxiexie**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by daisybanks — APPROVED** [review]
Welcome OnBoard @devxiexie! Everything looks good on Bank's side @hackclub/boarding-party!

**Review by Leo32345 — APPROVED** [review]
Looks good to me!

**Comment by devxiexie** [comment]
Alright, thanks! When should I receive an email about the grant information?

**Comment by maxwofford** [comment]
@devxiexie I was just checking out your project while going through the list of designs and I love it! I didn't see a schematic file though and wanted to ask if you can share that with me-- I want to see what parts you used.

**Comment by devxiexie** [comment]
> @devxiexie I was just checking out your project while going through the list of designs and I love it! I didn't see a schematic file though and wanted to ask if you can share that with me-- I want to see what parts you used.

I don't think I have a schematic file, however, the parts I used were the pcb, a pro micro with headers [(this)](https://www.amazon.com/OSOYOO-ATmega32U4-arduino-Leonardo-ATmega328/dp/B012FOV17O?th=1),
mill-max sockets to make the pcb hot-swappable [this](https://divinikey.com/products/mill-max-hotswap-sockets?variant=39313620697153), 2 switches and 2 keycaps

**Comment by maxwofford** [comment]
Thanks @devxiexie! The json file only contains the trace instead of the schematic view of easyeda. Think you can find that?

**Comment by devxiexie** [comment]
[BOM_2Switch_2023-10-17.csv](https://github.com/hackclub/OnBoard/files/12969575/BOM_2Switch_2023-10-17.csv)
[PickAndPlace_2Switch_2023-10-17.csv](https://github.com/hackclub/OnBoard/files/12969576/PickAndPlace_2Switch_2023-10-17.csv)
could it be these?

**Comment by maxwofford** [comment]
Just above those on the export
Screenshot 2023-10-18 at 10 39 07
Screenshot 2023-10-18 at 10 39 25

**Comment by devxiexie** [comment]
[PCB_2Switch_2023-10-18.pdf](https://github.com/hackclub/OnBoard/files/13034559/PCB_2Switch_2023-10-18.pdf)
Is this good?

**Pull request merged**
