### PR TITLE
Anirudh's Heart LED

### PR DESCRIPTION
**Pull request by anirudh12032008**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Anirudh's Heart LED:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/4bd89bb6193919b88daac357a2e638eef9f98391/projects/Anirudh's Heart LED/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/4bd89bb6193919b88daac357a2e638eef9f98391/projects/Anirudh's Heart LED/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/4bd89bb6193919b88daac357a2e638eef9f98391/projects/Anirudh's Heart LED/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by blazecoding2009 — APPROVED** [review]
Hey @anirudh12032008 

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/XRGI0z). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @anirudh12032008 

Looks like one side of your LEDs aren't connected

image

**Comment by blazecoding2009** [comment]
> @blazecoding2009 actually I have used net labels there so all the leds are connected to the 555 , I would be really grateful if you could review the PCB once as this is my first time and I don't know wheather it's correct or not I posted it in #electronics also but no one responded there

In the schematic, I don't see it connected

**Comment by anirudh12032008** [comment]
> > @blazecoding2009 actually I have used net labels there so all the leds are connected to the 555 , I would be really grateful if you could review the PCB once as this is my first time and I don't know wheather it's correct or not I posted it in #electronics also but no one responded there
> 
> In the schematic, I don't see it connected to VCC/3.3v

But they are connected to the out pin(3) of the NE555P doesn't that supplies the current to it?

**Comment by blazecoding2009** [comment]
It does but you need a positive and negative connection to the LEDS

**Comment by blazecoding2009** [comment]
@LimesKey would you mind double checking for me if I'm correct here?

**Comment by LimesKey** [comment]
Looks okay in the Gerber view but the schematic is wrong like what @blazecoding2009 said. Can I ask why your LEDs are THT and so large? I think your PCB should work but some of the design decisions you did are interesting.

**Comment by blazecoding2009** [comment]
Also that, smd would be a better option and would look a bit better in my opinion. Tht usually Is also more pricey for PCBA

**Comment by anirudh12032008** [comment]
> Looks okay in the Gerber view but the schematic is wrong like what @blazecoding2009 said. Can I ask why your LEDs are THT and so large? I think your PCB should work but some of the design decisions you did are interesting.

This was really my first time creating a full PCB design so I also don't know what I did but I just did it I selected THT because with the SMT I was facing issue with the bottom copper layer 🥲
Please share your thoughts and suggestions so that I could incorporate them. 
For the LED connection I wanted to connect all the leds one end to the out (3) so I searched how can I do it and then choice net labels, if there's something I need to change in it please let me know.

**Comment by anirudh12032008** [comment]
> Also that, smd would be a better option and would look a bit better in my opinion. Tht usually Is also more pricey for PCBA

I was facing problem with the back layer and when I switched it worked pretty well that's why I choice it, if its possible with smt could you please share any tutorial or project with it. Then I would change it to SMT

**Comment by blazecoding2009** [comment]
SMD is the same as THT, just want to say that it's okay to have positive and negative on the same layer

**Comment by anirudh12032008** [comment]
> SMD is the same as THT, just want to say that it's okay to have positive and negative on the same layer

But while creating the routes they were contradicting. I'll try once again today with SMT 👍

**Comment by blazecoding2009** [comment]
> > SMD is the same as THT, just want to say that it's okay to have positive and negative on the same layer
> 
> But while creating the routes they were contradicting. I'll try once again today with SMT 👍

Try using vias! You should seen an optoin

**Comment by anirudh12032008** [comment]
> > > SMD is the same as THT, just want to say that it's okay to have positive and negative on the same layer
> > 
> > But while creating the routes they were contradicting. I'll try once again today with SMT 👍
> 
> Try using vias! You should seen an optoin

Thank you I'm currently a bit busy due to some assignments but I'll do it soon 👍

**Comment by anirudh12032008** [comment]
@blazecoding2009 Could you please help me out by confirming if everything is right this is my schematic so that I could move on to the pcb. Here's a 3d img also on the pcb, looking forward to your feedbacks.
3d
Schematic_heart_sim_2024-08-19 (1)

**Comment by blazecoding2009** [comment]
What's that huge thing in the top left?

**Comment by anirudh12032008** [comment]
> What's that huge thing in the top left?

they are the headers for +ve and -ve terminal
Heres a rough pcb view

**Comment by blazecoding2009** [comment]
I was talking about this: 
image

that is a resistor, that is HUGEEEE. use a smaller footprint one

**Comment by anirudh12032008** [comment]
> I was talking about this: image
> 
> that is a resistor, that is HUGEEEE. use a smaller footprint one

Done
3d

**Comment by blazecoding2009** [comment]
Can you update the cart.png?

**Review by blazecoding2009 — APPROVED** [review]
Hey @anirudh12032008 

Good luck! I've just sent your [grant](https://hcb.hackclub.com/grants/vLoI3z)

**Comment by anirudh12032008** [comment]
> Hey @anirudh12032008 
> 
> Good luck! I've just sent your [grant](https://hcb.hackclub.com/grants/vLoI3z)

Thank you could you please review the circuit once that it would be working? Please

**Comment by blazecoding2009** [comment]
You're good

**Pull request merged**
