### PR TITLE
Add "Krishna's USB hub" board

### PR DESCRIPTION
**Pull request by Ggkkhi**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Krishna's USB-hub:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @Ggkkhi, this looks pretty good, but I see the cost is over $50. We only give $50 for [tutorial projects](https://jams.hackclub.com/batch/usb-hub) so I can't issue this grant yet. You might be able to cut costs with different components and a smaller board though!

**Comment by Ggkkhi** [comment]
But as per website, grant is given of 100$. And this project I have made
highly as per the tutorial video

**Comment by Ggkkhi** [comment]
And the USB port in the tutorial used was available only in Standard PCB
assembly not in Economic which is costing that much, so what should I do?

**Comment by BrightTheBackpack** [comment]
In order to encourage people to design their own PCBs(or maybe for some other reason), tutorials give 50 dollars. When you make your own board, you'll get the other 50 dollars!

**Comment by BrightTheBackpack** [comment]
Also, it looks like you might have unfinished connections.
image

**Comment by Ggkkhi** [comment]
Thanks, I'll look into it.

**Comment by Ggkkhi** [comment]
Hey can anyone tell me a USB-A male connector available for Economic PCBA because the part used in the project is only available in Standard PCBA which is increasing the price. Please reply ASAP.

**Comment by abitchinmorewaysthanone** [comment]
I am closing this PR for cleanup. Please ask any questions in the #electronics Slack channel! We can help you much faster that way.

**Pull request closed without merging**
