### PR TITLE
Kashvi-Finished!

### PR DESCRIPTION
**Pull request by kashguppy**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/PROJECT_NAME:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by SerenityUX** [comment]
hi! I see you marked this as "trail". Can you tell me a bit more of how you'd plan to use this on The Trail?

https://trail.hackclub.com/

**Comment by kashguppy** [comment]
Hey! Sorry I think I had mistakenly clicked on "trail", I just fixed that!
The intended purpose of my card is to be a tech savvy card which has the
ability to transmit URLs and light up! Thank you for the learning
experiences!

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @kashguppy, looks like the bot is flagging some files as out of place. can you go through and fix up your filenames and folders?

**Comment by abitchinmorewaysthanone** [comment]
Closing for cleanup. Please resubmit with the files organized correctly! Our bot needs them organized correctly to render the PCB. You can look at some of the other folders in [main/projects](https://github.com/hackclub/OnBoard/tree/main/projects) to see how. You can look at  Also, your project folder is called /PROJECT_NAME/ for some reason.

**Pull request closed without merging**
