### PR TITLE
Add "Business_Card" Board

### PR DESCRIPTION
**Pull request by Sushi365**
## Submission Checklist:

- [ Yes] I am a current high school, middle school, or home schooled student.
  - [ Yes] I am 18 or under
  - [ Yes] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Yes ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ yes] I made this board from scratch, even if I followed a tutorial
- [ Yes] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Yes ] Created a folder under `onboard/projects`
  - [Yes ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [Yes ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [Yes ] Created a folder called `src` and uploaded design files
  - [Yes ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [Yes ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [Doesn't Apply to me ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [Yes ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [FRC 7451 ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Business_card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @Sushi365,

Thanks for submitting your PCB order! However, it looks like you took a picture of your cart instead of completing the checkout process. To ensure your order gets processed correctly, please follow the steps in [this](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) guide or in here:


1. Click "Secure Checkout": After adding your PCB to the cart, make sure to click "Secure Checkout."
2. Enter your shipping information: Fill in your shipping details as prompted.
3. Take a screenshot of your unpaid order: Once you reach the final page before payment, take a screenshot of this page. It should show all the details of your order.


Please send me a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will help us review your order more efficiently. Congrats on making the PCB though!

**Comment by Sushi365** [comment]
Hello LimesKey, I've been having an issue. One of my parts is not available, so does that mean I have to redo my project?

**Comment by LimesKey** [comment]
Which part? Unlikely you'll have to redo the project, all the parts in the guide should be available to order and if not we can find a replacement.

**Comment by Sushi365** [comment]
The NFC antenna I picked the same one from the tutorial.

**Comment by elinzhang507** [comment]
You don't have to place that part. From the hacker jam: "this is not an actual part, so it doesn't need to be assembled onto the board -- it's formed by the copper traces on the PCB."

**Comment by Sushi365** [comment]
Ok, thanks for the clarification.

**Comment by LimesKey** [comment]
Hi @Sushi365!

Please feel free to ask for help if you need any here or [#electronics on Slack](https://hackclub.com/slack/?event=onboard). I'm closing this for cleanup right now, but if you update your PR with the requested changes, please open up a new PR and link the old one!

**Pull request closed without merging**
