### PR TITLE
Parkers first try

### PR DESCRIPTION
**Pull request by parker1224**
## Submission Checklist:

- [ I am a current middle school student]
  - [yes ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ yes] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [yes ] I made this board from scratch, even if I followed a tutorial
- [ yes] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ yes] Created a folder under `onboard/projects`
  - [ yes] Filled out `TEMPLATE.md` as `README.md`
  - [ yes] Uploaded Gerber, sources, and schematic
  - [ yes] Uploaded screenshot of PCB order with all costs included
  - [yes but not in the picture I have added more of the board so that after taxes and shipping it is the same] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [yes ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [im in first ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 5927

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by Leo32345 — APPROVED** [review]
Looks great! Congrats Parker on your first PCB!

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi @parker1224! You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order 5 assembled boards.

Additionally, please make a "src" folder in projects/[name]/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

Also, you need to export your schematic tab as a PDF (in the schematic tab go to [File > Export > PDF](https://docs.easyeda.com/en/Export/Export-Schematic/index.html)), and upload that.

**Comment by karmanyaahm** [comment]
If you have any questions feel free to ask!

**Comment by sarthaktexas** [comment]
student verification approved!

**Review by sarthaktexas — APPROVED** [review]

**Comment by karmanyaahm** [comment]
Hi Parker! Feel free to ask if you have any questions about the changes I asked for above

**Comment by karmanyaahm** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/bb4cc0f3312e6f92c5158c71b0e9c9b41dfb9f7e/projects/PROJECT_NAME/Gerber_PCB_New Project (1).zip>)!

  Happy OnBoarding!

**Comment by maxwofford** [comment]
I haven't seen any activity on this so I'm going to silence this PR for now. @parker1224 it'll say it's closed but you can still 100% get the grant, just [talk to @karmanyaahm](https://github.com/hackclub/OnBoard/pull/308#issuecomment-1886256578) if you need help.

**Pull request closed without merging**
