### PR TITLE
1.4 Amp Laser Driver

### PR DESCRIPTION
**Pull request by Someon332**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) This project is for Hacky Holidays[^3].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Hacky Holidays](https://hacky-holidays.hackclub.com/) is a limited time PCB event, design a holiday-themed PCB this Winter, and get it shipped.

@LimesKey

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/1.4Amp Laser Driver:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/e65babfeb8c3851dced700d5ba819ff48401b56e/projects/1.4Amp Laser Driver/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/e65babfeb8c3851dced700d5ba819ff48401b56e/projects/1.4Amp Laser Driver/schematic.pdf>) |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/e65babfeb8c3851dced700d5ba819ff48401b56e/projects/1.4Amp Laser Driver/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by LimesKey** [comment]
Looks good, however, is this line supposed to be disconnected? 
image
And do you want to round the corners a little and add some things to the silkscreen? Some of the designators on the silkscreen are cut off.

**Comment by Someon332** [comment]
Yep, I left it disconnected on the schematic because I didn't want to merge
the two grounds (I needed a power ground and analog ground). I connected
the grounds on the back of the PCB by using a trace that ignored
boundaries.
I don't care about rounded corners or the silkscreen designators. It's
coming assembled and the only component that I'm adding myself is THT so it
dosen't matter to me.

Thanks for checking in!

**Comment by LimesKey** [comment]
Can you provide just the `.WRL` VRML 3D Model and not a zipped file of an OBJ?

**Review by LimesKey — APPROVED** [review]
Hi @Someon332!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/GyI9Gx). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the [#electronics](https://slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/) once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by WolfGamer2** [comment]
Oop, forgot to merge.

**Pull request merged**
