### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Screen-sLaYeR**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Que Management:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ed52d0a7521dbd70d29bf67b745911bfb13b133e/projects/Que Management/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ed52d0a7521dbd70d29bf67b745911bfb13b133e/projects/Que Management/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/ed52d0a7521dbd70d29bf67b745911bfb13b133e/projects/Que Management/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by MichaByte** [comment]
Hi @Screen-sLaYeR!
This queue management project looks awesome! However, we are unable to provide parts for it that are ordered separately from your board, so that means you would need to use your own money on Amazon, Aliexpress, Digikey, etc. Your best bet would be to modify this design to use parts available in the JLCPCB assembly library. If you need any help, feel free to reach out to me or join the [#electronics channel on Slack!](https://hackclub.com/slack/?event=onboard)

**Comment by MichaByte** [comment]
To clarify, I can still give you a $100 grant that you can use for the PCB, but it won't cover any of the parts.

**Comment by Screen-sLaYeR** [comment]
> To clarify, I can still give you a $100 grant that you can use for the PCB, but it won't cover any of the parts.

So should I remove the components from the list? or should I order a PCB Assembly for the supplier because it is costly for no reason and also I have used all the through hole components that are all required to just plug them in the female headers 
Please Consider this beacuse the PCBA takes a lot of money for no reason and also not all the components are with them they don't have ESP-12F which is the main component for processing and driving the 7 - Segments
What should I do now ?

**Comment by karmanyaahm** [comment]
Hey @Screen-sLaYeR! Sorry for the delay, but if you are fine with buying the parts yourself, we can send you the grant (for just the PCB). If you want PCBA, please update the cart image, and we can get you the grant for that. Either option is fine.

**Comment by Screen-sLaYeR** [comment]
I'll change the cart then

**Pull request closed without merging**
