### PR TITLE
Pull pcb-trophy project into repositor

### PR DESCRIPTION
**Pull request by roy-rishi**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md`
  - [X] Uploaded Gerber.zip and Schematic.pdf
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/pcb-trophy:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/0578b4adf088670253bf24c330168d42b87e7e30/projects/pcb-trophy/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/0578b4adf088670253bf24c330168d42b87e7e30/projects/pcb-trophy/schematic.pdf>) |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/0578b4adf088670253bf24c330168d42b87e7e30/projects/pcb-trophy/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by maxwofford — CHANGES_REQUESTED** [review]
This looks awesome! I'm a little surprised at how expensive shipping is though– there might be a cheaper option. Also, have you double checked your battery has enough current to handle that many LEDs in parallel?

**Comment by maxwofford** [comment]
I just marked it as "requested changes" for now– your verification is approved and I'll send the grant if there's no cheaper option & the LEDs are fine with the battery.

**Comment by roy-rishi** [comment]
Hey Max, thanks for reviewing my PR. Shipping surprised me too; I believe it's due to the 1-1.5 kg mass of all 5 PCBs. There is one slightly cheaper option, however the timeline for needing this makes me less inclined to choose the 15 day shipping option.
Thanks for mentioning the current draw; although I am current limiting the LEDs at about 10 mA each (total 200 mA), upon your suggestion I decided to change to a AAA, which I have tested with a load resistor and multimeter to verify it can meet the current demands. I will, however, need to add a dc-dc boost converter to the board, as I'd prefer to avoid requiring 2 AAAs due to size. Might as well add a transistor to the circuit, while I'm at it.
I'm happy to re-upload the files and await approval afterwards, if you'd like.

**Review by maxwofford — CHANGES_REQUESTED** [review]
Swap out those files and I can approve the PR!

**Comment by roy-rishi** [comment]
Just swapped them!

**Review by maxwofford — APPROVED** [review]
Thanks! I just [sent out the grant](https://hcb.hackclub.com/grants/w2dIlD)

**Comment by roy-rishi** [comment]
Thanks!

**Pull request merged**
