### PR TITLE
Amir Z's Macros Keyboard

### PR DESCRIPTION
**Pull request by amirzzz23**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Amir Z's Macros Keyboard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ee92806363d8e4cabdad9ad02bb3416d104019d2/projects/Amir Z's Macros Keyboard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/ee92806363d8e4cabdad9ad02bb3416d104019d2/projects/Amir Z's Macros Keyboard/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/ee92806363d8e4cabdad9ad02bb3416d104019d2/projects/Amir Z's Macros Keyboard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @amirzzz23. I see we have a previous grant card out for you but it still has the $50 grant on it unused https://github.com/hackclub/OnBoard/pull/524.

I do see 2 attempts at personal transactions on your card:

Screenshot 2024-05-13 at 09 39 32

Why should I approve this?

**Comment by amirzzz23** [comment]
Oh, I am sorry. As far as I can tell, it is required that I spend the grant
on the JLCPCB website?
I can do that right now.

Thank you!
Amir Zholdassov

пн, 13 мая 2024 г., 06:42 Max Wofford ***@***.***>:

**Comment by amirzzz23** [comment]
Please give me one day to complete the transaction. Thank you!

пн, 13 мая 2024 г., 08:14 Bsb ***@***.***>:

**Comment by maxwofford** [comment]
@amirzzz23 you don't need to complete the previous transaction if you're hoping to save the funds for the macros keyboard, but you can't spend the funds on spotify and amazon– the PCB grant is for PCB fulfillment.

**Comment by amirzzz23** [comment]
Oh, I deeply appologize, is there is anything I could do? I am not going to spend it on anything else but PCB fulfillment. HackClub has been a huge enjoyment to me, and I do not want to lose this opportunity. 
Again sorry.
Thank You!

-Amir Zholdassov

**Comment by amirzzz23** [comment]
I am not going to use this Grant for personal use, but I will use it for PCB fulfillment. OnBoard has been a huge opportunity to me, and I do not want to lose it. 
Thank You
-Amir Zholdassov

**Review by maxwofford — APPROVED** [review]
I'm giving another change to use the grant– [it's $72.11](https://hcb.hackclub.com/grants/woQIKL) to cover the $100 for both grants -$27.89 for the JLCPCB order you already made.

There's also some cancelled grant emails you probably got– you can ignore those.

**Comment by amirzzz23** [comment]
Thank you So Much! I really do appreciate that! This is not going to happen again!

**Pull request merged**
