### PR TITLE
arjuns nfc card

### PR DESCRIPTION
**Pull request by arjundeshpande08**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/arjun's-nfc-card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/43179b19ceadd581a1036dc50f6d28ab8eca32f7/projects/arjun's-nfc-card/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/43179b19ceadd581a1036dc50f6d28ab8eca32f7/projects/arjun's-nfc-card/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/43179b19ceadd581a1036dc50f6d28ab8eca32f7/projects/arjun's-nfc-card/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by blazecoding2009** [comment]
@arjundeshpande08 Please don't delete and recreate PRs when we are requesting a change even if you have fixed it. PRs auto update when you commit files even after you have created the PR

**Comment by blazecoding2009** [comment]
Hey @arjundeshpande08 

You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order up to 5 assembled boards.

**Comment by arjundeshpande08** [comment]
Do I need to re upload any files afterwards?

**Comment by blazecoding2009** [comment]
> @blazecoding2009 Do I need to re upload any files afterwards?

Yes, your cart.png.

**Comment by arjundeshpande08** [comment]
when i say do not place for the nfc chip (as it says to do on the link you sent me) will the pcb sent to me still include them?

**Comment by blazecoding2009** [comment]
> when i say do not place for the nfc antenna (as it says to do on the link you sent me) will the pcb sent to me still include them?

Yes. The nfc antenna is a trace component

**Comment by arjundeshpande08** [comment]
hello sorry, please can we close this pr as i have just seen on of the parts needed for assembly is out of stock :(

**Pull request closed without merging**
