### PR TITLE
project

### PR DESCRIPTION
**Pull request by comicsansgood**
## Submission Checklist:

- [ /] I am a current high school, middle school, or home schooled student.
  - [/ ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [/ ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- /[ ] I made this board from scratch, even if I followed a tutorial
- [/ ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [/ ] Created a folder under `onboard/projects`
  - [ /] Filled out `TEMPLATE.md` as `README.md`
  - [/ ] Uploaded Gerber, sources, and schematic
  - [/ ] Uploaded screenshot of PCB order with all costs included
  - [/ ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [/ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ /] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: _8046___

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by Hugoyhu — CHANGES_REQUESTED** [review]
Hi! Thanks for your PR. 

Wanted to note something: your current Logo (the IL one, as well as the 8046 text) is on the COPPER layer. The location you have placed this means that it is currently shorting all your traces and your design will not function as the power lines will be shorted.

Here are two ways I might suggest to fix this
- you have nothing on the back layer, so you can move the logo to the back layer (BottomLayer). If you want this to show up shiny (copper exposed), you'll also want to copy and paste the logo, align it completely and make one on BottomSolderMaskLayer. This way you'll have the same image, on both layers. 
- you can change the text and image into "TopSilkLayer". this is a non-conductive "paint" (in simple terms) that is applied, and will thus not have any effect on the circuit itself.

Once you're done, please resubmit your files so I can take a look! And feel free to reply directly here (or DM me over slack!) in case you're having any troubles or have questions. Thank you and good evening!

**Comment by karmanyaahm** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/eec9e8741716cb06f49174c744b625a29e0df2a6/projects/masonPCBproject/Gerber_PCB_attempt2_2024-01-11.zip>)!

  Happy OnBoarding!

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/eec9e8741716cb06f49174c744b625a29e0df2a6/projects/masonPCBproject/Gerber_PCB_attempt2_2024-01-11.zip>)!

  Happy OnBoarding!

**Comment by maxwofford** [comment]
@comicsansgood I just wanted to check in and see how it's going? I'd love to get this board fabricated!

**Comment by karmanyaahm** [comment]
Hi @comicsansgood! I'm closing this PR for cleanup right now, but feel free to reopen it at any time. You can get your grant once you fix the errors mentioned above. Please ask if you need help with anything!

**Pull request closed without merging**
