### PR TITLE
johns2ndcard

### PR DESCRIPTION
**Pull request by johncohn**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/johns2ndcard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
You haven't submitted the student verification, I'm assuming that's intentional since this is only for testing?

**Comment by karmanyaahm** [comment]
One small issue here is that you have your gerber.zip uploaded twice, I'll delete that for you 
image

**Comment by karmanyaahm** [comment]
Also, the current one is good enough, but ideally your schematic.pdf would be exported directly from easyeda, instead of being a screenshot.

Also, you are missing the Schematic JSON and PCB JSON files.
The buttons needed to export all 3 files are covered in Max's video in the repo README https://www.youtube.com/watch?v=Bh3dm81X_zs

**Comment by johncohn** [comment]
Correct.. nd since im not a student.. Max said it wS OK TO APPRIVE,, IF THAT’S HARD TO DO.. NO WORRIES

John Cohn  PhD.
IBM Fellow Emeritus
***@***.******@***.***>
1-802-578-0985

From: Karmanyaah Malhotra ***@***.***>
Date: Saturday, April 20, 2024 at 4:59 PM
To: hackclub/OnBoard ***@***.***>
Cc: John Cohn ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [hackclub/OnBoard] johns2ndcard (PR #470)
You haven't submitted the student verification, I'm assuming that's intentional since this is only for testing? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!97FQeHxZOGTzX7aWZSrLex9HV1XJ8cnFmb_NFDvCCBvfr6E9Lsi-xDxsfiGBmSTrwCixxMcv5yP704n3MWMyyFo61B1XiGJyEes$>
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!97FQeHxZOGTzX7aWZSrLex9HV1XJ8cnFmb_NFDvCCBvfr6E9Lsi-xDxsfiGBmSTrwCixxMcv5yP704n3MWMyyFo61B1XiGJyEes$>


ZjQcmQRYFpfptBannerEnd

You haven't submitted the student verification, I'm assuming that's intentional since this is only for testing?

**Comment by johncohn** [comment]
The instructions Force submitting a PR are a little confusing… At one point it said your Gerber file should be in the top level and then when I did the PR the check said it needed to be in the src  directory

the tutorial at https://github.com/hackclub/OnBoard says:
In all, you should have the following files under your project folder:

  *    README.md: A filled out TEMPLATE.md<https://github.com/hackclub/OnBoard/blob/main/projects/!Template/TEMPLATE.md?plain=1>, renamed to README.md
  *    cart.png: A screenshot of your order details
  *    gerber.zip: This should be the file that you send off to the vendor.
  *    schematic.pdf: Export the schematic from your EDA program as a PDF
  *    src/: Design files in a folder called src. Whatever format your designer outputs should be included.
     *   The files might look like SCH_name.json and PCB_name.json for EasyEDA
     *   Or name.kicad_pro, name_kicad_sch, and name.kicad_pcb
     *   Or design.json, design.sch, design.brd, etc.
If you have all the above, you're done with this step!

But the automation seemed to flag me that I didn’t have the gerber.zip in the ./src dir..
I think that’s what happened. .. where is the gerber supposed to be ?

John Cohn  PhD.
IBM Fellow Emeritus
***@***.******@***.***>
1-802-578-0985

From: Karmanyaah Malhotra ***@***.***>
Date: Saturday, April 20, 2024 at 5:00 PM
To: hackclub/OnBoard ***@***.***>
Cc: John Cohn ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [hackclub/OnBoard] johns2ndcard (PR #470)
One small issue here is that you have your gerber. zip uploaded twice, I'll delete that for you image. png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!97FQeHxZOGTzX7aWZSrLex9HV1XJ8cnFmb_NFDvCCBvfr6E9Lum_pDxsfiGBmSTrQ9eSxOrholFNxXh5j--mhyUocfKsdbWvAbM$>
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!97FQeHxZOGTzX7aWZSrLex9HV1XJ8cnFmb_NFDvCCBvfr6E9Lum_pDxsfiGBmSTrQ9eSxOrholFNxXh5j--mhyUocfKsdbWvAbM$>


ZjQcmQRYFpfptBannerEnd

One small issue here is that you have your gerber.zip uploaded twice, I'll delete that for you
image.png (view on web)<https://github.com/hackclub/OnBoard/assets/32671690/b8d800cf-e1c7-4bd7-bbfe-ac58f6a6e467>

**Comment by johncohn** [comment]
Hmm..

Thanks for the info..
I generally don’t look at the tubes for detailed instructions. For me the Bible is. https://github.com/hackclub/OnBoard/README.md

I didn’t see any mention of the JSON’s export in there     . Just this mention that they exist in this . Maybe we should add that step in the written tutorial
 ***@***.***


that pdf was generated from EasyEda  was generated this way.. Is there another way ? If so we may need to be more specific

***@***.***








John Cohn  PhD.
IBM Fellow Emeritus
***@***.******@***.***>
1-802-578-0985

From: Karmanyaah Malhotra ***@***.***>
Date: Saturday, April 20, 2024 at 5:05 PM
To: hackclub/OnBoard ***@***.***>
Cc: John Cohn ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [hackclub/OnBoard] johns2ndcard (PR #470)
Also, the current one is good enough, but ideally your schematic. pdf would be exported directly from easyeda, instead of being a screenshot. Also, you are missing the Schematic JSON and PCB JSON files. The buttons needed to export all 3 files
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!97FQeHxZOGTzX7aWZSrLex9HV1XJ8cnFmb_NFDvCCBvfr6DcDym-JDxsfiGBmSTr7mLPJ7hxxgJlH1CPGq87_IHZaBgSKLDUKDU$>
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!97FQeHxZOGTzX7aWZSrLex9HV1XJ8cnFmb_NFDvCCBvfr6DcDym-JDxsfiGBmSTr7mLPJ7hxxgJlH1CPGq87_IHZaBgSKLDUKDU$>


ZjQcmQRYFpfptBannerEnd

Also, the current one is good enough, but ideally your schematic.pdf would be exported directly from easyeda, instead of being a screenshot.

Also, you are missing the Schematic JSON and PCB JSON files.
The buttons needed to export all 3 files are covered in Max's video in the repo README https://www.youtube.com/watch?v=Bh3dm81X_zs<https://www.youtube.com/watch?v=Bh3dm81X_zs>

**Comment by karmanyaahm** [comment]
> src/: Design files in a folder called src. Whatever format your designer outputs should be included.
>     *   The files might look like SCH_name.json and PCB_name.json for EasyEDA


You're right, it specifies that the files need to be included, but doesn't say how to do it. We need to add more instructions.


Here are the instructions:

> Please make a "src" folder in projects/[name]/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.
> image
> 
> Also, you need to export your schematic tab as a PDF (in the schematic tab go to [File > Export > PDF](https://docs.easyeda.com/en/Export/Export-Schematic/index.html)), and upload that.

**Pull request closed without merging**
