### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by reyanshsharma0**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Reyansh LED Matrix:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/845993cbad0557394bc865e4a851cc19e978fd95/projects/Reyansh LED Matrix/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/845993cbad0557394bc865e4a851cc19e978fd95/projects/Reyansh LED Matrix/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/845993cbad0557394bc865e4a851cc19e978fd95/projects/Reyansh LED Matrix/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by maxwofford — APPROVED** [review]
This looks awesome! I've never worked with 4-layer boards and I'm curious how this comes out. Send pictures once it ships! I just [sent your grant](https://hcb.hackclub.com/grants/qerIoe)

**Comment by reyanshsharma0** [comment]
eyyy thank you so much!!! :D

I have also worked on the 4 layer pcb for the first time but I had to do it anyway here because there was literally no way I could route all of it on a 2 Layer PCB lol.

**Comment by maxwofford** [comment]
Yeah, that makes sense. I think that's the most individual components we've had on an OnBoard submission so far!

**Pull request merged**
