### PR TITLE
Check list

### PR DESCRIPTION
**Pull request by KrauseOlly**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  Cannot find a Gerber File

  Happy OnBoarding!

**Comment by KrauseOlly** [comment]
Not sure why this is saying unsuccessful when I download them from the Github everything seems to be there https://github.com/KrauseOlly/OnBoard/raw/main/projects/GPS%20Tracker%20for%20GOKART/Stuff.zip

**Review by maxwofford — APPROVED** [review]
Your student verification is approved!

**Comment by karmanyaahm** [comment]
> Not sure why this is saying unsuccessful when I download them from the Github everything seems to be there https://github.com/KrauseOlly/OnBoard/raw/main/projects/GPS%20Tracker%20for%20GOKART/Stuff.zip

@KrauseOlly it's because the gerber file is supposed to be called 'gerber.zip', but it's not a big problem, I'll fix it.

**Comment by KrauseOlly** [comment]
> > Not sure why this is saying unsuccessful when I download them from the Github everything seems to be there https://github.com/KrauseOlly/OnBoard/raw/main/projects/GPS%20Tracker%20for%20GOKART/Stuff.zip
> 
> @KrauseOlly it's because the gerber file is supposed to be called 'gerber.zip', but it's not a big problem, I'll fix it.

thank you :)

**Review by karmanyaahm — APPROVED** [review]
Very cool idea! LGTM. just to confirm, you have not selected pcb assembly and will solder the parts yourself?

**Comment by KrauseOlly** [comment]
> Very cool idea! LGTM. just to confirm, you have not selected pcb assembly and will solder the parts yourself?

yep I already have all the parts as I've built a prototype on a breadboard, so once I get the pcb I will be able to test it properly on the track

**Comment by karmanyaahm** [comment]
Sounds good, you should get an email with your grant in a couple of days!

**Comment by KrauseOlly** [comment]
> Sounds good, you should get an email with your grant in a couple of days!

Thanks looking forward to being one step closer before being able to use this thing :)

**Comment by maxwofford** [comment]
Just [sent!](https://hcb.hackclub.com/grants/qVMIeL)

**Pull request merged**
