### PR TITLE
Juan Zarco's PCB Business Card

### PR DESCRIPTION
**Pull request by Scrlpter**
## Submission Checklist:

- [ X] I am a current high school, middle school, or home schooled student.
  - [ X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ X] I made this board from scratch, even if I followed a tutorial
- [ X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ X] Created a folder under `onboard/projects`
  - [ X] Filled out `TEMPLATE.md` as `README.md`
  - [ X] Uploaded Gerber.zip and Schematic.pdf
  - [ X] Created a folder called `src` and uploaded design files
  - [ X] Uploaded screenshot of PCB order with all costs included
  - [ X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
@Scrlpter I haven't seen a student verification submitted so I can't merge this yet!

**Comment by BrightTheBackpack** [comment]
Just an fyi, your images are on the top layer, which means that they are part of the copper traces. This won't cause any issues, other than it might not look how you want it to look. I would suggest moving those to the TopSilkLayer

**Comment by Scrlpter** [comment]
Hey I appreciate the feedback, I would like to see how the layer affects the images so that I can make my diy board look the best it can!Sent from my iPhoneOn Mar 6, 2024, at 6:09 PM, BrightTheBackpack ***@***.***> wrote:﻿
Just an fyi, your images are on the top layer, which means that they are part of the copper traces. This won't cause any issues, other than it might not look how you want it to look. I would suggest moving those to the TopSilkLayer

**Comment by BrightTheBackpack** [comment]
Current:
current

With Silkscreen: 
image

**Comment by maxwofford** [comment]
@Scrlpter can you comment here once you fill out the student [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form). I see it checked off in your PR description, but I don't see it submitted on my end.

**Comment by Scrlpter** [comment]
I see the difference it makes, I changed the design to have the pokemon
TopSilkLayer, will i have to change the gerber file on the PR?

**Comment by Scrlpter** [comment]
> @Scrlpter can you comment here once you fill out the student [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form). I see it checked off in your PR description, but I don't see it submitted on my end.

I have submitted the form, I did it a couple days ago also but hopefully this one gets through!

**Comment by karmanyaahm** [comment]
Your design and student verification look good to me! Emailing grant now!

**Comment by karmanyaahm** [comment]
Do send pictures of your card in #onboard on slack when you get it!

**Pull request merged**
