### PR TITLE
Added Brain Hat

### PR DESCRIPTION
**Pull request by AverseABFun**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 21606. This is separate and unfortunately the team may no longer exist this year.

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/BrainHat:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
I can't seem to find an entry on your github username in our Airtable, have you done our verification form?

**Comment by AverseABFun** [comment]
Hm, it's been a while but yes. I guess I reached the auto-erase time. The main problem is my school year is starting tomorrow so I don't have a student ID yet. I'm guessing a school schedule wouldn't work? Although I do still have the onboard card, https://hcb.hackclub.com/grants/XgkIeP if you can view it

**Comment by blazecoding2009** [comment]
> @blazecoding2009 Hm, it's been a while but yes. I guess I reached the auto-erase time. The main problem is my school year is starting tomorrow so I don't have a student ID yet. I'm guessing a school schedule wouldn't work? Although I do still have the onboard card, https://hcb.hackclub.com/grants/XgkIeP if you can view it

Ah no worries, I just needed to find your previous grant via your email address. You already have been given your full $100 grant. See if you can lower the price of your PCB by either selecting cheaper components or if possible, slower shipping. Let me know if you need any more help!

**Comment by AverseABFun** [comment]
> > @blazecoding2009 Hm, it's been a while but yes. I guess I reached the auto-erase time. The main problem is my school year is starting tomorrow so I don't have a student ID yet. I'm guessing a school schedule wouldn't work? Although I do still have the onboard card, https://hcb.hackclub.com/grants/XgkIeP if you can view it
> 
> Ah no worries, I just needed to find your previous grant via your email address. You already have been given your full $100 grant. See if you can lower the price of your PCB by either selecting cheaper components or if possible, slower shipping. Let me know if you need any more help!

The main issue is extended components. The components themselves are reasonably cheap, but the extended components thing is messing with me. Also, the AD8232 ECG chip is not commonly used as EEG/ECGs are not designed very often(citation needed). Overall there just isn't much I can do and the PCB is only two dollars anyway, and I don't have the necessary tools to use a stencil(and it sounds like a pain given that almost all of the components are SMT).

**Comment by blazecoding2009** [comment]
> > > @blazecoding2009 Hm, it's been a while but yes. I guess I reached the auto-erase time. The main problem is my school year is starting tomorrow so I don't have a student ID yet. I'm guessing a school schedule wouldn't work? Although I do still have the onboard card, https://hcb.hackclub.com/grants/XgkIeP if you can view it
> > 
> > 
> > Ah no worries, I just needed to find your previous grant via your email address. You already have been given your full $100 grant. See if you can lower the price of your PCB by either selecting cheaper components or if possible, slower shipping. Let me know if you need any more help!
> 
> The main issue is extended components. The components themselves are reasonably cheap, but the extended components thing is messing with me. Also, the AD8232 ECG chip is not commonly used as EEG/ECGs are not designed very often(citation needed). Overall there just isn't much I can do and the PCB is only two dollars anyway, and I don't have the necessary tools to use a stencil(and it sounds like a pain given that almost all of the components are SMT).

I see, are you able to donate to the onboard HCB? I can top off your grant with the amount you donate.

**Comment by AverseABFun** [comment]
> > > > @blazecoding2009 Hm, it's been a while but yes. I guess I reached the auto-erase time. The main problem is my school year is starting tomorrow so I don't have a student ID yet. I'm guessing a school schedule wouldn't work? Although I do still have the onboard card, https://hcb.hackclub.com/grants/XgkIeP if you can view it
> > > 
> > > 
> > > Ah no worries, I just needed to find your previous grant via your email address. You already have been given your full $100 grant. See if you can lower the price of your PCB by either selecting cheaper components or if possible, slower shipping. Let me know if you need any more help!
> > 
> > 
> > The main issue is extended components. The components themselves are reasonably cheap, but the extended components thing is messing with me. Also, the AD8232 ECG chip is not commonly used as EEG/ECGs are not designed very often(citation needed). Overall there just isn't much I can do and the PCB is only two dollars anyway, and I don't have the necessary tools to use a stencil(and it sounds like a pain given that almost all of the components are SMT).
> 
> I see, are you able to donate to the onboard HCB? I can top off your grant with the amount you donate.

I don't need any more, I have $3.02 extra remaining if I buy it.

**Review by blazecoding2009 — APPROVED** [review]
Sounds good! Merging

**Pull request merged**
