### PR TITLE
HLPCB 

### PR DESCRIPTION
**Pull request by HudsonL213**
## Submission Checklist:

- [ Y] I am a current high school, middle school, or home schooled student.
  - [Y ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Y ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [Y ] I made this board from scratch, even if I followed a tutorial
- [Y ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ Y] Created a folder under `onboard/projects`
  - [Y ] Filled out `TEMPLATE.md` as `README.md`
  - [ Y] Uploaded Gerber, sources, and schematic
  - [ Y] Uploaded screenshot of PCB order with all costs included
  - [ Y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ Y] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ Y] (Optional) This project is from a tutorial[^1].
- [N ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by Hugoyhu — CHANGES_REQUESTED** [review]
Hi! Could you please submit the .json files for your PCB and schematic into a /src folder in this directory? Thank you.

**Comment by HudsonL213** [comment]
> Hi! Could you please submit the .json files for your PCB and schematic into a /src folder in this directory? Thank you.

Sorry about that I have added the file to the file, Im pretty sure I did it correctly but I'm not positive. Please let me know if y'all need anything else

**Comment by Hugoyhu** [comment]
Hi! You uploaded the PCB .json, thank you: could you also upload the schematic .json? thank you!

**Comment by HudsonL213** [comment]
> Hi! You uploaded the PCB .json, thank you: could you also upload the schematic .json? thank you!

once again sorry iv uploaded the schematic file, please let me know if yall need anything else

**Review by Hugoyhu — CHANGES_REQUESTED** [review]
The coil antenna seems a bit too close to the edge. Attached are current and proposed. 

Screenshot 2024-01-22 at 7 54 01 PM
Screenshot 2024-01-22 at 7 53 36 PM


Additional note. Your .json files are currently in the main directory: they should be in a folder named "src" inside your project folder. The directory should be: projects/HLPCB/...

**Review by Hugoyhu — APPROVED** [review]
Design looks OK to me. Approved pending student verification!

**Comment by HudsonL213** [comment]
> Design looks OK to me. Approved pending student verification!

Thanks for all your help and please let me know if you need anything else

**Review by sarthaktexas — APPROVED** [review]
Approving student verification!

**Comment by karmanyaahm** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/5353ba57eacd159b34b12bdda9e8dc8422cec361/projects/HLPCB/Gerber_PCB_First (3).zip>)!

  Happy OnBoarding!

**Comment by HudsonL213** [comment]
> Hi, I'm Orpheus Leap! Here to help you review your PR.
> You can view a render of your board over on [tracespace.io](https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/5353ba57eacd159b34b12bdda9e8dc8422cec361/projects/HLPCB/Gerber_PCB_First%20(3).zip)!
> 
> Happy OnBoarding!

Thank you so much for all yall's help and I'm looking forward to designing more boards

**Comment by HudsonL213** [comment]
And I'm just wonder what are the next steps for me to get the PCB.

**Review by karmanyaahm — APPROVED** [review]
LGTM!

**Comment by karmanyaahm** [comment]
@sarthaktexas will send you an email with your grant card in 24-48 hours!

**Comment by sarthaktexas** [comment]
sent!

**Pull request merged**
