### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by GeckoK**
## Submission Checklist:

- [X ] I am a current high school, middle school, or home schooled student.
  - [X ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X ] I made this board from scratch, even if I followed a tutorial
- [ X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ X] Created a folder under `onboard/projects`
  - [ X] Filled out `TEMPLATE.md` as `README.md`
  - [X ] Uploaded Gerber.zip and Schematic.pdf
  - [X ] Created a folder called `src` and uploaded design files
  - [ X] Uploaded screenshot of PCB order with all costs included
  - [ X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Hi @GeckoK! 

In your "src" folder, please put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
see above

**Comment by karmanyaahm** [comment]
Also can you please submit your student verification with either your digicard or just a plain ID without any writing on it

**Comment by karmanyaahm** [comment]
Hey @GeckoK! Can you submit just your ID again to [the verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)

**Comment by GeckoK** [comment]
Done :)

Karmanyaah Malhotra ***@***.***> schrieb am Di. 9. Apr. 2024
um 00:53:

**Comment by karmanyaahm** [comment]
Oops I'm so sorry I just saw this

**Comment by karmanyaahm** [comment]
Hi @GeckoK!
I've just sent you [your grant](https://hcb.hackclub.com/grants/XRGIB9) for OnBoard. You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.**

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
