### PR TITLE
Xavier Hack Card NFC

### PR DESCRIPTION
**Pull request by Electric534093**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) This project is for [Trick or Trace](https://showcase.hackclub.com/)[^3].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Pegoku** [comment]
Hi, I see you have 2 README.md, could you please remove the extra file? Thanks.

**Comment by Electric534093** [comment]
Yep! i cant seem to find the project folder though... Do you know how i could fix that?

**Comment by Electric534093** [comment]
@Pegoku I think I removed it then.

**Comment by Pegoku** [comment]
Hi, please continue the checkout process

**Comment by Electric534093** [comment]
What do i do for the payment?

________________________________

**Comment by Electric534093** [comment]
[cid:8b94703c-a9e3-45e9-801b-fc5005cd5777]This good?

________________________________

**Comment by Pegoku** [comment]
Can't see the image, answer via the gh website. Also, upload it to the repo.

**Comment by Electric534093** [comment]
Screenshot 2024-11-05 092017

**Comment by Electric534093** [comment]
> Screenshot 2024-11-05 092017

i cant find my repo to post it

**Comment by Electric534093** [comment]
I don't have any orders in my history because I haven't been able to pay, so I don't know how to finish the order
________________________________

**Comment by Electric534093** [comment]
nvm I found it, thanks
Here is the screenshot, can you please post it for me?
[cid:355bdaad-a761-45e3-a572-53306be675f4]
________________________________

**Comment by Electric534093** [comment]
maybe this might be better
Screenshot 2024-11-10 172902

**Comment by Electric534093** [comment]
[like]  Xavier Butler reacted to your message:
________________________________

**Comment by Pegoku** [comment]
Yes, this is correct. Can you upload it to the gh?

**Comment by Electric534093** [comment]
I cant post it, is there a way I can get you to post it?
________________________________

**Comment by Pegoku** [comment]
yes, I'll try to upload it for you

**Comment by Pegoku** [comment]
Also (recommend) you try to move the capacitor closer to the NFC IC. It probably should still work, but I recommend you to do it just to be safe.

**Comment by Pegoku** [comment]
it's just a suggestion, if don't want to do it, don't need to. It'll prob work fine

**Comment by Electric534093** [comment]
okay! I'll maybe take a pass, but thanks so much for the advice! anything else i need to do?

**Comment by Pegoku** [comment]
No, that should be it.

**Comment by Pegoku** [comment]
Hi @Electric534093    !

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/oQI8Jx). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please keep this in mind before you make any purchases.** More info in the OnBoard community shipping doc.

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
