### PR TITLE
Nat3z's 65% Keyboard

### PR DESCRIPTION
**Pull request by Nat3z**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Nat3z_65_Keyboard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/4aab779423a77da4bec9a7a9e18214e3313dc6a7/projects/Nat3z_65_Keyboard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/4aab779423a77da4bec9a7a9e18214e3313dc6a7/projects/Nat3z_65_Keyboard/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/4aab779423a77da4bec9a7a9e18214e3313dc6a7/projects/Nat3z_65_Keyboard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Nat3z** [comment]
Update:
So the price was a lie, I didn’t check shipping yet:

$93.82 total (wow)

**Comment by Nat3z** [comment]
This is the final edit to the pcb and the final price, sorry for editing it so much in PR.

**Review by maxwofford — APPROVED** [review]
Nice work on this, thanks for linking the resources– I bet others will find that really helpful for making their own keyboards. I just [sent the grant](https://hcb.hackclub.com/grants/vA5IzB)

**Pull request merged**
