### PR TITLE
LED Moon PCB

### PR DESCRIPTION
**Pull request by selenejq**
## Submission Checklist:

- [ ✅] I am a current high school, middle school, or home schooled student.
  - [✅ ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ ✅] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ ✅] I made this board from scratch, even if I followed a tutorial
- [ ✅] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [✅ ] Created a folder under `onboard/projects`
  - [ ✅] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ ✅] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ ✅] Created a folder called `src` and uploaded design files
  - [ ✅] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [✅ ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [✅ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/moonPCB:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by abitchinmorewaysthanone** [comment]
This design is so pretty! Your engineering looks good but your submission has several issues.

1. You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order up to 5 assembled boards.

2. Please rename Schematic_Moon.pdf to schematic.pdf and place both .json files in a folder projects/moonPCB/src/.

your board looks excellent! I love to see the more artistic submissions. Please post any more questions in the OnBoard slack channel.

**Review by abitchinmorewaysthanone — CHANGES_REQUESTED** [review]
This design is so pretty! Your engineering looks good but your submission has several issues.

1. You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order up to 5 assembled boards.

2. Please rename Schematic_Moon.pdf to schematic.pdf and place both .json files in a folder projects/moonPCB/src/.

your board looks excellent! I love to see the more artistic submissions. Please post any more questions in the OnBoard slack channel.

**Comment by abitchinmorewaysthanone** [comment]
I am going to close this PR for cleanup but please ask for help in the #electronics channel in Slack if you need it! Your board is beautiful!

**Pull request closed without merging**
