### PR TITLE
Add Elin's PCB business card

### PR DESCRIPTION
**Pull request by elinzhang507**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/projects/Elin's PCB business card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/c7222472ebdb7ea2338607e61240e29edcdd21f1/projects/projects/Elin's PCB business card/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/c7222472ebdb7ea2338607e61240e29edcdd21f1/projects/projects/Elin's PCB business card/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/c7222472ebdb7ea2338607e61240e29edcdd21f1/projects/projects/Elin's PCB business card/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by elinzhang507** [comment]
I forgot to add "submission" label and not sure how to change it

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @elinzhang507,

Thanks for submitting your PCB PR for OnBoard! However, it looks like you took a picture of your cart instead of completing the checkout process. To ensure your order gets processed correctly, please follow the steps in [this](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) guide or in here:


1. Click "Secure Checkout": After adding your PCB to the cart, make sure to click "Secure Checkout."
2. Enter your shipping information: Fill in your shipping details as prompted.
3. Take a screenshot of your unpaid order: Once you reach the final page before payment, take a screenshot of this page. It should show all the details of your order.


Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will help us review your order more effectively. Congrats on making the PCB though!

**Comment by elinzhang507** [comment]
> Hi @elinzhang507,
> 
> Thanks for submitting your PCB PR for OnBoard! However, it looks like you took a picture of your cart instead of completing the checkout process. To ensure your order gets processed correctly, please follow the steps in [this](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) guide or in here:
> 
> 1. Click "Secure Checkout": After adding your PCB to the cart, make sure to click "Secure Checkout."
> 2. Enter your shipping information: Fill in your shipping details as prompted.
> 3. Take a screenshot of your unpaid order: Once you reach the final page before payment, take a screenshot of this page. It should show all the details of your order.
> 
> Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will help us review your order more effectively. Congrats on making the PCB though!

Thank you for the review! I have decided to make more changes to my card so I'll issue a new pr and this time I'll screenshot the correct cart

**Comment by LimesKey** [comment]
I'll close this pull request for you then

**Pull request closed without merging**
