### PR TITLE
Saran W's PCB Pull Request

### PR DESCRIPTION
**Pull request by glitchyfuzzy**
## Submission Checklist:

- [ X] I am a current high school, middle school, or home schooled student.
  - [X ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ X] I made this board from scratch, even if I followed a tutorial
- [X ] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [X ] Created a folder under `onboard/projects`
  - [ X] Filled out `TEMPLATE.md` as `README.md`
  - [X ] Uploaded Gerber, sources, and schematic
  - [ X] Uploaded screenshot of PCB order with all costs included
  - [X ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X ] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi! Please make a "src" folder in projects/saranPCBBoard/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab. Also if you'd like you can get 5 cards assembled, not just the 2.

**Comment by glitchyfuzzy** [comment]
It should be fixed now

**Review by karmanyaahm — APPROVED** [review]
LGTM!

**Comment by karmanyaahm** [comment]
Merged because @glitchyfuzzy was already approved by Daisy in #235, but @sarthaktexas the grant still needs to be sent. @glitchyfuzzy You should get an email with your grant card in 24-48 hours!

**Comment by sarthaktexas** [comment]
sent!

**Pull request merged**
