### PR TITLE
Request for "Rocket Airbrake Avionic PCB"

### PR DESCRIPTION
**Pull request by fhwolff**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Hi Finn! This is a realllllly cool board! I was also part of a TARC team last year and although I mostly just helped around it was a really fascinating experience!

I think your $96 price doesn't include shipping. With shipping, your board might go over the $100 grant limit. Can you please go through [these few steps](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#cart) and post the final final cart image? (it should include shipping and you will probably have some JLCPCB coupons if you're new to them)

If it goes over you can post your design in #onboard on Slack (specifically the screen where JLCPCB lists all parts and prices of each part), or you could cover the difference.

**Comment by karmanyaahm** [comment]
Other than that, your design looks great to me and your student verification is approved.

**Comment by fhwolff** [comment]
Hi Karmanyaah!
Yes, let me get the photo of the final checkout for you. I'm planning to
cover the additional costs as JLCPCB is currently out of stock of
barometric pressure sensors, and I need to pre order those as well, which
was not included in the PCB order. That's really cool to hear that you were
also part of a TARC team, I really do love the process of making rockets
and the whole competition.
[image: cart.png]
Thanks so much for letting me know about sending the wrong photo, this
grant really helps me out. I've had this PCB sitting in my EasyEDA library
for quite some time, and I've just been waiting to order it, and this grant
was what got me to.

**Comment by karmanyaahm** [comment]
image
I think you tried to attach an image but it's not showing up on github, can you comment directly on github?

**Comment by fhwolff** [comment]
Ok I did just that, it should be there. Let me know if it isn't showing up.
Thank you!

**Comment by JoseMoranUrena523** [comment]
wow!

**Comment by fhwolff** [comment]
Thank you! I’m very proud of this board and I’m really happy I’ll be able
to see it constructed!

**Comment by karmanyaahm** [comment]
Merging and will DM on Slack to cover the excess amount

**Comment by karmanyaahm** [comment]
Hi Finn!
~~I've just sent you your grant for OnBoard. You should have received an invite in your email.~~ There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.**

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #onboard channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by karmanyaahm** [comment]
Grant [sent](https://hcb.hackclub.com/grants/qWPIxl)!

**Pull request merged**
