### PR TITLE
Angelaisthr usbhub

### PR DESCRIPTION
**Pull request by angelaisthr**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ ] Created a folder under `onboard/projects`
  - [ ] Filled out `TEMPLATE.md` as `README.md`
  - [ ] Uploaded Gerber.zip and Schematic.pdf
  - [ ] Created a folder called `src` and uploaded design files
  - [ ] Uploaded screenshot of PCB order with all costs included
  - [ ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @angelaisthr, your gerber.zip should be a ZIP file instead of a folder!

**Comment by maxwofford** [comment]
@angelaisthr heads up, this deleted the `README.md` for OnBoard. Can you remove that change?

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @angelaisthr it looks like your order is a bit pricey– the grant for usb-hubs are $50 & your order is a little over $80. I think you can save by changing the components you're using. If you need help cutting the cost down you can post your design in the #electronics channel in the Slack.

**Review by maxwofford — APPROVED** [review]
Wow, that redesign really cut down on the cost! I just [sent your grant out](https://hcb.hackclub.com/grants/XOWILK), good luck with manufacturing!

**Pull request merged**
