### PR TITLE
FIX: Remove wording of Hack Club Bank and rewrite a bit to make it better

### PR DESCRIPTION
**Pull request by mickeydarrenlau**
Removes all mentions to Hack Club Bank

### CODE REVIEW

**Review by LimesKey — CHANGES_REQUESTED** [review]
I don't see how this is helpful or relevant to anything? The "grant account" is a Hack Club Bank account and we want to make that clear.

**Comment by mickeydarrenlau** [comment]
Hack Club Bank is not allowed because hcb cannot call themselve a bank

**Comment by mickeydarrenlau** [comment]
And also it's a shared backed account 
Not a personal bank account

**Review by LimesKey — APPROVED** [review]
I did not know this, thank you for your pull request.

**Pull request merged**
