### PR TITLE
Making a project - Cool NFC card

### PR DESCRIPTION
**Pull request by 0day-Yash**
## Submission Checklist:

- [ X] I am a current high school, middle school, or home schooled student.
  - [X ] I am 18 or under
  - [ X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [ X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ X] I made this board from scratch, even if I followed a tutorial
- [X ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X ] Created a folder under `onboard/projects`
  - [X ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X ] Created a folder called `src` and uploaded design files
  - [X ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/CoolNFCcard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi, you've selected Standard Assembly, this is very costly and normally not required, are you able to use economic assembly instead?

**Comment by 0day-Yash** [comment]
> Hi, you've selected Standard Assembly, this is very costly and normally not required, are you able to use economic assembly instead?

Yeah of course, thats no problem!

**Comment by LimesKey** [comment]
Great, just upload the new cart.png. Also make sure you go through the order process and click "Secure Checkout".

**Comment by 0day-Yash** [comment]
> Great, just upload the new cart.png. Also make sure you go through the order process and click "Secure Checkout".

Okay I've done the required changes, also, ive uploaded the second screenshot of 'secure checkout' page, and named it as cart2.png.

**Comment by LimesKey** [comment]
It looks like you're still trying to purchase the unassembled PCB as well as the assembled PCB, can you remove the bottom PCB that is 2$ from your cart?

**Comment by 0day-Yash** [comment]
> It looks like you're still trying to purchase the unassembled PCB as well as the assembled PCB, can you remove the bottom PCB that is 2$ from your cart?

Oh yeah sorry, its my first time ordering one. I'll remove that right away

**Comment by 0day-Yash** [comment]
@LimesKey ?

**Review by LimesKey — CHANGES_REQUESTED** [review]
it looks like you took a picture of your cart rather than the completed unpaid order.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to the [JLCPCB Order page](https://jlcpcb.com/user-center/orders/), then take a rectangular screenshot of the PCB you just submitted. It should show all the details of your order including the price and assembly.

This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congratulations on making the PCB! Please ask in [#electronics](https://slack.com/archives/C056AMWSFKJ) in the [Slack](https://hackclub.com/slack/) if you need any further help.

**Comment by 0day-Yash** [comment]
Just fixed that, pls have a look when you can @LimesKey

**Comment by LimesKey** [comment]
Your bridging a few nets, is this intentional? If not or you're not sure, are you able to ask somebody in the Slack in the #electronics channel to look over it?
image

**Comment by 0day-Yash** [comment]
Sure, I'll do that

**Pull request closed without merging**
