### PR TITLE
add "PROFESIONNAL_WEB_CARD" board

### PR DESCRIPTION
**Pull request by wllm-lhy**
## Submission Checklist:

- [x ] I am a current high school, middle school, or home schooled student.
  - [x ] I am 18 or under
  - [x ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ x] I made this board from scratch, even if I followed a tutorial
- [x ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x ] Created a folder under `onboard/projects`
  - [x ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x ] Created a folder called `src` and uploaded design files
  - [x ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/PROFESIONNAL_WEB_CARD:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Willm-Lhy** [comment]
im going to reupload the gerber file with the right name and my cart.png is a screenshot of my cart so i won't send a new one. the other png shows in detail the taxes and shipping

**Review by Willm-Lhy — COMMENTED** [review]
[gerber.zip](https://github.com/user-attachments/files/16338879/gerber.zip)

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hi @wllm-lhy,

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by wllm-lhy** [comment]
hi!
sorry for the mistake, here is the right picture
cart

**Review by LimesKey — CHANGES_REQUESTED** [review]
Looks good but is there any way you can get a cheaper shipping option? If not that's okay.

**Comment by wllm-lhy** [comment]
I can try to get it shipped to some family in the US, I'll reply when I have an answer and ask a review

**Comment by wllm-lhy** [comment]
I'll send a photo of the new cart as soon as I can (and yes the prices are in USD$)

**Comment by wllm-lhy** [comment]
okay! i'm now going to send it to some family in the USA so here is the new cart. there is no hyper-expensive shipping cost now.
cart

**Comment by LimesKey** [comment]
Oh, you didn't need to do that if it was too much trouble, do you want to do the one where you ship it to USA? We can do the more expensive one, it's your grant, but I would have just suggested if there was a cheaper shipping option so you would have funds for other PCBs.

**Comment by wllm-lhy** [comment]
Oh well  it's okay @LimesKey I'm going to take the option where I ship to the US if it's okay with you.

**Comment by LimesKey** [comment]
That's great! I'm having trouble finding your [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form), are you sure you submitted it with your correct GitHub username?

**Comment by wllm-lhy** [comment]
Oh @LimesKey I'm sorry, I changed my username in between without thinking. My old username was Willm-lhy and not Willm-lhy.
Try with **Willm-lhy**.

**Comment by wllm-lhy** [comment]
Oh @LimesKey I'm sorry, I changed my username in between without thinking. My old username was Willm-lhy and not Willm-lhy.
Try with **Willm-lhy**.

**Comment by wllm-lhy** [comment]
Here is a picture of my confirmation email

**Review by LimesKey — APPROVED** [review]
Hi @wllm-lhy!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/qKbIxz). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by wllm-lhy** [comment]
Perfect thanks a lot! I uploaded my receipt on the card site. I can't wait to receive it!!

**Pull request merged**
