### PR TITLE
!!davidgoliath-pcb-nfc-hackercard

### PR DESCRIPTION
**Pull request by itskme**
## Submission Checklist:

- [ Y] I am a current high school, middle school, or home schooled student.
  - [ Y] I am 18 or under
  - [ Y] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ Y] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [Y ] I made this board from scratch, even if I followed a tutorial
- [ Y] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ Y] Created a folder under `onboard/projects`
  - [Y ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [Y ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ Y] Created a folder called `src` and uploaded design files
  - [ Y] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ Y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ Y] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [Y ] (Optional) This project is from a tutorial[^1].
- [ N] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/!!davidgoliath-nfc-card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/7a00c3925e664759fa3a88aa3921fb2586c1a9a2/projects/!!davidgoliath-nfc-card/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/7a00c3925e664759fa3a88aa3921fb2586c1a9a2/projects/!!davidgoliath-nfc-card/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/7a00c3925e664759fa3a88aa3921fb2586c1a9a2/projects/!!davidgoliath-nfc-card/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by blazecoding2009** [comment]
Hey @itskme 

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by itskme** [comment]
hi, hopefully I have done it correctly this time...

**Comment by blazecoding2009** [comment]
Hey
Please do  your verification form

**Comment by itskme** [comment]
> Hey Please do your verification form

I am already verified in the slack

**Comment by itskme** [comment]
> That doesn't matter, please do the form. https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form

Form done

**Comment by blazecoding2009** [comment]
IT doesn't seem that you've uploaded any ID, would you mind redoing the form?

**Comment by itskme** [comment]
> IT doesn't seem that you've uploaded any ID, would you mind redoing the form?

it says it isn't required if you're already verified. I dont want to find them again.

**Comment by blazecoding2009** [comment]
The issue is that you are not verified within our system, We're still merging arcade and onboard's databases and it will take some time for that to happen.

**Comment by itskme** [comment]
proof-of-minor
I cannot get my official papers. Refer to this screenshot or better yet [this](https://hackclub.slack.com/archives/C01504DCLVD/p1723530252091289?thread_ts=1723390730.267229&cid=C01504DCLVD) thread where I got approval. You can follow the github link to see it is me.

**Review by blazecoding2009 — APPROVED** [review]
Hey @itskme 

I've just sent your [grant](https://hcb.hackclub.com/grants/XyWInQ)!

**Comment by itskme** [comment]
Thanks blaze 👍👊



Sent from my Galaxy



-------- Original message --------
From: blaze ***@***.***>
Date: 2024-08-17 12:34 a.m. (GMT-05:00)
To: hackclub/OnBoard ***@***.***>
Cc: itskme ***@***.***>, Mention ***@***.***>
Subject: Re: [hackclub/OnBoard] !!davidgoliath-pcb-nfc-hackercard (PR #988)


@blazecoding2009 approved this pull request.

Hey @itskme<https://github.com/itskme>

I've just sent your grant<https://hcb.hackclub.com/grants/XyWInQ>!

**Pull request merged**
