### PR TITLE
BENS USB HUB

### PR DESCRIPTION
**Pull request by 2008wbbv**
## Submission Checklist:

- [ x] I am a current high school, middle school, or home schooled student.
  - [ x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ x] I made this board from scratch, even if I followed a tutorial
- [ x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x ] Created a folder under `onboard/projects`
  - [x ] Filled out `TEMPLATE.md` as `README.md`
  - [ x] Uploaded Gerber, sources, and schematic
  - [x ] Uploaded screenshot of PCB order with all costs included
  - [x ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @2008wbbv, it's awesome to see how much cheaper your USB hub is than mine, great work with changing the shape!

It looks like something happened on your upload and this is missing a couple files. Could you upload all the missing files on your card project and the schematic.pdf part of the usb hub?

**Comment by 2008wbbv** [comment]
What's missing other than the schematic? I put that in when i get the chance.

**Comment by maxwofford** [comment]
@2008wbbv oh, looks like all the files are there now! Our script just isn't detecting them because of the filenames. Could you rename them to:

- screenshot.png
- gerber.zip
- bom.csv
- pickandplace.csv
- schematic.pdf

**Comment by maxwofford** [comment]
@sarthaktexas is this approved on the HCB side?

**Review by sarthaktexas — APPROVED** [review]
Ben has been approved before! Thanks for submitting another PR :)

**Comment by 2008wbbv** [comment]
renamed.

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
~~sorry for taking over your PR max~~
It's awesome to see you submitting another project Ben! Since the last time you submitted we've started requiring some additional files, I've renamed all the ones you've already posted to the right names.

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Please make a "src" folder in projects/BENS NEW CARD/ and projects/BENS USB HUB/, and put your project sources there. They should be two .JSON files for each project, one from the schematic tab, one from the PCB tab. They look something like PCB.....name...json and SCH_SCH.....name....json

**Comment by 2008wbbv** [comment]
I had that project backed up, the other one, the usb hub I didnt because I was on a guest account, and for opsec reasons I delete cookies every 12 hours, so I longer have those source files.

**Review by karmanyaahm — APPROVED** [review]
Sounds good, thanks

**Pull request merged**
