### PR TITLE
USB hub

### PR DESCRIPTION
**Pull request by manifhlow**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Found multiple files named README.md. Please only provide one per PR. Make seperate PRs for multiple independent projects.
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @manifhlow 

Looks like you have 2 projects in here, please remove one and reupload and create a new PR once this has been approved

**Comment by manifhlow** [comment]
> Hey @manifhlow
> 
> Looks like you have 2 projects in here, please remove one and reupload and create a new PR once this has been approved

can you help me and tell me what i should do?

**Comment by blazecoding2009** [comment]
> > Hey @manifhlow
> > Looks like you have 2 projects in here, please remove one and reupload and create a new PR once this has been approved
> 
> can you help me and tell me what i should do?

Just delete one of the project folders

**Comment by manifhlow** [comment]
> > > Hey @manifhlow
> > > Looks like you have 2 projects in here, please remove one and reupload and create a new PR once this has been approved
> > 
> > 
> > can you help me and tell me what i should do?
> 
> Just delete one of the project folders

the project folder wont let me delete my pcbcard image

**Comment by blazecoding2009** [comment]
> > > > Hey @manifhlow
> > > > Looks like you have 2 projects in here, please remove one and reupload and create a new PR once this has been approved
> > > 
> > > 
> > > can you help me and tell me what i should do?
> > 
> > 
> > Just delete one of the project folders
> 
> the project folder wont let me delete my pcbcard image

You have to open it in github desktop and then you can delete the folder and push

**Comment by manifhlow** [comment]
> > > Hey @manifhlow
> > > Looks like you have 2 projects in here, please remove one and reupload and create a new PR once this has been approved
> > 
> > 
> > can you help me and tell me what i should do?
> 
> Just delete one of the project folders



> > > > Hey @manifhlow
> > > > Looks like you have 2 projects in here, please remove one and reupload and create a new PR once this has been approved
> > > 
> > > 
> > > can you help me and tell me what i should do?
> > 
> > 
> > Just delete one of the project folders
> 
> the project folder wont let me delete my pcbcard image
did



> > > > > Hey @manifhlow
> > > > > Looks like you have 2 projects in here, please remove one and reupload and create a new PR once this has been approved
> > > > 
> > > > 
> > > > can you help me and tell me what i should do?
> > > 
> > > 
> > > Just delete one of the project folders
> > 
> > 
> > the project folder wont let me delete my pcbcard image
> 
> You have to open it in github desktop and then you can delete the folder and push


> > > > > Hey @manifhlow
> > > > > Looks like you have 2 projects in here, please remove one and reupload and create a new PR once this has been approved
> > > > 
> > > > 
> > > > can you help me and tell me what i should do?
> > > 
> > > 
> > > Just delete one of the project folders
> > 
> > 
> > the project folder wont let me delete my pcbcard image
> 
> You have to open it in github desktop and then you can delete the folder and push

i deleted my cart.png in my pcb card, did i do it right?

**Comment by blazecoding2009** [comment]
Thats good, what shipping option have you selected? That is very expensive considering you live in Canada

**Comment by manifhlow** [comment]
> Thats good, what shipping option have you selected? That is very expensive considering you live in Canada

i think i did global standard something

**Comment by blazecoding2009** [comment]
> > Thats good, what shipping option have you selected? That is very expensive considering you live in Canada
> 
> i think i did global standard something

Global standard is not that expensive, can you show me all the options available?

**Comment by manifhlow** [comment]
> > > Thats good, what shipping option have you selected? That is very expensive considering you live in Canada
> > 
> > 
> > i think i did global standard something
> 
> Global standard is not that expensive, can you show me all the options available?

should i just resubmit my order one more time?

**Comment by manifhlow** [comment]
> > > > Thats good, what shipping option have you selected? That is very expensive considering you live in Canada
> > > 
> > > 
> > > i think i did global standard something
> > 
> > 
> > Global standard is not that expensive, can you show me all the options available?
> 
> should i just resubmit my order one more time?
i did global, its 61 dollars i think

**Comment by blazecoding2009** [comment]
We only offer $50 for tutorial based projects, are you able to get it a bit lower?

**Comment by manifhlow** [comment]
> We only offer $50 for tutorial based projects, are you able to get it a bit lower?

i think i can pay the rest, since i have left overs for my first pcb

**Review by blazecoding2009 — APPROVED** [review]
Sounds good, I've topped off your grant

**Pull request merged**
