### PR TITLE
My Project

### PR DESCRIPTION
**Pull request by FlipMods**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md`
  - [X] Uploaded Gerber.zip and Schematic.pdf
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Cassidy C's NFC Card PCB:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by FlipMods** [comment]
Finally finished the checks from merges and orpheus

**Comment by karmanyaahm** [comment]
Student verification is approved

**Comment by karmanyaahm** [comment]
Hi Cassidy! 

You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order 5 assembled boards.

**Comment by karmanyaahm** [comment]
Also ignore the bot about the source files, your files are good, that's another bug for me to fix.

**Comment by FlipMods** [comment]
Will Do In About An Hour Or Two

**Comment by FlipMods** [comment]
image Updated Cart Image

**Comment by maxwofford** [comment]
Grant [sent](https://hcb.hackclub.com/grants/vm3IN7)! Hope assembly goes well.

**Pull request merged**
