### PR TITLE
Jay's NFC Card

### PR DESCRIPTION
**Pull request by iUnstable0**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/8df2900a8abc340d88a583b54cc3d6c6b39c3784/projects/Jay's NFC Card/gerber.zip>)!

  Happy OnBoarding!

**Comment by BrightTheBackpack** [comment]
Potential wire impedance issues?

**Comment by iUnstable0** [comment]
?? how do you check that? i'm new to Pcb designn

**Comment by BrightTheBackpack** [comment]
Idk, i'm not sure if wire impedance will be an issue, just writing it down so the technical reviewer(who knows way more than me) can see if it's an issue

**Review by maxwofford — APPROVED** [review]
Your student verification is approved!

**Review by karmanyaahm — APPROVED** [review]
Your PR formatting looks great to me! But as bright was saying, it's possible that your antenna may or may not work given that the wires are so long. It'll very likely be fine, but if you want to be extra safe, I'd put the main IC right next to the antenna instead of far away. 

Your LED, resistor, and capacitor can be wherever you'd like on the board though.

I'm going to approve it, and your grant will be sent soon, but I'd recommend making the change.

**Comment by iUnstable0** [comment]
thank you!

**Comment by karmanyaahm** [comment]
Oh wait, I just saw this:
image
The squiggly designs in the back are on the copper layer, which means they will be wires. You probably want to put them in the silkscreen layer, so they're visibly printed with ink
Here, they are shorting all your wires together and so your board won't work because of that:
image
Please post in #onboard on slack if you want any clarification about this or DM me.

**Comment by iUnstable0** [comment]
wait, i thought they’re on the front?
CleanShot 2024-02-21 at 14 33 07@2x

**Comment by karmanyaahm** [comment]
It needs to be on front silkscreen

**Comment by maxwofford** [comment]
Know you're still getting it working, but I've got ahead and [issued the grant.](https://hcb.hackclub.com/grants/wPxIR2) Make sure to fix the change though so your wires will still work!

**Pull request merged**
