### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by codesbykrish**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x ] I made this board from scratch, even if I followed a tutorial
- [x ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ x] Created a folder called `src` and uploaded design files
  - [ x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/PCB_Hacker Card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/3d4626c86cd1e3f69c28ce52d43013f31d28a0c8/projects/PCB_Hacker Card/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/3d4626c86cd1e3f69c28ce52d43013f31d28a0c8/projects/PCB_Hacker Card/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/3d4626c86cd1e3f69c28ce52d43013f31d28a0c8/projects/PCB_Hacker Card/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by abitchinmorewaysthanone — CHANGES_REQUESTED** [review]
Dude, this is one of may favorite shows! I'm looking forward to seeing the card completed.

Unfortunately it doesn't seem like you've filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form). This is super super important!

Additionally, your readme.md is incomplete. Please add your github handle and your slack handle (you *do* have to [join Slack](https://hackclub.com/slack/?event=onboard)).

Finally, your screenshot of your cart should be a .png file, not a .jpg. We use a bot for some of the verification and it is picky.

I will merge your project & send you the grant after you have made these changes!

**Comment by abitchinmorewaysthanone** [comment]
Ok. You're so close.
Could you screenshot your cart BEFORE you fill out all the shipping details? So I can see the pcb printing and assembly prices individually. Also, it has to be a .png file.
Also, you do have to join [Slack](https://hackclub.com/slack/?event=onboard) so you can post your project and we can communicate with you.
After you do this I will send your grant!

**Comment by abitchinmorewaysthanone** [comment]
I'm closing this PR for cleanup. Please [join Slack](https://hackclub.com/slack/?event=onboard) and resubmit the PR when you are ready!

**Pull request closed without merging**
