### PR TITLE
Kai NFC Card

### PR DESCRIPTION
**Pull request by KaiEtkin**
## Submission Checklist:

- [ x] I am a current high school, middle school, or home schooled student.
  - [ x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ x] I made this board from scratch, even if I followed a tutorial
- [ x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x ] Created a folder under `onboard/projects`
  - [ x] Filled out `TEMPLATE.md` as `README.md`
  - [ x] Uploaded Gerber, sources, and schematic
  - [ x] Uploaded screenshot of PCB order with all costs included
  - [ x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by sarthaktexas — APPROVED** [review]
Howdy! I'm approving your student verification :) The next step will be to wait 24-48 hours for the technical review and then your PR will be merged and you'll receive your grant! [@hackclub/boarding-party](https://github.com/orgs/hackclub/teams/boarding-party)

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi! Sorry for the delay in reviewing. You need to make a couple of small changes and then we'll be good to go

- Please make a "src" folder in projects/[name]/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

- Also, you need to export your schematic tab as a PDF (in the schematic tab go to [File > Export > PDF](https://docs.easyeda.com/en/Export/Export-Schematic/index.html)), and upload that.

- Assuming you want to keep using the ENIG finish (which then requires standard assembly), you can contact @sarthaktexas on Slack about covering the difference from the $50 provided for jams once your PR is merged.

**Comment by Hugoyhu** [comment]
Hi Kai! A few major things I wanted to note and flag for revision.

On both the front: you have a logo and it's on the top copper layer. This means that it is currently shorting your entire design and it will _not_ work. You can change this to "silkscreen" layer ("TopSilkLayer") so it is no longer conductive / electrical. 

On the back: you have the text and QR code on the bottom copper layer. While there are no traces / circuits / whatever that this is shorting, it is generally recommended to keep the area under the coil antenna clear of any copper, to avoid signal interference. You should also change the text and QR code to silkscreen.

Once you're done correcting these issues, feel free to reply in the thread, or ping me on Slack (@Hugo Hu) to review your new design. Thank you and good night!

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
fyi the file format looks good to me, but please do what hugo said, otherwise your card won't work

**Comment by Hugoyhu** [comment]
Your design looks good to proceed. One quick note for purely visual purposes: 
Screenshot 2024-01-21 at 9 51 50 AM
Screenshot 2024-01-21 at 9 44 13 AM

Some of your part reference silkscreen labels cross the logo, so you might have a few little dots that you see on the logo. View images for reference. 

Otherwise, electrical is OK. Thanks for prompt re-sub!

**Review by Hugoyhu — APPROVED** [review]
PCB Routing is OK to me.

**Review by karmanyaahm — APPROVED** [review]

**Comment by karmanyaahm** [comment]
@sarthaktexas will send you an email with your grant card soon!

**Pull request merged**
