### PR TITLE
Add "HACKER CARD" Board

### PR DESCRIPTION
**Pull request by Swamstick911**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber.zip and Schematic.pdf
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Swastik's NFC card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|🟨 | schematic.pdf | Manually check schematic.pdf |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/8e3ec76254638b25e82c39c440070ed466bc237e/projects/Swastik's NFC card/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Swamstick911** [comment]
Hey I am ordering the board but it is asking for payment not for customs
but for the product what should I do?

**Comment by Swamstick911** [comment]
What should I do after this??

**Comment by maxwofford** [comment]
Hey @Swamstick911, your board is being reviewed. Once it's approved you'll get a card you can use to pay for the manufacturing!

**Comment by Swamstick911** [comment]
Awesome, thanks for the update! 😁

**Comment by BrightTheBackpack** [comment]
Just an FYI, you're "Hacker Card" text is in the top layer, not the silk layer.

You're current board:
Screen Shot 2024-03-19 at 9 36 25 AM

With silklayer:
Screen Shot 2024-03-19 at 9 36 04 AM


Furthermore, it appears that one of you're traces in the bottom layer is not connected with the top layer. In the image below, the pad circled in a white circle is set as multilayer when it does not need to be, while the pad circled in red is only toplayer, when it needs to be multilayer.
Screen Shot 2024-03-19 at 9 40 38 AM

These pads should also be set as multilayer.
Screen Shot 2024-03-19 at 9 42 47 AM

**Comment by Swamstick911** [comment]
Soo, should I re-upload the files?

**Comment by karmanyaahm** [comment]
Yes please reupload the corrected files

**Comment by Swamstick911** [comment]
Ok, I will do that.

**Comment by Swamstick911** [comment]
Hey I have done the changes please see the changes and please tell if anything's left

**Comment by karmanyaahm** [comment]
Your student verification looks good to me, but we'll take a look at your updated design in a little bit, sorry for the delay!

**Comment by Swamstick911** [comment]
No problem, take your time.

**Comment by BrightTheBackpack** [comment]
Hi there!
It seems like you still need one more multilayer pad(see image)
image

Other than that, I think the design is good! (karmanyaahm correct me if i'm wrong)

**Comment by karmanyaahm** [comment]
Yeah instead of making it a multilayer pad under the IC, I would recommend making a via (a hole through the PCB) using the via tool then connecting all those traces to it. Feel free to ask on Slack if you have any question or are confused about any of this!

Also, I think you accidentally selected the wrong capacitor
image
This is the one linked in the Hacker Card jam: image

The other one will probably still work, but might make your grant price go beyond the ~$40 target price of hacker cards.

**Comment by Swamstick911** [comment]
Hey @karmanyaahm added new files please review ASAP

**Comment by karmanyaahm** [comment]
Hey @Swamstick911! I would love to approve your PR ASAP, but in it's current state, your board won't work. If you look here, one of the antenna wires is overlapping with the GND and SDA pins, which will stop it from talking to your phone
image


This is what I would recommend you change it to using the wire and via tools:
image
image


If you would like, we could also hop on a Slack call and I can help you figure this out! Just send me a message over there about that.

**Comment by Swamstick911** [comment]
Hey @karmanyaahm where is the wire from U1_8 going, is it going to connect the pad or something else?

**Comment by karmanyaahm** [comment]
U1 8 is going to the inside port of the antenna

**Comment by Swamstick911** [comment]
image
like this?

**Comment by karmanyaahm** [comment]
Yup that looks good to me! Also U2 doesn't need a multilayer pad. As soon as you upload your new files I can send you the grant!

**Comment by Swamstick911** [comment]
Ok I will update all the files rn

**Comment by Swamstick911** [comment]
@karmanyaahm added new files please check and give the grant as I am tooooooooo excited for my first PCB 😂😅

**Comment by karmanyaahm** [comment]
LGTM!

**Comment by karmanyaahm** [comment]
Also see https://github.com/hackclub/OnBoard/blob/main/community/shipping.md

You will have to pick a cheaper shipping option than $40. Make sure to use Air Registered Mail to not have to pay customs seperately.

**Comment by Swamstick911** [comment]
ok

**Pull request merged**
