### PR TITLE
Manufacturing

### PR DESCRIPTION
**Pull request by aicoder2009**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md`
  - [X] Uploaded Gerber, sources, and schematic
  - [X] Uploaded screenshot of PCB order with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by aicoder2009** [comment]
If someone could approve this soon it would be great

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi! Sorry I'm a little confused on what the files in the repo are. There is a list of files you need under [this section of the README](https://github.com/hackclub/onboard#5-add-your-design-to-your-project-repo). If you need a reference for what your Hacker Card submission should look like, [this is a great example](https://github.com/hackclub/OnBoard/tree/main/projects/Alex%20P's%20NFC%20Card).

Also, you need to use Economic assembly, not Standard assembly, please refer to the assembly [instructions document](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) for more info.

**Comment by aicoder2009** [comment]
> Hi! Sorry I'm a little confused on what the files in the repo are. There is a list of files you need under [this section of the README](https://github.com/hackclub/onboard#5-add-your-design-to-your-project-repo). If you need a reference for what your Hacker Card submission should look like, [this is a great example](https://github.com/hackclub/OnBoard/tree/main/projects/Alex%20P's%20NFC%20Card).
> 
> Also, you need to use Economic assembly, not Standard assembly, please refer to the assembly [instructions document](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) for more info.

the files are the ones requested in the templete

**Comment by aicoder2009** [comment]
> Hi! Sorry I'm a little confused on what the files in the repo are. There is a list of files you need under [this section of the README](https://github.com/hackclub/onboard#5-add-your-design-to-your-project-repo). If you need a reference for what your Hacker Card submission should look like, [this is a great example](https://github.com/hackclub/OnBoard/tree/main/projects/Alex%20P's%20NFC%20Card).
> 
> Also, you need to use Economic assembly, not Standard assembly, please refer to the assembly [instructions document](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) for more info.

I will change to standard shipping

**Comment by aicoder2009** [comment]
> > Hi! Sorry I'm a little confused on what the files in the repo are. There is a list of files you need under [this section of the README](https://github.com/hackclub/onboard#5-add-your-design-to-your-project-repo). If you need a reference for what your Hacker Card submission should look like, [this is a great example](https://github.com/hackclub/OnBoard/tree/main/projects/Alex%20P's%20NFC%20Card).
> > Also, you need to use Economic assembly, not Standard assembly, please refer to the assembly [instructions document](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) for more info.
> 
> the files are the ones requested in the templete

some of them are just different screenshots of cart.png

**Comment by aicoder2009** [comment]
> Hi! Sorry I'm a little confused on what the files in the repo are. There is a list of files you need under [this section of the README](https://github.com/hackclub/onboard#5-add-your-design-to-your-project-repo). If you need a reference for what your Hacker Card submission should look like, [this is a great example](https://github.com/hackclub/OnBoard/tree/main/projects/Alex%20P's%20NFC%20Card).
> 
> Also, you need to use Economic assembly, not Standard assembly, please refer to the assembly [instructions document](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) for more info.

I just checked and i got this message when i tried to apply economic assesembly:
Screenshot 2024-01-06 at 12 57 05 AM

**Comment by aicoder2009** [comment]
> Hi! Sorry I'm a little confused on what the files in the repo are. There is a list of files you need under [this section of the README](https://github.com/hackclub/onboard#5-add-your-design-to-your-project-repo). If you need a reference for what your Hacker Card submission should look like, [this is a great example](https://github.com/hackclub/OnBoard/tree/main/projects/Alex%20P's%20NFC%20Card).
> 
> Also, you need to use Economic assembly, not Standard assembly, please refer to the assembly [instructions document](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) for more info.

I Fixed the file names also

**Comment by aicoder2009** [comment]
I fixed it up all ready for review

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
The order and other files look great to me! Please make a "src" folder in projects/karthicks nfc card/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

After that we're just waiting on the approval of your student verification form! Looking forward to merging this PR and getting you your OnBoard grant soon!

**Comment by karmanyaahm** [comment]
Oh wait nevermind student verification was approved here accidentally https://github.com/hackclub/OnBoard/pull/299#pullrequestreview-1803306097

**Comment by aicoder2009** [comment]
I uploaded the files both of them in the src folder

**Review by karmanyaahm — APPROVED** [review]
lgtm

**Comment by karmanyaahm** [comment]
Merging because @sarthaktexas already approved your student verification in another PR. He'll send your grant in 24-48 business hours. Looking forward to seeing your PCB!

**Comment by sarthaktexas** [comment]
sending grant now

**Comment by aicoder2009** [comment]
got it now

**Pull request merged**
