### PR TITLE
mtg life counter

### PR DESCRIPTION
**Pull request by Wildbush76**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 9081/127

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/mtg_life_counter:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/c5239c1d19b0c5f1677f5a25b6d49f7ad166d8d3/projects/mtg_life_counter/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/c5239c1d19b0c5f1677f5a25b6d49f7ad166d8d3/projects/mtg_life_counter/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/c5239c1d19b0c5f1677f5a25b6d49f7ad166d8d3/projects/mtg_life_counter/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Lightshayan** [comment]
Hey! You have not filled out your checklist. Could you go back and make sure you have complete every step on the checklist? Thanks!

**Comment by Wildbush76** [comment]
> Hey! You have not filled out your checklist. Could you go back and make sure you have complete every step on the checklist? Thanks!

Don

**Review by maxwofford — APPROVED** [review]
This is awesome @Wildbush76 – I'm going to have to get some of my own fabricated for our games at Hack Club HQ!

Because this is your second grant, you don't need to resubmit your student verification & your card is unlocked for a second purchase.

**Comment by Wildbush76** [comment]
I just got the pcbs and have it be noted if you do try to make it the pads which a battery would be connected to are miss labeled, the positive one is labeled "-" and the negative side is labeld "+"

**Pull request merged**
