### PR TITLE
Rushil's Card

### PR DESCRIPTION
**Pull request by WolfGamer2**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [ ✅ ] I am 18 or under
  - [ ✅ ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [✅  ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [✅  ] I made this board from scratch, even if I followed a tutorial
- [✅  ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [✅  ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ ✅ ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ ✅ ] Created a folder called `src` and uploaded design files
  - [ ✅ ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [✅  ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [✅  ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Rushil'sCardPROJECT_NAME:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by LimesKey** [comment]
Hi @WolfGamer2, I see that your file names you're trying to merge are not as specified on the template. Your gerber zip file should be named "gerber.zip" and you don't have a /src directory. Please follow all the instructions [here](https://github.com/hackclub/OnBoard?tab=readme-ov-file#getting-started), specifically under the "Add Your Design to Your Project Repo" section. 

Thanks

**Comment by LimesKey** [comment]
It looks good, I just fixed up some of the file paths for you. One more thing I noticed, your `schematic.pdf` doesn't link to the electrical schematic design and instead, it's a photo of your PCB layout, can you please fix this?

**Comment by LimesKey** [comment]
Also, I noticed that you only just have a picture of the ordering screen. You have to add it to cart then click order and send a photo of the unpaid order. See [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) for instructions.

**Comment by Lightshayan** [comment]
Hi @WolfGamer2 !

Please feel free to ask for help if you need any here or [[#electronics on Slack](https://hackclub.com/slack/?event=onboard)](https://hackclub.com/slack/?event=onboard). I'm closing this for cleanup right now, but if you get your PR fixed, please let me or LimesKey know.

**Pull request closed without merging**
