### PR TITLE
USB C Breakout Board

### PR DESCRIPTION
**Pull request by WizardCatz**
## Submission Checklist:
**THIS IS MY SECOND PCB BOARD**
- [ yes] I am a current high school, middle school, or home schooled student.
  - [ yes] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ yes] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [yes ] I made this board from scratch, even if I followed a tutorial
- [yes ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [yes ] Created a folder under `onboard/projects`
  - [ yes] Filled out `TEMPLATE.md` as `README.md`
  - [yes ] Uploaded Gerber.zip and Schematic.pdf
  - [yes ] Created a folder called `src` and uploaded design files
  - [yes ] Uploaded screenshot of PCB order with all costs included
  - [yes ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [NA ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by WizardCatz** [comment]
I have created a second PR request (above), but I have also deleted the first (business card) file. I honestly don't need the file since I have already paid for the first board (hopefully you guys don't need the file). Thanks for all that you guys do!

**Comment by maxwofford** [comment]
@karmanyaahm any clue why the tests didn't run on this PR?

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/USB C Breakout Board:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/10c1c14b266e5f213ef710e643817228b322e6c0/projects/USB C Breakout Board/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/10c1c14b266e5f213ef710e643817228b322e6c0/projects/USB C Breakout Board/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/10c1c14b266e5f213ef710e643817228b322e6c0/projects/USB C Breakout Board/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by 24c02** [comment]
pardon the ring, CI didn't run bc the project directory wasn't in `projects/`.
@WizardCatz this board looks good to me! just sent [the rest of your grant](https://hcb.hackclub.com/grants/qlYIWz) :-D

**Pull request merged**
