### PR TITLE
Dexter Pico Macro Pad

### PR DESCRIPTION
**Pull request by Speedlet1**
## Submission Checklist:

- [✓] I am a current high school, middle school, or home schooled student.
  - [✓] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [✓] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [✓] I made this board from scratch, even if I followed a tutorial
- [✓] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [✓] Created a folder under `onboard/projects`
  - [✓] Filled out `TEMPLATE.md`
  - [✓] Uploaded Gerber and design files
  - [✓] Uploaded screen shot of PCB passing JLCPCB inspection
  - [✓] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [✓] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [✓] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by Leo32345 — CHANGES_REQUESTED** [review]
Looks cool! Unfortunately, we can only cover the cost for the PCB, not the Pico, key switches, or keycaps. Can you remove the `Component-cart.png.png` file from your submission?

**Comment by Speedlet1** [comment]
Thats fine, just done it. I thought that the grants also covered the cost
of the materials to populate the PCB's?
Thanks,
Dexter Speed

**Comment by karmanyaahm** [comment]
> I thought that the grants also covered the cost of the materials to populate the PCB's?

You can order PCB assembly from JLCPCB, but not components from a 3rd party.

**Comment by Speedlet1** [comment]
Ok thanks for the clarification. Is there any way for me to set this up
with similar parts to those I had specced?

**Comment by Leo32345** [comment]
@Speedlet1 If you select the assembly option at JLCPCB checkout, they should be able to assemble all the parts for you. You can look up parts at https://lcsc.com

**Comment by Leo32345** [comment]
Otherwise, everything looks great!

**Review by Leo32345 — APPROVED** [review]

**Comment by Speedlet1** [comment]
Hi Leo, I'm currently in the process of ordering my boards from JLCPCB, however the microcontroller board I was using to control my circuit is currently out of stock according to the JLCPCB assembly site? What can I do in able to order my boards without having to wait for a restock as there is currently no expected date for restocking?

**Pull request merged**
