### PR TITLE
Grant request

### PR DESCRIPTION
**Pull request by adammakesthingsdev**
## Submission Checklist:

- [Y] I am a current high school, middle school, or home schooled student.
- [Y] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Y] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [Y] I made this board from scratch, even if I followed a tutorial
- [Y] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Y] Created a folder under `onboard/projects`
  - [Y] Filled out `TEMPLATE.md` as `README.md`
  - [Y] Uploaded Gerber, sources, and schematic
  - [Y] Uploaded screenshot of PCB order with all costs included
  - [Y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [Y] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [Y] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 18351

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Woah this is so cool! I can't wait to see it manufactured and operational.

Small blocker, can you please File > Export > EasyEDA a JSON from the Schematic tab just like you have the PCB.json under src. Thanks!

**Comment by adammakesthingsdev** [comment]
Yes, that's my bad, sorry. Can't believe I missed that. It's been fixed

**Review by karmanyaahm — APPROVED** [review]
LGTM! Looking forward to seeing your board!

**Comment by karmanyaahm** [comment]
Waiting on HCB review of your student verification!

**Comment by adammakesthingsdev** [comment]
Verification has been properly submitted.

**Review by sarthaktexas — APPROVED** [review]
Howdy Adam! I'm approving your student verification :) Sending your grant now as well.

**Pull request merged**
