### PR TITLE
JPL.mp3

### PR DESCRIPTION
**Pull request by JPLabsystems**
## Submission Checklist:

- [ Y] I am a current high school, middle school, or home schooled student.
  - [ Y] I am 18 or under
  - [Y ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Y ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [Y ] I made this board from scratch, even if I followed a tutorial
- [ Y] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Y ] Created a folder under `onboard/projects`
  - [ Y] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [Y ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ Y] Created a folder called `src` and uploaded design files
  - [ Y] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ Y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ Y] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ N] (Optional) This project is from a tutorial[^1].
- [Y ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 5804

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/JPL.mp3:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by 46-HA** [comment]
Hi Justinas!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/qQgIBQ). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please keep this in mind before you make any purchases.** More info in the OnBoard community shipping doc.

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by JPLabsystems** [comment]
Hello @46-HA! Thank you to you and HackClub for making this possible! I seem to be having some trouble joining #electronics on the slack. Where should I go to join and share photos of my boards?

Regards
Justinas

**Comment by 46-HA** [comment]
Hey, what’s the problem with slack? You might have to verify yourself for high seas.

**Comment by JPLabsystems** [comment]
The #electronics hyperlinks in the README say "there's been an error when" clicked...my slack handle is JustinasPetkauskas just in case!

**Comment by 46-HA** [comment]
It looks like you’re a multichannel guest, you’ll have to verify to view the rest of slack. 
“Why can’t I do anything?
Check your DMs with Slackbot. You should have a message telling you to make your way to the Harbor. From here, you can complete the tutorial to graduate Pirate Academy.
Why am I getting an error that I am not authorised to install High Seas on Hack Club?
Multi-Channel guests are not able to connect to High Seas through the Slack login. Once your verification is accepted, you will be upgraded to a full slack user and the Slack login will work. Until your verification is accepted, please use the link that was sent to you in direct messages!”
Hope this helps!

**Comment by JPLabsystems** [comment]
Thank you! Did that and it worked!

Best,
Justinas

**Pull request merged**
