### PR TITLE
NFC-Ammen

### PR DESCRIPTION
**Pull request by AmeenHackClub**
## Submission Checklist:

- [x ] I am a current high school, middle school, or home schooled student.
  - [ x] I am 18 or under
  - [x ] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [ ]x I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x ] I made this board from scratch, even if I followed a tutorial
- [ x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x ] Created a folder under `onboard/projects`
  - [x ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ x] Created a folder called `src` and uploaded design files
  - [ x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) This project is for [Trick or Trace](https://showcase.hackclub.com/)[^3].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

### CODE REVIEW

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hey, good job on the PCB, but you have not selected assembly, meaning none of the components will be on your board. Also, are you able to select a cheaper shipping option?

**Comment by AmeenHackClub** [comment]
Sorry on that, i forget to mention in the readme.md file . i already have the required components from a previous project of mine.
Also, Air Registered Mail is the cheapest option

**Comment by LimesKey** [comment]
You'll likely need a stencil to assemble the hackercard, do you have all the other tools you'd need for assembling like the solder paste, solder, soldering iron and maybe a hot plate?

**Comment by AmeenHackClub** [comment]
Will do the needful

**Comment by LimesKey** [comment]
Could you order 2 PCBs instead of 5?

**Comment by AmeenHackClub** [comment]
the minimum in JLCPCB is 5

**Comment by LimesKey** [comment]
Just to confirm, the price of your JLCPCB is a little over 50$ USD, right? Not in United Arab Emirates Dirham?

**Comment by AmeenHackClub** [comment]
Yes that’s right

**Comment by LimesKey** [comment]
The most we can offer for the grant is $50. Here are some suggestions for reducing the price:

* Select the default green soldermask and leaded HASL finish
* Make sure as many parts as possible are "Basic" or "Preferred Extended" parts; these parts have the $3 assembly fee waived. Here is the list: https://jlcpcb.com/parts/basic_parts
* Use a coupon by JLCPCB for a minor price reduction
* Assemble the PCB yourself with a stencil

If the cost still ends up above $50, send a message in [[#onboard-help](https://slack.com/archives/C0593MG26TT)](https://slack.com/archives/C0593MG26TT) and I can help you pay the remainder with your own card.

**Pull request closed without merging**
