### PR TITLE
Solomon Gilder PCB/ DRDOOMPCB

### PR DESCRIPTION
**Pull request by Parrotito**
## Submission Checklist:

- [x] I am a current high school, student
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form) Y
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack Y
- [x] I made this board from scratch, even if I followed a tutorial Y
- [x] I have followed the directions in [README.md] (https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started) Y
  - [x] Created a folder under `onboard/projects` Y
  - [x] Filled out `TEMPLATE.md` as `README.md` Y
  - [x] Uploaded Gerber, sources, and schematic Y
  - [x] Uploaded screenshot of PCB order with all costs included Y
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards) Y
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/14948dcae4da5db8c02c6cef847d6d8fefec6caf/Gerber_PCB_pcb card_2024-01-26.zip>)!

  Happy OnBoarding!

**Review by sarthaktexas — APPROVED** [review]
Howdy Solomon! I'm approving your student verification :) The next step will be to wait 24-48 hours for the technical review and then your PR will be merged and you'll receive your grant! [@hackclub/boarding-party](https://github.com/orgs/hackclub/teams/boarding-party)

**Comment by karmanyaahm** [comment]
Hi Solomon! It looks like one side of your antenna is not connected to anything, so your board won't work.
image
Please post a link to your PR in the #onboard Slack channel, and someone will help you out.


Also, I'm not sure how your board is costing $94 when the screenshot says $27?

Additionally, please make a "src" folder in projects/[name]/, and put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) there. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

**Comment by Parrotito** [comment]
Hello,

So, funny little issue with the pricing of the board, so it says $94 because I accidentally put it as 94 and can’t edit it. I did put a comment though that says the actual price is $27. The schematics as well are both on the GitHub repository already? But I’ll connect my antenna.

Best regards,
Solomon

**Comment by karmanyaahm** [comment]
Can you please upload your fixed files?

**Comment by maxwofford** [comment]
Hey, haven't heard anything on this thread for a while so I'm going to close the PR so it's not in our actively monitored list. You can still totally reopen it by just commenting here or pushing those file changes.

**Pull request closed without merging**
