### PR TITLE
Blender Macropad

### PR DESCRIPTION
**Pull request by Ethancatepete**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md`
  - [X] Uploaded Gerber, sources, and schematic
  - [X] Uploaded screenshot of PCB order with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by daisybanks — APPROVED** [review]
Approving student verification! The next step will be to wait for an engineering review. After that, your pr will be merged and I'll get you your grant within 48 hours. :)

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
The project looks good to me but I just want to confirm - are you buying the switches and microcontroller board yourself? Your JLCPCB cart doesn't have any parts selected

The OnBoard grant only supports payments to JLCPCB and a couple of other PCB manufacturers, not amazon, digikey or other generic sellers: https://github.com/hackclub/OnBoard/blob/main/docs/VENDORS.md

**Comment by Ethancatepete** [comment]
Yeah I am buying those components myself

**Review by karmanyaahm — APPROVED** [review]
Awesome! Looking forward to how the Macropad turns out

**Comment by karmanyaahm** [comment]
You should get an email with your grant virtual card in 24-48 hours.

**Pull request merged**
