### PR TITLE
Submit test project

### PR DESCRIPTION
**Pull request by maxwofford**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
- [x] I am a member of the Hack Club Slack (Join [here](https://hackclub.com/slack>)).
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/directions.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md`
  - [x] Uploaded Gerber and design files
  - [x] Uploaded screen shot of PCB passing JLCPCB inspection

### CODE REVIEW

**Comment by bykevinyang** [comment]
Hello Max, this PR seems good. However it seems like you've put in your screenshot in the main repo. That might be a problem! 

Can you resubmit with your screenshot in your project folder?

**Comment by bykevinyang** [comment]
Hey Max! Thanks for the change. Merging!

**Comment by souptik-samanta** [comment]
Is this supposed to be a submission?

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/test_project:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Pull request merged**
