### PR TITLE
RP2040 LTE Communicator

### PR DESCRIPTION
**Pull request by E-Krabs**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/RP2040_LTE_COMMUNICATOR:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/612414022535c5b361ea844522b69ec5160f3693/projects/RP2040_LTE_COMMUNICATOR/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/612414022535c5b361ea844522b69ec5160f3693/projects/RP2040_LTE_COMMUNICATOR/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/612414022535c5b361ea844522b69ec5160f3693/projects/RP2040_LTE_COMMUNICATOR/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — COMMENTED** [review]
I'm very intrigued by your electrical schematic and PCB design, 3 pages wow, how long did that take you? Personally, my largest design is a page and a half and I don't believe I've seen any pull request more than a page for OnBoard, assuming everything is laid out nicely in the schematic of course. 

This would have been great for [The Trail](https://trail.hackclub.com/) but you just missed it. Do you happen to have 3D models for all your components in KiCad? I would love to see a 3d view of your PCB.

Just wanted to confirm that you're able to purchase the LCSC components by yourself as the grant doesn't cover components outside of JLCPCB's assembly. Amazing design though.

**Comment by E-Krabs** [comment]
Thank you! I began this project at the first week of June and finished 2 days ago, as I had to learn a lot for it; It has been incredibly fun and by far my largest design. The Trail seems really awesome I wish I had come across it much earlier. And yes I am able to purchase the components myself.
Attached are the 3D renders of the PCB, only the SIM connector I was unable to find a model for. The IC socket on the back is for an [HDSP-2101 Display](https://docs.broadcom.com/doc/AV02-0629EN) and the 8x2 jumper is for a keypad.
back
front

**Review by LimesKey — APPROVED** [review]
Hi @E-Krabs!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/XOWIrV). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
