### PR TITLE
Bitcoin keychain

### PR DESCRIPTION
**Pull request by eesazahed**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

I am making a Bitcoin keychain. It contains my lightning address and my bitcoin address. It also has an NFC tag.

$37

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Eesas-bitcoin-keychain:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/d736b22de50ea6f749c6a310a39bea4f203d9a09/projects/Eesas-bitcoin-keychain/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/d736b22de50ea6f749c6a310a39bea4f203d9a09/projects/Eesas-bitcoin-keychain/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/d736b22de50ea6f749c6a310a39bea4f203d9a09/projects/Eesas-bitcoin-keychain/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by blazecoding2009** [comment]
Hey @eesazahed 
Your files are all correct but it seems like you haven't done the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form) - we need this info to contact you and send your grant! Thank you!

**Comment by eesazahed** [comment]
I've done the verification.

**Comment by blazecoding2009** [comment]
I do not see any entry for `eesazahed` on our airtable, please do the one which was linked, you might be mixing up arcade with onboard.

**Comment by eesazahed** [comment]
Maybe @eesazahed? I did the form for onboard before and got my $50 grant,
Im here for my second one.

**Comment by blazecoding2009** [comment]
Whoops! My fault

**Comment by blazecoding2009** [comment]
Just went ahead and have added $50 to your grant, have fun!

**Review by blazecoding2009 — APPROVED** [review]
topped off grant

**Comment by eesazahed** [comment]
thanks blaze

**Pull request merged**
