### PR TITLE
Aryavrat's PCB creation

### PR DESCRIPTION
**Pull request by AV-01**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by sarthaktexas — APPROVED** [review]
Howdy Aryavrat! I'm approving your student verification :) The next step will be to wait 24-48 hours for the technical review and then your PR will be merged and you'll receive your grant! [@hackclub/boarding-party](https://github.com/orgs/hackclub/teams/boarding-party)

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
Hi @AV-01! You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this.

Additionally, in your "src" folder, please export your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) from the PCB tab as well. In addition to the SCH_NEW.json you already have, we also need a PCB_something.json.

**Comment by AV-01** [comment]
I updated everything, let me know if anything else needs to be changed!

**Review by karmanyaahm — APPROVED** [review]
LGTM!

**Comment by karmanyaahm** [comment]
You should get an email with your grant card in 24-48 hours!

**Comment by AV-01** [comment]
Hello, sorry to bother you again, but it's been around 3 days and I haven't received a grant card yet. Is there another form I need to fill out?

**Comment by sarthaktexas** [comment]
sending right now! stay tuned for an email :)

**Pull request merged**
