### PR TITLE
Shiva's NFC Card 

### PR DESCRIPTION
**Pull request by shiva233**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/ShivaPrakash_Card:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/71bbfc2aef0d149fdf6cf2047b81cc55e461407b/projects/ShivaPrakash_Card/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/71bbfc2aef0d149fdf6cf2047b81cc55e461407b/projects/ShivaPrakash_Card/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/71bbfc2aef0d149fdf6cf2047b81cc55e461407b/projects/ShivaPrakash_Card/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by blazecoding2009** [comment]
Hey @shiva233 

I don't seen to be able to see the capacitors and resistors on your PCB order. Can you send me a more clear screenshot?

**Comment by shiva233** [comment]
Hey @blazecoding2009 ,

Sorry about that.  I Believe the capictor and resistor are there on the pcba order. Here is another screenshot zoomed in 
image

image

**Comment by blazecoding2009** [comment]
I can't find your verification form, have you done it?

**Comment by shiva233** [comment]
Hey, @blazecoding2009 . Sorry about that I confused the arcade verification form and the onboard verification form. I thought they were one in the same, I have filled out the onboard verification form just now. Sorry if this caused any problems D:

**Comment by shiva233** [comment]
Is there anything else I need to do on my part? this is my first time using onboard.

**Review by blazecoding2009 — APPROVED** [review]
Looks good! Have fun with your [grant](https://hcb.hackclub.com/grants/qnZIMR)

**Comment by shiva233** [comment]
Thanks :D

**Pull request merged**
