### PR TITLE
PixelCard PR

### PR DESCRIPTION
**Pull request by Techpro709**
## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [X] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [X] Uploaded Gerber.zip and Schematic.pdf
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: I don't remember it was a while ago but I was teaching FLL

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/PixelCard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|🟨 | schematic.pdf | Manually check schematic.pdf |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/df40190c13efdfe8c89b8f07f630b7e6dc0d4ee3/projects/PixelCard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Hi @Techpro709! For schematic.pdf, you need to export your schematic tab as a PDF (in the schematic tab go to [File > Export > PDF](https://docs.easyeda.com/en/Export/Export-Schematic/index.html)), not your PCB tab.


Other than that your design looks great to me!

**Comment by karmanyaahm** [comment]
Hey @Techpro709, as soon as you post the updated file, I can get you your grant!

**Comment by karmanyaahm** [comment]
Student verification is approved

**Comment by Techpro709** [comment]
@karmanyaahm I sent in update 

# "I'm stupid for not realizing that"

**Comment by karmanyaahm** [comment]
Hi Name!
I've just sent you [your grant](https://hcb.hackclub.com/grants/XdBI5e) for OnBoard. You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.**

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #onboard channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
