### PR TITLE
Atmega32u4AU Macro-Pad

### PR DESCRIPTION
**Pull request by KoKoOogit**
## Submission Checklist:

- [x ] I am a current high school, middle school, or home schooled student.
  - [x ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ x] I made this board from scratch, even if I followed a tutorial
- [ x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x ] Created a folder under `onboard/projects`
  - [ x] Filled out `TEMPLATE.md` as `README.md`
  - [ x] Uploaded Gerber.zip and Schematic.pdf
  - [ x] Created a folder called `src` and uploaded design files
  - [ x] Uploaded screenshot of PCB order with all costs included
  - [ x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/b9b4974b2de9b4c24271a9c5c5e892e3c4a44f0c/projects/AtMega32u4-MacroPad/gerber.zip>)!

  Happy OnBoarding!

**Review by maxwofford — APPROVED** [review]
Your student verification is approved! I'll send the grant once we review the board files!

**Comment by maxwofford** [comment]
@KoKoOogit can you order the parts via JLCPCB? We don't currently support ordering through LCSC

**Comment by KoKoOogit** [comment]
@maxwofford Yes, I can order from JLCPCB but it won't ship in one order. In that case, I guess it might exceed $100. Whereas, LCSC shipping is quite affordable and includes more components.

**Comment by maxwofford** [comment]
@KoKoOogit The cards are locked to specific vendors where we can verify what is being purchased. We can't support LCSC as a vendor because they're a general purpose distributor. Can you try and see how much it'd cost to do all under JLCPCB or another [approved vendor](https://github.com/hackclub/OnBoard/blob/main/docs/VENDORS.md)?

**Comment by KoKoOogit** [comment]
@maxwofford The total cost exceeds $100. So, I will redesign using an arduino micro or I will make another pcb project. Thanks for your support though!

**Comment by karmanyaahm** [comment]
Closing as @KoKoOogit is no longer pursuing the project?

**Comment by maxwofford** [comment]
That's fine for now, but because the project is getting a redesign, @KoKoOogit please reopen this when you have your new design! I think it'd be cool for people to see the iteration from your old design to new one.

**Pull request closed without merging**
