### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by ZachNegin**
## Submission Checklist:

- [ yes] I am a current high school, middle school, or home schooled student.
  - [ Yes] I am 18 or under
  - [ Yes] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [ Yes] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [Yes ] I made this board from scratch, even if I followed a tutorial
- [ Yes] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [Yes ] Created a folder under `onboard/projects`
  - [Yes ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [Yes ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [Yes ] Created a folder called `src` and uploaded design files
  - [Yes ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ Yes] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ I live in the US] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Neopixel_POV_globe:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by 46-HA** [comment]
Hello! Can you rename pcbcart to just cart? Also are these all separate boards because each PR is one board, you would have to open another pull request for each board

**Comment by ZachNegin** [comment]
Hello, I will get started on fixing my pull request. Should I make a new
request, or is there a way to edit the old one?

Thank you, Zachary Negin

**Comment by 46-HA** [comment]
Each pull request is only for 1 PCB, you would have to resubmit it. Also please note that the Onboard grant is only $100 dollars, I think yours might be a bit too expensive but you can do onboard live or donate to your grant money. Check out the onboard live channel on slack, it's new and really cool! I'm closing this PR, if you have any questions reach out to me on Slack (HenHen). Good luck and keep on hacking :)

**Pull request closed without merging**
