### PR TITLE
Add "selectric-conversion" board

### PR DESCRIPTION
**Pull request by victor11035**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/selectric-terminal:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/be395365586b40e0e34653a4c3fd47b31aa774cb/projects/selectric-terminal/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/be395365586b40e0e34653a4c3fd47b31aa774cb/projects/selectric-terminal/schematic.pdf>) |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/be395365586b40e0e34653a4c3fd47b31aa774cb/projects/selectric-terminal/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hey @victor11035! There should be two `.JSON` files for your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html), one from the schematic tab, one from the PCB tab. Right now you have the `.epro` which isn't the right one.

Check out the README or the video for more help! https://github.com/hackclub/OnBoard?tab=readme-ov-file#getting-started

**Comment by victor11035** [comment]
Unfortunately I couldn't figure out a way to download the .json files, as I had accidentally used the pro version of EasyEDA (which to the best of knowledge can't export .json files). I have linked a picture below of what I get when following the tutorial. If the .json files are strictly required, I can try to figure out how to convert the project to EasyEDA standard edition.

image

**Review by LimesKey — CHANGES_REQUESTED** [review]
Thanks for adding the PCB JSON files, however, I noticed two issues still. Your `cart.png` shows as not including assembly by JLCPCB, is this intentional? Your `cart.png` also is not of the unpaid ordered PCB, it's of the cart. Here's some instructions regarding that,

> it looks like you took a picture of your cart instead of completing the checkout process. To ensure your order gets processed correctly, please follow the steps in [this](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) guide or in here:


>1. Click "Secure Checkout": After adding your PCB to the cart, make sure to click "Secure Checkout."
>2. Enter your shipping information: Fill in your shipping details as prompted.
>3. Take a screenshot of your unpaid order: Once you reach the final page before payment, take a screenshot of this page. It should show all the details of your order.


>Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will help us review your order more effectively. Congrats on making the PCB though!

**Comment by victor11035** [comment]
Sorry about the screenshot - I've updated it to be hopefully the correct one. As for the assembly, I plan on doing it myself as the total cost of assembly by JLCPCB exceeds the $100 limit of the grant.

**Comment by LimesKey** [comment]
I cannot seem to find your verification form, are you sure you've done it and submitted it with your correct GitHub username?

**Comment by whatwareweb** [comment]
Sorry for random comment but i just wanted to say this project is super cool!!!

**Comment by LimesKey** [comment]
Hi @victor11035!

Please feel free to ask for help if you need any here or [#electronics on Slack](https://hackclub.com/slack/?event=onboard). I'm closing this for cleanup right now, but if you update your PR with the requested changes, please open up a new PR and link the old one!

**Pull request closed without merging**
