### PR TITLE
Tiny converter by Shaunak from #518

### PR DESCRIPTION
**Pull request by Umurmiria**
## Submission Checklist:

- [Y ] I am a current high school, middle school, or home schooled student.
  - [Y ] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Y ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [Y ] I made this board from scratch, even if I followed a tutorial
- [Y ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [Y ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [ Y] Created a folder called `src` and uploaded design files
  - [Y ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ Y] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [NA ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Tiny converter by shaunak:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/948c4c16b32967f9dc6f44c3db37b8665a65f03a/projects/Tiny converter by shaunak/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/948c4c16b32967f9dc6f44c3db37b8665a65f03a/projects/Tiny converter by shaunak/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/948c4c16b32967f9dc6f44c3db37b8665a65f03a/projects/Tiny converter by shaunak/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Umurmiria** [comment]
Hi @maxwofford, was unable to fork and borrowed my sister's account to do so. What's in a name?

**Comment by Umurmiria** [comment]
OnBoard team, pl check #518 for history

**Comment by Umurmiria** [comment]
Heres a comment for proof

**Comment by MrKillerShaunBa** [comment]
Here is a comment from my account as proof

**Comment by MrKillerShaunBa** [comment]
@maxwofford pl reply asap

**Comment by maxwofford** [comment]
@MrKillerShaunBa please don't ping me 5 min after your previous posts. I get direct notifications to my phone for every change in this repo. I take time to respond because there are 35 other open PRs I'm also reviewing and helping people submit.

**Comment by zachlatta** [comment]
Hi, we are rejecting this grant for the reasons outlined in #518. You are welcome to resubmit a PR that qualifies.

**Pull request closed without merging**
