### PR TITLE
Cedric's USB Hub

### PR DESCRIPTION
**Pull request by CedricL1u**
## Submission Checklist:

- [Y] I am a current high school, middle school, or home schooled student.
 - [Y] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [Y ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [Y ] I made this board from scratch, even if I followed a tutorial
- [Y ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ Y] Created a folder under `onboard/projects`
  - [ Y] Filled out `TEMPLATE.md` as `README.md`
  - [ Y] Uploaded Gerber.zip and Schematic.pdf
  - [ Y] Created a folder called `src` and uploaded design files
  - [Y ] Uploaded screenshot of PCB order with all costs included
  - [Y ] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [Y ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [Y ] (Optional) This project is from a tutorial[^1].
- [Y ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 13356

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Cedric's_USB-Hub:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](https://raw.githubusercontent.com/hackclub/OnBoard/651a118ca7851fbd2cd26d063fc0d8171f34fae0/projects/Cedric's_USB-Hub/schematic.pdf) | Manually check schematic.pdf |
|❌| Source files - Unknown | No source files found. Please make a directory called 'src' and put your gerbers and upload your source files there. There must be two files, one for the schematic and one for the PCB. . |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/651a118ca7851fbd2cd26d063fc0d8171f34fae0/projects/Cedric's_USB-Hub/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by karmanyaahm** [comment]
Hi @CedricL1u!

Please put your [project sources](https://docs.easyeda.com/en/Export/Export-EasyEDA-Source-File/index.html) in your "src" folder. They should be two .JSON files, one from the schematic tab, one from the PCB tab.

**Comment by karmanyaahm** [comment]
Other than that your design and student verification look great to me!

**Comment by karmanyaahm** [comment]
Hey @CedricL1u as soon as you fix this I can get you your PCB! Please feel free to ask if you need any help

**Comment by CedricL1u** [comment]
can i switch designs?

**Comment by MichaByte** [comment]
@CedricL1u Sure, just submit a new pull request! Make sure to close this one first.

**Comment by MichaByte** [comment]
Hi @CedricL1u! I'm going to close this request for cleanup. Feel free to open another when you've made your new project. Let me know if you have any questions!

**Pull request closed without merging**
