### PR TITLE
Fixing issue.

### PR DESCRIPTION
**Pull request by AstroGuy1**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/NishantaPCB:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/9e2a2e14a617d8c5d0c74e78b1d0dbb76780dd8a/projects/NishantaPCB/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/9e2a2e14a617d8c5d0c74e78b1d0dbb76780dd8a/projects/NishantaPCB/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/9e2a2e14a617d8c5d0c74e78b1d0dbb76780dd8a/projects/NishantaPCB/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by abitchinmorewaysthanone** [comment]
Hi Nishanta,
Your board looks good, but your submission checklist has not been filled out. You will need to submit the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form), join Slack, and complete the Submission Checklist - we need this information to send you your grant! Thank you!

**Comment by AstroGuy1** [comment]
Hi, so the verification form has not been responding to me, I have submitted the forms multiple times, but I have not gotten a response yet. I can do the same verification here if that helps, but I don't know where to proceed from here.

**Comment by abitchinmorewaysthanone** [comment]
Your verification has come through!

I've just sent you [your grant[(https://hcb.hackclub.com/grants/vGyIOJ) for OnBoard. You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Comment by AstroGuy1** [comment]
Thank you, and would it be possible to get a higher funded grant in the future with more complex design?

**Comment by abitchinmorewaysthanone** [comment]
Gosh, you should've asked before I merged the pull! For OnBoard we have a fairly strict policy of one grant per person for the program. For completely original designs the grant is $100, for the business card or USB hub tutorial it is $50. In the future I'm sure we'll have more opportunities. 
Actually, if you haven't ordered the business cards yet, and you wanted me to cancel the grant for them, you could design and submit your own thing and receive the $100. I'd love to see what you make!

**Pull request merged**
