### PR TITLE
Esp temperature reader

### PR DESCRIPTION
**Pull request by 1millon1**
## Submission Checklist:

- [ ✓] I am a current high school, middle school, or home schooled student.
  - [✓ ] I am 18 or under
  - [ ✓] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [✓ ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ ✓] I made this board from scratch, even if I followed a tutorial
- [ ✓] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [✓ ] Created a folder under `onboard/projects`
  - [✓ ] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [✓ ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [✓] Created a folder called `src` and uploaded design files
  - [✓ ] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ ✓] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ✓] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/esp32-temperature:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png |  |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/76c935774ce92509d9be438151276bf042f62414/projects/esp32-temperature/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/76c935774ce92509d9be438151276bf042f62414/projects/esp32-temperature/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/76c935774ce92509d9be438151276bf042f62414/projects/esp32-temperature/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @1millon1 

Just went over your schematic and saw something wrong, you need to connect RX to TX and TX to RX. Not TX to TX and RX to RX

**Comment by 1millon1** [comment]
> Hey @1millon1
> 
> Just went over your schematic and saw something wrong, you need to connect RX to TX and TX to RX. Not TX to TX and RX to RX

Thank you a lot for noticing the error, I have fixed this now

**Comment by blazecoding2009** [comment]
Also connect your VDD to your 5v rail

**Comment by 1millon1** [comment]
> Also connect your VDD to your 5v rail

Yes, I also corrected that mistake. Thanks again very much

**Comment by blazecoding2009** [comment]
Hey @1millon1 

The most we can offer for the grant is $100. Here are some suggestions for reducing the price:


* Select PCBA for only two boards rather than all 5. You will still receive all 5, but only two will have components.
* Select green soldermask and leaded HASL finish
* Make sure as many parts as possible are "Basic" or "Preferred Extended" parts; these parts have the $3 assembly fee waived. Here is the list: https://jlcpcb.com/parts/basic_parts
* Use a coupon by JLCPCB for a minor price reduction

If the cost still ends up above $100, DM me on Slack (@blaze) and I can help you pay the remainder with your own card.
Thanks

**Comment by 1millon1** [comment]
> Hey @1millon1
> 
> The most we can offer for the grant is $100. Here are some suggestions for reducing the price:
> 
> * Select PCBA for only two boards rather than all 5. You will still receive all 5, but only two will have components.
> * Select green soldermask and leaded HASL finish
> * Make sure as many parts as possible are "Basic" or "Preferred Extended" parts; these parts have the $3 assembly fee waived. Here is the list: https://jlcpcb.com/parts/basic_parts
> * Use a coupon by JLCPCB for a minor price reduction
> 
> If the cost still ends up above $100, DM me on Slack (@blaze) and I can help you pay the remainder with your own card. Thanks

I can use a coupon to make the cost under 100 dollars.

**Comment by blazecoding2009** [comment]
@1millon1 You're only given one single $100 grant, usually you should be able to get through a few iterations with this. Are you sure you want to use it all at once?

**Comment by 1millon1** [comment]
> @1millon1 You're only given one single $100 grant, usually you should be able to get through a few iterations with this. Are you sure you want to use it all at once?

yeah im sure

**Review by blazecoding2009 — APPROVED** [review]
Sounds good, I've sent your [grant](https://hcb.hackclub.com/grants/XOWIVl)

**Pull request merged**
