### PR TITLE
Ashes Business Card

### PR DESCRIPTION
**Pull request by TheNewsYorkTime**
## Submission Checklist:

- [*] I am a current high school, middle school, or home schooled student.
  - [*] I am 18 or under
  - [*] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [*] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [*] I made this board from scratch, even if I followed a tutorial
- [*] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [*] Created a folder under `onboard/projects`
  - [*] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [*] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [*] Created a folder called `src` and uploaded design files
  - [*] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [*] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [*] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [*] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

Meow

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  Cannot find a file describing your project called "README.md".
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by TheNewsYorkTime** [comment]
> Hi, I'm Orpheus Leap! Here to help you review your PR.
> 
> Cannot find a file describing your project called "README.md". Happy OnBoarding! This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.

It's there?

**Review by LimesKey — CHANGES_REQUESTED** [review]
Everything is good except the `cart.png` image is of the ordering process and not the finished unpaid completed order, if you go back to JLCPCB and go to the past orders page you can take a picture of that and upload it as your cart.png instead. Take a look at other pull requests as an example, let me know if you get stuck.

**Comment by TheNewsYorkTime** [comment]
Ok, I think I fixed it

**Review by LimesKey — CHANGES_REQUESTED** [review]
The new `cart.png` is not what we're looking for, please take a look at other pull requests for an example. Here's some instructions, 

Thanks for submitting your PCB order! However, it looks like you took a picture of your cart instead of completing the checkout process. To ensure your order gets processed correctly, please follow the steps in [this](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) guide or in here:


1. Click "Secure Checkout": After adding your PCB to the cart, make sure to click "Secure Checkout."
2. Enter your shipping information: Fill in your shipping details as prompted.
3. Take a screenshot of your unpaid order: Once you reach the final page before payment, take a screenshot of this page. It should show all the details of your order.


Please send me a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will help us review your order more efficiently. Congrats on making the PCB though!

**Comment by TheNewsYorkTime** [comment]
> Ok, I think I fixed it
This looks better.

**Review by LimesKey — CHANGES_REQUESTED** [review]
I'm having issues viewing your proof of high school enrollment, can you resubmit the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)? You uploaded a `.html` file last time, please upload preferably a png or pdf.

**Comment by TheNewsYorkTime** [comment]
I tried to redo it, but got an error. It's probably on my end, bit here is the image anyway.

On July 4, 2024 4:03:50 AM PDT, LimesKey ***@***.***> wrote:
>@LimesKey requested changes on this pull request.
>
>I'm having issues viewing your proof of high school enrollment, can you resubmit the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)? You uploaded a `.html` file last time, please upload preferably a png or pdf.
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/hackclub/OnBoard/pull/763#pullrequestreview-2158660699
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
 - Ashes Settling After a Fire

**Comment by TheNewsYorkTime** [comment]
> I tried to redo it, but got an error. It's probably on my end, bit here is the image anyway.
> On July 4, 2024 4:03:50 AM PDT, LimesKey ***@***.***> wrote: @LimesKey requested changes on this pull request. I'm having issues viewing your proof of high school enrollment, can you resubmit the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)? You uploaded a `.html` file last time, please upload preferably a png or pdf. -- Reply to this email directly or view it on GitHub: [#763 (review)](https://github.com/hackclub/OnBoard/pull/763#pullrequestreview-2158660699) You are receiving this because you authored the thread. Message ID: ***@***.***>
> - Ashes Settling After a Fire

Oh, images.dont work via email?
IMG_20240704_131715610
Screenshot_20240704-131912

**Review by LimesKey — CHANGES_REQUESTED** [review]
Hey, thanks for the ID, not sure why Airtables was acting up, it appears to be some issue with Firefox? Anyways, I've updated your ID for you so that's all good, but I'd recommend deleting your message with your student ID from GitHub since it can be sensitive information.

I did notice a possible issue with your PCB though, I could be wrong but I believe you're bridging the LA/LB traces of the NFC antenna together with the VIA through the large unsolder masked QR code you have at the back. Here's some photos, Screenshot from 2024-07-05 01-14-50 
Screenshot from 2024-07-05 01-14-32
Even if this is not a problem, I'd recommend not having a large copper trace (the QR code) so close to the antenna as that may cause issues, it's unlikely but I'd just update it anyway and move the QR code a little further way or vice-versa with the antenna.

**Comment by TheNewsYorkTime** [comment]
Sorry It's been so long, but I think I fixed the Qr Code issue.

**Review by LimesKey — APPROVED** [review]
Hi @TheNewsYorkTime!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/qQgI5Q). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

**Pull request merged**
