### PR TITLE
Mahanth's Card

### PR DESCRIPTION
**Pull request by Mahanth-07**
## Submission Checklist:

- [✅ ] I am a current high school, middle school, or home schooled student.
  - [ ✅] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [✅ ] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [ ✅] I made this board from scratch, even if I followed a tutorial
- [✅ ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [✅ ] Created a folder under `onboard/projects`
  - [ ✅] Filled out `TEMPLATE.md` as `README.md`
  - [✅ ] Uploaded Gerber.zip and Schematic.pdf
  - [ ✅] Created a folder called `src` and uploaded design files (JUST HAVE ONE DESIGN FILE SO PUT IT THERE)
  - [✅ ] Uploaded screenshot of PCB order with all costs included
  - [ ✅] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ✅] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [✅ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/MahanthsCard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by Mahanth-07** [comment]
updated everything

**Comment by MichaByte** [comment]
Hi @Mahanth-07!
You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order 5 assembled boards. Once you do that, I can get you your grant!

P.S. Please re-upload `cart.png` when you're done so that we can see the updated price!

**Comment by Mahanth-07** [comment]
When i add an assembly, it is forcing me to pay upfront (and not retrieve a cart.png). How do i fix this?

**Comment by Mahanth-07** [comment]
never mind - fixed it

**Review by maxwofford — APPROVED** [review]
Hey Mahanth-07, thanks for submitting the project!

**Comment by maxwofford** [comment]
I just [sent the grant](https://hcb.hackclub.com/grants/XRGIBm)

**Pull request merged**
