### PR TITLE
yutaro hack card (multi NFC)

### PR DESCRIPTION
**Pull request by yutarour**
## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form) (quite a while ago from #117)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Review by karmanyaahm — COMMENTED** [review]
OMG OMG I love this! I did a double take looking at the DIP switches, because RF engineering can be scary and weird at times, but I love that you tested it! Looking forward to seeing this built! (yes I put exclamation marks on all of my sentences but I think its very cool that you took the hacker card jam and made something better out of it)

**Review by karmanyaahm — CHANGES_REQUESTED** [review]
One tiny thing though, can you please export your schematic as an EasyEDA JSON just like you did your PCB, and put it in the src folder?
Also we have a new verification form, so please fill it out again.

**Comment by yutarour** [comment]
Fixed.

**Review by sarthaktexas — APPROVED** [review]
Howdy Yutaro! I'm approving your student verification :) Once your PR is merged, you'll receive your grant!

**Review by karmanyaahm — APPROVED** [review]
LGTM. Very excited to see it, please post photos/a video in Slack when you get it!

**Comment by karmanyaahm** [comment]
You should get an email with your HCB card grant in 24-48 hrs :money_with_wings:

**Comment by yutarour** [comment]
> LGTM. Very excited to see it, please post photos/a video in Slack when you get it!

Sure will

**Comment by sarthaktexas** [comment]
Sent!

**Pull request merged**
