### PR TITLE
USB A to C Adapter

### PR DESCRIPTION
**Pull request by BuildNCode1**
## Submission Checklist:

- [✔️] I am a current high school, middle school, or home schooled student.
  - [✔️] I am 18 or under
  - [✔️] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [✔️] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [✔️] I made this board from scratch, even if I followed a tutorial
- [✔️] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [✔️] Created a folder under `onboard/projects`
  - [✔️] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [✔️] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [✔️] Created a folder called `src` and uploaded design files
  - [✔️] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [✔️] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [✔️] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [✔️] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

### CODE REVIEW

**Comment by prophetorpheus** [comment]
Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/first_Pcb:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

**Comment by blazecoding2009** [comment]
Hey @BuildNCode1 
It seems that you've deleted your files from your repository. If you'd like to get a grant, please put them back so that we can review them.

**Comment by BuildNCode1** [comment]
Hey @blazecoding2009 I had misnamed the files when I uploaded them. All I did was remove the files, rename them, and reupload the exact same files, just with the correct names. Can you still accept this or help me figure out another solution? thank you.

**Comment by blazecoding2009** [comment]
Hey
Yeah we can still accept this, let me go through your files and check

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @BuildNCode1 

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

**Comment by BuildNCode1** [comment]
Ok, I have updated cart.png. Now we should be good, right?🤞

**Comment by blazecoding2009** [comment]
> Ok, I have updated cart.png. Now we should be good, right?🤞

Looks like you've selected Standard Assembly, can you see if you can use economic? It's a lot cheaper and would allow you to use your grant for more projects like this

**Comment by BuildNCode1** [comment]
Unfortunately, I cannot switch to economic, as one of the parts I need is only assembled in standard, as you can see here:
image
The "USB-1" part says "Standard only".

**Comment by BuildNCode1** [comment]
So once we are done resolving all the issues, will you guys just automatically print it? Or will you send the grant to me and then I order it?

**Comment by blazecoding2009** [comment]
> Unfortunately, I cannot switch to economic, as one of the parts I need is only assembled in standard, as you can see here:
> image
> The "USB-1" part says "Standard only".
> 

No worries that's fine

**Comment by blazecoding2009** [comment]
> So once we are done resolving all the issues, will you guys just automatically print it? Or will you send the grant to me and then I order it?

We'll send a game and then you order

**Comment by blazecoding2009** [comment]
Just took a look at your  PCB and it looks like once its made, you won't be able to plug in a UCB C as the cable will get stuck on the PCB. Please fix that also please use the proper resistor values for the CC resistors and connect them to GROUND not VCC

**Comment by BuildNCode1** [comment]
> Just took a look at your PCB and it looks like once its made, you won't be able to plug in a UCB C as the cable will get stuck on the PCB. Please fix that also please use the proper resistor values for the CC resistors and connect them to GROUND not VCC

Can you please tell me what resistance I should use? Because I followed [this tutorial](https://www.youtube.com/watch?v=LrSKs35nR8k&list=PLbNbddgD-XxECO7C2z-FAlSoJ57VqcJA3&t=25s) to a tee, and it said to use 22 kiloohms (k).

**Comment by blazecoding2009** [comment]
The CC resistor should be 5.1k ohm iirc

**Comment by BuildNCode1** [comment]
Thank you. I just reuploaded the new and improved version of the PCB.

**Comment by blazecoding2009** [comment]
Hey @BuildNCode1 

There seem to be 2 projects here, would you mind removing the hacker card? You can reupload it once we're finished with this. 
image

Thanks!

**Comment by BuildNCode1** [comment]
> Hey @BuildNCode1
> 
> There seem to be 2 projects here, would you mind removing the hacker card? You can reupload it once we're finished with this. image
> 
> Thanks!

Just deleted it!

**Comment by BuildNCode1** [comment]
What else do we have to do before you can send me the grant?

**Comment by blazecoding2009** [comment]
Would it be possible for you to upload another piece of ID or a recent report card?

**Review by blazecoding2009 — COMMENTED** [review]
Hey @BuildNCode1 

I just sent your [grant!](https://hcb.hackclub.com/grants/qVMINV)

**Review by blazecoding2009 — APPROVED** [review]
Hey @BuildNCode1 

I just sent your [grant!](https://hcb.hackclub.com/grants/qVMINV)

**Pull request merged**
